lichess-org/lila

- ui/analyse/src/explorer/explorerConfig.ts
Closes #10064.
I'm adding the game participants as an option inside `playerModal`. Right now, in my code if you do select a participant, it doesn't get added to the stored prop. I figured I'd do it this way to keep things simple.
Let me know what you think.
> Add option to quickly select game participants in explorer

- ui/analyse/src/study/studyCtrl.ts
- ui/analyse/src/study/studyShare.ts
Fixes #10457.
~This change makes it possible to share a position that is on a sideline. Prior, sharing a position was done by ply number, so the linked position would always be on the mainline. Now, we share by tree path.~
~Since we won't be generating sharing URLs with ply number anymore, we eventually want to remove the code that loads a position via ply number. We aren't doing it immediately with this code change so as not to disrupt users who have just generated URLs with ply numbers.~
See below discussion.
> Only share mainline study positions 

- modules/common/src/main/Form.scala
- modules/common/src/main/Markdown.scala
- modules/team/src/main/TeamForm.scala
- modules/ublog/src/main/UblogForm.scala
Goals:
* No postprocessing on raw HTML. If the markdown parser is safe, then the whole pipeline is safe.
* Parse, don't validate: Use the actual markdown parser and a real URL parser for image whitelisting. Fixes https://hackerone.com/reports/1482486.
> robust markdown links and image whitelist

- modules/insight/src/main/Preset.scala
- modules/team/src/main/TeamForm.scala
Fixes #10577 
Corrects the dimension variable for two presets:
1. "When I trade queens, how do games end?"
2.  "Do I gain rating when I don't castle kingside?"
Previously, both would appear with "Variant" selected as the dimension.
Now, 
1. "Queen trade"
2. "My castling side"
> Corrects insight preset variables

- conf/routes
Moving to `/api` gives us support for CORS preflighting (#10587).
Could also pick a different path for consistency. The only releated one I see is:
```
GET   /api/game/:id                    controllers.Api.game(id: String)
````
> add alias for /games/export/_ids under /api (fixes #10587)

- modules/team/src/main/TeamApi.scala
To allow adding Lichess as team leader in the variant teams and keep it there.
Also allows ppl to kick Lichess from their team now but that seems unproblematic.
Tbh not sure whether this check is even needed in the first place since you can only add it if it's in the team anyway.
> Allow mods to make Lichess a team leader and keep it if it's already one

- modules/tournament/src/main/TournamentApi.scala
- ui/site/src/teamBattleForm.ts
This isn't really something that makes much sense and it allows making random tournaments (with potentially not really Lichess-aligned messages) seem official.
> Don't allow adding official teams to team battles

- app/views/tournament/side.scala
Slightly weird going via the condition but I don't think there's a better way to figure out which team a tournament belongs to
> Don't show variant team notice on un-official tournaments

- modules/study/src/main/Node.scala
See #10608
Arguably, evals are also annotations but it's not great if it leaves a half-broken eval graph. I guess an alternative would be to remove the eval graph/server eval completely? Or maybe add another button for that?
> study: Don't remove evals on clearAnnotations

- app/views/site/faq.scala
`https://https://playstrategy.org` -> `https://playstrategy.org`
> Fix typo in URL in FAQ

- modules/study/src/main/StudyRepo.scala
- modules/ublog/src/main/UblogRank.scala
Fixes https://hackerone.com/reports/1500457 and
https://hackerone.com/reports/1500956.
Users could increase or decrease the denormalized like counter arbitrarily.
Split the query to ensure the like count and rank matches a value that
has really been achieved.
There is a race condition with very limited impact that I consider to be
acceptable. It was also present before this patch.
---
Queries on master:
1. Count likers
2. Write denormalized count of likers and rank after unchecked +/-1
With patch:
1. Update set of likers
2. Count likers
3. Write denormalized count of likers and rank
> fix double like (or unlike)

- modules/rating/src/main/java/glicko2/RatingCalculator.java
When fC == 0, regula falsi (https://en.wikipedia.org/wiki/Regula_falsi) has found an actual zero C of the function f and should return it. The previous implementation would instead enter an infinite loop, doing fA = fA / 2.0 endlessly. The change from this PR causes this case to be handled correctly, returning after one additional iteration. The paper this code is based on (http://www.glicko.net/glicko/glicko2.pdf) was updated by Mark Glickman today with this change; see step 5.4b.
> Handle 0 properly in regula falsi

- app/controllers/Team.scala
- app/views/team/form.scala
- modules/api/src/main/ForumAccess.scala
- modules/team/src/main/Team.scala
- modules/team/src/main/TeamForm.scala
tested:
- Outsiders can see but not write in forums
- Member can post when the forum is open to all and members, but not leaders
- Leaders can post in the afored mentioned situation + Leader
- Only mods can post when forum setting set to `NONE`
close https://github.com/lichess-org/lila/issues/10719
Only question pending is if the default setting when creating a team should be switched back to allow forum view for everyone.
> Add back team setting so that team forum can be seen by everyone again

- modules/forum/src/main/PostApi.scala
- modules/forum/src/main/model.scala
This field is unused and unnecessarily complicates the view functions in PostApi in a related branch.  If the need for it arises somewhere, maybe it can be calculated there.  This change was originally made in a feature branch, but was broken out into a separate PR where it is more likely to be accepted.
> remove PostView.topicLastPage in model.scala

- app/controllers/ForumController.scala
- app/controllers/ForumPost.scala
- app/controllers/ForumTopic.scala
- modules/api/src/main/ForumAccess.scala
To avoid accidentally posting in a team they aren't a member of.
And also require Shusher perms.
> Prevent non-mod posts from mods in team forums without being a member

- app/controllers/ForumPost.scala
- app/controllers/ForumTopic.scala
This PR applies the net.rateLimit setting in config to rateLimiters in app/controllers/ForumTopic.scala and app/controllers/ForumPost.scala, in case one wants to create a bunch of stuff quickly in the UI rather than interacting with the db directly.
> use config's net.rateLimit setting in forum actions

- ui/site/css/_plan.scss
`#paypal-button-container` doesn't actually get used. And the `color-scheme` is to revert the `color-scheme: dark` on the top-level `html` which for some reason causes white iframe backgrounds.
|Before|![before](https://user-images.githubusercontent.com/19309705/161229743-1f85c2e6-1ea5-4b05-840d-7be41a58cec3.png)|
|--|--|
|After|![after](https://user-images.githubusercontent.com/19309705/161229751-074bd177-3ce7-444a-83a0-5b9aeca7f9fe.png)|
> Fix new PayPal button styling

- modules/i18n/src/main/LangList.scala
(Source: https://de.wikipedia.org/wiki/Schweizerdeutsch / me ><)
> corrected name of swiss german language

- app/controllers/ForumPost.scala
- app/views/forum/search.scala
- modules/forum/src/main/model.scala
Instead of just checking if the user belongs to the team.
Could not be tested locally due to lack of elasticSearch
> Use actual forum access policy when displaying post searchs

- ui/keyboardMove/src/main.ts
- ui/puzzle/src/ctrl.ts
- ui/round/src/ctrl.ts
Similar to what is already possible on the round page when the keyboard input is focused.
> Allow navigating move list from keyboard move input on puzzle page

- app/views/analyse/replay.scala
- ui/analyse/src/study/chapterNewForm.ts
- ui/analyse/src/study/studyView.ts
- ui/chat/src/view.ts
- ui/lobby/src/view/main.ts
- ui/lobby/src/view/tabs.ts
A very modest accessibility improvement to add the `tab`/`tablist` roles [where appropriate](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role). I noticed this because I use vimium, which wasn't recognizing our tabs as clickable elements.
> Add tab and tablist roles

- ui/analyse/src/study/studyShare.ts
Show the "Start at <move>" box after "current game url" in broadcasts.
In studies there is the box also after "study url", but it redirect to
the selected move in the first game, so I have removed it.
> Select starting move when export broadcast game

- app/controllers/Setup.scala
- modules/rating/src/main/RatingRange.scala
- modules/setup/src/main/HookConfig.scala
- ui/lobby/src/boot.ts
- ui/lobby/src/setupCtrl.ts
I realized with the last refactor that we are using a somewhat arbitrary rating range when creating hook like games ("new opponent" button for non-pool games). Currently, we compute a rating range based on the perf of what was last selected in the modal. This change makes it such that we only grab the deltas (min and max) from the modal, and give those to the backend. Then we apply those deltas to the appropriate rating.
My scala has a long way to go... I'm sure some refactoring is in order :D
> Hook like rating range fix

- ui/lobby/css/_setup.scss
- ui/lobby/src/setupCtrl.ts
Fixes #10858. Chessground was breaking when it encountered underscores in FEN.
Also fixes #10860 with a quick CSS change to make the modal scrollable.
> From position fen bug fix

- package.json
- yarn.lock
Update prettier to the latest version - Version 2.6.2 instead of version 2.5.1.
> Update prettier to the latest version.

- app/controllers/User.scala
- app/views/stat/ratingDistribution.scala
- app/views/user/perfStat.scala
- conf/routes
- ui/chart/src/ratingDistribution.ts
Implements https://github.com/lichess-org/lila/issues/3980
**Summary of changes**
- Add a new `ratingDistributionCompare` endpoint and controller method 
- Modify the rating distribution link on a user's perf stats page to go to the new endpoint
- Show a vertical bar on the rating distribution page indicating the rating of the target user, in addition to the logged-in user
**Screenshot**
> Show rating distribution for particular player

- app/views/team/bits.scala
- app/views/team/request.scala
- app/views/team/show.scala
fix for #10875
Testing this reveals a related issue, markdown description displayed raw in team lists.  This isn't a huge problem and there's probably overhead/other implications of applying markdown there as well, but it's something to keep in mind - I haven't thought about it any.
> Fix join team view not using markdown to render description

- modules/importer/src/main/Importer.scala
The validation from #10887 doesn't work for variant PGNs since the move compression only handles standard games so everything else is invalid by default. This causes all imports of variant PGNs (e.g. on /analysis) including FromPosition setups with at least one move to fail.
Probably would make sense to validate them some other way but for now, reverting the validation on variant games at least makes imports work again.
> Fix variant PGN imports

- ui/round/src/ctrl.ts
- ui/round/src/interfaces.ts
- ui/round/src/plugins/nvui.ts
Resolves #10849. Normally, inputting premoves happens via the chessground ui, but we have to do so differently in nvui.  The nvui plug in now holds a bit of state (the premove input) as well as more functions to achieve premove functionality.
> Implement premoves in nvui

- modules/streamer/src/main/Streaming.scala
I think the first condition was supposed to be a longer delay in case the previous call failed? Which probably shouldn't be needed now? Unless we want to set it to something even longer? But given that the API quota only seems to reset once a day and for actual errors 15 mins seems like a fine delay, I'm not sure there's much of a point to that.
From the monitoring, I think what currently happens is that the API quota resets once a day, then we immediately use it up with the once-a-minute calls, and then it starts failing and switches to 15 mins waits (but ofc never succeeds until the next day).
So I think this should fix #10921
> Actually only query the YouTube API every 15 mins

- modules/security/src/main/Permission.scala
As discussed on zulip: https://hq.lichess.ovh/#narrow/stream/24-mod-hunter-boost/topic/rankban.20permission
> Make `rankban` permission admin only

- app/controllers/Team.scala
After https://github.com/lichess-org/lila/commit/e6657dac818ce57a2032931a9f5004fe7b4e033d
Everywhere else it already checked for the relevant perms (shusher to see chat, forum mod to see the forum, other stuff only for ManageTeam).
Shushers sometimes need to see this for comms reports.
> Allow Shushers to see team mod view again

- ui/chat/src/ctrl.ts
- ui/chat/src/discussion.ts
- ui/chat/src/interfaces.ts
- ui/chat/src/note.ts
- ui/chat/src/view.ts
After b517e790fd13f474b9d32186abf9a83639d7101b
On slower devices, the insert handler can run after more than 1s.
> Don't auto-focus chat or notes on page load

- ui/lobby/src/setupCtrl.ts
- ui/lobby/src/view/setup/components/ratingDifferenceSliders.ts
Don't love the implementation but this seems like the most user-friendly way to handle this.
Alternative might be to silently (or maybe even explicitly) increase 0-0 to -25 - 25 or something like that?
> setup: Disallow empty rating range

- app/templating/FormHelper.scala
Just gonna describe the bug here for simplicity
**Issue Description**
Happens on all OSes and browsers.
1. Go to signup page
2. Put in a random username and password
3. Put `1@gamil.com` as the email (or any clearly illegal email with a domain from [here](https://github.com/lichess-org/lila/blob/c48da4e2cd22837a9f6e8b7eb4a59924967aec3f/modules/security/src/main/DisposableEmailDomain.scala#L49))
4. Click Register
5. Account creation fails with the error message repeated:
This should happen on all instances of `form3` with email validation.
**Issue cause**
An email like `1@gamil.com` triggers multiple instances of `ValidationError("error.email_acceptable")` which are mapped to the same error string. The form displays an error string per instance of this error. Using …
> [Bugfix] Remove duplicate error messages on email validation

- modules/i18n/src/main/I18nLangPicker.scala
- modules/i18n/src/main/LangList.scala
https://hq.lichess.ovh/#narrow/stream/16-dev-translation/topic/using.20country.20in.20language.20selector
country codes that have multiple languages (which users may not even look for in the full list):
```
{'en-GB', 'gd-GB', 'cy-GB'}
{'af-ZA', 'zu-ZA'}
{'es-ES', 'gl-ES', 'ca-ES', 'eu-ES', 'an-ES'}
{'gu-IN', 'hi-IN', 'ta-IN', 'kn-IN', 'pi-IN', 'mr-IN', 'ml-IN', 'as-IN', 'sa-IN'}
{'co-FR', 'fr-FR', 'br-FR'}
{'it-IT', 'frp-IT'}
{'fy-NL', 'nl-NL'}
{'id-ID', 'jv-ID'}
{'io-EN', 'jbo-EN'}
{'kmr-TR', 'tr-TR'}
{'nb-NO', 'nn-NO'}
```
> suggest additional languages by country

- ui/round/src/view/replay.ts
#10989 - the bug where play from fen (copied from game in progress) resulted in move list being unclickable.  With this change, the game will use the FEN's fullmove value as the starting move index (if present) rather than 1 and the user will see this in the index column ("why is 22 the first move?").  However, this is how it works in analysis, so I figured that's better than other solutions such as truncating fullmove from FEN in Lila when creating from position.
> fix move list indices when playing from fen with fullmove specified

- app/controllers/Pref.scala
- app/views/account/bits.scala
- app/views/account/pref.scala
- modules/i18n/src/main/I18nKeys.scala
- modules/pref/src/main/PrefCateg.scala
- translation/source/preferences.xml
- ui/dasher/src/links.ts
- ui/dasher/src/view.ts
Reviving #10052
Time to finally translate that settings category.
After thinking about it a bit more, I think it makes the most sense to rename "game display" to "display" and move "hide ratings" there. The privacy settings are all very clearly related and I think it's good to have an explicit "privacy" category to find that stuff.
Though "game display" also already has a fair amount of settings. If you think it's best not to add more to that, I guess the alternatives are a new category or just sticking with the "site settings" category and possibly finding a slightly better name for that (maybe "general settings" or "other settings"?).
imo, keeping it out of what is essentially just "privacy" is still better. Possibly, we could move it together with the courtesy setting (which really …
> Move "hide ratings" pref to "display" (renamed from "game display") and rename "site settings" back to "privacy"

- modules/round/src/main/TreeBuilder.scala
Addresses #10878 
**Issue Description**
Happens whenever White berserks but Black does not. The clocks in post-game analysis show both players starting with the berserked amount of time. Clocks are correct after the first move.
You can see an example in the listed issue or at this URL: https://lichess.org/TKVJqdRx/white
**Issue Cause**
When the game tree is built in [`TreeBuilder.scala`](https://github.com/lichess-org/lila/blob/c48da4e2cd22837a9f6e8b7eb4a59924967aec3f/modules/round/src/main/TreeBuilder.scala#L48), the root node uses the clock value from the first move. This value is then used to initialise both clocks on the frontend. If White has berserked, both clocks end up initialised to White's berserked time.
**Fix Details**
I'm initialising the clock on the root node to be the …
> [Bugfix] Fix initial clock values when only White berserks

- modules/tournament/src/main/ApiJsonView.scala
- modules/tournament/src/main/Condition.scala
- modules/tournament/src/main/JsonView.scala
Since you can't update the tournament without knowing these (bc they will be reset if you don't specify them again).
Not sure about adding the team member condition, it might be useful to know but at least isn't necessary for updating them and probably isn't useful to know in most cases?
Also, I noticed that you can also specify the perf type for all the conditions but it's not explained in the docs or shown in the UI. Are they intentionally hidden or should they be added? ig if they shouldn't be used, probably would make sense to block them instead?
> Add tournament conditions to API

- modules/tournament/src/main/TournamentScheduler.scala
Probably would also make sense to give it a nicer image/icon? ig the event trophy image or the lichess logo?
> Give aniversary arena 24h of homepage hours

- modules/common/src/main/HTTPRequest.scala
With this change HTTPRequest.appOrigin doesn't do an exact match, instead it returns the client's origin header if it starts with any of those allowed - a source port in the url string no longer prevents matching. 
The Origin header cannot be set in a chrome-js XmlHttpRequest.  It always sends "http://localhost:<port>" and the source port varies.  Other flutter targets (everything but web) can set Origin header directly.  Flutter web probably is not even useful for any lichess development, but who knows.
> fix CORS for flutter web

- ui/chat/css/_discussion.scss
- ui/chat/src/discussion.ts
Implementing the suggestion from #11042. Chat messages that mention you are highlighted green.
Tested in dev:
Tested in a simul (where hosts' messages are also highlighted):
Let me know any thoughts on the approach/colors used.
> Highlight chat messages when you are mentioned

- ui/analyse/css/_acpl.scss
- ui/analyse/src/acpl.ts
- ui/common/css/theme/_dark.scss
- ui/common/css/theme/_default.scss
- ui/tree/css/_tree.scss
closes #11051 (if you happen to see this thanks 1vader for that github tip)
I tried for dav1312's "side idea" stretch goal in the video, but honestly the different hover backgrounds in tree view are a bit schizophrentic.  Maybe don't merge changes to _tree.scss except lines 208-216, or even skip those.
> color error categories in acpl summary, and taking crayons to tree view

- ui/analyse/css/study/panel/_share.scss
The checkbox inputs to share a study have `cursor: default` over the input itself but `cursor: pointer` on the text. This is because the `cursor: pointer` that should be inherited is getting overridden. It should be consistent with the other checkbox inputs on the site
Currently looks like:
With these changes:
> Tiny tweak to checkbox cursor CSS

- public/javascripts/study/tour.js
- ui/@types/lichess/index.d.ts
- ui/analyse/src/study/studyTour.ts
**Steps to Repro**:
1. Go to any study (eg. https://lichess.org/study/KCtNgx2P)
2. Open the action menu on the left:
3. Start the tour and click past the first step. The second step appears in the bottom corner and the tour is entirely broken.
**Cause**:
Issue is that the second step tries to attach to [an element on the left](https://github.com/lichess-org/lila/blob/master/public/javascripts/study/tour.js#L42) which doesn't exist when the action menu is open.
**Fix**:
Other tour steps that attach to possibly-nonexistent elements programmatically go to the right screen before the step. I used that pattern to make sure the action menu was closed before this step. Can't really show how this works via screenshot but you can test by trying the repro steps above.
Example of this pattern:
- …
> Fix bug where study tour breaks if action menu is open

- app/controllers/Challenge.scala
- app/controllers/LilaController.scala
This may be causing streams to break after 1 minute, but it should be fixed regardless.  The `map (_ as JSON)` call on line 354 of Challenge.scala was blowing away the correct nginx hint and entity type on keep alive requests.
https://discord.com/channels/280713822073913354/436555632964010005/991459275283124365
All props to Torom for isolating this.  I also noticed that the api allows challenges to nonexistent user ids.  The destUser resolves to None which is propagated all throughout the code without triggering any errors.  Is there a reason bad request isn't returned?
> specify application/x-ndjson in response header for keep alive api challenge creates

- ui/site/src/component/watchers.ts
While watching the candidates broadcast, I noticed that the usernames below the chat aren't hover-friendly: the card that appears on hover flickers twice a second or so. This is happening because the username link is being destroyed and recreated on every `socket.in.crowd` message, even when the usernames haven't changed.
With this PR, the username links won't render unless they are different from the previously-rendered usernames.
> Only render watchers when necessary

- README.md
- app/views/analyse/replay.scala
- ui/analyse/src/plugins/nvui.ts
- ui/site/src/site.ts
[`document.execCommand('copy')` is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) and can be replaced with the clipboard api.
The clipboard api doesn't need to select text to copy it, so I removed the text selection. 
Downside: we would need to bump the minimum Firefox version from 61 (June 2018) to 63 (October 2018). Our other supported browsers already support what we need. [Caniuse](https://caniuse.com/mdn-api_clipboard_writetext).
> Replace deprecated execCommand with clipboard api

- ui/round/css/_clock.scss
Fixes issue #11114 
Issue was actually visible on any game using clock
> time should always be displayed Left to Right

- app/controllers/Setup.scala
- ui/lobby/src/setupCtrl.ts
closes #11118
Alternatively, fiddling with the json can provide the hint without abandoning BadRequest.  I do feel somewhat dirty using HTTP status codes for their intended purpose.  Lemme know if json is preferred.
> close game setup modal on challenge denied

- ui/analyse/src/study/inviteForm.ts
Basically the same as #11081 
The study tour should close when the `Add member` dialog is opened otherwise you get stuff like this:
The `Add member` dialog should take priority since it was the most recent action by the user
> Close study tour when "Add member" dialog is opened

- ui/@types/lichess/index.d.ts
- ui/analyse/src/ctrl.ts
- ui/analyse/src/interfaces.ts
- ui/analyse/src/plugins/nvui.ts
- ui/analyse/src/view.ts
- ui/nvui/src/chess.ts
- ui/puzzle/src/plugins/nvui.ts
- ui/round/src/plugins/nvui.ts
Minimal initial implementation.
- One new shortcut (c for computer) that announces eval + depth. Works in nvui only. I want to keep the number of shortcuts down since there are so many already.
- Document the shortcuts.
- Reuse existing elements for analysis toggle and pvs.
Covers part of #11089
> Local analysis for analysis board & studies

- ui/editor/src/ctrl.ts
- ui/editor/src/view.ts
Fixes #11188 by passing in the current orientation as a query param already being handled [here](https://github.com/lichess-org/lila/blob/3a64ba8690ca54bb9064d1b8dcc5328af40a9f0b/app/controllers/UserAnalysis.scala#L46)
> Create analysis with right color

- app/templating/AssetHelper.scala
- app/views/practice/show.scala
- app/views/relay/show.scala
- app/views/study/embed.scala
- app/views/study/show.scala
- ui/analyse/rollup.config.mjs
- ui/analyse/src/boot.ts
- ui/analyse/src/ctrl.ts
- ui/analyse/src/patch.ts
- ui/analyse/src/plugins/studyMain.ts
- ui/analyse/src/start.ts
- ui/analyse/src/study/studyDeps.ts
- ui/analyse/src/treeView/contextMenu.ts
- ui/analyse/src/view.ts
- ui/build
Closes #5862.
The wanted label got removed, so I'm not sure what the status of the issue is, but here's an implementation.
Makes a new entry point into ui/analyse and passes study-related code using dependency injection so that rollup knows to tree-shake it.
Study js stripped in:
- game embeds
- game replay analysis
- user analysis
Study js kept in:
- practice
- relay
- studies
- study embeds
Sizes before compression:
| file | size (bytes) | delta |
| --- | ---: | ---: |
| old analysisBoard.min.js | 285953 | +0 |
| new analysisBoard.study.min.js | 287302 | +1349 (+0.5%) |
| new analysisBoard.min.js | 219816 | -66137 (-23.1%) |
I left crazyhouse code in the small bundle because /analysis allows switching variants on the fly. We could make more bundles to cover variant and forecast presence …
> Allow bundling ui/analyse without study code

- app/templating/DateHelper.scala
- app/views/appeal/tree.scala
- app/views/blog/index.scala
- app/views/blog/show.scala
- app/views/tutor/compare.scala
- ui/site/css/_blog.scss
Lichess blog is written in English so it is safe to assume it should be left aligned even in ltr languages
There is an issue I'm trying to solve that may not be specific to blog content ...
Notice that the date is displayed in a strange format
I'm not sure if this is in  the dateFormatter of templating.DateHelper or if this has to do with css ...
> Force ltr on blog content

- ui/analyse/src/actionMenu.ts
- ui/editor/src/ctrl.ts
- ui/editor/src/view.ts
Adds orientation to as a query param to board editor. This fixes up two small issues:
**1. Analysis -> board editor orientation not persisted**
i. Go to analysis board
ii. In the action menu, flip the board to be from Black's pov and then go to board editor
iii. Board editor will be from White pov
**2. Board editor orientation change not persisted on refresh**
Unlike FEN changes, orientation of the board editor is not stored anywhere.
i. Go to board editor
ii. Make some moves then flip the board
iii. Refresh the page
iv. Changes made to the board stay but the orientation is flipped back
> Add orientation to editor url

- ui/analyse/rollup.config.mjs
#11202 broke study embeds because analyseEmbed.ts relies on the ui/analyse entry point being called "LichessAnalyse"
> Fix study embed regression

- ui/puzzle/src/ctrl.ts
Fixes a common-but-not-always issue where a selected square remains selected when the next puzzle is shown. It doesn't happen everytime and I can't seem to figure out what's actually causing it, some sort of race condition I imagine. In any case clearing the selected square when drawn shapes are being cleared does the job .
Attached is a recording of the bug:
[recording.webm](https://user-images.githubusercontent.com/30640147/179779734-8765435d-e4dd-44d4-a9b8-f0569b3d12fd.webm)
> Unselect square when new puzzle is shown

- ui/keyboardMove/src/plugins/keyboardMove.ts
Fixes bug from my commit in #11215 which is giving `Uncaught TypeError: Cannot read properties of null (reading 'innerText')` when you run the "who" command in a game right now.
This fixes games against regular opponents and still works for games against Stockfish.
> Fix CSS selector when speaking opponent name

- ui/round/src/boot.ts
https://lichess.org/forum/lichess-feedback/winslosses-not-scoring-currently
Since we no longer send the "end" event (d8fa8be3d699c739808f1db0c61372650035a290), boot.ts needs to listen to "endData" events instead to update the cross table.
> Fix cross table not updating at game end

- app/controllers/Relation.scala
- modules/oauth/src/main/OAuthScope.scala
Change the /api/rel/following endpoint from requiring empty scoped token,
to requiring the new follow:read scope.
Resolves: #11250
> Add follow:read scope

- ui/editor/src/view.ts
1. Go to board editor
2. Make a move
3. Flip the board
4. URL in the box below still has `color=white`
This happens bc `makeEditorUrl` wasn't supplying a value for color so it defaults to White
> Add color to editor url box

- ui/analyse/src/study/studyCtrl.ts
- ui/common/src/throttle.ts
- ui/coordinateTrainer/src/ctrl.ts
- ui/dasher/src/background.ts
- ui/insight/src/ctrl.ts
- ui/puzzle/src/xhr.ts
- ui/racer/src/ctrl.ts
- ui/round/src/xhr.ts
- ui/simul/src/xhr.ts
- ui/site/src/ublog.ts
- ui/storm/src/xhr.ts
- ui/swiss/src/ctrl.ts
- ui/swiss/src/xhr.ts
- ui/tournament/src/xhr.ts
Resolves #10266. In the past, we've used `throttle` on async functions, which will throttle without respecting the length of time that it takes for the promise to resolve. Implement `throttlePromiseDelay` that will correctly throttle async functions by first waiting for the promise to resolve/reject, then tacking on a delay.
> Throttle async calls safely with throttlePromiseDelay

- ui/analyse/src/plugins/nvui.ts
> Thanks very much for your help, if I might ask one more question, would it be possible to have the "e" key read out loud the current evaluation when going through moves?
As it is, I have to jump into browse mode, go back to the command input, type in eval, then go back out of browse mode and repeat the next time I want to see how the evaluation changed.
Closes #11253
> Add keybind to read current eval in analysis nvui

- ui/analyse/src/ctrl.ts
Premoves should be cancelled on user jump in practice (same behavior as in real games)
1. Go to any practice lesson
2. Make a move
3. Jump backwards and make a premove
4. The premove highlighted squares stick around
Otherwise you end up with stuff like this:
> Cancel premove on jump in practice

- public/javascripts/study/tour-chapter.js
- public/javascripts/study/tour.js
- ui/analyse/src/keyboard.ts
- ui/analyse/src/study/chapterNewForm.ts
- ui/analyse/src/study/inviteForm.ts
- ui/analyse/src/study/studyMembers.ts
If you do Shift+? to open the keyboard dialog with any of
- Study/chapter tour
- Add member dialog
- Add chapter dialog
open, 
You get weird overlapping dialogs which is generally bad ux. Since Shift+? is the most recent action from the user, it should take priority and other dialogs should close. Since the keyboard cheat sheet is owned by `AnalyseCtrl` and the various dialogs are owned by subcontrollers the only reasonable way I can think of to close those subdialogs is [with `pubsub` like in this PR](https://github.com/lichess-org/lila/pull/11081). Plus if there's any other dialogs on the site with the same issue we could use the same socket message.
As an example:
> Close various dialogs when the keyboard help comes up

- app/templating/AssetHelper.scala
- app/views/forum/topic.scala
- app/views/msg.scala
- app/views/ublog/post.scala
- modules/common/src/main/ContentSecurityPolicy.scala
- ui/common/package.json
- ui/opening/package.json
- ui/site/package.json
- yarn.lock
I think it's secure? Couldn't find a way to be more precise than `data:` in the new `font-src` CSP header.
> Lpv 1.0.0 with icon font for portability, has inline SVG requiring a CSP change

- app/controllers/Streamer.scala
- app/views/streamer/edit.scala
- modules/streamer/src/main/Streamer.scala
gave them a pretty green success banner.  don't think they will buy it.
Removes the 404 preventing db object creation to maximize their frustration a few minutes later.  if that's not desired, put the NoShadowban guard back in.  But apparently there are a ton of trolls applying for streamer who visited the your streamer page (creating their streamer object) prior to being marked.
> fast track streamer applications for trolls

- ui/ceval/src/worker.ts
Came across an if statement that doesn't seem to do anything. The outer if already checks if `cache` is truthy.
> Remove redundant if

- ui/analyse/src/ctrl.ts
- ui/analyse/src/study/interfaces.ts
- ui/analyse/src/study/studyCtrl.ts
no longer reset them to chapter's original orientation when they toggle a sync/rec button.  probably less desirable is that their pov now persists across manual page reloads.  it's straightforward to fix that and limit this to button toggles but...  i figured it's a good time to find out whether this change would completely ruin all of our lives before going any further.
this PR is just a question in source code form.  i choose not to dip into my stash of unused thibault discord pings at this time.
> persist user's pov for study chapters

- ui/analyse/src/study/studyCtrl.ts
Otherwise after manually refreshing a chapter, you get the chapter orientation but as soon as you toggle a mode button it could potentially flip your POV to whatever value the map had.
A different fix would be to use an in-memory map.  This would preserve POV across mode toggles but reset POV to chapter orientation on page loads.
In this commit the POV is just always preserved (for consistency sake).
> also maintain POV across page loads

- app/views/site/keyboardMoveHelp.scala
- ui/keyboardMove/src/main.ts
- ui/keyboardMove/src/plugins/keyboardMove.test.ts
- ui/keyboardMove/src/plugins/keyboardMove.ts
- ui/puzzle/src/ctrl.ts
- ui/puzzle/src/keyboard.ts
This is a first take on #11338 please let me know if I'm on the right track.
If I understand correctly the KeyboardMove interface is designed so different ctrl's can implement different functionality. So I made the command `next` optional given that not all controls are likely to implement it.
The next step would be to add it to the `?` documentation. However I'm not sure if I should always display this command or only if inside a Puzzle context (is there precedent for contextual keyboardMove documentation?)
> feat: add keyboardMove command for moving to next puzzle

- ui/mod/src/inquiry.ts
i.e. when it's just ending a sentence instead of doing a field access like "sort.order" in an advanced serach URL
> Don't linkify period with nothing after it

- modules/report/src/main/ReportApi.scala
- modules/report/src/main/ReportScore.scala
https://hq.lichess.ovh/#narrow/stream/34-mod-dev/topic/report.20accuracy
Not sure if this might have been intentional, definitely seems weird though, see linked discussion
> Don't apply report accuracy to non-cheat reports

- ui/analyse/css/_analyse.free.scss
- ui/analyse/src/ctrl.ts
**Importing a PGN doesn't update material difference until the next time the board is updated**
1. Go to the analysis board and **make sure computer eval is off**
2. Set the PGN to `1. d4 e5 2. dxe5`
3. The one pawn material difference doesn't appear unless you reload the board
This happens because the [material diffs are calculated using chessground's current state](https://github.com/lichess-org/lila/blob/7b92fe1f60d338761bf88cbedcc02ede689b9aeb/ui/analyse/src/view.ts#L313). During the redraw, this calculation happens before chessground gets updated to the new PGN so the material diffs end up not correctly reflecting the game state.
My fix here just manually sets chessground's board state before the redraw happens so the calculation proceeds as expected.
---
**Import PGN button is not …
> Two bugs with PGN imports on analysis board

- modules/setup/src/main/AiConfig.scala
Resolves #11377. Even when the user wanted to start an unlimited time mode game with the computer, we were enforcing the rule that the time (their last entered real time "time" setting) be greater than or equal to one minute. Make sure that we only enforce that rule when we are in the real time time mode.
> Narrow logic for computer time control check

- app/views/tournament/side.scala
Tested with shield tournaments as well
This also gives them a max-height of 20vh which means medium-length descriptions that previously fit will now scroll but otoh if there are a few streamers, the chat is currently basically unusable with longer descriptions.
> Make description set via Tournament Manager scroll on overflow

- ui/site/css/ublog/_card.scss
`3vmin` creates comparatively huge margins around the cards on high-res monitors with downscaling which leads to 2-column layouts and ridiculously oversized cards compared to everything else.
`1.5em` seems about a reasonable amount for pretty much all screen sizes.
> Avoid huge margins around ubloc cards on large monitors

- modules/appeal/src/main/Appeal.scala
Avoid bumping appeals with old replies after the mod response to the top by using a new message as the new sort date if the previous one was older than 2 weeks.
2 weeks is kinda arbitrary but seems like a safe amount to be very certain old appeals don't get lost.
> Don't prefer appeals with old responses

- ui/chess/css/_zh-pocket.scss
CSS background for .pocket class was only working for "min-width: 800px".
The background was black, making pieces almost invisible.
> Add grey background to the .pocket class

- ui/analyse/src/persistence.ts
Last week, we set the initial path correctly.  This week, we're setting the initial ply correctly.  Next week, we break it all again.
fixes #11423
> launch correspondence analysis at latest game ply

- modules/appeal/src/main/Appeal.scala
Follow up/better version of #11432
Just realized it makes much more sense to just consider whether the last msg was read already.
> Don't prefer appeals with old read responses

- app/controllers/Account.scala
force reauth device to continue getting push messages, discussed by jas14, lakin, benedikt in lila-development discord.  they concluded revoking token(s) "seems reasonable".
> revoke device tokens on pwd change & 2fa in addition to logout

- app/views/analyse/replay.scala
- app/views/opening/show.scala
- conf/routes
- ui/analyse/src/serverSideUnderboard.ts
- ui/analyse/src/study/studyShare.ts
As observed by @brollin in https://github.com/lichess-org/lila/pull/11455#discussion_r961084894, https://lichess1.org/export/fen always redirects to https://lichess.org/export/fen.
That's because:
* We forgot to add nginx config when adding this route, so nginx redirects
* lila itself also [redirects unexpected domains](https://github.com/lichess-org/lila/blob/9e87d11d8b0bd19aa2818cc248b536370ce25375/app/http/HttpFilter.scala#L48). In particular these gifs don't have a file extension in the URL
We could add another exception there, but I like just changing `/export/gif/<fen>` to `/export/fen.gif?fen=...`.
> fix fenThumbnail from cdn redirected to lila

- ui/round/css/_user.scss
Fixes #11485 by placing the username in the right spot for rtl languages.
Pun intended.
> Use start instead of left to align ruser

- modules/swiss/src/main/SwissApi.scala
Originally implemented in https://github.com/lichess-org/lila/commit/15cd13d7759a898cc9d5c059dbd912dbe8f05007 but it's never actually called with `forfeit = true`.
Not sure if any other places should use it, mainly kickTeam and account closure.
> Actually forfeit swiss games on marks

- ui/tournament/src/search.ts
When searching players on tournament standing, this was before:
And after this change:
> Disable spellcheck for username search

- app/controllers/Challenge.scala
- modules/bot/src/main/BotPlayer.scala
- modules/round/src/main/Env.scala
Due to https://github.com/lichess-org/lila/commit/41ae99507ce16dcb156d8eb89df9c1cbc8546ddb
As far as I can tell, games only are `abortable` but not `abortableByUser` if they were created via the bulk pairings API.
> Fix API response when game isn't abortableByUser

- ui/site/css/tv/_side.scss
> Fix rtl alignment in /games

- modules/db/src/main/dsl.scala
i'm assuming that behavior is not intended.
also change `set` so that it can be safely invoked with no arguments (to support building `ElementProducer` sequences programmatically that might end up empty)
neither of these should break anything - the `set` change can save a bit of boilerplate but isn't really needed per se
> don't empty document when unsetting an empty list of fields

- ui/tournament/css/_leaderboard.scss
> Reduce the size of tournament shields on mobile devices

- ui/@types/lichess/index.d.ts
- ui/analyse/src/explorer/tablebaseView.ts
- ui/analyse/src/forecast/forecastView.ts
- ui/analyse/src/study/chapterNewForm.ts
- ui/analyse/src/study/studyView.ts
- ui/lobby/src/view/correspondence.ts
- ui/puzzle/src/view/side.ts
- ui/round/src/corresClock/corresClockView.ts
- ui/simul/src/view/results.ts
- ui/site/src/component/friends.ts
- ui/site/src/component/timeago.ts
- ui/site/src/component/trans.ts
- ui/swiss/src/view/header.ts
Currently, there is no equivalent for the scala `plural` function in the typescript code and `trans.plural` performs what the scala `pluralSame` function does. This renames the typescript `trans.plural` function to `trans.pluralSame` and creates a `trans.plural` function that has a similar interface to the scala code. If merged, the [wiki page for translation](https://github.com/lichess-org/lila/wiki/How-translations-work) should be updated.
Resolves #11587
> Refactor typescript trans.plural to mimic the scala codebase

- ui/common/css/form/_cmn-toggle.scss
Before: <img width="47" alt="image" src="https://user-images.githubusercontent.com/19309705/192150908-026d57d5-2860-48ee-b21e-e976f1d64882.png">
After: <img width="40" alt="image" src="https://user-images.githubusercontent.com/19309705/192150913-1847ea5c-f57d-4830-b4c8-40160a137f42.png">
> Don't make cmn-toggle button transparent in transp theme

- ui/analyse/css/study/panel/_server-eval.scss
- ui/analyse/src/serverSideUnderboard.ts
- ui/analyse/src/study/serverEval.ts
- ui/build
- ui/chart/package.json
- ui/chart/src/acpl.ts
- ui/chart/src/common.ts
- ui/chart/src/division.ts
- ui/chart/src/interface.ts
- ui/chart/src/movetime.ts
And also make it a bit more typesafe + some other small chart adjustments (see commit messages).
The chart module now builds type declarations but without js (--emitDeclarationOnly) to avoid accidentally importing stuff. The "dist" imports are kinda annoying but not sure how to make that work properly. Using "exports" in package.json didn't seem to work. I guess maybe it's not possible to do this without js files 🤔
Fixes #11617
> Fix ply cursor in study movetime charts

- ui/analyse/src/explorer/explorerConfig.ts
- ui/analyse/src/study/inviteForm.ts
- ui/analyse/src/study/studyTags.ts
- ui/analyse/src/view.ts
- ui/editor/src/view.ts
- ui/keyboardMove/src/main.ts
- ui/racer/src/view/main.ts
- ui/swiss/src/search.ts
Snabbdom removes `false` attributes, so to get `<input spellcheck="false" />` we'll pass `(string) 'false'` instead of `(bool) false`.
I also found some other username inputs so I disabled spellcheck for those too.
Related to my previous PR #11530
> Fix snabbdom false attributes

- ui/analyse/src/view/roundTraining.ts
I added a link and information simple before "accuracy" text, when user click on it, a link to description will be opened in new tab.
Closes #11567
Closes #11593
> Add link into accuracy report

- ui/@types/lichess/index.d.ts
- ui/analyse/src/ctrl.ts
- ui/analyse/src/serverSideUnderboard.ts
- ui/analyse/src/study/serverEval.ts
- ui/chart/src/acpl.ts
- ui/chart/src/division.ts
- ui/chart/src/interface.ts
- ui/chart/src/movetime.ts
- ui/game/src/interfaces.ts
And do some more refactoring for even more typesafety and less attaching stuff to DOM nodes.
Fixes #11679
The main fix is moving `pubsub.on('ply', (..) => chart.selectPly(...))` into the initializers in the chart module so that it's called when setting them up in a study as well.
> Fix acpl chart cursor in studys again

- app/views/appeal/tree.scala
- ui/site/css/_appeal.scss
On the Appeal page, it may not be immediately clear that the h2 is dynamic text. It looks like a normal page/section header, so it may be skipped over.
| - | - |
| ![Screenshot from 2022-10-09 14-27-46](https://user-images.githubusercontent.com/271432/194773965-b704e4e1-cf81-4151-820d-e323b0d17b97.png) | ![Screenshot from 2022-10-10 18-05-02](https://user-images.githubusercontent.com/271432/194959563-f5bcaf7a-9d8b-4804-8f06-021d653aedb9.png) |
| ![Screenshot from 2022-10-09 14-30-06](https://user-images.githubusercontent.com/271432/194773991-d0548cfb-afdd-4e4d-9bb4-594bc1ff791b.png) | ![Screenshot from 2022-10-10 18-04-23](https://user-images.githubusercontent.com/271432/194959589-09b284b6-48ab-4049-abab-7e2172622c39.png) |
| ![Screenshot from 2022-10-09 …
> Add styling for account status on Appeal page

- ui/@build/bleep/bleep.config.json.default
- ui/@build/bleep/package.json
- ui/@build/bleep/src/build.ts
- ui/@build/bleep/src/env.ts
- ui/@build/rollupProject/index.mjs
- ui/@build/rollupProject/package.json
- yarn.lock
rollup won't give us error info in the watch event, but at least make the generic error scary. I also moved from @rollup/plugin-typescript -> rollup-plugin-typescript2 as it gives better diagnostics (when run in config mode - ui/build). There are a few additional dev packages this brings but I think it's worth it.
> make bleep rollup failures scary and improve rollup --config ts errors for ui/build

- ui/common/css/component/_quote.scss
Fixes #11769
Doesn't seem like there's a nice way to make this work with transparency and seems like the border doesn't show up well on most backgrounds anyway so seems best to just remove it.
> Remove quote border on transparent theme

- ui/build
When I was setting up my local environment for the first time `ui/build` script failed with:
`Node version >=14.13 and <=18 required. Found: 14.20.1`
The version I have matches the criteria. The problem was that the regular expression we use does not work correctly with two digits numbers. I adjusted it to allow versions `14.2*.*`
> Adjust ui/build script to allow Node.js versions 14.20.*

- app/views/forum/categ.scala
- modules/plan/src/main/Currency.scala
- modules/swiss/src/main/SwissNotify.scala
Resolves #11826 
The change here
```
.flatMap { code => scala.util.Try(new Locale.Builder().setRegion(code).build()).toOption }
```
Prevents the deprecation error on JDK 19. `Locale.of` was an alternative but it breaks compatibility with JDK 18
> Reposition 'Your team boards' text

- app/views/base/layout.scala
- ui/site/src/component/serviceWorker.ts
The problem:  **Anyone who logs out does not receive web push notifications until up to 12 hours after they log back in (including new users).**  
When the most recent 12 hour localStorage-based WebSubscription reup timer has expired, a client calls /push/subscribe first thing on site load. If they are not logged in, AuthBody redirects the xhr fetch to /signup which returns 200 OK so the client thinks it has succeeded, causing it to reset the 12 hour reup timer.  Meanwhile, the user has no valid web subscription as far as lila is concerned.  If their session survives at least 12 hours beyond that, they will subscribe on the next reload.
This change requires a no redirect 200 to reset the timer.  It would be smart to also not call /push/subscribe unless/until there's a user session.  It is …
> ui register web push fix

- ui/round/src/socket.ts
- ui/site/src/component/socket.ts
I don't think explicitly closing the socket on `unload` does anything, but having an unload listener [prevents some browser optimizations](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event#usage_notes).
> remove window.unload listener from StrongSocket

- app/templating/GameHelper.scala
Adds parentheses back to player rating in the sidebar ([issue explanation with screenshots in forums](https://lichess.org/forum/lichess-feedback/please-return-back-the-parentheses-around-the-rating)).
> Fix regression: missing parentheses around rating

- app/templating/StringHelper.scala
I don't know what to suggest; French and Brazilian Portuguese do not pluralize zero.
> 0 video found -> 0 videos found (#11868)

- app/views/site/contact.scala
- translation/source/contact.xml
The full stop was duplicated in the UI:
Notably, this change will also have to be applied in the translations.
Alternatively, it could also be removed in the UI code:
<https://github.com/lichess-org/lila/blob/fdeaca9529c9038e758a9294ff2ae31af56affa8/app/views/site/contact.scala#L184>
However, not including the full stop in the URL seems to be more consistent with the other pages.
> Fix typo in 'tryEnPassant' string

- ui/analyse/css/_action-menu.scss
On the [Analysis page](https://lichess.org/analysis) options, the CPUs and Memory range sliders don't show as 100% when you max out the values.
Before:
After:
> Analysis page settings slider styling

- app/views/ublog/index.scala
1. Browse to https://lichess.org/blog/community
`/blog/community`
2. Optional - Click the Language filter drop-down box and then select "English"
`/en/blog/community`
3. Click the Language filter drop-down box and then select "All languages"
`/all/blog/community` 404
This fix proposal routes 'language' "all" to the base route `/blog/community`
> 404 - Community Blogs - when (re-)selecting "All Languages"

- app/views/mod/search.scala
I guess this is some obscure Scala 3 change that `if`s without an `else` are now statements/return unit or something?
Did a cursory search and didn't find any other cases like this in `app/views`.
> Fix ban button on IP/print pages

- modules/forum/src/main/PostRepo.scala
Due to #11759 (specifically https://github.com/lichess-org/lila/pull/11759/files#diff-7cf58bc48ad004db530d19f1e8c89de585979ceefbed0e592fdc5a737497cfb5L100)
This means it will now just show the same top posts as the team forum page instead of hiding topics after 10 posts like it was before that PR. And I guess the "feature" button allowed Lichess mods to control what showed up there.
But not sure how much that matters? I guess we could also partially revert that PR and maybe have a feature button for team leaders as well but maybe too much of a niche feature and imo also hard to understand?
I guess an alternative if we do want to keep only showing the first few posts in a topic would be to just limit by the post number in the query but tbh it's not clear to me whether we actually want to …
> Fix team page forum section not showing new posts

- modules/tournament/src/main/TournamentApi.scala
Not sure there's any reason why it was like this before but tested it (also with a team battle) and seems to work fine.
> Remove cheaters from ongoing tournaments

- app/controllers/Timeline.scala
FIxes lichess-org/lichobile#2264
Using `UserId`s as keys causes a different serialization (as list of pairs instead of an object). Not sure there's a better way to fix this.
> Fix timeline json response for mobile app

- modules/db/src/main/dsl.scala
- modules/game/src/main/GameRepo.scala
- modules/irwin/src/main/IrwinApi.scala
- modules/mod/src/main/AssessApi.scala
- modules/mod/src/main/Gamify.scala
- modules/mod/src/main/ModActivity.scala
- modules/mod/src/main/ModQueueStats.scala
- modules/mod/src/main/ModlogApi.scala
- modules/playban/src/main/PlaybanApi.scala
- modules/report/src/main/ReportApi.scala
- modules/security/src/main/UserLogins.scala
- modules/user/src/main/UserRepo.scala
Primarily to fix all the sporadic mod zone failures.
I also changed it for some `aggregateList` calls but in hindsight, not sure if those actually do have failures like the cursors?
Though on the other hand, not sure if https://github.com/lichess-org/lila/blob/master/modules/mod/src/main/ModQueueStats.scala/#L41 alone explains all the mod stats/hall of fame issues.
Also, there are still a few irwin/kaladin related cursors but I don't know if there actually have been any issues with those.
> Temporarily read any mod stuff from primary

- app/views/forum/topic.scala
I guess not super sure we actually want embeds there but probably doesn't hurt? The half-broken behavior currently at least looks a bit weird, though I guess not super noticeable: https://lichess.org/forum/lichess-feedback/abort-a-game-at-move-27#2)
> Add twitter to CSP on forum for tweet embeds

- ui/ceval/src/platform.ts
- ui/ceval/src/util.ts
- ui/common/src/mobile.ts
Broken by #12005 (changed navigator.platform to userAgent which needs to check for "Macintosh" instead of "MacIntel")
Fixes #12049
> Fix iPad faking Mac detection and handle limited max wasm memory better

- modules/user/src/main/UserRepo.scala
I think this is probably the remaining part that's causing only some mods to show up? And it doesn't crash bc it uses Cursor.ContOnError?
Also used by [favorite opponent](https://github.com/lichess-org/lila/blame/master/modules/game/src/main/FavoriteOpponents.scala/#L23) though. Not sure whether that's an issue?
> Make stuff called by the mod leaderboard use temporarilyPrimary

- ui/common/css/component/_lichess-pgn-viewer.scss
Primarily to fix the PGN display.
Not sure about the menu background but to make the black text in the light theme work the bg has to be light and to make it clear and readable, it needs to be rather opaque. Alternative would be to give it a separate style in lpv.
Also, in dark mode, the variations and comments are now lighter than the moves (comparing the before and after, it weirdly looks like the colors have been swapped but that's just an illusion, the moves still have the same background color, though the font is slightly lighter). Tbh I think I slightly prefer how it looked before but on the other hand, this is how it looks on the analysis board as well, so not sure.
Also re-ordered the variables to match the definitions in lpv.
|Before|After|
|:--:|:--:|
|<img width="665" …
> Fix pgn viewer light theme

- pnpm-lock.yaml
- ui/site/package.json
Until this gets resolved: https://github.com/nhn/tui.editor/pull/2742
Causes issues like `**heading**:` being converted to `<strong>heading</strong>:` which will be rendered as is i.e. non-bold showing the HTML tags.
3.2.0 and 3.2.1 only introduced this bug and fixed something to do with plugins as far as I can tell.
> Downgrade toast ui markdown editor to 3.1.10

- translation/source/site.xml
See #12124 
This fixes the notification for British English (translation/source), the other translations will have to be updated on Crowdin, I presume.
> Fix rating refund notification

- app/views/swiss/side.scala
- modules/swiss/src/main/SwissCondition.scala
Would probably be nicer to use relative times but then it would get translated and getting the wording to match properly seems tricky.
> Display swiss ban end time with client time zone

- modules/fishnet/src/main/FishnetOpeningBook.scala
We could consider adding a timeout like this. There are tail latencies, and with so many requests even p99 would happen a lot, so this would probably also need something to reduce noisy logs like
```
[info] [info] fishnet - Request timeout to explorer.lichess.ovh:443 after 800 ms
```
> limit impact of explorer hickups on fishnet

- pnpm-lock.yaml
- ui/site/package.json
Working version of https://github.com/lichess-org/lila/commit/f0a4e2b762c8791d093a7470a44348d32550b3f5
Until https://github.com/nhn/tui.editor/pull/2742 is fixed which causes lots of markdown to emit HTML tags which won't work and also generates incorrect markdown in certain cases.
3.1.7 is the last version that handles this correctly (before https://github.com/nhn/tui.editor/pull/2572).
Checking the [history](https://github.com/nhn/tui.editor/commits/master/apps/editor), the only stuff relevant to us I can see that this downgrade loses is a minor bugfix: https://github.com/nhn/tui.editor/pull/2598
> Downgrade toast-ui/editor to v3.1.7

- ui/site/src/account.ts
I think that default got mangled in a merge somewhere, but this is a PR just to make sure.
I wonder if there's a better way to handle defaults for boolean prefs.  I appreciate the explicit nature of getOrDefault obviating the need for things like (x !== false) but it would be nice to have a single authoritative list of defaults for local prefs.
> Fix (one of) the default setting(s) for playBellSound

- ui/site/src/component/reload.ts
Otherwise, this causes issues when hosting Lichess with a subdomain, e.g. on gitpod, because the JS cookie will be set for a different domain than the cookies set via headers.
I assume this was originally there when we used language subdomains but I don't think we're doing anything like that anymore? Otherwise, I guess we could just send the correct domain with the cookie json.
> Use full domain when setting cookie from JS

- modules/tree/src/main/tree.scala
If a user's title changes, the titleName doesn't match anymore. Possibly also the same if they change the name casing.
> Compare study comment authors only by id

- app/templating/GameHelper.scala
`game.chess.ply.value / 2` gives the wrong value if white moved last:
I've tested `(game.chess.ply.value + 1) / 2`  and it works correctly for games where either side moved last as well as games that were aborted before any moves were played.
> Fix move number in link preview if white moved last

- modules/racer/src/main/RacerApi.scala
The idea behind this change is to make life easier for streamers hosting racers for their viewers. For this purpose it is important that the streamer is the owner of the racer so they have control over when it is started, while currently after the first racer has finished, the first user to click "Join rematch" will be the owner of the next racer and the only real way to get around this is to just create a new racer every time and not use the rematch feature.
The functionality that will be lost with this change is if the group wants to keep playing even after the original owner drops out, but I would consider this to be less important than what is gained. Presumably the friendly racers are generally used by streamers and actual friends who communicate frequently, so the problem of the …
> Continuing friend racers will keep the same owner as the original

- modules/shutup/src/main/Analyser.scala
- modules/shutup/src/main/Dictionary.scala
Makes "rat" match "rated". Most of the words are nouns anyway.
> shutup dict: Don't match past tense for all words

- modules/api/src/main/TextLpvExpand.scala
- modules/api/src/test/LpvGameRegexTest.scala
- modules/blog/src/main/BlogApi.scala
split TextLpvExpand regex into two to better suit each purpose, and add tests and comments to illustrate how these regexes are expected to work.
don't expand links inside site header of pasted pgn.  allow 'last' as a valid value for ply.  tested ublogs, forums, prismic.
Closes #11450
Closes #11951
> harden regexes to prevent failed game db lookups

- modules/round/src/main/RoundAsyncActor.scala
I guess this has niche relevance bc you can generally just make a move first but e.g. in Antichess, it's possible that making your move forces stalemate i.e. your loss in which case it's probably fair to allow the opponent to quit the game and still win.
> Disallow claiming draw if my turn

- ui/site/src/speech.ts
Reported in https://lichess.org/forum/lichess-feedback/text-to-speech-0-0-0-does-not-say-check
> Fix: text to speech 0-0-0+ does not say "check"

- modules/game/src/main/Game.scala
https://lichess.org/forum/lichess-feedback/bug-about-because-you-missed-your-last-swiss-game-you-cannot-enter-a-new-swiss-tournament
Players will no longer get a temp ban or get recorded as absent when their opponent resigns before they can make their first move.
This change also affects arena: it should prevent you from being withdrawn if your opponent resigns before your turn 1.
Was tempted to write this as `} filterNot winner.contains`, but ended up going the wordier and slightly more efficient route.
Small downside: this lets no-shows go scot-free if their opponent resigns in frustration. I think this is fine since this change only applies to tournaments, where opponents should prefer to take the free points rather than resign.
> Don't punish players in swiss when opponent resigns before turn 1

- ui/ceval/src/protocol.ts
So we can see when there are emscripten errors or similar.
> Log unexpected SF messages

- modules/shutup/src/main/Analyser.scala
- modules/shutup/src/main/Dictionary.scala
- Make all groups non-capturing
- Make all repetitions possessive (shouldn't change the result if the repetition doesn't contain the next character which is always the case here)
- Remove unnecessary repetition (we don't need to match "kill yourself and .." if "kill yourself" would already match anyways)
> Optimize shutup regexes

- modules/common/src/main/EmailAddress.scala
- modules/common/src/main/model.scala
The new email regex should behave exactly the same. The only changes are using `(?i)` and `[a-z]` instead of `[a-zA-Z]` and replacing `[a-zA-Z0-9-]{0,61}[a-zA-Z0-9]` with `[a-z0-9-]{0,62}+(?<!-)` which should match the same stuff but uses non-greedy repetition.
For the domains, it now allows leading hyphens and underscores in the TLD which previously wasn't allowed. The previous regex already allowed quite a lot of weird hyphen and underscore stuff though. But looks like it's only used for email domains which already disallow this stuff anyway? Would be simple to just change it to be like the domain part of the email regex though and disallow all this stuff.
> Optimize email and domain regex

- modules/api/src/main/GameApiV2.scala
For consistency (acpl is also there) and less code duplication. Since the field is brand new, was added for the app and the output isn't documented yet (only the accuracy query param), it should be fine to still change it?
> game api: Move accuracy into analyisis object

- modules/msg/src/main/MsgApi.scala
Fix issue where only one pre-existing conversation with a team member exists and a PM all is sent.
> fix team leader inbox sorting issue

- modules/shutup/src/main/Dictionary.scala
note: not merging `nigg?` and `nigg?ah?`,  the second may be moved to critical soon
> update en, critical

- ui/@types/lichess/index.d.ts
- ui/analyse/src/evalCache.ts
The main difference between `prop: undefined` and `prop?: undefined` is that even though that they are (without reflection) the same, `prop?: undefined` removes the necessity to explicitly define the type.
> refactor: optional maxDepth | millis

- app/views/oAuth/token/index.scala
Updates the the `authorization code flow` link on the [OAuth Token page](https://lichess.org/account/oauth/token) to point to the new section link.
This section was restored yesterday here: https://github.com/lichess-org/api/commit/0a6f9f4517a76d00683ad6067f18d4393bcbfc8e but it's now under the `/Introduction` section.
> Update OAuth code flow link

- ui/common/css/abstract/_media-queries.scss
Tested in FF and Chrome, they now both show the small layout on 799px and 800px. I went for slightly below since I think we want to keep the current layout on 800px screens.
> Fix $mq-not-... media queries

- ui/input/src/handlerUtil.ts
- ui/input/src/interfaces.ts
- ui/input/src/moveCtrl.ts
- ui/input/src/util.ts
- ui/input/src/voiceCtrl.ts
- ui/input/src/voiceMoveHandler.ts
A pretty simple change to account for the problem that Trevlar brought up where you say "bishop" followed by a pause because you are figuring out the name of the coordinate, but by the time you say the coordinate, it's an entirely new input.
Now you can say "bishop", or the name of any other piece, and we will save it as a partial move, updating the text to show "bishop...". It's kind of subtle, the fact that we have saved that piece name. If you really didn't want that piece, I added a command to "cancel". The cancel command could be useful in other contexts as well perhaps. All in all I think this "partial move" feature needs more improvement, but maybe it's a good starting point?
> Voice input partial moves

- app/views/tournament/faq.scala
- modules/tournament/src/main/Pairing.scala
Follow up to #11580
RK 20 => 10
ZH/KOTH 25 => 20
Some members of the RK community have pointed out that 20 is still way too high. Checking some stats again, the vast majority (~90%) of RK games and draws are shorter than 20 moves. Looks like originally, 15 was the suggested value but then it got bumped to 20 for consistency.
The ZH and KOTH adjustment is mostly for increased consistency. But checking some games, they do seem to have legitimate draws in that move range and are ofc generally shorter than standard games.
> Adjust variant draw streak thresholds

- conf/routes
This ad on the router side, hopefully negligible 
The other solution would be to assign the `ku` lang code to `Kurdish (Kurmanji)` instead of `kmr`, since we do not support other kurdish dialects. This solution would potentially be problematic with crowndin though.
> Expand lang regex in route to take into account Kurdish (Kurmanji)

- app/views/game/importGame.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/site.xml
Current design:
Prior was a bit too intrusive.
Another option was to display this warning only if the pasted PGN contained variations but was more complex to implement (rendering warning with forms)
> PGN import: warn that variations will be lost and redirect to study

- modules/puzzle/src/main/PuzzleTheme.scala
Due to an incorrect key, the en passant puzzle theme was not localized
Re-using the string from `trans.learn`, as it should be the same, and I believe this was the original intention.
Please test; I don't have the dev setup locally, and i don't know scala lmao
https://lichess.org/training/themes
> Fix incorrect I18nKey for en passant puzzle theme.

- ui/msg/src/view/msgs.ts
I noticed the date format in chat wasn't localized.
> Using Date.prototype.toLocaleDateString() for chat

- ui/analyse/src/serverSideUnderboard.ts
After https://github.com/lichess-org/lila/commit/103771011a3926f4f9449bdec1947b52cb67ccd4 @ #12544 , which mentions two problems, the first problem was solved (error console), but not the second one (mentioned as 6a & 6b in the Issue + videos @ https://github.com/lichess-org/lila/issues/12544#issuecomment-1474872958 ) : screen shake under certain resolutions (2560x1440 for me).
After the first fix, when scrolling and pressing/spamming z; the issue's 2nd sub-bug is still present : 
https://user-images.githubusercontent.com/2840135/226924187-bf9df795-4de6-47df-82f7-b7a189c6d8c0.mp4
After this PR : 
https://user-images.githubusercontent.com/2840135/226924249-463acdaf-4c1e-43e3-bce4-05f8488a3a83.mp4
Should I create a new issue for this ?
> ~Fix 2nd part of #12544 : Screen shake/scroll problem

- app/ui/scalatags.scala
- app/views/base/bits.scala
Mastodon requires `<a rel="me" href="https://mastodon.online/@lichess">Mastodon</a>` in the page(s) linked.
Further info/discussion: https://hq.lichess.ovh/#narrow/stream/63-content-social/topic/Mastodon/near/2505256 and following.
> Verify website on Mastodon

- public/oops/font.html
Path to font file is returning a 404 on https://lichess.org/oops/font.html
> fix path to font file on oops page

- modules/oauth/src/main/OAuthScope.scala
Hidden to regular users by: https://github.com/lichess-org/lila/blob/461b6bb7f1d7966128fa1cb52ca6ac5196223b67/app/views/oAuth/token/create.scala#L43-L46
> Show web:mod scope to mods on API token creation page again

- COPYING.md
Update the copyright year from 2012-2022 to 2021-2023.
> Update copyright year in COPYING.md

- app/views/appeal/tree.scala
- modules/user/src/main/UserMark.scala
Since the policy is to close marked account with a higher chance to sue, the appeal page can be misleading to those users if we show the alt-closed screen.
close https://github.com/lichess-org/lila/issues/12553
> Priorite visible mark over account closure in user appeal view

- app/http/ResponseHeaders.scala
The [endpoint to update an external engine](https://lichess.org/api#tag/External-engine/operation/apiExternalEnginePut) looks like the first API endpoint that uses PUT so adding that method to `Access-Control-Allow-Methods`
Fixes this error that I am getting:
> Add PUT method to Access-Control-Allow-Methods for API endpoints

- modules/tree/src/main/tree.scala
Without the Writes given, it writes them as ints which breaks chessground i.e. doesn't show any shapes in studies and for users without animations, doesn't update the board anymore after an attempt to draw a shape.
Probably also should deny the default opaque writer to avoid this but forgot how exactly to do that again. I guess maybe then it also wouldn't warn that it's unused anymore.
Fix https://github.com/lichess-org/lila/issues/12617
> Fix shapes in studies

- modules/tournament/src/main/Pause.scala
They don't give pauses on leaving so it's from a different earlier tournament.
> Don't consider tour join pause for tournaments that haven't started yet

- modules/chat/src/main/ChatApi.scala
- modules/chat/src/main/ChatTimeout.scala
- ui/chat/src/moderation.ts
- ui/chat/src/xhr.ts
Via the HTTP endpoint since non-team-members can't connect to the room anymore so timeout msgs via the socket don't work.
Not exactly the cleanest solution but at least makes it work. Letting mods connect to the socket would be nicer but seems a bit tricky to avoid showing their names.
> Make mod timeouts in teams work again

- app/controllers/Study.scala
- conf/routes
Closes #12548
Mirrored the all chapters API endpoint but I wonder if it really makes sense to return error JSON here 🤔
Not doing it certainly would make things cleaner. Though I guess maybe it also just makes sense to duplicate the bit of code instead of having a fairly small function with a lot of parameters 🤔
> Add /api/study/<id>/<chapter>.pgn endpoint

- ui/common/css/component/_lichess-pgn-viewer.scss
Fixes #12393
This commit fixes the issue by adding a background around the text, similar to dark mode.
**Before:**  ![before](https://user-images.githubusercontent.com/78294042/232368353-4a149583-6865-4494-8fd9-b940878a101f.png) **After:**  ![after](https://user-images.githubusercontent.com/78294042/232368363-6ce5cd7c-ca91-4e9e-a5d2-bea2951f987e.png)
> Fix: PGNs transparent background

- app/controllers/I18n.scala
Constructing raw URLs is deprecated since Java20, this is the recommended way to handle it: https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/net/URL.html#constructor-deprecation
The new version can throw several exceptions: `URISyntaxException`, `MalformedURLException` or `IllegalArgumentException` so thought it was better to handle general exceptions.
> Fix depreciation notice about `java.net.Url`

- app/views/tournament/crud.scala
- modules/tournament/src/main/crud/CrudApi.scala
- modules/tournament/src/main/crud/CrudForm.scala
close https://github.com/lichess-org/lila/issues/12692
I think we could refactor the tournament manager by just wrapping a normal tournament form with the additional fields, would also allow more flexibility. Will look into it in the future.
> Create unrated tournaments via the tournament manager

- translation/source/learn.xml
Change "Learn common chess.Positions" - > "Learn common chess positions"
> Fix a typo on Learn page

- ui/common/src/modal.ts
Fixes #12566
This fix ensures that the modal remains open even if a user clicks outside of it accidentally while the mouse is still down.
> Fix: modal close on mouse-up outside modal

- package.json
By default `prettier` will output a line for every file it will format, this definitely remove a sense of speed, but preserve your terminal output from spam.
Maybe break someone's workflow so made a PR.
> Set prettier log level to `warning`

- ui/common/src/modal.ts
I would like to apologize for accidentally undoing one of my changes while formatting the code. Specifically, I reverted the event from `'mousedown'` back to `'click'`. However, I'd like to clarify that the correct event is `'mousedown'` as opposed to `'click'` because of known issues with `'click'` events in Chrome since version 73.
> Fix: typo in modal.ts

- ui/puzzle/src/view/side.ts
The other solution was to disable the button, but then it was only added clutter for anonymous players. 
Close https://github.com/lichess-org/lila/issues/12673
> Hide the puzzle difficulty toggle for anonymous players

- ui/analyse/src/study/studyShare.ts
The issue was that we waited for the PGN http request to return before calling the clipboard API, and at that time it was already disabled back by the browser.
Safari fix is a simplified version of https://developer.apple.com/forums/thread/691873. Unfortunately, Firefox does not support the `ClipboardItem` so made a workaround.
Tested on Safari and Firefox.
> Study chapter: fix PGN to clipboard for Safari

- modules/security/src/main/PasswordCheck.scala
- modules/security/src/main/SecurityForm.scala
Not sure If it pass the utility/complexity threshold but still convenient to add users with easy to use pwd via the UI instead of fiddling with the db.
> Signup: disable weak password protection on dev instances

- app/views/game/mini.scala
- app/views/user/show/gamesContent.scala
- ui/@types/lichess/index.d.ts
- ui/analyse/css/study/panel/_multiboard.scss
- ui/analyse/src/socket.ts
- ui/analyse/src/study/multiBoard.ts
- ui/site/src/component/mini-game.ts
The snabbdom code was mainly taken from the code in swiss/arena to show ongoing games.
Tested on both finished and ongoing games, as well as update via ws. Should allow "easy" integration in a 2nd time (even though for now mini-game has a limitation about clock, re-putting it at the beginning of the turn at every refresh, that should be fixed for classical)
before:
after
> Use mini-game for broadcast multi-boards

- ui/analyse/src/study/studyShare.ts
Adds an empty href to give the Copy PGN button focus for tab navigation.
Resolves #12741
> Fix Copy PGN tab navigation

- modules/game/src/main/JsonView.scala
Adds `ratingDiff` to `/api/stream/event`. The ratingDiff is only displayed when the type is `gameFinish`.
I considered adding the [player method](https://github.com/lichess-org/lila/blob/master/modules/game/src/main/JsonView.scala#L77-L85) to the `ownerPreview` but thought adding the ratingDiff directly was more of a straightforward addition, and doesn't repeat data. If there is a better approach to handling this I'll gladly update the PR.
Resolves #12491
> Add ratingDiff to /api/stream/event

- ui/lobby/css/_lobby.scss
I've enhanced the legibility of text on lighter backgrounds for lobby blog cards by adding a subtle text shadow.
Before:
After:
> Fix: Improve legibility by adding a text shadow

- .gitignore
- bin/dependency-graph
- build.sbt
There were no issue regarding this PR, but maybe it may still be useful.
While working on lila I was advised not to add module dependencies to the build.sbt because it may lead to circular dependencies and break the build. However, I could not find any easy way to check this except try it out. Moreover, I could not answer: 
- Which module depends on which? 
- Is there a way to easily see if some dependency relation is no longer needed?
- What is the general structure/architecture of lila at all?
This PR adds a `bin/dependency-graph` script that for each module outputs all dependencies (explicit and transitive) and attempts to build a minimal set of essential explicit dependencies while preserving the overall structure. It also generates the graph as a png for better visual understanding. …
> Graph and clean build.sbt module inter-dependencies

- ui/puzzle/src/ctrl.ts
Fixes https://github.com/lichess-org/lila/issues/12717
With this fix, the redirect will only take place when the user clicks on the green "thumbs up" or red "thumbs down" icon, indicating that they have completed the puzzle.
> Puzzle replay: redirect to dashboard only after voting

- translation/source/site.xml
This is just a tiny change I thought would be nice to have.
There's already a transgender flag, this change further accommodates trans people (and all people with chosen names!), because "given name" usually implies it's the name assigned at birth
The term "first name" is just as common in British English as it is in American English (even though "last name" isn't)
> Change "given name" to "first name"

- modules/forum/src/main/ForumPostApi.scala
Since the topic is no longer bumped, it becomes hard to find. So the only way to continue a conversation is for remaining participants to aggressively ping each other
This has made it difficult for me to troubleshoot issues on long running feedback forum threads. I feel like it's overkill.
> don't stop timeline for large threads

- modules/study/src/main/StudyMultiBoard.scala
- ui/analyse/src/explorer/explorerCtrl.ts
- ui/analyse/src/explorer/explorerUtil.ts
- ui/analyse/src/study/interfaces.ts
- ui/analyse/src/study/multiBoard.ts
- ui/analyse/src/study/studyCtrl.ts
- ui/common/src/mini-game.ts
- ui/simul/src/view/pairings.ts
- ui/site/src/component/mini-game.ts
- ui/swiss/src/view/boards.ts
close https://github.com/lichess-org/lila/issues/12106
The change to the aggregation query has been isolated to this commit: https://github.com/lichess-org/lila/commit/24936cd48173b52ed002a1e2fb6a12cd6305c9c4. The change in size is mostly due to reformatting.
Globally I think the integration is quite clean and doesn't add that much complexity, beside the query being slightly more expensive.
Testing on the other end is hard because of complete lack of type checking and errors only happening at runtime. I've tested to the best of my abilities:
- Tested on real broadcast (pic above)
- Tested on Lichess game from start to end
- Tested on Lichess game from position where black start first (which permitted do discover a bug with the query)
Worst case scenario the query fail and the overview …
> Broadcast preview: add live clocks

- app/views/board/userAnalysisI18n.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/site.xml
- ui/analyse/src/explorer/explorerCtrl.ts
- ui/analyse/src/explorer/explorerView.ts
Fixes #12775 
This changes the error message when we get to the max depth of explorer analysis to the message mentioned in the linked issue.
> Change empty message on explorer max depth

- ui/common/css/abstract/_uniboard.scss
- ui/round/css/_app-layout.scss
Adapted from #9659
See #12839 for the same PR but with additional fallbacks to support really old browsers that don't support the CSS min() function.
Still the same idea:
Instead of guessing which values might work, calculate the maximum available space for the board by calculating the max height (basically as before) and the max width (100vw - everything left and right of the board if it's as small as possible). The board shouldn't be larger than the smaller of those two. This is our 100% scaling and everything else is just scaled from there. By moving the scaling to the outside, it's not really necessary to have an extra minimum since the scaling is already capped at 30%. Although I guess in theory, an extra minimum could be added.
I also increased the max-height slightly by not …
> Fix uniboard overflow

- ui/analyse/css/_layout.scss
- ui/common/css/abstract/_uniboard.scss
- ui/common/css/layout/_uniboard.scss
- ui/coordinateTrainer/css/_layout.scss
- ui/learn/css/_layout.scss
- ui/puzzle/css/_layout.scss
- ui/racer/css/_racer.scss
- ui/round/css/_app-layout.scss
- ui/round/css/_layout.scss
- ui/simul/css/_layout.scss
- ui/site/css/tv/_single.scss
- ui/storm/css/_play.scss
- ui/swiss/css/_layout.scss
- ui/tournament/css/_layout.scss
Same as #12837 but uses the old layout (before schlawg's changes) for browsers that don't support the min()/max() CSS functions. Though I ofc wasn't able to test the fallback part properly.
Not sure whether this actually makes sense. It's kinda ugly and such browsers are quite severely outdated and probably quite insecure. So far, I've also only seen one complaint. But Google doesn't seem to provide updates to Chromebooks for very long so I guess this applies to moderately old Chromebooks (roughly 7-8 years old it seems).
> Fix uniboard overflow with fallback

- modules/fishnet/src/main/AnalysisBuilder.scala
- modules/fishnet/src/main/JsonApi.scala
Refactor `Either[Skipped.type, Evaluation]` to
```scala
enum OrSkipped:
case Skipped
case Evaluated(eval: Evaluation)
```
I think It's nicer to have specific type than the generic `Either`.
> Make OrSkipped an enum

- ui/lobby/css/_lobby.scss
Addresses #12836
Here is the original:
Here is the difference with this PR:
And as discussed in the issue, here is the change with #12761 reverted:
> Add existing metal type BG for blog posts in lobby

- app/controllers/Simul.scala
I think not requiring any scope is fine because simuls are public (similar to export game endpoints), but otherwise can create a new scope.
Will edit api docs
> API: Allow to retrieve pending simuls when authenticated

- app/views/analyse/jsI18n.scala
- app/views/game/side.scala
- modules/user/src/main/UserContext.scala
- ui/analyse/src/view/actionMenu.ts
- ui/round/css/_meta.scss
Fixes #12562.
This is my proposal for a new "Delete" button location for imported games.
The changes remove the existing button (pictured below) from the analysis menu.
> Better display how to remove imported games 

- ui/analyse/css/_layout.scss
- ui/ceval/css/_eval-gauge.scss
- ui/common/css/layout/_uniboard.scss
- ui/coordinateTrainer/css/_layout.scss
- ui/learn/css/_layout.scss
- ui/puzzle/css/_layout.scss
- ui/racer/css/_racer.scss
- ui/round/css/_app-layout.scss
- ui/round/css/_layout.scss
- ui/simul/css/_layout.scss
- ui/site/css/tv/_single.scss
- ui/storm/css/_play.scss
- ui/swiss/css/_layout.scss
- ui/tournament/css/_layout.scss
Since they apparently can't figure out on there own that they don't understand `min` in nested expressions (see also #12841).
> Fix uniboard layout fallback for old browsers

- ui/analyse/src/study/studyShare.ts
- ui/common/css/form/_form3.scss
Hello,
This PR is attempting to resolve [this issue](https://github.com/lichess-org/lila/issues/12403).
Right now this is how the UI change is looking like (the blue clipboard buttons):
Feedback would be appreciated.
> Clipboard action with icon for broadcast sharing 

- app/views/mod/inquiry.scala
- ui/site/css/mod/_inquiry.scss
https://hq.lichess.ovh/#narrow/stream/34-mod-dev/topic/advance.20game.20search.20presets.20for.20boost.20reports/near/2781136
> Inquiry: make "view games" a link to the mod game tables again

- modules/game/src/main/Source.scala
- modules/mod/src/main/AssessApi.scala
- modules/playban/src/main/PlaybanApi.scala
- modules/tournament/src/main/AutoPairing.scala
Fixes https://github.com/lichess-org/lila/issues/12932 according to the comments section.
The fix only affects the Scala 'Source' enum name used to populate the front-end 'Source' dropdown select list. 
Because the 'Source' int mapping remains equal to 5, no back-end update are required (URL path of tournament and arena search = /games/search?source=5").
> Rename source 'Tournament' to 'Arena' in advanced game search

- ui/common/src/storage.ts
only look for `analyse.` prefixed key when the value is missing.
> fix storedProp key without losing existing data

- app/http/HttpFilter.scala
- app/ui/scalatags.scala
- app/views/base/notFound.scala
- app/views/coach/show.scala
- app/views/site/bits.scala
- app/views/streamer/show.scala
- app/views/video/show.scala
- modules/common/src/main/HTTPRequest.scala
- public/oops/scheduled-maintenance.html
- public/oops/toomanyrequests.html
- ui/common/src/richText.ts
- ui/site/src/expandText.ts
Second attempt at #11614
Using the "credentialless" (formerly called "anonymous") attribute on iframes new in Chrome 110 to make YT/Twitch embeds work:
- https://developer.chrome.com/blog/anonymous-iframe-origin-trial/
- https://chromestatus.com/feature/5729461725036544
- https://developer.mozilla.org/en-US/docs/Web/Security/IFrame_credentialless
Chrome 110 just got released on the dev channel and should become stable in 4 weeks so probably still a bit early to merge but from cursory testing, everything seems to work. Probably still should be tested on .dev a bit once 110 is stable.
Also, I guess might make sense to create a custom iframe tag or something to always set the attribute?
> Use "coep: credentialless" with credentialless iframes on all pages on Chrome 110+

- modules/study/src/main/ChapterMaker.scala
- modules/study/src/main/StudyApi.scala
Currently lichess study chapter names are only partially related to the PGN Event tags. When exporting a lichess study, if a chapter _does not_ have an Event tag associated with it, an Event tag is automatically added with the form <Study Name> - <Chapter Name>. However, if an Event tag is associated with a chapter that is used instead. Additionally, when importing a PGN into a lichess study the Event tag is not used to initialize a chapter title. Instead, a default chapter title of the form "Chatper <N>" is used. Combined this creates a non-intuitive user experience for users that frequently import & export PGNs into lichess studies as edits to chapter titles are not reflected back in the exported PGN.
This commit addresses these issues by coupling the PGN Event tag with the lichess …
> Couple lichess study chapter names w/ PGN Event tag

- modules/user/src/main/UserForm.scala
FIDE ratings cannot be lower than 1000, let's use the correct limit.
> Update FIDE rating min.

- app/views/practice/show.scala
Found another. Back when embed studies were actually embedded (and not pgn viewers), there was actual mode parameter (relay, practice, embed, etc.) passed to the study initModule to differentiate site studies from embeds. During the controller refactor conflicts, I for some reason decided it was a good idea to create entirely fictional modules with those parameters embedded in the name.
> fix controller refactor & esm collision bug

- modules/security/src/main/DisposableEmailDomain.scala
anonaddy.com is an email forwarder just the same as simplelogin.io, that allows to create unique email addresses in order to protect privacy, increase security in case of data leak and provide some degree of anonymity.
> Allow custom domain email domains pointing to anonaddy.me.

- ui/analyse/src/ctrl.ts
- ui/analyse/src/practice/practiceCtrl.ts
When opening `/analysis?engine=eei_12345`, from an external client, the first load would have a console error and not activate the engine sidebar until you refresh the page.
I helped introduce the original bug in #12574
I also noticed there was an `ensureCevalRunning()` function so I used that instead because it will ensure that the computer option is enabled, running, and in a good state to start evaluating.
https://github.com/lichess-org/lila/assets/271432/865cd386-117d-4e50-9513-810991047fda
https://github.com/lichess-org/lila/assets/271432/f0b5ce1f-ceb1-4be6-a404-b1ebe7b88034
> Fix automatic selection of external engine on Analysis board

- app/controllers/ForumCateg.scala
- modules/common/src/main/LilaFuture.scala
- modules/forum/src/main/MentionNotifier.scala
- modules/puzzle/src/main/PuzzleFinisher.scala
- modules/relay/src/main/RelayFormat.scala
- modules/relay/src/main/RelaySync.scala
- modules/report/src/main/ReportScore.scala
- modules/security/src/main/GarbageCollector.scala
- modules/study/src/main/ServerEval.scala
Most of LilaFuture functions are already exists in cats. Either with A (for [Applicative](https://typelevel.org/cats/typeclasses/applicative.html)) or M (for [Monad](https://typelevel.org/cats/typeclasses/monad.html)) suffix:
- filter => filterA
- fold => foldM
- find => findM
- exists => existsM
This also refactor `RelaySync.apply` function using for comprehension to make it easier to read.
> Use cats for LilaFuture & Refactor RelayAsync

- project/Dependencies.scala
Pleas use 15.4.2 over 15.4.1, it contains some performance optimization from https://github.com/lichess-org/scalachess/pull/440
> Bump scalachess 15.4.2

- ui/@types/lichess/index.d.ts
- ui/site/src/component/mic.ts
- ui/site/src/component/sound.ts
Maybe would be nicer to just set `AudioContext` on the window object but not super sure where a good place to do that would be 🤔 Maybe in `site.liches.globals.ts`?
> Use webkitAudioContext as a fallback for iOS Safari < 14.5

- modules/common/src/main/HTTPRequest.scala
Started getting login errors today. When submitting the login form, the POST request was getting a 404.
I did a git bisect and tracked it down to 51a47677e67bc1fb34d8e92f6487656e34737e0e
> Fix typo in crawler matcher regex

- project/BuildSettings.scala
- scalac `-Xtarget` is deprecated.
- scalac `-release` is an alias for `-java-output-version`
- javac `--release` is the new option (so it has to be better :D): https://openjdk.org/jeps/247
> Use `-release:17` for both scalac and javac

- ui/site/css/_blog.scss
The patron link [gets added to Lichess blog posts](https://lichess.org/blog/ZK7htxEAACUAYgoX/womens-world-chess-championship-half-way-done)
Visual UI tweak so it's not so close to the sides
| Before                                                                                           | After                                                                                            |
|--------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------|
| ![image](https://github.com/lichess-org/lila/assets/271432/33bcd59c-2bab-4fdc-9d23-2bb8f5e1a2e4) | ![image](https://github.com/lichess-org/lila/assets/271432/6ea4b332-36b7-426b-bc83-70a47455d4ed) |
> Add side padding to patron-info in blog footer

- modules/security/src/test/LevenshteinTest.scala
From default 30 seconds to 1 minute to void LevenshteinTest timeout: https://github.com/lichess-org/lila/actions/runs/5614742993/job/15213508733#step:5:308.
I see it happen at least twice.
> Increase LevenshteinTest timeout

- ui/common/css/vendor/chessground/_dark-board.scss
Fixes #12508
This pull request addresses and resolves the issue related to legal moves for the dark board background theme. The changes only affect the dark board background theme and should also make them more visible for other board themes.
> Fix: move-dest dark board background

- ui/site/src/component/sound.ts
Overall a touch more complex due to promise executor constraints, but better to isolate autoplay fail detection in resumeContext rather than embedded in play.
> Always Be Resolving

- ui/chess/css/_variant-style.scss
`%popup-shadow` got a blur in #13196
> Fix racing kings goal being blurred with transp bg

- ui/site/src/account.ts
Creating an API token can trigger duplicate browser `confirm()`s.
To recreate:
1. Go to http://lichess.org/account/oauth/token/create?scopes[]=team:lead&description=Test+Token
2. The URL automatically checks the `team:lead` permission (1 of the `isDanger` permissions)
3. Click Submit
4. You will get 2 browser `confirm()`s
This PR prevents [the handler in site.ts](https://github.com/lichess-org/lila/blob/71369a95062403e21780787fbd49994976ec06d6/ui/site/src/site.ts#L107-L109) from also being added for this form.
> Prevent duplicate browser confirm() when creating token

- modules/game/src/main/JsonView.scala
Fixes #13183
It may be tempting to, following this, use that "drawOffers" array (well, "Set"), to replace the use of the variable "lastDrawOfferAtPly" (added to JSON to fix #13139) in "ui/round/src/ctrl.ts". However "lastDrawOfferAtPly" is not normalized, while the Set are, meaning the value risk being +- 1 off.
> ~Fix draw offers missing when reloading (Fixes #13183)

- modules/analyse/src/main/Annotator.scala
- modules/api/src/main/PgnDump.scala
- modules/api/src/main/TextLpvExpand.scala
- modules/game/src/main/PgnDump.scala
- modules/game/src/main/PgnStorage.scala
- modules/game/src/test/PgnDumpTest.scala
- project/Dependencies.scala
With https://github.com/lichess-org/scalachess/pull/464
The PR above, removed `Pgn.toString`, so, something like `s"something$pgn"` will not work anymore. 
I reviewed all the places, we use `Pgn` but it's possible that I missed some.
Edit: I found one place using `Pgn.toString`: https://github.com/lichess-org/lila/blob/af19a5cef1cbb7e44c7240619790526d66f83c99/app/controllers/Analyse.scala#L81
So, I'll revert `toString` for Pgn to be safe.
Edit2: Fixed
> Scalachess 15.6.2

- modules/mod/src/main/Gamify.scala
It's been there since 2016 bb19f26f140b90fdec62137f5387f662a4862fe8, so maybe it's just a quick way of logging it?
> remove `.pp` in mod leaderboard gamify

- ui/@build/src/esbuild.ts
- ui/@build/src/tsc.ts
all ui/build tsc and esbuild error message filenames should now be ctrl-clickable with location in embedded terminals
> uniform filename format for ctrl-click in embedded vscode terminals

- modules/security/src/main/DisposableEmailDomain.scala
sapo.pt: https://mail.sapo.pt/
outlook.pt: Microsoft email in Portugal
> Domains in Portugal

- modules/common/src/main/AutoConfig.scala
Mostly to override default behavior that cannot be accurately represented by a single value. For example, a developer may override the delay calculation in FishnetPlayer with some value. This change allows us to rely on None for default behavior rather than nonsense sentinel values in base.conf.
> allow optional config values

- modules/security/src/main/DisposableEmailDomain.scala
It is also an alternative domain of ProtonMail
> Add "proton.me"

- ui/challenge/src/view.ts
Right now, it's kind of an obstacle that can obscure the accept/decline buttons unless you know what you're doing.
> move user popup to the side of challenge menu item

- app/controllers/Clas.scala
- app/views/clas/student.scala
- modules/clas/src/main/ClasApi.scala
This seemed pretty simple, but it's my first time touching any scala so feedback is welcome.
Fixes https://github.com/lichess-org/lila/issues/10736
Existing accounts that were invited to a class could be placed in 'Removed' status but then could only be re-invited or left in that state. This change lets them be taken out entirely.
> fix(classes): Make it possible to fully remove invited accounts

- ui/nvui/src/chess.ts
- ui/site/src/component/mousetrap.ts
Fixes #13165
- The fix makes it possible to move pieces on the analysis board in blind mode, similar to how it is implemented on a round board
- The issue was coming from the `mousetrap.ts` stopping key event propagation. The fix adds a `trap_bypass` attribute to the board buttons. Events on elements with this attribute are exempt from being trapped by `mousetrap.ts`
> Fix key bind for analysis board in blind mode

- app/controllers/Report.scala
- modules/report/src/main/ReportForm.scala
Show input error instead of 404 page when attempting to report yourself. Thanks to fitztrev for the initial work on the draft pr.
Self report error (new):
Fixes #13078
> Show input error if attempting to report yourself

- ui/racer/css/_zen.scss
Fixes #13433
This pull request aims to enhance the Zen mode experience in Puzzle Racer by addressing distracting elements that are currently present in the mode. This highlights the need for a more focused and serene Zen mode that aligns with user expectations. Furthermore, these changes will bring Zen mode's consistency in line with the rest of the puzzle-solving experiences across the application.
Puzzle Racer Zen Mode:
Puzzle Storm Zen Mode:
> Fix: consistent zen mode for puzzle racer

- app/templating/DateHelper.scala
> Fix how dates are displayed in RTL languages

- ui/lobby/src/setupCtrl.ts
There's an issue in the "Play with a friend" control where standard games with an unlimited time control can be played rated, but variants cannot. This differs from the "Create a game" control where _all_  game types with an unlimited time control cannot play rated.
In the PR I went with the comment the line above the changes that states unlimited games cannot be rated, and applied that as the fix. If friends should be able to play all game types rated with unlimited time control let me know and I'll get the PR updated with the proper fix.
**Video showing the problem:**
https://github.com/lichess-org/lila/assets/3620552/4a45bcc7-b7e3-430f-9fef-410b02fafd60
> Fix "Create a game" and "Play with a friend" control discrepancies

- modules/analyse/src/main/Info.scala
`traverseIndexM` is slower and building up stack
I did my benchmark [here](https://gist.github.com/lenguyenthanh/5d6f51c1678db2072236c5fab9d4195c) with results:
```
[info] CatsTraverseWithIndex.traverseWithIndexM               50  thrpt       232250.931          ops/s
[info] CatsTraverseWithIndex.traverseWithIndexM             1000  thrpt         9221.258          ops/s
[info] CatsTraverseWithIndex.traverseWithIndexM           100000  thrpt           61.646          ops/s
[info] CatsTraverseWithIndex.traverseWithIndexM         10000000  thrpt            0.329          ops/s
[info] CatsTraverseWithIndex.zipMapSequence                   50  thrpt       495305.959          ops/s
[info] CatsTraverseWithIndex.zipMapSequence                 1000  thrpt        16892.090          ops/s
[info] …
```
> Use zipWithIndex.traverse for traverseIndexM

- app/views/puzzle/theme.scala
- ui/puzzle/css/_themes.scss
> Fix how puzzle theme text is rendered in RTL languages

- ui/round/src/ctrl.ts
- ui/round/src/view/boardMenu.ts
Fixes zen mode toggling via the board menu. There's an issue where if you're spectating a TV game (l.org/tv/best), you _can_ toggle zen mode using the hotkey, but not via the board menu even though this page has a zen view. Additionally, if you are watching the TV channel _of a user_ (e.g. l.org/@/temp006/tv) the zen mode toggle should actually be disabled (which it is), but you can still use the 'z' hotkey and affect the zen toggle status (even though it won't do anything on this page as a zen view has not been implemented).
This change enables the zen toggle when necessary and blocks the 'z' hotkey from affecting the zen status when it's disabled.
**Screenshots showing the issue:**
Toggled via hotkey
> Fix zen mode toggling via the board menu

- app/views/plan/index.scala
- app/views/relation/actions.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/patron.xml
- ui/site/src/checkout.ts
This would add a new button on player profiles that links to `https://lichess.org/patron?dest=gift&giftUsername=Elizabeth`
Will prefill the donation form
> Add link to gift Patron wings from player profile

- app/views/puzzle/theme.scala
- ui/puzzle/css/_themes.scss
Unfortunately, I'm not a native speaker of Arabic, so I missed this when double-checking my original fix.
As you can see, `f7` is spelled backwards.
Before:
After:
> Correct the text direction when mixing LTR and RTL text.

- app/templating/DateHelper.scala
- ui/common/css/base/_elements.scss
- ui/site/css/ublog/_post.scss
In response to https://github.com/lichess-org/lila/pull/13461#pullrequestreview-1596825476, I have updated the fix to use CSS only.
Moreover, I have updated the fix so that the username appears beside the donor badge. I also validated the order of the date components with Google Translate: it should be `<year> <month> <day>` in RTL languages (e.g. Arabic, Farsi, Urdu).
Before:
After:
> Use CSS to fix how dates are displayed in RTL languages

- ui/analyse/src/explorer/explorerConfig.ts
In this example, we are opening up the Personal Opening Explorer player selection modal in the analysis board for Aleksandr vs. Jacob. Aleksandr is already in the search history, whereas Jacob is not.
Before:
After:
Please let me know if you'd like me to swap the colours that I'm using for the game participants and the players in the search history.
> Remove duplicates between game participants and username search history

- app/views/relation/actions.scala
Fix #13496
The `list` works for both patrons and non-patrons
> Fix Gift Patron wings for monthly patrons

- ui/site/src/checkout.ts
After clicking the gift link on a non-patron profile, the username is automatically completed, but the form buttons are not enabled.
Moves `toggleCheckout()` (used to enable the stripe + paypal buttons) to after the input values are automatically set.
Fixes #13498
Followup to #13395
> Fix gift checkout buttons

- app/controllers/RelayTour.scala
Fixes duplicate broadcasts being created via api by removing the second call to `env.relay.api.tourCreate`.
Fixes #13481
> Fix duplicate broadcast created via api

- ui/common/src/common.ts
Currently, clicking on the board menu button to close it won't trigger the click away listener so when you then immediately open it again you will have two listeners and clicking on the toggles in the menu will immediately close the menu because the toggle isn't contained in the old menu element.
> Fix click away triggering on old element

- modules/blog/src/main/Youtube.scala
- modules/blog/src/test/Fixtures.scala
- modules/blog/src/test/YoutubeTest.scala
The fix makes the iframe replacement regex more robust.
The problem lies on [the Racing Kings variant page](https://lichess.org/variant/racingKings): the embedded YouTube player doesn't work.
This happens because the Racing Kings iframe ends in `allowfullscreen="" title="Racing Kings variant - Blitz Chess w/ commentary"></iframe>`, which means that it is not picked up by the regex in https://github.com/lichess-org/lila/commit/ddc248d0ab14b345c97c008520ec04db7e14388d, which is supposed to detect the `iframe` tag and add the `credentialless` attribute. As a result, that attribute was not added to the YouTube `iframe` tag for the Racing Kings page.
Tests have been added for this extra case as well.
> Fix YouTube iframe for the Racing Kings variant page

- modules/gathering/src/main/Quote.scala
Noticed a few more inconsistencies etc. in the quotes file and this fixes them:
- "Chernev" -> Irving Chernev
- "Keres" -> Paul Keres
- "Euwe" -> Max Euwe
- "Teichmann" -> Richard Teichmann
- "Tevis" -> Walter Tevis
- "Bogolyubov" -> Efim Bogolyubov
- "Dostoyevsky" -> Fyodor Dostoyevsky
- "Mato" -> Mato Jelic
- "Victor Korchnoi" -> Viktor Korchnoi
- "Samuel Standige Boden" -> Samuel Standidge Boden
- "Rueben Fine" -> Reuben Fine
- "Frederick Milne Edge" -> Frederick Milnes Edge
- "Yefim Geller" -> Efim Geller
- "Soren Kierkegaard" -> Søren Kierkegaard
- "Baron Tassilo" -> Baron von der Lasa
- "Matthew Selman" -> Matt Selman
- "Jose Raul Capablanca" -> José Raúl Capablanca
- "Robt. Burton (1621) (clergyman and Librarian at Oxford University)" -> Robert Burton
- "Eugene Znosko-Borowski" & …
> Fix some more inconsistencies etc. in quotes

- ui/game/src/view/status.ts
The [scala code](https://github.com/lichess-org/lila/blob/8d769b28e1fd6e82ddffdf01eb06a739b58e358c/app/templating/GameHelper.scala#L215-L223) checks for threefold before checking for insufficient material. Updates the ts to do the same.
Fixes #13540
> Fix draw label for threefold games with insufficient material

- modules/round/src/main/CorrespondenceEmail.scala
The function `tick()` is run every 10 min, but the emails are sent in a timeframe of 11 minutes, so they can be sent at 5:00 and 5:10. That minute laps was set to be sure at least once per day an email would be sent, but it seems unecessary and produce way too more duplication emails.
fix https://github.com/lichess-org/lila/issues/12688
> Fix double correspondence email notification

- app/views/site/faq.scala
- translation/source/faq.xml
This
- changes the "fideHandbookUrl" link to the [current version](https://handbook.fide.com/chapter/E012023) which is in effect since 1 January 2023,
- replaces **_section 3.7 (d)_** in the "explainingEnPassant" string with **_sections 3.7.3.1 and 3.7.3.2_** as the former doesn't exist and is split into two sections,
- replaces **_Article 9.2 (d)_** in the "threefoldRepetitionExplanation" string with **_Article 9.2_** as the former doesn't exist.
And I wasn't sure if the corresponding translation keys should be renamed for this, so I left it out.
> Update FIDE handbook url & related faq entries

- modules/user/src/main/Flags.scala
A crossmatch between `public/images/flags/` and `modules/user/src/main/Flags.scala` showed that two flags are present in the repository, but haven't been added as user options.
> add flags of Netherlands Antilles, Canary Islands

- modules/activity/src/main/ActivityWriteApi.scala
- modules/activity/src/main/Env.scala
Includes activities for unlimited time correspondence games. I didn't immediately see a reason why unlimited correspondence games were omitted, but I'll close this PR if there is one.
Resolves #12908
> Include activities for unlimited correspondence games on profile

- ui/round/src/view/boardMenu.ts
Update to avoid seemingly unnecessary page refresh when flipping the board via the board menu when spectating a TV game (user or lichess TV). This also fixes the issue where if watching a users TV channel and the "flip board" button is pressed, it brings me to the game URL on flip instead of keeping me on the users TV URL.
> Update board menu to have consistent board flip

- ui/learn/src/assert.ts
- ui/learn/src/chess.ts
- ui/learn/src/stage/castling.ts
bugfix for Learn:Board setup 6 to not get stuck  and minor improvemens to castling lessons.
This attempts to solve: https://github.com/lichess-org/lila/issues/13581
I believe fully solving the stuck issues with the castling excersises will require patching chess.js
https://github.com/jhlywa/chess.js/releases/tag/v0.10.2
Probably worth looking into upgrading to a more recent release first as v0.13.4 seems to be latest.
https://github.com/jhlywa/chess.js/releases/tag/v0.13.4
If no one is attempting this I could look into it.
> bugfix for Learn:Board setup 6 to not get stuck 

- modules/setup/src/main/HookConfig.scala
- modules/setup/src/main/HumanConfig.scala
- modules/setup/src/main/SetupForm.scala
- ui/lobby/src/setupCtrl.ts
This PR addresses two related issues surrounding the setupCtrl modal.
The first issue is that the "Rated" game mode can be set on unlimited time control games (if "Rated" was previously selected for a different time mode), even though casual is only allowed. The game creation in this case is stopped correctly.
The second issue is the same, but via "Play a friend". However in this case I can successfully set up a rated unlimited game.
**Issue 1**
https://github.com/lichess-org/lila/assets/3620552/0ff1f0ad-4587-45cb-adfa-424b9bd62c35
**Issue 2**
https://github.com/lichess-org/lila/assets/3620552/66d67ef4-6aef-4588-beb4-82c5bfb0c124
> setupCtrl modal and rated unlimited vs friend fixes

- modules/history/src/main/RatingChartApi.scala
The highchart navigator on a users profile is not displaying the correct data series. It's being defaulted to "Bullet" as that's the first series in the chart (according to highchart docs). For those who do not play bullet, the navigator data is empty. This is a regression introduced in [this commit](https://github.com/lichess-org/lila/commit/12da21d30925ff7325963d19a4b4fb88e9aaabf9).
The navigator on a users profile should be showing the best rated perf data.
**Issue**
**After testing**
> Fix highchart navigator series used on profile

- ui/chart/src/ratingHistory.ts
Fixes the access of an undefined index that can occur in `ratingHistory.ts: initModule`:
From prod:
Unminified:
The above console error occurs when accessing the `/perf/standard` page of a player. Not high priority as this page generally won't be accessed as there aren't any links to it, but considering this is shared code with the other perfs, I figured it be best to ensure the index is available.
> ratingHistory - Fix access of undefined index

- app/views/lobby/home.scala
- ui/lobby/src/setupCtrl.ts
- ui/lobby/src/view/setup/components/fenInput.ts
Fixes related to the SetupController when "From Position" is selected (Play a Friend / Play with the Computer):
1) Currently, you can attempt to start a "From Position" game with the FEN input field empty. This causes a dialog to pop up and leaves the modal in an odd state where the spinner is still displayed instead of the color buttons. This PR disables the color buttons if the FEN is empty.
2) Currently, if you enter a valid FEN in the input a miniboard is displayed showing the position. If you delete the FEN, the miniboard is still displayed. This PR removes the miniboard when the FEN is deleted.
3) The board editor pencil icon next to the FEN input has a tooltip that reads "boardEditor". This PR adds the missing `boardEditor` translation to the i18nKeys list so the tooltip displays …
> SetupController "From Position" fixes

- ui/common/css/header/_topnav-visible.scss
It takes unnecessary care to properly click the last menu item in a drop down due to over-aggressive closure around the lower pixels. Instigated by #13665 but not sure the issues are the same so I'm reluctant to close it.
> add small chin to dropdown menus

- ui/lobby/src/view/setup/components/fenInput.ts
Fixes:
1. From position miniboard href uses default `/editor` link instead of the displayed position
2. From position miniboard is empty if the FEN input has prepended spaces:
> From position FEN input and miniboard fixes

- app/views/team/admin.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/team.xml
I'm trying to internationalize the phrase
"Only invite leaders that you fully trust. Team leaders can kick members and other leaders out of the team."
note:
I committed via gitpod
and when trying to test it only shows "team:onlyInviteLeadersTrust"
I may have done something wrong
> Internationalization "onlyInviteLeadersTrust"

- ui/lobby/src/view/setup/components/fenInput.ts
Update to use the default board editor path if the FEN input is invalid.
> From position: Use default board editor path on invalid FEN input

- app/http/HttpFilter.scala
- modules/mailer/src/main/AutomaticEmail.scala
Well this one took me forever to track down...
See a video of the _issue_ in detail here: https://github.com/lichess-org/lila/assets/3620552/cc7a9702-8995-4f37-ac8e-01c0e2ea5d04. I recorded the video on lichess.dev, but I assure you this same issue happens on prod. This issue is oddly dependent on browser, as I can only get this to replicate using Chrome (and not everyone can even replicate it using Chrome).
This issue isn't specific to _gifting_, but instead specific to the `/patron/list` page as it was adding credentialless headers and `/patron` is not.
Tested in my local development instance as I was able to get stripe set up. Video of fix in local development instance: 
https://github.com/lichess-org/lila/assets/3620552/d78d6d49-b8f9-44fc-aaca-7ed545f756ca
Also touched up the wording …
> Fix /patron/list donation buttons not working on some browsers

- modules/user/src/main/User.scala
Sometimes closed accounts stay on the leaderboard, my guess they are added after their closure by a rating-refund.
This will ensure it does not happen anymore.
Lichess forum: https://lichess.org/forum/lichess-feedback/closed-account-in-leaderboard#9
> make sure closed accounts do not re-appear on the leaderboard

- app/controllers/GameMod.scala
Otherwise the whole form was failing and the empty filter was used in place, with no visual feedback for the mod.
> Better fallback for gameMod when excessive number of games is put

- app/views/plan/index.scala
Centers the disabled paypal button text seen if gifting without a username entered. Changes do not affect the enabled paypal button.
**Before:**
**After:**
> Center disabled paypal button text

- ui/simul/src/view/created.ts
When a host creates a simul with multiple variants, the participants can select which variant they want for their game. They're presented a modal dialog after clicking Join.
This PR fixes a current bug where none of the buttons have any action when clicked.
Copied `domDialog()` behavior from [publicChats.ts](https://github.com/lichess-org/lila/blob/27f1db88d269c17a04ccdbdfa67ed9cda6bd4514/ui/site/src/publicChats.ts#L43-L62)
> Fix simul join dialog when multiple variants available

- ui/chart/src/ratingHistory.ts
This reverts commit 1c07e6b9f8a6be207e890ef59e3b4ed079faf66c.
I don't think it looks better, since the root issue is that unicode symbols do not have the same size, and it also introduce problems with alignment and rounding.
before the revert
fix https://github.com/lichess-org/lila/issues/13715
> Revert "Ratinghistory tooltip symbols"

- app/views/account/notification.scala
- modules/mailer/src/main/AutomaticEmail.scala
was broken since d9cb18bdcd12ac2b40ba950559c62e348f763712
For now the `id` link is a bit overkill, but I think it's a nice thing to have, and future proof in case the notification page grows longer
> Fix unsubscribe link in correspondence notification emails

- ui/common/css/component/_markdown.scss
- ui/site/css/ublog/_markup.scss
As long as the width is kept to 100% it's still easy to read/see by scrolling. This notably will allow data-analysis figures to be more readable, as they're usually the pictures with high heights.
For example, after the change https://lichess.org/@/oortcloud_o/blog/tell-me-the-elo/JGcZSVhN is much easier to read (can be tested locally by overriding the value in browser). The `450hv` comes from this blog post.
The introduction of the new variable `$img-max-height` is to minimise disturbance as it is also used in team descriptions or class, where larger images may not be wanted.
> Ublog: Increase max image height

- app/controllers/Swiss.scala
- app/controllers/Team.scala
- app/controllers/Tournament.scala
- app/mashup/TeamInfo.scala
- app/views/team/form.scala
- app/views/team/show.scala
- modules/api/src/main/ForumAccess.scala
- modules/team/src/main/Team.scala
- modules/team/src/main/TeamApi.scala
- modules/team/src/main/TeamMember.scala
Main change is in controllers/Swiss, to only consider actual team members with the Comm perm to be local mods so that real mods still get the full timeout view.
But to reduce confusion, I also removed the isGranted overload that only considered team perms (while the remaining one considers both mods and team perms) and renamed all other team-related isGranted methods that in reality only checked perms. Now, isGranted always checks both and hasPerm is used to only check the team perm.
I also noticed that the removed TeamApi.isGranted didn't check for team membership while hasPerm does. Not too sure about this but presumably, it's superfluous in hasPerm as well, since non-team members won't be in the members repo?
> Don't consider mods as local team mods in swiss

- ui/analyse/src/explorer/explorerConfig.ts
Deleting a player from the personal opening search history should unselect it.
Currently, the deleted player remains selected.
Before deleting "Boris" from the personal search history:
After:
> Unselect player in personal opening search history upon deletion.

- app/views/tournament/crud.scala
- modules/tournament/src/main/crud/CrudForm.scala
Once the team battle option is checked, the tournament cannot be changed back to a normal tournament. I think it used to be the same before
> Add team battle option back for tournament manager

- ui/site/src/forum.ts
If the incomplete mention ends with a dash or underscore it causes a 400 Bad Request bc that's an invalid username which currently causes the autocomplete to get stuck. Now, it at least won't get stuck anymore.
I guess ideally, such requests would also be allowed but that seems a bit annoying to implement since most of the search methods currently require a valid `UserId`.
> Fix forum autocomplete getting stuck on error response

- modules/common/src/main/base/LilaUserId.scala
All client-code for Lichess already check that and lichobile does too: https://github.com/lichess-org/lichobile/blob/663e69fab10e4267a9b3369febe85d1363816ba2/src/ui/players/PlayersCtrl.ts#L51
prompted by https://github.com/lichess-org/berserk/pull/48.
Note that currently it does sometimes return a result (undocumented), hitting the `userIdsLikeCache` cache, so maybe this is intended.
> Player autocomplete, return bad request for usernames shorter than 3 characters

- ui/lobby/css/_layout.scss
In current master, wide desktop layout with hide ratings will show:
Here's what I had in the lobby-tweaks branch, noone noticed the symmetry breaking. Doesn't bother me either, ymmv
> layout issue when ratings are hidden

- ui/round/src/ctrl.ts
As titled. There's some weird behaviour if the promotion dialog is open while the game ends. We should cancel any promotions when `endWithData` triggers. `promotion.cancel()` already checks if one is ongoing and no-ops otherwise so it should be safe to call in all cases.
See below for the before/after behaviour comparison. Screen recording wasn't working so I had to improvise.
**Before**
Weird post-game promotion:
https://github.com/lichess-org/lila/assets/30640147/144e0279-6621-44d6-ae83-a3aca4d94c1b
Promotion flips to other color during timeout:
https://github.com/lichess-org/lila/assets/30640147/0eba8891-d772-48d0-be1e-3d839056bc7e
**After**
https://github.com/lichess-org/lila/assets/30640147/dda1dc4e-b1bc-41cc-99d2-1a3e9fd02dfd
> Cancel promotion after game ends

- ui/analyse/src/study/studyView.ts
In the underboard of a study, the "tour button" (![image](https://github.com/lichess-org/lila/assets/3620552/7b0d2f18-e513-4a03-bae3-7ad135542054)) only works if the study is not an interactive (gamebook) chapter. This is correct [per design](https://github.com/lichess-org/lila/blob/master/ui/analyse/src/study/studyTour.ts#L5), but it's odd to click the button and not receive any sort of feedback. This PR removes the tour button if the chapter is interactive.
[Video showing issue](https://github.com/lichess-org/lila/assets/3620552/1a025a7c-fe0b-436a-a0a3-245d93e7f1da)
[Video of fix](https://github.com/lichess-org/lila/assets/3620552/1e25928e-0ffd-441e-974d-55ccc679c551)
> Remove study tour button from underboard on interactive chapters

- app/views/plan/index.scala
- modules/game/src/main/Namer.scala
Multiple browser console errors can be seen when navigating to `/patron` while not logged in. This is because the stripe and paypal scripts are started regardless if the div elements `paypal--order` and `paypal--subscription` are displayed ([code](https://github.com/lichess-org/lila/blob/master/app/views/plan/index.scala#L210-L222)).
This PR updates to only provide `moreJs` the frag to load the stripe and paypal scripts only when logged in, otherwise provide `emptyFrag`.
> Only load stripe and paypal scripts when logged in

- modules/security/src/main/SecurityForm.scala
The password reset form at `/password/reset/confirm/{token}` (sent via email) does not check if the new password is empty. Therefore, you can successfully set your password to all spaces. However, after the first auto login you cannot login again as the login form checks for an empty password.
> Do not allow empty passwords on /password/reset/confirm/{token} form

- ui/analyse/src/study/commentForm.ts
Fixes #13782
Enable Escape key to to blur the comment textarea so user can resume other keyboard shortcuts on the board.
> Blur study textarea on Esc key

- pnpm-lock.yaml
- ui/keyboardMove/package.json
- ui/keyboardMove/src/main.ts
- ui/keyboardMove/src/plugins/keyboardMove.ts
Resolving review feedback from #11252.
1. Uses opponent name from controller data instead of DOM. Would work with flipped boards now.
1. Typing "who" will always speak now, even if speech synthesis is not selected as the sound
> Keyboard shortcut "who" to read from controller instead of DOM

- ui/analyse/src/wiki.ts
closes #13877
If the extract given by Wikibooks is an empty string, but is still there, it currently throws that api error due to
https://github.com/lichess-org/lila/blob/a2f76a964261d1df724354ffceb023969bc973f6/ui/analyse/src/wiki.ts#L61-L62
Need to check that it is not empty first, so that it doesn't show an api error in this case
I chose to just show nothing as if the opening doesn't exist (because it doesn't in Wikibooks)
> fix wiki api failure if extract is empty but still present

- modules/study/src/main/StudyApi.scala
At this point, We already added the new node to the chapter successfully.
> Remove duplicated addChild action when add a node to Study

- ui/round/src/ground.ts
Update to always show the board resize handle when spectating a game. This would align functionality where the board resize handle is always displayed on puzzles and analysis.
Fixes #13902
> Always show board resize handle when spectating

- ui/puzzle/src/view/side.ts
Shows the ID of the puzzle in the top left
Hidden when puzzle is not yet completed
Shown when it is completed
Chose to hide it when not complete so it can't be played out in normal puzzles first to get the correct answer.
> Show puzzle ID in streak after puzzle is completed

- ui/site/src/component/timeago.ts
For many users, using the islamic calendar is not practical on the internet, due to international context, so we make sure it's displayed using the gregorian calender.
This was reported by and confirmed by native speakers. ~~`ar-ma`~~ `ar-ly` is a locale which displays the date in arabic while still using gregorian calender and latin numbers.
now renders like this:
close https://github.com/lichess-org/lila/issues/11893
> Use gregorian calender and western numerics for arabic users

- app/views/round/player.scala
Fixes #13904
This would have the side-effect of removing the css "fixed-scroll" from the body (only outside active/potentially-active games), but it was commented that it is for "dragging a piece out"; meaning gameplay shouldn't be affected. I also couldn't find any effective side-effect.
> Fix being in zen out of a game with in-game option

- ui/lobby/src/ctrl.ts
The current behavior after coming back on the homepage when last tab selected was `now_playing`
Now fallback to pools
> lobby: do not redirect to current games when no games being played

- app/controllers/Analyse.scala
- app/controllers/Study.scala
- modules/api/src/main/TextLpvExpand.scala
- modules/blog/src/main/BlogApi.scala
- modules/common/src/main/MarkdownRender.scala
- modules/common/src/main/model.scala
- modules/common/src/test/MarkdownTest.scala
- modules/hub/src/main/actorApi.scala
- modules/ublog/src/main/UblogMarkup.scala
- ui/site/css/ublog/_markup.scss
Fixes lichess-org/pgn-viewer#29 (by not embedding the private study at all).
Hopefully the padlock is enough to explain why the particular embed is not working.
Matches the icon at:
> distinguished link instead of embed for private studies

- modules/simul/src/main/JsonView.scala
- modules/simul/src/main/Simul.scala
- modules/simul/src/main/SimulApi.scala
- modules/user/src/main/UserPerfs.scala
- ui/simul/src/interfaces.ts
Currently, all simuls show players' rapid rating. (i.e. a blitz simul shows rapid ratings).
This fixes that so it shows the rating that corresponds to the simul's time control. (i.e. a blitz simul shows blitz ratings).
https://discord.com/channels/280713822073913354/352976626558042122/1169767913234894858
> show correct ratings in simul

- modules/simul/src/main/SimulApi.scala
Currently, if a simul host has two variants selected and then updates the simul to remove one of the variants, the players who joined with the removed variant remain there.
This fixes that by removing players of the wrong variant when the simul host updates the simul.
> remove players in wrong variant on simul update

- ui/analyse/src/study/studyXhr.ts
tested locally for both endpoints. fix https://github.com/lichess-org/lila/issues/13919
> Do not use `xhr.json` on study endpoints returning no content

- ui/site/css/tv/_games.scss
Go to https://lichess.org/games on a phone, and you will see the problem with overflow resorting to horizontal scrolling. Hard to screenshot.
This fixes that, while maintaining desktop view as the same.
> fix games page overflow

- app/views/site/faq.scala
Updates the autoplay page for Safari to display what will actually be shown for Safari users
> fix safari autoplay text

- ui/site/css/ublog/_post.scss
Fixes #13921 
Image credit after fix:
> word-break image credit text to fix layout issue

- app/controllers/Dasher.scala
- conf/base.conf
- modules/common/src/main/config.scala
Would it be possible to add a separate config value to fix an issue in gitpod/docker-compose environments? Ref lichess-org/lila-docker#15
In this case of the Dasher controller, the request to gallery.json is coming from the lila backend, and I need to customize the hostname to get the networking to work.
> Allow different asset url for requests from Dasher

- bin/mongodb/user-playtime.js
Calculates an approximate `time.total` value for users missing it by using the createdAt and updatedAt ISODate values from their game records.
To run:
```bash
mongo lichess user-playtime.js
```
To remove a local user's `time` value (for testing):
```js
mongo lichess
db.user4.updateOne({ _id: 'bobby' }, { $unset: { time: 1 } });
```
Tested on mongodb 4.4.25 and 5.0.22
Fixes #6995
> Add script to backfill user playTime

- modules/team/src/main/TeamApi.scala
`def $doc(elements: ElementProducer*): Bdoc = BSONDocument.strict(elements*)` used internally by `$set` did not produce fields when they were empty, so it was impossible to unset fields.
A cleaner version would have been to have a `updateOrUnsetFields(doc: Bdoc)` but there was no functions like that, so for one case it seemed a bit overkill.
fix https://github.com/lichess-org/lila/issues/13948
Another option was to make blocklist part of `Team` object. Generally it seems a bit funky that we both have a team blocklist AND set a declined join request.
> Fix removing fields from teams

- modules/round/src/main/Rematcher.scala
Fix illegal castles in rematch games where starting positions partially allow castles. Fix #13786
> Copy unmovedRooks when creating rematch games

- ui/analyse/src/retrospect/retroCtrl.ts
Frequently, when I use "Learn from your mistakes" I browse away from the main mistake node to look at a different variation and end up "solving" one of my mistakes. This is because it's checking the ply of the fault node against the current ply (even if browsed away).
This fix allows browsing away, and only allows solving when at the fault node.
**Video showing problem:**
https://github.com/lichess-org/lila/assets/3620552/f780c2b5-d09e-4103-96d9-0f4c0d4afcf7
**Video of fix:**
https://github.com/lichess-org/lila/assets/3620552/4399d8da-2277-470f-a6f9-6c03cbaff23c
> Fix accidentally solving retro mistake when browsed away

- ui/site/css/ublog/_post.scss
This pull request addresses Issue #14000, where the 'like' button on blog posts was observed to be cut off when viewed on the Safari browser. The issue was caused by insufficient margin on the left of the `ublog-post__like` type icons.
- Added additional left margin to the `ublog-post__like` icons in the `ui/site/css/ublog/_post.scss` file.
- Ensured that the change does not affect the layout on other browsers (Chrome, Firefox, Edge).
The added margin provides sufficient space to render the icons properly on Safari without affecting their appearance or layout on other browsers. This solution was chosen for its simplicity and effectiveness in resolving the display issue specifically on Safari.
The changes have been tested on:
- Safari
- Chrome
- Firefox
- Edge
No adverse effects on the …
> Fix issue #14000: Correct blog like button cut-off on Safari

- app/views/account/pref.scala
- ui/site/css/_account.scss
Every now and then, a person does not know that a configuration exists and asks or complains about not knowing that this configuration exists
My idea is to add a tag for each configuration
and with a link style (like `md` does with titles)
As soon as the person complains about something missing, just send the link with the selected configuration rather than just sending the page link
the only thing missing was CSS
> Add an ID for each config

- app/views/blog/index.scala
- ui/site/css/_blog.scss
resolve #14001
Weird text flow of intro paragraphs in trevlar's blog. This PR proposes a basic flex layout rather than text flow.
Before:
After:
> dont flow text around blog image in teaser

- app/Env.scala
- modules/common/src/main/config.scala
- modules/user/src/main/Env.scala
- modules/user/src/main/UserFlair.scala
Similar request to #13937 - gitpod/docker environments use an `assetBaseUrl` that is not resolvable from lila's container, only the host.
Error was only visible in the logs after adding:
```scala
.recover { case e =>
logger.error(s"Cannot fetch $listUrl", e)
}
```
I had to add the opaque type back in and unsure if this is the right way to do it, but it works.
> Use internal asset base url to fetch flair list

- ui/ceval/src/engines/engines.ts
- ui/ceval/src/types.ts
- ui/ceval/src/view/main.ts
- ui/common/src/device.ts
* Make the engine requires an array to support this change.
* Removes dynamicImport as a feature for any user on firefox < 114.
* Adds dynamicImport as a require for SF16 engines.
Fixes https://github.com/lichess-org/lila/issues/14029
> Add dynamicImport as an engine require

- ui/ceval/css/_ctrl.scss
- ui/ceval/src/ctrl.ts
- ui/ceval/src/engines/engines.ts
- ui/ceval/src/engines/externalEngine.ts
- ui/ceval/src/engines/simpleEngine.ts
- ui/ceval/src/engines/stockfishWebEngine.ts
- ui/ceval/src/engines/threadedEngine.ts
- ui/ceval/src/types.ts
- ui/ceval/src/util.ts
- styled to pre-select error text on focus
- now used throughout the engine family
- if unnecessarily dialogs are shown due to spurious stderr text from some random engine, we can spot fix. but we want to hear about any exceptions.
> show engine error dialog always and forever

- ui/puzzle/src/view/side.ts
> Puzzles: do not show online status of players

- ui/chart/src/common.ts
- ui/chart/src/movetime.ts
| Before |  After |
| --- | --- |
|![old](https://github.com/lichess-org/lila/assets/53343585/7da7364b-5a07-403e-9e23-90639a1b9378) | ![new](https://github.com/lichess-org/lila/assets/53343585/5017dadc-5408-4360-9d36-cf864de797fc)|
> Fix movetime graph not filling entire canvas area

- ui/chat/src/spam.ts
I discovered a rise of several url shorteners that are used to hide suspicious or NSFW urls.
I added those to the spam regex, so those will be filtered in lichess.
Those pages were:
t.ly
shorturl.at
> Added additional suspicious URL Shorteners to spam

- ui/site/css/user/_list.scss
- ui/tournament/css/_leaderboard.scss
removed the border from the large box and added borders from the smaller sections
#14142
> 14142-leaderboard border styles

- ui/lobby/src/view/setup/friendContent.ts
https://github.com/lichess-org/lila/issues/14153
Couldn't find a way to get the `online` status of the `u` :(
> hide online status when challenging

- modules/streamer/src/main/StreamerApi.scala
Even if the ratio of additional fake streamers in limbo versus support instances reduced is like 100x1, this might still be worth it.
Case in point, timochka_cutie in Ukraine was re-approved this week (a measure that has been taken multiple times over the past year), but still has no `liveAt` in the db and will not be able to stream for another month. With the 1 week window, we'd have to re-approve him before that happens.
> bigger activation window for well-intentioned but occasional streamers

- ui/editor/src/ctrl.ts
- ui/editor/src/view.ts
-Remove an unused sort()
Relates to #14139 and PR #14165 
Notes : 
- I can cut half the option of the select (the opposite color possible en passant), as it is safe to do so and the bug mentioned in PR 14165 cannot occur due to enPassant pawn being reset when changing color.
- Sort isn't used as the values checked against don't need to be sorted anymore (since they are not calculated to be shown, but to be compared against).
> -Board editor : Remove half unused En Passant options visible under Safari

- ui/dgt/src/config.ts
Re: https://hq.lichess.ovh/#narrow/stream/8-dev/topic/lila.20ui.20dgt.20exceptions/near/3095335
Resolves the following errors when visiting the dgt page:
From firefox:
From chrome:
> Resolve browser console errors on DGT page

- modules/user/src/main/Flags.scala
Correct name Asturia -> Asturias
https://en.wikipedia.org/wiki/Asturias
> Correct name "Asturias" in Flags.scala 

- app/views/team/show.scala
- ui/site/css/team/_show.scss
close #14089
i had used `" "` instead of `""`  
i could also do something like 
```scala
fragList(
t.publicLeaders.toList.map: l =>
userIdLink(l.some),
""
)
```
and 
```css
.user-link {
display: inline-block;
vertical-align: bottom;
padding-#{$end-direction}: 0.25em;
}
```
not sure what would be best
> remove comma from team leaders

- ui/@types/lichess/index.d.ts
- ui/analyse/src/study/chapterNewForm.ts
- ui/editor/src/chessground.ts
close #14204
i'm not sure why `coordinates` was coupled with the `embed` value so I created a new type field. hopefully, this didn't break somewhere else
> show study chapter coords

- ui/chart/src/acpl.ts
- ui/chart/src/interface.ts
Steps to reproduce:
1. Have a game where the first played move is inaccurate or worse.
2. Hovering over the advice changes the chart line color to the color of the first move's judgment.
Reproducible here https://lichess.org/Ne9qZ9Fy (or any other objectively bad opening like the Grob)
> acpl chart: fix christmastree hover bug

- app/views/game/importGame.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/site.xml
in my previous pr on data privacy on importing games #14110 I mixed up the importgame caveats at the bottom of the page and as a result duplicated the first caveat, and that was removed later. Now I add importgame 2nd caveat on data privacy (differentiates) so Is better.
> use disused importGameCaveat2 key

- ui/common/src/userLink.ts
close #14256
noticed that in the the normal game view there are two spaces between the ratings that's why i went with this
> space between username and rating

- ui/@types/lichess/index.d.ts
- ui/site/src/component/log.ts
- ui/site/src/component/socket.ts
- ui/site/src/component/storage.ts
- round robin (rather than random) selection of socket name on failures
- random selection of socket name on ttl expiry
- ttl is every 30 minutes ~~but can be given in millis with `data-socket-change-ttl` attribute~~
- call `lichess.log` when rotating socket names due to error
- i believe there are scenarios where an unclean close can happen without an `error` event. on the other hand we always get `'close'` events for a successfully constructed socket. so all our failure logic is just in `onClose` now, and we call that manually when the socket cannot be constructed.
> round robin and log ws failures to idb, add ttl

- conf/routes
Prevents CORS error
Similar PR to #14241
> Alias broadcast pgn push to /api prefix

- ui/ceval/src/engines/engines.ts
- ui/ceval/src/types.ts
allow brave warriors a way to test sf16 on brave, and hopefully isolate those errors.
> add local storage key to force enable lila-stockfish-web

- modules/relay/src/main/JsonView.scala
Adds `createdAt` for both the broadcast tournament and round info.
Use case is to be able to show this in a client UI to help when displaying lots of rounds.
> Add createdAt in broadcast api response

- modules/common/src/main/HTTPRequest.scala
[httpie's --json flag](https://httpie.io/docs/cli/explicit-json) sends this Accept header by default
```
"Accept": "application/json, */*;q=0.5"
```
```bash
http --json httpbin.org/get
```
Example, this sends that header but doesn't return JSON.
```bash
http --json https://lichess.org/broadcast/-/lZo9v6Nu
```
> AcceptsJson to work with httpie's default --json header

- app/views/user/bots.scala
- ui/site/css/user/_list-bot.scss
Fix for #14336. 'overflow-wrap: anywhere' is applied to both featured bots and community bots. See attached screenshot
> fix for massive single line on bot page

- modules/shutup/src/main/Dictionary.scala
"hijo de perra" for es dict.
Turkish regex can capture more creative swear words now.
> Update  ES and TR Dictionary

- ui/analyse/src/plugins/studyTour.ts
- ui/analyse/src/study/chapterNewForm.ts
- ui/analyse/src/study/interfaces.ts
Add a type for a study's chapter tabs like the one for study tabs.
https://github.com/lichess-org/lila/blob/d58f24d66ce56da2ca3bf92680d5c4eaa5151ecc/ui/analyse/src/study/interfaces.ts#L8
Noticed while working on #14358
> Add type for study chapter tabs

- app/views/dailyFeed.scala
Show dates and times instead of time ago on dedicated feed page (lichess.org/feed) #14348
> Show dates on dedicated feed page

- app/Env.scala
- app/controllers/Dev.scala
- app/http/CtrlExtensions.scala
- modules/common/src/main/HTTPRequest.scala
Fix what seems like a firefox origin trial expiration that prevents cross origin isolation on prod.
> update min firefox version for credentialless

- ui/puzzle/src/view/main.ts
Fixes #14393
The issuse was created #14277 which itself was introduced by 4a54a23. More specifically a76f4c3 and 0649bc5.
It was caused by changing to `looseH` which cannot handle a number, and which tried to re-unify 0 and null as the same value, which is not possible in this case. I rolled back to the old version.
I chose to use the original `h` function, so had to revert the `looseH` alias. It's more code but felt cleaner than aliasing h.
Tested for:
- rated
- unrated
- streak
> Fix rating diff being undefined when solving unrated puzzles

- ui/chart/src/common.ts
- ui/insight/src/chart.ts
The better color was already in use for insights. Color taken from highchart version, consultable here: https://web.archive.org/web/20200108113001/https://lichess.org/@/thibault
before
after
before
after
Well done @allanjoseph98 btw for finishing the migration! 🎉
> Better chart grid color on light mode for rating graph and distribution

- app/views/user/show/page.scala
- modules/history/src/main/RatingChartApi.scala
- ui/chart/src/ratingHistory.ts
- ui/common/css/component/_chart.scss
1. Fix perf chart not showing for variants. Edit- Closes #14394
2. Remove best perf index for user profiles. Was previously used in highcharts to construct a mini-graph of the user's best perf to display along with the time selector. Currently unusable with nouislider.
3. Change time-selector-button active color to be less harsh.
> Chartjs fixes part2

- app/controllers/ForumCateg.scala
- app/controllers/ForumTopic.scala
- app/views/forum/categ.scala
- app/views/forum/topic.scala
- bin/mongodb/diagnostic-categ.js
- conf/routes
- modules/forum/src/main/ForumCateg.scala
- modules/forum/src/main/ForumCategRepo.scala
- modules/forum/src/main/ForumForm.scala
- modules/forum/src/main/ForumPost.scala
- modules/forum/src/main/ForumPostApi.scala
- modules/forum/src/main/ForumTopic.scala
- modules/forum/src/main/ForumTopicApi.scala
- ui/site/css/_diagnostic.scss
- ui/site/src/component/log.ts
- ui/site/src/diagnostic.ts
- ui/site/src/forum.ts
- Before using this code, you must run `mongosh lichess bin/mongodb/diagnostic-categ.js` or `lila-db-seed/spamdb/spamdb.py`
- The #debug dialog gets a _send to lichess_ button.
- It takes you to a post/topic creation page with the dialog's contents prepopulated in the form.
- The new `diagnostic` category is only browseable with `Permission.ModerateForum`. Others will see it if they have an active diagnostics thread, but the category link just points to their topic. Regular users can't access and don't know about any other troubleshooting threads.
- Users and mods may delete these threads at any time.
> send diagnostics to lichess from debug dialog

- modules/plan/src/main/PayPalClient.scala
According to https://www.paypal-community.com/t5/Transactions-Archives/Subscription-Paused-by-paypal/td-p/2964741
> Suspended: If the funding source for a subscription (i.e. the card or bank account) is removed, all connected subscriptions will be automatically cancelled or suspended. If the subscription is suspended, it will remain as such until the funding source is updated.
Crucially could NOT test locally. Fix is based on prod Error log.
close https://github.com/lichess-org/lila/issues/14354
> Paypal: consider SUSPENDED subscription status as cancelled

- app/views/dailyFeed.scala
> Hey, I went to lichess.og/feed and noticed that the time shown is in UTC. This is the time shown on home page. ![image](https://private-user-images.githubusercontent.com/95964955/294870354-5d163da4-711f-40b0-9933-8080a8fa26fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTY0MDQsIm5iZiI6MTcwNDcxNjEwNCwicGF0aCI6Ii85NTk2NDk1NS8yOTQ4NzAzNTQtNWQxNjNkYTQtNzExZi00MGIwLTk5MzMtODA4MGE4ZmEyNmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEyMTUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NDIwNmZkZWNkZTg3Nzc1NTRjMTZiOGNjYzEyZmM1YTRiMmJhNjA1YWU0ZDc4YjQ …
> Fixed feed page time shows local time instead of UTC

- ui/build
- Check for the `pnpm` availability and provide a clue for the people who do not have the `pnpm` script installed.
- Fail fast with `set -e`.
> More robust UI build script.

- modules/report/src/main/ReportThresholds.scala
A bit spammy. With critical being 84 it will currently generate a burst even if there are mods instantly on it, so going over that seems wise.
> Increase comm burst score threshold

- ui/site/src/forum.ts
Currently, it includes all text inside an lpv embed and creates an unsightly long list.
> Forum post quotes: don't include lpv in quote

- modules/storm/src/main/StormJson.scala
- ui/puz/src/interfaces.ts
- ui/puz/src/view/history.ts
After deactivating the show ratings on my user I just noticed that on puzzle racer and puzzle storm history the puzzle rating is show despite having it deactivated. On other puzzle training the rating is not show.
The behaviour with this MR is the following: 
**With show ratings activated:**
**With show ratings deactivated:**
Note this is my first PR on the project and I'm not sure if I followed all the contribution guides.
Let me know if there is something I should fix/improve. 
Thanks for such amazin project!
> Honor show ratings setings in puzzle history

- app/views/dailyFeed.scala
- modules/blog/src/main/DailyFeed.scala
- modules/common/src/main/MarkdownRender.scala
This bug is upsetting my favorite broadcaster and his bots, so it has to go. This PR qualifies user mention links in the feed atom. I'm sure there's a better way to do this, so we're all counting on you to fix it in the merge. Godspeed.
> hack feed atom mention links

- ui/lobby/src/ctrl.ts
This is going to be useful for [LeelaKnightOdds](https://lichess.org/@/LeelaKnightOdds) and [LeelaQueenForKnight](https://lichess.org/@/LeelaQueenForKnight). :slightly_smiling_face:
> allow both 'fen' and 'user' in '#friend' URL (for the lobby)

- app/views/site/help.scala
- ui/puzzle/src/keyboard.ts
- ui/round/src/keyboard.ts
I am sympathetic to those used to the permanent mode. In games, `shift-B` would make toggling easier for players who are used to the dedicated blindfold account flow and find accessing the board menu at the start of each game to be a chore. This shortcut should have a reduced likelihood of mistaken blindfold activation compared to `b`.
> shift-b toggles blindfold

- ui/puzzle/css/_dashboard.scss
Line 67: `margin-#{$start-direction}: 2%;` is applied by default.
Fix is to ensure that the `--win`, `--perf` and `--fix` buttons have `margin-left: 0` and aligned with first child button when `@media` breakpoint is applied.
Fixes #14535
> Margin fix for buttons on puzzle dashboard

- app/views/study/jsI18n.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/study.xml
- ui/analyse/css/study/panel/_multiboard.scss
- ui/analyse/src/study/multiBoard.ts
Added show eval toggle on broadcast multiboard page. This currently only shows eval if it is currently available. Should this toggle request eval if it is not available? Closes #14497 
Also can you help me with ctrl.trans.noarg('Show Eval'), the playing above gets translated to other languages but this does not?
> Added show eval toggle on broadcast multiboard page

- modules/study/src/main/PgnDump.scala
This PR tries to solve issue:
https://github.com/lichess-org/lila/issues/14023
by not adding UTCDate, UTCTime tags to study chapter PGNDumps.
Related forum topic:
https://lichess.org/forum/lichess-feedback/why-games-dates-always-change-to-the-current-after-downloading-chaptersstudies?page=1
> Do not add UTCDate, UTCTime tags to study chapter PGNDumps

- app/controllers/Game.scala
- modules/api/src/main/GameApiV2.scala
- modules/game/src/main/PgnDump.scala
closes #14503
`division` is independent of `analysis`. Both the site and lichobile use it for movetime graphs even if there is no analysis available. Therefore, I've made `division` an independent field in case it's required in the future. I hope that's alright.
> Add game division to game json export

- ui/editor/css/_editor.scss
- ui/editor/src/ctrl.ts
- ui/editor/src/view.ts
Displays the url for the image which can be easily copy and pasted. URL updates as the position is updated. I think its probably better than displaying the image itself as that might mess up the UI. Close #14521
> Board editor: export position as image

- app/controllers/Ublog.scala
- modules/mod/src/main/Modlog.scala
- modules/mod/src/main/ModlogApi.scala
Use blogPostEdit log action for rank adjustement
Which also fix the issue where the modlog would be posted on the mod account instead of the poster account.
Delete ublogRankAdjust mod log. Too few actions made, and not recorded at the right place to bother with backward compatibility. Actions were discussed and copied to zulip.
run afterwards ```db.modlog.delete({"action": "ublogRankAdjust"})``` (data saved to zulip for accountability)
> Simplify and fix modlog for ublog ranking adjustment

- modules/api/src/main/Env.scala
- modules/api/src/main/PersonalDataExport.scala
- modules/mod/src/main/ModlogApi.scala
Tested. I could import `modLogApi` directly but not `shutupApi`, I'm not sure why but I assumes it's because it was not yet initialised at that point.
> Personal export: include dubious chats and timeouts

- ui/analyse/src/ctrl.ts
- ui/analyse/src/interfaces.ts
- ui/analyse/src/study/serverEval.ts
- ui/chart/src/interface.ts
- ui/site/src/component/pubsub.ts
Redo of https://github.com/lichess-org/lila/pull/14549 
1. I've tried to include the spinner for as long as study analysis is going, simulating extra moves that sometimes happen during broadcasts. In my testing, it works.
2. Fixes https://github.com/lichess-org/lila/issues/14565
3. I erroneously committed a pubsub function that would keep being added to the callback stack everytime a view was called. To save myself and others from future similar mistakes, I've made the pubsub callbacks a set instead of an array. I don't see any reason why you would need to execute the same function multiple times within one pubsub event so I don't think this borks anything but again, I may be wrong.
> Acpl chart study spinner redo

- modules/push/src/main/FirebasePush.scala
When receiving a data message, it is up to the client application to react to it. So in order to update the badge number, it need needed in the `data` payload.
For https://github.com/lichess-org/mobile/issues/464
> Mobile: add the ios badge in FCM data payload

- lila
There have been some questions about `error: release version 21 not supported` in onboarding channel.
Having the `lila` shell script output warnings on unusual java configuration could perhaps help.
Warn if JAVA_HOME is unset.
Warn if JAVA_HOME is set, but differs from the java command on PATH.
Warn if the java command on PATH doesnt contain the module jdk.compiler.
```
$ export JAVA_HOME=""
$ ./lila
Java 21.0.2
Warning, JAVA_HOME is unset
sbt -Dreactivemongo.api.bson.document.strict=false
```
```
$ export JAVA_HOME="."
$ ./lila
Java 21.0.2
Warning, JAVA_HOME [.] is not the same as java on PATH [/opt/java/openjdk/bin/java]
sbt -Dreactivemongo.api.bson.document.strict=false
```
```
$ export JAVA_HOME="/opt/java/jre"
$ export PATH=$JAVA_HOME/bin:$PATH
$ ./lila
Java 21.0.2
Warning, …
```
> Add java/jdk sanity checks

- app/views/clas/clas.scala
This change resolves issue #14622 by removing the word 'and'. Also this code now displays '_1 archived class_' when singular and '_n archived classes_' when multiple.
Adding tested screenshots.
> Handling plurals and removing 'and'

- modules/forum/src/main/ForumForm.scala
I originally raised this to 30k on the sly, but I might need even more than that. And since it's getting up there, time for a PR I suppose. Although we only keep the most recent 100 log events in the clientside idb, some of them can be quite large such as:
```
2024-02-09 08:48:44.875 #3f6cfcb - /meX6rbWk/black - Uncaught TypeError: Cannot read properties of undefined (reading 'trim') - (lichess1.org/assets/_oQtF03/compiled/analysisBoard.min.js:1:25518)
TypeError: Cannot read properties of undefined (reading 'trim')
at $e.received (lichess1.org/assets/_oQtF03/compiled/analysisBoard.min.js:1:25518)
at lichess1.org/assets/_oQtF03/compiled/analysisBoard.min.js:5:5181
at A.print.A.printErr (lichess1.org/assets/_b6939d/npm/stockfish-nnue.wasm/stockfish.js:11:468)
at M …
```
> up diagnostic form cap to 100k

- app/views/site/help.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/site.xml
- ui/analyse/src/keyboard.ts
When using lichess to analyze openings or solve chess studies, one needs to frequently select a position evaluation annotation like `=` (equal) or `+-` (white is winning) – much more frequent than _Zugzwang_ or similar symbols; more times than the existing move annotation glyphs (`?!` `?` `!!` etc.).
Use Shift+1 to Shift+8 for these, analogous to 1 to 6 for the move annotations.
Likely, the help text for move annotations should be changed (no chess player knows what a _glyph annotation_ is, but a _move annotation_ is widely known), but as I am unfamiliar with the i18n system, I'll leave that for a future PR.
> Make position evaluation glyphs available via shortcuts

- ui/chart/src/ratingHistory.ts
Fixes #14683 in my testing.
But I created the issue for future tracking just in case.
> Explicitly zoom rating history chart on initial load after slider creation

- ui/common/css/component/_markdown.scss
Can be seen on [the Changelog page](https://lichess.org/changelog)
| - | - |
| ![image](https://github.com/lichess-org/lila/assets/271432/ae845a8f-3cc3-477d-90e6-a9cb271cf056) | ![image](https://github.com/lichess-org/lila/assets/271432/47e4693e-b9e1-4c48-87f2-7f45fe7d41db) |
> Fix wrapping text in markdown lists

- ui/puzzle/src/view/theme.ts
Fixes a code regression (introduced in a76f4c3a1577ed0ffc0c722833c6bbd2f1aeabb9 -> `ui/puzzle/src/view/theme.ts`) which is causing the "puzzle theme" menu to be displayed when playing Puzzle Streak. This menu should only be displayed when playing normal non-daily training puzzles.
> Fix regression: remove puzzle theme menu from puzzle streak

- ui/analyse/css/_zh.scss
Closes #14682 
> Drag and drop for extra pieces is very error prone atleast on phone. Click click functionality would be better.
What about this?
> Fix crazyhouse analysis overlap

- app/controllers/RelayRound.scala
Here is a suggestion of a restructuring of the JSON response of the the broadcast PGN push endpoint,
https://lichess.org/api#tag/Broadcasts/operation/broadcastPush
It changes from JSON array of name:value objects,
to a single keys:values object.
Oh, as I'm writing this Pull Request, I realize that the original format might have the benefit of keeping a desired order of the tags... Well, opening the Pull Request anyways - in case order isn't important... :thinking:  
<details>
<summary>Before</summary>
```json
{
"games": [
{
"tags": [
{
"White": "Rasmus Svane"
},
{
"WhiteElo": "2632"
},
{
"WhiteTitle": "GM"
},
{
"WhiteTeam": "Germany"
},
{
"Black": "Rajat Makkar"
},
{
"BlackElo": "2453"
},
{
"BlackTitle": "FM"
},
{
"BlackTeam": "France"
},
{
"Result": "1-0"
}
],
"moves": 2
},
{
"tags": [
{ …
```
> Update JSON response format for Broadcast PGN push

- app/views/base/layout.scala
- ui/lobby/src/main.ts
- ui/site/package.json
- ui/site/src/devMode.ts
`ui/build --debug` adds a fake TV element to the homepage for debugging
- Ensure always a 2D board is displayed
- Adds titles, ratings, and clocks to be more like prod
| - | - |
| ![image](https://github.com/lichess-org/lila/assets/271432/95b43e5b-55ed-45f4-85a8-15c41815c8b5) | ![image](https://github.com/lichess-org/lila/assets/271432/f9ec4de2-a56d-459c-91a2-4b4120b7a54c) |
> Fake TV improvements to be more like prod

- modules/ublog/src/main/UblogRank.scala
This PR comes from my observation of mods managing content-blog and the constant shuffling of anyone at normal tier to high tier just to give them a shot at front paging (i.e. welcome them into the club). In a sense, high tier has become the new normal tier, normal tier is the new low/unlisted. And those tiers might as well not even exist. It's a race to the top resulting in an insular community of high visibility coaching ad purveyors, the membership in which much be meticulously micromanaged by our content team.
I would like to try an experiment where we flatten things a bit, and yes we will likely front page crap more often, but I think it's an acceptable tradeoff with increased opportunities for normal (and even low) tier bloggers to get some visibility or at least redeem themselves …
> flatten blog tiers

- app/views/video/bits.scala
- ui/pagelets/css/_video.scss
Fixes #14741
As proposed in #14743
> Remove Tags From Video Card Info

- ui/pagelets/css/coach/_show.scss
This should fix any hyperlink that is attached along with the content.
I was thinking of applying the styling directly to the section tag instead of the a tag (that has content as parent) but felt this is more precise and should fix the current issue. Let me know if this needs to be changed.
Before fix:
After fix:
> HTML will now wrap to the next line instead of overlapping

- modules/fishnet/src/main/FishnetPlayer.scala
Lila always send the last move to `lila-fishnet` even when the game is finished. This causes extra works for `lila-fishnet` and `fishnet` clients.
Example logs from `lila-fishnet`
```
Feb 28 08:21:10 starr lila-fishnet[3697036]: 2024-02-28 08:21:10,900 [io-compute-26] WARN  lila.fishnet.App - HTTP/1.1 POST /fishnet/move/Yuh568ZX Headers(content-type: application/json, accept: */*, authorization: <REDACTED>, user-agent: fishnet-linux-x86_64/2.7.0, host: starr.vrack.lichess.ovh:9665, content-length: 73) body="{"fishnet":{"version":"2.7.0","apikey":"sirch"},"move":{"bestmove":null}}"
Feb 28 08:21:10 starr lila-fishnet[3697036]: 2024-02-28 08:21:10,901 [io-compute-26] WARN  lila.fishnet.App - HTTP/1.1 422 Unprocessable Entity Headers(Content-Length: 29, Content-Type: text/plain; …
```
> Dont send move to lila fishnet if the game is finished

- modules/fide/src/main/Federation.scala
I don't have a big opinion on this, but for consistency, and (IMO)
makes it a lot easier to read the definition as I don't have to
visually scan the line looking for `=`. This should apply for all
non one liner functions.
>  Put function definition on a separate line 

- modules/user/src/main/Flags.scala
Country named Turkey before officially changed its name to Turkiye. 
Some related news and sources for confirmation: 
1) https://www.un.org/en/about-us/member-states/turkiye
2) https://turkiye.un.org/en/184798-turkeys-name-changed-t%C3%BCrkiye
3) https://www.theguardian.com/world/2022/jun/03/turkey-changes-name-to-turkiye-as-other-name-is-for-the-birds
> Country name Turkey officially changed to Turkiye

- modules/study/src/main/Node.scala
Close #14637
- Makes the same value of the games [played](https://github.com/lichess-org/lila/blob/6c52b5363d0185b579754123db488822e2771dfa/modules/game/src/main/Game.scala#L604) and [imported](https://github.com/lichess-org/lila/blob/6c52b5363d0185b579754123db488822e2771dfa/modules/importer/src/main/ImporterForm.scala#L42)
- Making it possible to import the game played from lichess to studies
- Solve the [World Cup](https://lichess.org/broadcast/2023-fide-womens-world-blitz-championship/round-16/icV7Z1EB/p1elo9yr) problem (219 moves)
- Reducing the possibility of it happening again
- reduces users a little from complaining about little
I know it's to reduce DoS, but it's also affecting the content area unfortunately
> Study: up max_plies to 600

- modules/puzzle/src/main/JsonView.scala
They're equivalent as example below:
```scala
val xs = List(1,2,3,4)
xs.foldLeft[Option[Int]](None) {
case (None, y) => Some(y)
case (Some(x), y) => Some(x + 2*y)
} // Some(19)
xs.reduceOption((x, y) => x + 2*y) // Some(19)
```
> Use reduceOption instead of foldLeft[Option]

- modules/gameSearch/src/main/GameSearchForm.scala
- modules/gameSearch/src/main/Query.scala
Fixes #14299 . Along with the corresponding pr to `lila-search` (https://github.com/lichess-org/lila-search/pull/184)
> Fixes Variant: Standard not working on `/games/search`

- pnpm-lock.yaml
- ui/@types/lichess/index.d.ts
- ui/pagelets/package.json
- ui/pagelets/src/user.ts
- ui/round/package.json
- ui/round/src/ctrl.ts
- ui/round/src/interfaces.ts
- ui/round/src/plugins/tour.ts
- ui/site/src/assets.ts
[hopscotch](https://www.npmjs.com/package/hopscotch) isn't maintained anymore. Our implementation actually doesn't appear to be working because neither of the selectors that it tried to attach to exist.
The first time you send a rematch to someone in a correspondence game and they are offline, it used to give a message. This PR recreates that but using [shepherd.js](https://shepherdjs.dev/), which is what we use for the guided tours on Studies.
> Remove hopscotch dependency, use shepherd.js

- app/views/base/bits.scala
> Add Lichess's Instagram to frontpage footer

- ui/lobby/css/_layout.scss
Set minimum height when only Tournament winners is getting displayed in the lobby screen. This will fix #14864   .Adding screenshots before and after code change for reference:
Before :
After :
> Set min height for Tournament winners

- modules/study/src/test/Helpers.scala
- modules/study/src/test/StudyArbitraries.scala
- modules/study/src/test/newTreeTest.scala
When trying to make `takeMainlineWhile` function works for the NewTree, I found a subtle bug in the current Tree: it always take the first child of the root despite the predicate as demonstrated in the first commit.
> Fix NewTree takeMainlineWhile test

- app/ui/scalatags.scala
- app/views/base/bits.scala
- app/views/user/show/header.scala
close #14771
note: github does the same thing (puts rel="me" everywhere)
> creating relMe and use all user social link profile

- build.sbt
Also add round as a dependency for Study as result.
I believe `study` shouldn't depend on round either, but for now it depends on `round.TreeBuilder` and `round.WithFlags`. We should them to `importer` (maybe 🤔) and remove `round` from `study`
> Make importer depends on game instead of round

- modules/relay/src/main/RelayPush.scala
When creating a broadcast,
it is possible to specify player replacements which will happen for rounds belonging to the broadcast, i.e `<player name> = <fide id>`
This works for rounds which uses Sync URL, i.e fetched PGN, but it doesn't apply to PGN which is being pushed.
This Pull Request applies player replacements also for pushed PGN.
Note, maybe this isn't desired... Maybe not applying replacements on pushed PGNs was a deliberate choice... :sweat_smile:
<details>
<summary>scala-cli reproducer PushPgn.scala</summary>
```scala
//> using scala 3.4.0
//> using dep io.github.tors42:chariot:0.0.84
@main
def main() =
val lichessApi = "http://localhost:8080"
val token      = "lip_diego"
val client = chariot.Client.basic(conf => conf.api(lichessApi))
.withToken(token)
val broadcast = …
```
> Apply player replacements also for Push PGN

- conf/base.conf
lila run currently not working
> [error] Caused by: com.typesafe.config.ConfigException$UnresolvedSubstitution: base.conf @ jar:file:/lila/target/bg-jobs/sbt_5cadf719/job-1/target/5086a3aa/6e009ac9/lila_3-4.0.jar!/base.conf: 451: Could not resolve substitution to a value: ${forumSearch.actor.name}
`forumSearch.actor.name` config removed in 5c94dc2a9c8988ab59e04882ca9db615415833fc
> Remove actor.forum.search from base.conf

- app/views/dgt.scala
The DGT play functionality failed with "error: No such token" message.
It seems it's because the token is wrapped within single-quotes.
This Pull Request removes the quotes.
Resolves: #15000
> Don't wrap token with single-quotes

- app/controllers/TeamApi.scala
- modules/chat/src/main/ChatApi.scala
When I try the `/api/team/<teamid>` endpoint, the `joined` flag seems to always be `false`.
I've noticed this earlier too, but got sidetracked when trying to figure out what was happening - and now I saw the #15022 Pull Request which adds the private team description in the response if user is authenticated and member.
From the example screenshot in #15022 it seems that this somehow works without this fix - so I'm not sure what is going on here... :sweat_smile:  
Example request from user "ana" which is member in team "diegoteam",
```
curl --header "authorization: Bearer lip_ana" http://localhost:8080/api/team/diegoteam
```
Response without fix:
```
{"id":"diegoteam", ... , "joined":false,"requested":false}
```
Response with fix:
```
{"id":"diegoteam", ... …
```
> Use OpenOrScoped TeamApi.show

- ui/analyse/css/_zh.scss
#14957 
https://github.com/lichess-org/lila/assets/126312812/f997541a-8abe-4605-91b7-dbd0252c49ea
The bug happens during the second media query, which is `min-width: 1259.3px`
https://github.com/lichess-org/lila/assets/126312812/a1e9b97c-d4b5-44d6-8cd2-980d1dcb5a41
> Fix Issue #14957: Crazyhouse pocket takes a lot of space on analysis board

- app/views/forum/search.scala
e.g. Searching for your username gives you results about who is talking about you behind your back in private team forums. Even if the contents are not visible, the poster is, and it's an avenue for trolls to harass them.
> Don't dox poster info in forum post search results

- ui/chat/css/_discussion.scss
- ui/common/src/richText.ts
Reverts lichess-org/lila#15017
It treats all links like user links.
https://lichess.org/forum/lichess-feedback/a-serious-security-hole-on-lichess#2
> Revert "add powerTip to @user "

- modules/challenge/src/main/ChallengeGranter.scala
`relation.Follow/`/`relation.Block` are the bus message, so the check currently ignores blocks and doesn't allow friends. Seems like it was broken in https://github.com/lichess-org/lila/commit/cc17923c539db40e9bf9e9d93c019b35f183d14f#diff-7427dafff9a8a406b95922a6bff3b2b582ad573b08e2eff7e1139163acb6b84e. Didn't find any other places with the same issue at first glance.
> Fix relation check on challenges

- modules/fide/src/main/FidePlayerSync.scala
Apparently, FIDE has three flags for inactive players:
> FLAG - flag of inactivity (I - inactive, WI - woman inactive, w - woman)
That means if the flag contains anything, the player is inactive.
I have a [test](https://github.com/lenguyenthanh/fide/blob/a1e1e02060f6bbf16d60db92b5cc328a8a4540a0/modules/crawler/src/test/scala/CrawlerTest.scala#L18) and a similar [fix](https://github.com/lenguyenthanh/fide/blob/a1e1e02060f6bbf16d60db92b5cc328a8a4540a0/modules/crawler/src/main/scala/Crawler.scala#L94) in [fide](https://github.com/lenguyenthanh/fide).
> Fix FidePSync to read FIDE's ridiculous woman inactive flag

- lila
Before, if an executable named "java" wasn't found, lila would simply print "Java " and exit (no matter what command line arguments were added) due to the version string being blank.  This is confusing and frustrating, so this commit fixes that by printing an error message
> Show error message when Java is not installed

- app/views/base/embed.scala
- app/views/base/layout.scala
- modules/web/src/main/views/layout.scala
- ui/common/src/theme.ts
Fixes #15172
The theme now needs to be set on the html tag instead of the body. And the system theme script needs a nonce.
Also removed the unused `supportsSystemTheme` JS function.
> Fix bg color scheme (dark/light/system) for embeds

- ui/analyse/css/study/relay/_layout.scss
An attempt to fix the underboard top margin in the 3d case. Fixes #15147.
Before:
After:
> Add margin to underboard in 3d case

- modules/insight/src/main/AggregationPipeline.scala
https://lichess.org/insights/thibault/acpl/openingFamily currently includes all openings and is not filtered.
Bug introduced by a scalafmt rewrite https://github.com/lichess-org/lila/commit/1aae0c7b022f9e505e1ca7fec3b32efeef9f9981.
> Fix insights aggregation by opening

- ui/lobby/src/view/correspondence.ts
- ui/lobby/src/view/pools.ts
- ui/lobby/src/view/realTime/list.ts
Some quick `role: 'button'` additions to various divs used in the lobby. This will alert screen readers and screen reader-adjacent technologies (e.g. the popular voice tool [rango](https://rango.click/#/)) that these divs are clickable, although to achieve full accessibility we would need to make them focusable and responsive to enter/spacebar key presses. Better to just refactor these divs into proper `<button>`s one day probably.
> Improve lobby accessibility

- ui/chart/src/chart.ratingHistory.ts
When the user rating graph initially loads, it does not display the selected timespan. This pull request addresses this issue.
Before:
After:
> show the selected timespan on page load in user rating graph

- modules/security/src/main/DisposableEmailDomain.scala
Simple change - Just adds outlook.com.au to the whitelist.
This domain's a bit rare, but I do have it and it's run by Microsoft.
> Add "outlook.com.au" to email whitelist

- app/views/site.scala
Pasting a youtube link was only working on variant pages, like [for Racing Kings](https://lichess.org/variant/racingKings)
> Enable youtube embed expansion on regular CMS pages

- app/controllers/Ublog.scala
Lookup the blog post to find author and slug,
and redirect the request if not matching.
Resolves: #15031
> Redirect blog requests not matching post meta

- ui/bits/css/_auth.scss
> Fix #15288: The password strength text overlaps the password field on mobile browser

- ui/common/css/header/_title.scss
As described in the issue, `.site-title` is "visible" on mobile layouts and can be inadvertently tapped bringing you back to the homepage. This PR hides `.site-title` on mobile layouts. Tested.
Fixes #15274
> Hide .site-title on mobile layout

- modules/core/src/main/userId.scala
- modules/user/src/test/UserTest.scala
There are also plenty (around 1.4k that have played rated games) of names starting or ending with a dash. Although only 2 are still actively playing rated games.
~~All users that have ever played a rated game match the new regex.~~
Edit: Actually, that's not quite true, there are 3 names that are too long. But they haven't played a rated game since at least 2022, possibly longer. So I guess might be fine to ignore?
> Fix historical username regex

- app/controllers/Challenge.scala
Here's a proposal for how to handle #15318
With the fix,
it won't be possible to set rules when challenging a BOT account:
```
curl -H "authorization: Bearer lip_yulia" \
http://localhost:8080/api/challenge/Bot0 \
-d 'clock.limit=600&clock.increment=15&rules=noGiveTime'
```
```json
{"error":"Rules not applicable for bots"}
```
> Dont allow rules when challenging BOT

- modules/user/src/main/ui/UserShow.scala
Added "Joined" before the user's age in the user tooltip to make info clearer
> Add text specifying user age in user tooltip

- ui/analyse/src/view/components.ts
This reverts commit 035867a2603cb1276ddcd564f48471e8766db39f, and fixes #15306.
I assume there was a bug in Safari that this commit fixed, but that bug no longer seems to apply. I tested this change in Safari 17.5:
before: 
https://github.com/lichess-org/lila/assets/14306627/4ac57896-4b98-4fa1-b5cd-e8fc3b4ad231
after: 
https://github.com/lichess-org/lila/assets/14306627/38e0d375-73f9-40a0-b43c-c6e462d2f993
> Fix analysis button on practice lesson boards changing current tab

- app/LilaComponents.scala
- app/controllers/Github.scala
- app/controllers/Main.scala
- conf/routes
[Github docs here](https://docs.github.com/en/code-security/secret-scanning/secret-scanning-partner-program#implement-signature-verification-in-your-secret-alert-service)
To test:
```bash
curl -X POST "http://localhost:8080/github/secret-scanning" \
-H "Content-Type: application/json" \
-H "Github-Public-Key-Identifier: bcb53661c06b4728e59d897fb6165d5c9cda0fd9cdf9d09ead458168deb7518c" \
-H "Github-Public-Key-Signature: MEQCIQDaMKqrGnE27S0kgMrEK0eYBmyG0LeZismAEz/BgZyt7AIfXt9fErtRS4XaeSt/AO1RtBY66YcAdjxji410VQV4xg==" \
-d '[{"source":"commit","token":"some_token","type":"some_type","url":"https://example.com/base-repo-url/"}]'
```
> Verify github signature

- ui/bits/src/bits.expandText.ts
The domain is already in use for those who were not logged in and the sharing links already use the new one
> correct the regex, and support if the user sends a link with the new domain

- ui/cli/css/_clinput.scss
Hides the donate button when opening search on smaller screens. The point at which it is hidden is the same as for the Lichess logo. Fixes #15366.
> Hide donate button when opening search on smaller screens

- ui/round/src/ctrl.ts
Cancel premoves when move confirmation is enabled and the move is canceled.
Fixes #15402
v is also a pretty bad variable name, but I did not touch it in case there was a convention or something.
> fixup: of  Premove during "confirm move" #15402

- modules/relay/src/main/JsonView.scala
It was only being included in fullTour but it would be helpful to always include
> API include tour url in all round responses

- ui/common/css/theme/board/_chessground.scss
Reverts 7caf56434dedb0240c67927e97db2afe02d4b385.
Without "pointer-events: none", the target square isn't highlighted anymore when dragging a piece around. The cursor change also doesn't make sense when using click to move and also makes piece positions visible in blind mode. Some people also have reported the cursor change to lag.
Most of those issues probably can be fixed but until then, I think it's best to revert the change for now.
See also the discussion on Zulip: https://hq.lichess.ovh/#narrow/stream/8-dev/topic/hand.20grab.20cursor
> Revert grab cursor

- modules/web/src/main/ui/DgtUi.scala
- ui/bits/css/_account.scss
```
section a {
text-decoration: none;
color: inherit;
}
```
This was being used for the account preferences like zen mode and show player ratings, so #15429 is not a solution.
> Use better solution to apply correct link color to DGT board page

- ui/common/css/component/_power-tip.scss
#14854 
Issue present with other languages besides pt-pt.
> Fix #14854: Rating Hidden: Red Mark text overflow in mini profile

- ui/learn/src/levelCtrl.ts
quick bugfix for something that pointed out in zulip, where switching levels quickly was causing some bugs.
> ui/learn: Clear scenario timeouts when switching levels

- ui/bits/css/user/_show.scss
before
https://github.com/lichess-org/lila/assets/56031107/62237fc3-873d-4bd5-8c2a-7c4e5c43757c
after
https://github.com/lichess-org/lila/assets/56031107/21665abd-b943-4248-bab1-c2e2f6f95fe1
The scroll bar does look a bit big, and is non-native, not sure if that was worth changing
> Profile, fix dropdown button covering others when screen too narrow

- modules/relay/src/main/ui/FormUi.scala
I think it looks a little strange in lichess.dev
See https://lichess.org/page/broadcaster-app but click for https://github.com/lichess-org/broadcaster
> FIX broadcasterURL

- modules/challenge/src/main/ui/ChallengeUi.scala
- ui/challenge/css/_page.scss
Closes https://github.com/lichess-org/lila/issues/15525.
| With font icons      | With flairs      |
| ------------- | ------------- |
| ![CleanShot 2024-06-23 at 16 01 24](https://github.com/lichess-org/lila/assets/58905488/62ffb776-ed23-4df8-b2f3-b7926eaef826) | ![CleanShot 2024-06-23 at 19 13 35](https://github.com/lichess-org/lila/assets/58905488/f5d31c77-d5d7-4e40-8805-d917e6680bbb) |
Suggestions for better suiting icons are welcome.
> Display challenge rules on the challenge page

- modules/forum/src/main/ForumTopicApi.scala
Fix the insert order by: topic then category then post. If We insert post first, sometime lila-search-ingestor is received change event before We finished insert topic which causes some fail ingestion.
> Fix topic creation insert order

- ui/analyse/src/study/relay/interfaces.ts
- ui/analyse/src/study/relay/relayTourView.ts
If it only works in official mode why do I need to show it to non-official
> Only show `Popularity stats` if is official

- modules/ui/src/main/helper/Form3.scala
With the recent password visibility toggle addition, when enter is pressed the password visibility toggle is "clicked" revealing the password instead of submitting the form. This PR fixes that.
> Submit form on enter instead of toggling password

- ui/common/css/form/_password.scss
Adds a focus indicator to the password reveal button specifically when tabbed on to add context on where you are in the form.
> Add focus indicator when tabbed on password reveal button

- ui/bits/css/user/_show.scss
When using a transparent background the user profile actions hamburger icon disappears when hovered. This is due to [%dropdown-shadow](https://github.com/lichess-org/lila/blob/67057907e67974841044ce9c498d942a683478d5/ui/common/css/abstract/_extends.scss#L106-L111) including the [back-blur](https://github.com/lichess-org/lila/blob/67057907e67974841044ce9c498d942a683478d5/ui/common/css/abstract/_mixins.scss#L87-L99) mixin if the background is transparent, which resets the ::before `content`.
Issue:
To keep the shadow (and icon), it seemed like the most straight-forward approach was to just include box-shadow directly instead of extending from dropdown-shadow.
> Fix user profile actions hamburger icon removed on transp background

- ui/common/css/component/_lichess-pgn-viewer.scss
making a PR just to post the before/after
before:
after:
> LPV movelist: make past moves font color same as upcoming moves

- modules/analyse/src/main/ui/AnalyseI18n.scala
> fix: add missing i18n keys for expand/collapse variations

- ui/lobby/src/ctrl.ts
- ui/lobby/src/interfaces.ts
- ui/lobby/src/setupCtrl.ts
When I originally started developing this feature, my intent was to close https://github.com/lichess-org/lila/issues/15628, but I missed the key part of that issue in regards to that wanting to have "a forced template". Nevertheless, I think that being able to specify time and increment using query parameters is a good addition.
https://github.com/lichess-org/lila/assets/58905488/57a904e0-f1dc-4a9a-b70f-f123dfc496b1
> Add ability to set time and increment in challenge query link

- ui/common/css/component/_lichess-pgn-viewer.scss
It was still using a fixed color used, probably for debug (CF git blame)
before:
after:
> LPV: fix border comment color

- ui/chess/src/glyphs.ts
They look better/slicker/more modern IMO.
checkmark
|--------|--------|
| ![Screenshot 2024-07-04 at 14 02 14](https://github.com/lichess-org/lila/assets/56031107/4649981c-23c1-4d5e-a3e6-ffd9c1247542) | ![Screenshot 2024-07-04 at 14 01 33](https://github.com/lichess-org/lila/assets/56031107/84749c5c-595e-4f34-a334-db41351671be) |
crossmark
|--------|--------|
| ![Screenshot 2024-07-04 at 14 05 43](https://github.com/lichess-org/lila/assets/56031107/ee5b6311-bfd5-4417-b6af-ae351c285148) | ![Screenshot 2024-07-04 at 14 04 21](https://github.com/lichess-org/lila/assets/56031107/b2c10ce6-ad34-4281-b876-c13d1db95311) |
> Puzzle move highlight/feedback: use SVG glyphs instead of text

- app/controllers/Tournament.scala
See https://hq.lichess.ovh/#narrow/stream/8-dev/topic/variant.20tournament.20scheduler.20getting.20rate-limited for additional context.
Basically, the `isGranted(_.ManageTournament)` doesn't apply when using the API with a token that doesn't have `web:mod` perms but I'm not sure creating a token with those perms just for creating tournaments is a good idea.
Adding a separate exception for Lichess seems like the simplest solution.
Also gave it a cost of 1 instead of 2 for a total limit of 240/day. It's not strictly necessary rn since the variant teams currently only create around 50/day but it's probably better to have some buffer, especially since there are 8 variant teams, some of which currently don't create a lot of tournaments, the limit is also shared for Swiss tournaments, and we …
> Increase tour create rate-limit for lichess user

- modules/analyse/src/main/ui/AnalyseUi.scala
- modules/ui/src/main/helper/Form3.scala
- ui/analyse/css/_side.scss
- ui/analyse/css/build/analyse.free.scss
- ui/analyse/src/view/main.ts
- ui/analyse/src/wiki.ts
- ui/bits/css/ublog/_form.scss
- ui/common/css/component/_toggle-box.scss
- ui/common/css/form/_form3.scss
- ui/site/src/boot.ts
Closes #10769 
This PR implements:
1. A toggleable fieldset display for Wikibook opening details on the Analysis page.
2. User preference is stored as site storage with key: **analyse.wikibooks.display**
Local Test Link: http://localhost:9663/analysis
Other implementation discussions in the comments
> feat: toggle for wiki opening info display

- modules/clas/src/main/Env.scala
- modules/common/src/main/Bus.scala
- modules/core/src/main/misc.scala
- modules/msg/src/main/MsgSearch.scala
- modules/msg/src/main/MsgSecurity.scala
Finally getting around moving more Bus to the safer API
Tests:
> Bus: use safer version for Class

- app/controllers/Puzzle.scala
- modules/activity/src/main/Env.scala
- modules/core/src/main/misc.scala
- modules/mailer/src/main/Env.scala
- modules/notify/src/main/Env.scala
- modules/racer/src/main/RacerApi.scala
- modules/round/src/main/CorrespondenceEmail.scala
- modules/socket/src/main/RemoteSocket.scala
- modules/storm/src/main/StormDay.scala
- modules/streamer/src/main/Streaming.scala
tests:
Couldn't test the streamer parts, the rest work and supposedly the new typing is supposed to make the two first one very likely to work too 😅
> Bus: migrate more components to new API

- build.sbt
- modules/game/src/main/Event.scala
- modules/game/src/test/EventTest.scala
To prevent: https://github.com/lichess-org/lila/pull/15699
We should add more tests to cover `game.Event`. I'll eventually do them all if no one interested in.
> Implement tests for game.Event.PossibleMoves

- modules/web/src/main/AssetManifest.scala
- ui/.build/src/manifest.ts
- ui/analyse/package.json
- ui/analyse/src/study/topics.ts
- ui/bits/src/exports/crop.ts
- ui/site/package.json
- ui/site/src/asset.ts
- hash top level files in npm
- hash javascripts
- tweak hashed filenames to include the original basename
- back off from base64url to hex encoding for the hash part. 32 bits is plenty and hex is easier to type/search/remember
> tweak asset hash links

- modules/core/src/main/bus.scala
- modules/core/src/main/fishnet.scala
- modules/core/src/main/forum.scala
- modules/core/src/main/misc.scala
using a trait and extending it instead of a class.
Made the `WithChannel`constructor private so instances can only be created by extending the `GivenChannel` trait
> Bus: refactor channel declaration to be shorter

- modules/analyse/src/main/AccuracyPercent.scala
- modules/db/src/main/Handlers.scala
- modules/db/src/main/package.scala
- modules/game/src/main/Blurs.scala
- modules/game/src/test/BlurTest.scala
- modules/insight/src/main/model.scala
- modules/tutor/src/main/model.scala
modules/game/src/main/Blurs.scala
the `given lila.db.NoDbHandler[Blurs] with {}` is now ignored (since https://github.com/scala/scala3/issues/20843) and as a result blurs are read using `opaqueReader` instead of `blursHandler`.
The last test fails because of it.
> game blurs are read from DB using the wrong BSON handler

- modules/analyse/src/main/AccuracyPercent.scala
- modules/db/src/main/Handlers.scala
- modules/db/src/main/package.scala
- modules/insight/src/main/model.scala
- modules/tutor/src/main/model.scala
For types that don't want default opaque reader and writer, We can provide NoDbHandler instead provide both NoBSONReader and NoBSONWriter
follow up #15755
> Re-introduce NoDbHandler

- modules/oauth/src/main/ui/TokenUi.scala
Inspect form data Map to see if a key (like "scopes[0]" or "scopes[1]") has a mapping to a value such as "email:read"
Resolves: #15765
Note, maybe it is bad form to inspect the data map like this,
and that the data is supposed to have been made available in some other manner (i.e some Play Framework "mapping" logic) - or this is fine... :sweat_smile:
> Personal Token - Re-check scopes upon validation

- modules/web/src/main/CtrlErrors.scala
Closes https://github.com/lichess-org/lila/issues/15761.
This change should not be taking lightly as it will affect all API responses using this function. 
To put it short, `e.args` is a `Seq[Matchable]`. Without these changes, `toString()` gets called which is causing this to output `ArraySeq(30)`, where `30` is the element in the sequence. If the sequence contained more elements, such as `60`, it would ouput `ArraySeq(30, 60)`. 
By doing `mkString` it will concatenate all elements of the sequence into a string. We might want to do `mkString(", ")` to comma-separate each element if there are more than one. Going back to my example of `ArraySeq(30, 60`), the output would look like `Must be at least 30, 60 characters long`. That output does not make sense in this context, but its worth …
> Fix API validation response when joining team

- translation/source/puzzle.xml
Closes https://github.com/lichess-org/lila/issues/15659.
This is done to align with the other menu-items having all their first letter uppercased in all words. I have done the necessary change in [Crowdin](https://crowdin.com/editor/lichess/86/en-enus?view=comfortable#13772l) as well I think?
> Uppercase second word in "Puzzle themes" menu-item

- modules/gathering/src/main/Quote.scala
The quote used on the [2024 Autumn Marathon](https://lichess.org/tournament/autumn24) tournament page is malformed:
While fixing, I noticed a few others that have been seemingly malformed by a previous "replace all" which I also addressed in this PR.
> Fix malformed quotes

- ui/puzzle/src/autoShape.ts
Consistent feedback requested it, and prior behavior was a bit strange, especially after capture where the checkmark would now be on the piece of the opposite color.
This has the side-effect of effectively disabling the checkmark for users with animation set to "none", and I'd argue it's better and consistent.
See attached videos for the before and after.
With move animation set to `normal`
|--------|--------|
| ![](https://github.com/user-attachments/assets/90a717d7-d49e-4924-b8d6-c43cc43b1e46) |  ![](https://github.com/user-attachments/assets/76777402-9832-4f04-85e7-a3289b34982f)
With move animation set to `none`
|--------|--------|
| ![](https://github.com/user-attachments/assets/842697b0-71da-44fb-a32f-8b04aa121f8d)| …
> Puzzle: only show feedback on your moves

- modules/core/src/main/lilaism/LilaLibraryExtensions.scala
We have better type inference since 3.3.0
> Remove unnecessary type annotation

- .github/workflows/lint.yml
Change node version to 20 from default 18 to match with https://github.com/lichess-org/lila/blob/3c4c0d144caad0fecac9bd82a0772af1bb691c4d/package.json#L22 recommended node version.
> node 20 for github lint workflow

- modules/evalCache/src/main/EvalCacheApi.scala
- modules/evalCache/src/main/EvalCacheEntry.scala
- modules/fishnet/src/main/FishnetEvalCache.scala
- modules/tree/src/main/eval.scala
submitted as pr, to not immediately add more churn to debugging the queue saturation
> avoid fen roundtrip for CloudEval.GetSinglePvEval

- project/BuildSettings.scala
Also set `-source:3.7` as they delay [new givens prioritization scheme](https://github.com/scala/scala3/pull/19300https://github.com/scala/scala3/pull/19300) to scala 3.7. And We want to keep using this new scheme as We already migrated to this scheme.
reference: https://contributors.scala-lang.org/t/3-5-0-release-thread/6666/40
> Bump scala 3.5.0-RC7

- modules/relation/src/main/RelationApi.scala
Fix ci: https://github.com/lichess-org/lila/actions/runs/10334049938/job/28607066309#step:5:194
```
[error] -- [E007] Type Mismatch Error: /home/runner/work/lila/lila/modules/relation/src/main/RelationApi.scala:193:52 
[error] 193 |        coll.exists($doc("_id".$in(by.map(makeId(_, me.id)))))
[error]     |                                                    ^^
[error]     |Found:    (me : lila.core.user.Me)
[error]     |Required: ?{ id: ? }
[error]     |Note that implicit extension methods cannot be applied because they are ambiguous;
[error]     |both given instance given_UserIdOf_Me in object Me and given instance given_Conversion_Me_User in object Me provide an extension method `id` on (me : lila.core.user.Me)
```
Not sure why I can't reproduce this locally.
> Try to fix ci

- modules/common/src/main/LameName.scala
Removing due to excessive false risk, per previous instances and internal discussion
> remove `anus` from `LameName`

- modules/perfStat/src/main/PerfStatUi.scala
Generally when I'm on a perf stats page of a user (e.g. https://lichess.org/@/maia5/perf/rapid), I'm interested in the games of that user (or my own) and would like the board orientation to be set appropriately when clicking any of the game links on that page. However, currently only the "Best rated victories" section uses `pov` links.
This PR brings in changes so all game links on perf stat pages use `pov` links (e.g. https://lichess.org/q1ZwYo6c?pov=maia5) to set the orientation appropriately.
> Add pov query to all game links on user perf stat pages

- modules/gathering/src/main/GatheringJson.scala
- modules/swiss/src/main/SwissJson.scala
- modules/tournament/src/main/ApiJsonView.scala
- modules/tournament/src/main/JsonView.scala
Background: Swiss tournaments can have custom positions, i.e games start from a FEN.
Problem: In the API, there is no `"position"` field in the "create swiss" and "get swiss" operations.
Suggestion: Include `"position"` field when a custom position exists.
Reproducers:
Create (needs existing team id, here 'yulias')
$ curl \
-d 'rated=false&clock.limit=180&clock.increment=2&nbRounds=3&variant=standard&position=rnbqkbnr%2Fpppp1ppp%2F4p3%2F8%2F4P3%2F8%2FPPPP1PPP%2FRNBQKBNR+w+KQkq+-' \
-H "authorization: Bearer lip_yulia" \
http://localhost:8080/api/swiss/new/yulias | jq
<details>
<summary>create response</summary>
```json
{
"id": "2wexQyFc",
"createdBy": "yulia",
"startsAt": "2024-08-18T08:57:41.030552736Z",
"name": "Gunina",
"clock": {
"limit": 180,
"increment": 2
},
"variant": "standard", …
```
> Show Swiss position in API

- modules/swiss/src/main/SwissJson.scala
Background: Swiss tournaments have stats, like how many games, wins per color, draws etc.
Problem: In the API, the `"stats"` field can be `null` when there exists no stats yet.
Suggestion: Don't include `"stats"` field when no stats exists.
Alternative: Generate an "all 0s"/empty stats object.
Reproducers:
Create (needs existing team id, here 'yulias')
$ curl \
-d 'clock.limit=180&clock.increment=2&nbRounds=3' \
-H "authorization: Bearer lip_yulia" \
http://localhost:8080/api/swiss/new/yulias | jq
<details>
<summary>create response</summary>
```json
{
"id": "WVP78M6P",
"createdBy": "yulia",
"startsAt": "2024-08-18T06:52:46.262Z",
"name": "Alekseev",
"clock": {
"limit": 180,
"increment": 2
},
"variant": "standard",
"round": 0,
"nbRounds": 3,
"nbPlayers": 0,
"nbOngoing": 0,
"status": …
```
> Only add swiss JSON "stats" field if exists

- app/views/analyse/replay.scala
- modules/ui/src/main/scalatags.scala
- ui/analyse/css/_round-underboard.scss
When using translations, underboard tab controls can break lines and look like this:
After this PR it should look like this forced to be only on 1 line:
Another option would be forcing all tab headers to have same height, tell me if you'd prefer to go this way
p.s. I'm not too much into Scala, didn't build the project, just found another `title :=` example in views and repeated the pattern to show the hover tooltip, hope those `.txt()` should work
> Improve ux of long underboard translations

- project/Dependencies.scala
The protocol is still the same so We don't need to redeploy `lila-search`. 
Just update to have the same Scala 3.5.0.
> Lila search 3.0.0 for real

- modules/relay/src/main/RelayPlayer.scala
- ui/analyse/src/study/relay/relayPlayers.ts
* Sort by score by default when the leaderboard is enabled.
* Merge `Games` column into `Score`. Data in the format of `Score/Games` e.g. `3.5/5` 
It takes up too much space. The games column doesn't really benefit from sorting.
> players' table tweaks

- ui/learn/src/ctrl.ts
Closes #15535. Thanks @fitztrev for surfacing and finding the issue! I think the cleanest fix is here: whenever some hash navigation occurred, we were initializing the level. We don't actually need to initialize a level if we are navigating to the main Learn page.
> ui/learn: Do not initialize level if navigating to level map

- ui/analyse/src/plugins/analyse.study.topic.form.ts
Resolves #15940
Fixes JS error when opening [/study/topic](https://www.lichess.org/study/topic) while not being signed in.
> Fix /study/topic error when not logged in

- app/views/mod/communication.scala
Allow to click on the source of the public message without adding it to a note.
Nested span needed to keep JS note pasting working
```js
// lila/ui/mod/src/mod.inquiry.ts
$('#communication').on('click', '.line.author, .post.author', function (this: HTMLElement) {
// Need to take username from the communication page so that when being in inquiry for user A and checking communication of user B
// the notes cannot be mistakenly attributed to user A.
const username = $('#communication').find('.title').text().split(' ')[0];
const message = $(this).find('.message').text();
addToNote(`${username}: "${message}"`);
});
```
> Mod comms: more accurate highlighting of public chat messages

- modules/fide/src/main/FidePlayerSync.scala
close https://github.com/lichess-org/lila/issues/15956
The FIDE db contains a flag "w" for women players. I don't get why it's there because there's already a sex field.
Example from the zip file, a woman player, and an inactive woman player.
```
ID Number      Name                                                         Fed Sex Tit  WTit OTit           FOA SRtng SGm SK RRtng RGm Rk BRtng BGm BK B-day Flag
8602980        Hou, Yifan                                                   CHN F   GM   WGM                     2633  3   10 2550  9   10 2529  18  10 1994  w
46668225       Aakarshna C G                                                IND F                                1498  0   20 0     0   0  0     0   0  2002  wi
```
after the fix, Hou Yifan correctly shows up in the player list
> Fide: fix database parsing considering women as inactive

- ui/analyse/css/study/relay/_tour.scss
- ui/analyse/src/study/relay/relayTourView.ts
I had an idea here: since we have the admin note
Maybe we can add information for viewers (sometimes chat can be complicated)
In this case we can use "Pinned study comment" to save space and have information even when it is not in multiboard
> Broadcast Public Notes

- ui/analyse/src/study/relay/relayPlayers.ts
problems showing 0 and hiding "/N" when not showing results
> Relay: Fix show score in popup

- app/controllers/Setup.scala
- modules/lobby/src/main/Biter.scala
- modules/lobby/src/main/Hook.scala
- modules/lobby/src/main/Seek.scala
- modules/lobby/src/main/SeekApi.scala
- modules/setup/src/main/AiConfig.scala
- modules/setup/src/main/ApiAiConfig.scala
- modules/setup/src/main/Config.scala
- modules/setup/src/main/FriendConfig.scala
- modules/setup/src/main/HookConfig.scala
- modules/setup/src/main/Processor.scala
- modules/setup/src/main/SetupForm.scala
- ui/lobby/css/app/_hook-list.scss
- ui/lobby/src/interfaces.ts
- ui/lobby/src/seekRepo.ts
- ui/lobby/src/view/correspondence.ts
- ui/lobby/src/view/realTime/chart.ts
- ui/lobby/src/view/realTime/list.ts
- ui/lobby/src/view/setup/components/colorButtons.ts
- ui/lobby/src/view/setup/modal.ts
- ui/lobby/src/view/util.ts
Removes the option to select black or white pieces when creating a public seek. Color choice remains available for games with AI and direct challenges.
Fixed color in public seeks is being used to play as white exclusively, and has little legit use cases.
> Random color seeks

- modules/api/src/main/AccountClosure.scala
- modules/core/src/main/forum.scala
- modules/core/src/main/user.scala
- modules/forum/src/main/Env.scala
- modules/forum/src/main/ForumPostApi.scala
- modules/forumSearch/src/main/Env.scala
As We already erased posts from database, and lila-search-ingestor handles the rest
Follow up #15992
> Remove forum index eraser when gdpred users

- modules/perfStat/src/main/PerfStatUi.scala
When visiting `{user}/perf/correspondence`, if their rating is not provisional and they have high/low rating stats then the tooltip displays the following:
This is because Correspondence is not included in the weekly rating distribution. Updated code to filter out 0.0 so the highlow tooltip is removed in this case. This matches the filtering done to remove the top perf section which indicates what percentage of players you are better than ([here](https://github.com/lichess-org/lila/blob/dbdf7da02fb705262f0e54f195cf5dab91b972ce/modules/perfStat/src/main/PerfStatUi.scala#L114)).
**After**
> Don't show highlow tooltip if percentile is 0.0

- modules/relay/src/main/ui/RelayTourUi.scala
I didn't realize that /broadcast/app needs expand in the previous commit
> add expandText in broadcast pages

- project/Dependencies.scala
Routine release for lila-search client
[GitHub Release Notes](https://github.com/lichess-org/lila-search/releases/tag/v3.0.1)
> Bump lila-search client 3.0.1

- modules/relay/src/main/RelayPager.scala
fixes #16040 
The issue seems to be because of MongoDB's underlying text search whose tokenisation doesn't prioritise the year enough to filter out tournaments titled with a different year. Being totally new to Scala and Mongo, I don't know if this is the right solution and what performance implications it may have, but it's a suggestion if the ability for users to easily filter on a year appearing in the tournament name is sufficiently important. Tested with a broadcast titled "British Championships 2024" where "championship 2021" would match under production code, and not match after the proposed change.
> Improve broadcast date filtering

- modules/opening/src/main/ui/OpeningBits.scala
The percentage label for uncommon openings isn't easy to read.
> fix: minimum width for uncommon openings percentage bar

- pnpm-lock.yaml
- ui/chart/package.json
- ui/insight/package.json
- ui/opening/package.json
- ui/puzzle/package.json
Upgrades chart.js to `4.4.4` to fix a crash that can happen when rendering the analysis chart. To recreate the crash you need to request analysis or view a game that has already been analyzed (generally with a longer move list), resize the board while the analysis graph is rendering, and while resizing hover the mouse in the chart area.
This was a known issue with the tooltip positioner in chart.js which has been resolved in `4.4.4` [here](https://github.com/chartjs/Chart.js/pull/11863). 
Tested change in local development instance and working as expected.
**Video of issue in local dev instance**
https://github.com/user-attachments/assets/563dd655-7efa-4dfe-9756-122bf2f8b428
> Upgrade chart.js to fix crash on analysis

- modules/tournament/src/main/Schedule.scala
- modules/tournament/src/main/TournamentScheduler.scala
(temporarily) restore old tourney scheduling logic.
This scheduling is non-deterministic when two tourneys abutt each-other, but will eventually work since the schedule is tried frequently.
This commit goes against the long term plan of making the tourney schedule consistent, clear and deterministic.  The long term plan is to ignore conflicts caused by the staggered start of a tourney (probably by pruning using planned start time) and to display tourneys using their unstaggered starts on the tourney page.
So this commit will be reverted, but is needed short term.
Fixes #16048.
> Restore old tourney scheduling behavior

- ui/analyse/css/study/panel/_metadata.scss
Fixes #16060 
Result on Chrome Version 129.0.6668.59 (Official Build) (arm64) below: 
https://github.com/user-attachments/assets/3f697865-8903-4402-9af0-8ec9ca7500ed
Note that this requires Opera 67+ (one higher than the 66+ listed as having 'reasonable support' on the README) and Safari 15.4+ (vs. the 11.1+ listed as having 'reasonable support').
> Adds `overflow-wrap` to prevent overflow of study__metadata table rows

- ui/puz/css/_history.scss
Currently hovering does not change the visibilety. Probably broken during some refactoring. 
After : 
https://github.com/user-attachments/assets/15a93102-312a-4fb5-b9a6-32887a279948
The fact that there is both a puz and a puzzle folder is a _bit_ confusing. Not sure what the intended diffrence between the files is. The change I made applies to both Storm and Racer.
https://github.com/lichess-org/lila/blob/2cc706c09468f95eb05d84771a703e845b5dc637/ui/puz/css/_history.scss
https://github.com/lichess-org/lila/blob/2cc706c09468f95eb05d84771a703e845b5dc637/ui/puzzle/css/_history.scss
> restore hovering to show puzzle id

- ui/analyse/css/study/panel/_multiboard.scss
- ui/analyse/src/study/multiBoard.ts
Hiding the team selector makes mobile players' vision worse It's better not to hide
In short: if I select a board and go back to the multiboard I only see one team and not all (until I refresh the page)
> not hide select team in broadcast

- ui/dasher/css/_dasher.scss
Resolves: #16073
Fixes Non-Standard and deprecated CSS issues with `writing-mode: bt-lr;` and `-webkit-appearance: slider-vertical`.
> Fixes sound slider CSS to remove logs

- ui/puzzle/src/puzzle.dashboard.ts
Resolves: #16101
Adds a check to see if there is any puzzle history.
The Puzzle Dashboard page will console error if no puzzle have been played in the timeframe.
https://lichess.org/training/dashboard/30/dashboard
> Fixes no puzzle history console error

- modules/relay/src/main/RelayTour.scala
fideTC is already selected by default as standard
old tournaments are saying they are in standard and not other modes I don't see anything that `tc` currently helps resolve
not to mention that tc has another use since there is fidetc
> remove useless code

- modules/tournament/src/main/TournamentScheduler.scala
`at()` does not generally need to return an Option. Reflecting the intention of the method, we now specify hours/minutes exactly instead of adjusting a LocalDateTime.
The existing impl returns Some[LocalDateTime] for nearly any hour value, even though arbitrary values (such as negatives) are not an intended use case of `at`.
> Tournament Scheduler: Simplify private "at" method

- bin/schlawg-dev
- modules/web/src/main/helper/AssetFullHelper.scala
- ui/.build/package.json
- ui/.build/readme
- ui/.build/src/console.ts
- ui/.build/src/main.ts
- ui/.build/src/manifest.ts
- ui/@types/lichess/index.d.ts
- ui/bits/src/bits.devMode.ts
- ui/ceval/src/protocol.ts
- `ui/build` watch modes with `-d` flag will log browser console messages over stdout
- useful if you combine build output and lila logs together
- safari does not allow it
- those bothered by a one time error message when connect localhost:8666 fails are encouraged to not use `-d`
> add browser console logging to ui/build

- modules/common/src/test/StringTest.scala
- modules/fishnet/src/test/UciToSanTest.scala
- modules/memo/src/main/Picfit.scala
- modules/streamer/src/main/YouTubeApi.scala
Replace list constructions that use `List()` with `Nil`.
In Scala 2, some compiler magic converts `List()` into Nil and so the code is equivalent.  However, apparently Dotty forgot to implement this optimization, and so List() requires several allocations before ultimately returning Nil.
See scala/scala#10876.
> List() -> Nil

- ui/common/css/form/_cmn-toggle.scss
This PR addresses two issues with the checkboxes.
1. When you check and then uncheck a checkbox the focus indicator (glowing background) remains active until you click away. This can be quickly seen by disabling the checkbox in a chat field. `focus-visible` fixes this while also still showing a focus indicator when tabbing as well.
2. The checkboxes have always looked a little fuzzy to me due to the color bleed around the edges. Fixed using `background-clip`.
**Before**
**After**
> Checkbox improvements

- modules/forum/src/main/ui/PostUi.scala
- ui/common/css/component/_slist.scss
> fix: use single column on mobile forum search 

- ui/analyse/src/ctrl.ts
- ui/ceval/src/ctrl.ts
- ui/ceval/src/protocol.ts
- ui/ceval/src/types.ts
- ui/puzzle/src/ctrl.ts
This doesn't fix whatever the underlying issue is, but completely tearing down and recreating ceval (with potentially a huge hash table and many threads) should be avoided anyway.
> use ucinewgame instead of destroying ceval between puzzles (fixes #16067)

- ui/tournament/src/view/battle.ts
When clicking the top username next to the team scores, `jumpToPageOf` that user is called but the redraw doesn't actually happen. See https://lichess.org/tournament/5WDVB4Li
> Fix team battle jump to page

- ui/bits/css/ublog/_card.scss
Otherwise the color defined with `@include` was more specific and overwrote the special color for lichess
also cc @schlawg because it's probably not the way to do it, but it avoids `!important`.
> Ublog: fix Lichess name color on light mode

- ui/lobby/src/view/table.ts
I'm able to recreate #16195 but only if long pressing the button and then releasing. Adjusted the trigger to happen on `click` instead of `mousedown` as that aligns with other modal bindings and resolves the issue.
Resolves #16195
> Fix lobby modals closing after opening

- modules/challenge/src/main/ui/ChallengeUi.scala
The vast majority of challenges will not have custom rules and are left with an empty "Custom rules:" section. PR brings in changes so this section is only displayed if there are custom rules to show.
> Only show custom rules section when there are custom rules

- ui/common/css/component/_chart.scss
Change the cursor style from w-resize to ew-resize on the rating graph time scale selector to better reflect bidirectional slider.
> Change cursor style for profile rating graph

- modules/oauth/src/main/ui/TokenUi.scala
- modules/ui/src/main/helper/Form3.scala
On page https://lichess.org/account/oauth/token/create
There was hover text over the label for `bot:play`/`board:play` but not the toggle button itself.
> Add title attr to token scope toggle when disabled

- app/controllers/Api.scala
before:
```json
{
"error": "Not found"
}
```
after:
```json
{
"error": "No cloud evaluation available for that position"
}
```
> Custom 404 for cloud eval position not found

- modules/study/src/main/ui/StudyBits.scala
When a new study is created the user has the option to select a flair for the study. If a flair is not selected the study silently defaults to the users flair on creation. Additionally, if the user has older studies before flairs existed these will all change to follow the current user flair every time they change their profile flair.
Maybe controversial, but to me this seems odd. I'd expect to receive the default "Study Board"  
icon if I don't specify a flair on study creation. Currently, the only way to get the default study board icon is to not have a user flair.
This PR makes it so by default if you don't select a study flair, the study will get the default study board icon. Old studies before flairs existed that have not been specifically assigned a flair will be reverted to the …
> Default study icon to study board if a flair is not selected

- modules/common/src/main/MarkdownRender.scala
- modules/common/src/test/MarkdownTest.scala
Resolves #15290, but also adds in other places
Therefore, making sure you don't leave the site completely when you click on a link
> Make adding `target="_blank"` to all Markdown links

- ui/common/css/header/_topnav-hidden.scss
- ui/site/src/topBar.ts
Fixes the navigation hamburger menu flicker that happens on window resize. The issue is `transition: transform 200ms;` always being applied when the layout changes. Changed to add the transition selectively when the menu is opened/closed.
The approach in this PR keeps all transitions as is. The new `opened` class cannot be simply `toggled` as we need to wait long enough for the transition to finish (for the close transition), hence the `setTimeout` call on menu close. I felt this was the most straightforward approach that maintains compatibility as listening to when a `transitioned` event completes seems to be browser specific.
Solves the problem seen here:
https://github.com/user-attachments/assets/d006125a-fa27-4f6a-a71a-61bbd13c60dd
> Fix nav flicker that happens on window resize

- ui/bits/src/bits.cropDialog.ts
safari 13 and below will see empty boxes for webps served by picfit. but those devices were left behind (with flairs) awhile ago.
> use webp for streamer, blog, coach, and tournament image uploads

- app/controllers/Round.scala
- modules/web/src/main/ui/help.scala
Bugfix for https://github.com/lichess-org/lila/issues/16255
Display the 'c' shortcuts when playing rounds in the 'Other' section
> Display the 'c' keyboard shortcut under the 'other' to focus chat for rounds

- modules/study/src/main/ChapterMaker.scala
Fixes #16262 
The problem was that when the data was handled, the orientation was set to either "White" or "Black". But the Orientation object needed it in lowercase to correctly get the Color from it.
It is working great now, but let me know if I missed something !
> Use toLowerCase on the orientation color to handle it correctly when adding a chapter

- .gitignore
- eslint.config.mjs
- package.json
And also align eslint ignored files with how eslint is automatically run.
This ensures that all contributors run lint on the same set of files. Prior to this change, eslint covers ts files outside ui with its default rules, meaning contributors might commit code with fresh eslint errors that only show up when eslint is run bare, or if an eslint extension is installed in a code editor.
Because this commit adds a global ignore pattern on all folders by default, the bare `eslint` command run no longer takes additional time over `eslint ui`. And the --cache flag means lint will usually be dramatically faster than before.
One-off eslint checks on files in ignored directories can still be performed with: `eslint <path to file>`
Pre-commit run of eslint
```
$ hyperfine -w 3 -N …
```
> Speed up eslint with --cache

- project/Dependencies.scala
https://github.com/lichess-org/lila-search/releases/tag/v3.0.2
> Bump lila-search 3.0.2

- modules/feed/src/main/FeedUi.scala
- modules/pref/src/main/ui/AccountPages.scala
- modules/team/src/main/ui/FormUi.scala
- modules/ui/src/main/helper/Form3.scala
- modules/ui/src/main/helper/FormHelper.scala
- ui/analyse/src/study/studyForm.ts
- ui/bits/src/bits.flairPicker.ts
- ui/bits/src/exports/flairPicker.ts
- ui/common/css/component/_dialog.scss
- ui/common/css/form/_emoji-picker.scss
- use native `<select>` control to style flair picker
- workaround emojimart not calling `onClickOutside` callback in modal dialogs
- change external delete button to "CLEAR" button inside the picker
- remove labels and assorted views from within flair picker buttons
> flair picker change proposal

- modules/practice/src/main/PracticeUi.scala
- ui/bits/src/bits.ts
otherwise practiceNag() needs dialog.ts
> remove practiceNag from bits.ts in favor of boot.ts confirm

- ui/common/src/permalog.ts
https://developer.mozilla.org/en-US/docs/Web/API/PromiseRejectionEvent/reason
`reason read-only property is any JavaScript value or Object which provides the reason passed into Promise.reject()`
fix https://github.com/lichess-org/lila/issues/16295
> Permalog: always convert reason to string before escaping to html

- app/controllers/User.scala
Resolves error
```
Found:    (me : lila.app.Me)
Required: ?{ id: ? }
Note that implicit extension methods cannot be applied because they are ambiguous;
both given instance given_UserIdOf_Me in object Me and given instance given_Conversion_Me_User in object Me provide an extension method `id` on (me : lila.app.Me)
```
Which I can reproduce when running:
```
sbt clean && ./lila.sh stage
```
Related https://github.com/lichess-org/lila/pull/15878
> Fix clean stage builds

- ui/nvui/src/command.ts
- ui/nvui/tests/command.test.ts
| - | - |
| ![image](https://github.com/user-attachments/assets/4964e26a-7154-4642-9a98-35b2573d83c5) | ![image](https://github.com/user-attachments/assets/22916463-6734-4004-b0e9-e525085d0699) |
> Fix nvui regex to prevent undefined on invalid input

- ui/round/src/ctrl.ts
Fixes bug possibly introduced in [#16220](https://github.com/lichess-org/lila/pull/16220)
Also noted in issue [#7209](https://github.com/lichess-org/lila/issues/7209) where checkmate and victory play at the same time.
Allow `checkmate` sound to finish playing by adding a delay to the `victory`, `defeat`, `draw` sounds.
I tested this locally with the Robot & Standard sounds, and I think it works.
> Add delay to victory, defeat sounds

- modules/web/src/main/ui/contact.scala
Make it easier for organizers to find the official Broadcast Team contact
Currently it is still a little hidden.
> add Contact broadcast team in contact page

- modules/study/src/main/ChapterMaker.scala
When a coach is solving studies with a student, or a training group is solving puzzles from a book / course in lichess studies, this is done by enabling Conceal mode.
The PGN for that is usually exported from Chessbase, or from the [ChessVision AI reader](https://ebook.chessvision.ai/).
The existing cases don't help: Often, the PGN goes all the way to game end, so the game would be seen as completed, and thus rendered from white's side.
So if a chapter is created in Conceal mode, set the orientation to the side that makes the next move that will be un-concealed if correct.
[My coach](https://lichess.org/@/josefineheinemann) shared this example PGN, where the student is supposed to find black's moves:
```
[Event "Frauenbundesliga 2023/24"]
[Site "lichess.org"]
[Date "2024.06.08"]
[Round …
```
> Automatic orientation for puzzles in studies

- app/views/user/show/header.scala
Resolves #16275
Enables newlines (as well as custom spacing) in a user's profile bio. By not calling `shorten`, all sequences of whitespace chars won't be replaced with single spaces. For the part about shortening the text if its length is over 400, the text the user enters can already never be over 400 chars, due to this line in UserForm.scala: 
`"bio"        -> optional(cleanNoSymbolsAndNonEmptyText(maxLength = 400)),`
> Enable newlines in profile bio and don't shorten text

- ui/chat/css/_palantir.scss
> Prevent overwrite of .mchat__tab border radius in voice tab

- ui/puzzle/src/report.ts
There was a catch where players would continue analysing the puzzle in the mainline, and reaching moves where there would be multiple good solutions
> Puzzle report: only report if the move is in the solution

- ui/site/src/sound.ts
Prevent console error when embedding a broadcast in an iframe which does not have access to `window.speechSynthesis`
> Detect speechSynthesis for embeds

- package.json
- ui/puzzle/src/ctrl.ts
- ui/puzzle/src/report.ts
The id of the puzzle was not updated when you switch to another puzzle, so the id would only match with the analysis if it's the first puzzle loaded on the page
> Puzzle report: make sure to report the correct puzzle id

- modules/core/src/main/user.scala
- modules/lobby/src/main/LobbySocket.scala
- modules/rating/src/main/Glicko.scala
- modules/user/src/main/UserPerfsRepo.scala
Ideally, new players would score 0.5 on their first game, but it looks
like we pair them too high:
| Time control   | Avg score | Elo |
| ---------------| --------- | --- |
| Ultra bullet   | 0.25      | -96 |
| Bullet         | 0.25      | -96 |
| Blitz          | 0.34      | -59 |
| Rapid          | 0.37      | -47 |
| Classical      | 0.37      | -47 |
| Correspondence | 0.39      | -40 |
Changing the initial rating would change the rating distribution over
time, requiring to lower the rating again and so on.
Instead, use a virtual rating for the first pairing, just like we
already use virtual offsets from a normal distribution.
> use lower virtual rating for first game pairing

- ui/ceval/src/winningChances.ts
- ui/ceval/test/winningChances.test.ts
- ui/puzzle/src/report.ts
The difference in winning chance of 0.7 taken from the chess-puzzler repo is just too high, for example the difference between +4 and 0 is roughly 0.65, so it's still triggered. Maybe during generation it was 0.72 due to difference in depth, versions etc.
> Puzzle report: much stricter eval similarity check

- ui/.build/readme
- ui/.build/src/main.ts
- ui/.build/src/tsc.ts
- ui/common/src/device.ts
- ui/common/src/gridHacks.ts
- ui/common/src/timing.ts
this compiles (and watches if -w) sources in tests directory. to make it work with vitest, i had to enable skipLibCheck so it's only appropriate to use this on dev machines.
as i said in discord, i could also set up a separate watch to run tests when sources change, but my arm would need to be twisted as i don't want to encourage testing. the less bugs i know about, the better.
> add --test/-t option to typecheck tests

- ui/ceval/tests/winningChances.test.ts
Fixes Argument of type 'string' is not assignable to parameter of type '"white" | "black"'.
> Move winningChances test to tests dir and add test value types

- ui/chess/src/moveRootCtrl.ts
- ui/round/src/ctrl.ts
- ui/round/src/interfaces.ts
- ui/round/src/view/boardMenu.ts
- ui/voice/src/move/voice.move.ts
- always add move confirm to board menu when voice is enabled
- smooth overlap between arrows / colors / numbers voice confirm and standard move confirm.
> voice move confirm tweaks

- .gitignore
For me, this file is created whenever I stop redis-server.
> Have Git ignore `dump.rdb`.

- ui/common/css/component/_friend-box.scss
- ui/site/src/powertip.ts
this is a more direct fix for https://github.com/lichess-org/lila/issues/4272 than https://github.com/lichess-org/lila/commit/de56429ea50c65442f660350565352296658e15a. but due to the increased surface area, it is for review.
worst case unintended impact would be an overly sticky hover on some element that has huge border/padding. but i doubt that will happen.
> use outerWidth/outerHeight for powertip hover hitbox

- modules/oauth/src/main/ui/AuthorizeUi.scala
- modules/tutor/src/main/ui/TutorBits.scala
- modules/web/src/main/helper/AssetFullHelper.scala
- modules/web/src/main/ui/layout.scala
it's possible we could change chessground, cash, etc in an asset deploy.
getting the right asset without restarting the server is worth the repeated function call overhead (which is infrequent on the MHz scale).
> always recompute expressions involving assetUrl calls

- package.json
- pnpm-lock.yaml
- ui/.build/package.json
- ui/.build/pnpm-lock.yaml
- ui/analyse/css/_layout.scss
- ui/analyse/css/study/relay/_layout.scss
- ui/analyse/package.json
- ui/chart/package.json
- ui/common/css/abstract/_uniboard.scss
- ui/coordinateTrainer/css/_layout.scss
- ui/keyboardMove/package.json
- ui/keyboardMove/src/exports.ts
- ui/keyboardMove/src/keyboardMove.ts
- ui/keyboardMove/src/keyboardSubmit.ts
- ui/lobby/css/_layout.scss
- ui/puzzle/css/_layout.scss
- sources in keyboardMove have been realigned so that the module code (which is small) isn't bundled with the factory and render function.
- we saw minor version increases in prettier, typescript, and chart-js zoom plugin used for the x-axis scale controls beneath the user profile rating chart. cc'ing allan but the newer version seems fine in my testing
> dependency updates & minor module cleanup

- ui/round/src/clock/clockCtrl.ts
It would speak the clocks but only if Speech was the selected sound effect. This uses `force: true` to always speak the clocks, similar to "who".
https://lichess.org/forum/lichess-feedback/clock-command-not-working
> Keyboard input "clock" to always speak

- ui/.build/src/manifest.ts
tweaks to your tweaks. i do prefer the uniform single quotes in manifest.js. and we don't need JSON.stringify overhead to protect us from globs matching bad filenames when a backslash can avert the apostralypse
> escape apostrophes when wrapping keys in single quotes

- ui/analyse/src/explorer/explorerConfig.ts
- ui/analyse/src/keyboard.ts
- ui/analyse/src/serverSideUnderboard.ts
- ui/analyse/src/study/chapterEditForm.ts
- ui/analyse/src/study/chapterNewForm.ts
- ui/analyse/src/study/inviteForm.ts
- ui/analyse/src/study/studyForm.ts
- ui/analyse/src/study/studySearch.ts
- ui/analyse/src/study/topics.ts
- ui/analyse/src/view/actionMenu.ts
- ui/bits/src/bits.cropDialog.ts
- ui/bits/src/bits.diagnosticDialog.ts
- ui/bits/src/bits.forum.ts
- ui/bits/src/bits.publicChats.ts
- ui/ceval/src/util.ts
- ui/cli/src/cli.ts
- ui/common/css/component/_dialog.scss
- ui/common/src/dialog.ts
- ui/common/src/linkPopup.ts
- ui/editor/src/view.ts
- ui/keyboardMove/src/exports.ts
- ui/lobby/src/view/setup/modal.ts
- ui/puzzle/src/keyboard.ts
- ui/puzzle/src/report.ts
- ui/round/src/keyboard.ts
- ui/simul/src/view/created.ts
- ui/tournament/src/view/battle.ts
- ui/voice/src/view.ts
- let would be team battlers click their modal button
- remove showModal call, it is now a property of dialog construction and cannot be changed
- more explicit `show` and `modal` properties
- also make them work properly
- add missing noClickAway on chapter edit dialog
- correct autofocus selector code, remove outdated 'start at query[1] to skip close button'
> ui dialog bugfixes

- modules/coreI18n/src/main/key.scala
- translation/source/preferences.xml
- ui/@types/lichess/i18n.d.ts
- ui/common/src/boardMenu.ts
- ui/puzzle/src/view/boardMenu.ts
- ui/round/src/view/boardMenu.ts
Note that I have used 2 translations from preferences (which are the titles of the preference pages)
'Game display preferences' becomes 'Display' (i18n.preferences.display)
'Game behavior preferences' becomes 'Game behavior' (i18n.preferences.gameBehavior)
If you prefer, I can add 2 specific keys
Puzzle board menu:
Game board menu:
> Translate board menu in puzzle and game

- ui/lobby/src/lobby.inline.ts
The inline javascript is trying to append an element that only exists when the user is logged in, resulting in viewing "null" instead when they are not logged in. Moreover, when the window size changes, a series of nulls are rendered.
Before
After
> Remove 'null' from lobby when the user is not logged in

- ui/recap/src/swiper.ts
If you go to the next slide that also has lpv before the opening is done animating, it was jumping back and forth between slides
> Stop any existing lpv animations when switching slides

- ui/.build/src/main.ts
- ui/build
if using a system node, we may lack permission to enable it
> add --no-corepack argument

- ui/tree/css/_tree.scss
> fix: align link in move comment

- ui/.build/src/sass.ts
- ui/common/css/theme/_default.scss
The sass build for colors currently only works for direct assignments, but doesn't work correctly when being assigned to another variables and causes the assignee to be #000 instead.
Should fix #16559.
> Enable sass parser in ui/build to parse indirect color assignments

- conf/base.conf
- modules/security/src/main/Env.scala
- modules/security/src/main/Pwned.scala
- modules/security/src/main/SecurityConfig.scala
reconsidering if we should use the public api directly. unlike some other offered apis, there's essentially no rate limiting for the k-anonymity api.
pros:
* new password leaks immediately reflected
* can retire https://github.com/lichess-org/lila-pwned, for one less service to maintain
cons:
* request latency: 30ms (was a bit surprised, but manta and rubik are in different data centers) -> ~60ms
> directly use pwned k-anonymity api

- pnpm-lock.yaml
- ui/@types/lichess/index.d.ts
- ui/analyse/src/ctrl.ts
- ui/api/package.json
- ui/api/src/api.ts
- ui/api/tsconfig.json
- ui/bits/package.json
- ui/bits/src/bits.challengePage.ts
- ui/bits/src/bits.infiniteScroll.ts
- ui/bits/src/bits.tvGames.ts
- ui/bits/src/bits.user.ts
- ui/chat/package.json
- ui/chat/src/ctrl.ts
- ui/chat/src/moderation.ts
- ui/common/src/pubsub.ts
- ui/lobby/src/lobby.ts
- ui/mod/src/mod.user.ts
- ui/notify/src/view.ts
- ui/round/src/round.ts
- ui/simul/src/simul.home.ts
- ui/site/package.json
- ui/site/src/announce.ts
- ui/site/src/friends.ts
- ui/site/src/powertip.ts
- ui/site/src/site.ts
i moved initializeDom to pubsub so there are less imports of the new api package. this should help us if api needs to depend on other packages (besides common) down the road.
remember - those pubsub strings are typed, so the 'content-loaded' string itself is as good as a function name
> import api rather than window.lichess

- build.sbt
We used to depend on scala-uri which depends on an old version of
cats-parse. But it seems we don't depend on it any more, so this is
not necessary any more.
> Remove cats-parse VersionScheme.Always

- pnpm-lock.yaml
- ui/api/src/api.ts
- ui/bits/src/bits.challengePage.ts
- ui/bits/src/bits.infiniteScroll.ts
- ui/bits/src/bits.tvGames.ts
- ui/bits/src/bits.user.ts
- ui/chat/package.json
- ui/chat/src/ctrl.ts
- ui/chat/src/moderation.ts
- ui/common/src/pubsub.ts
- ui/lobby/src/lobby.ts
- ui/mod/src/mod.user.ts
- ui/notify/src/view.ts
- ui/round/src/round.ts
- ui/simul/src/simul.home.ts
- ui/site/src/announce.ts
- ui/site/src/powertip.ts
- ui/site/src/site.ts
just in case you had forgotten that the pubsub.emit strings were union typed. but if pubsub.initializeDom makes more sense to you, i have no problem with it - just close this sucker down.
> remove internal initializeDom alias for pubsub.emit('content-loaded')

- modules/streamer/src/main/StreamerApi.scala
- modules/streamer/src/main/StreamerForm.scala
- modules/streamer/src/main/ui/StreamerEdit.scala
- remove "requested" -> true from picture apply, that was a relic which caused our zombie problem
- stop using wasListed to distinguish between declines and 
- when the form was last touched by a mod, approval.reason.isDefined is always true
- use reason.isDefined rather than wasListed to better determine the appropriate status display. this can result in confusing status text on the edit form if someone is both a mod and a streamer but at least behavior will still be correct
> prevent zombie forms on picture submission

- ui/lobby/src/setupCtrl.ts
- ui/lobby/src/view/setup/modal.ts
common/dialog has basic snab integration, but we still need to inform the Dialog instance when a dialog is closed for proper cleanup
> always close Dialog instance when closing modal

- ui/analyse/src/study/studyCtrl.ts
- ui/game/src/view/status.ts
Just a few things I came across in the code.
> Small misc changes

- ui/common/css/component/_power-tip.scss
Based on this issue:
https://github.com/lichess-org/lila/issues/16675
I added margin on the powertip:
Before:
After:
> added margin between flag and country title on the powertip

- ui/puzzle/src/autoShape.ts
Fix:
https://github.com/lichess-org/lila/issues/16710
I managed to recreate the bug with the example from the issue.
If hint square is 0 => opts.hint === 0, the expression:
hint = opts.hint && { orig: makeSquare(opts.hint), brush: 'green' }
will evaluate to 0 and not proceed into the makeSquare function. The resulting hint will be 0 instead of the object { orig: makeSquare(0), brush: 'green' }
Before:
https://github.com/user-attachments/assets/ac7621cc-e3db-4a4b-a42c-e0b5a0ca598a
With the fix its working ok:
https://github.com/user-attachments/assets/c1083a91-7a16-401f-80de-c6e6e8c5fecc
> Show puzzle hint when square is 0

- ui/analyse/src/study/practice/studyPracticeSuccess.ts
In practice mode when the goal is to checkmate the opponent and the onboard position is stalemate, the section under the board doesn't get updated to try again.
For example:
> Fix practice mode underboard in the case of stalemates

- modules/web/src/main/AssetManifest.scala
- ui/.build/src/i18n.ts
- ui/.build/src/manifest.ts
trim translation/js & public/compiled/i18n from 41MB to 28MB by mapping empty category/locale pairings to `<category>.en-GB.<hash>.js` in manifest.
> dont create identical javascripts

- modules/ublog/src/main/UblogApi.scala
- modules/ublog/src/main/UblogBsonHandlers.scala
- modules/ublog/src/main/UblogPaginator.scala
- modules/ublog/src/main/ui/UblogUi.scala
- translation/source/ublog.xml
- ui/@types/lichess/i18n.d.ts
It would make sense to keep the same order between profile recent posts and user blog.
This way, even the lichess blog could use sticky posts if needed
> Show sticky posts first on user blog (not only on profile recent posts)

- modules/oauth/src/main/ui/AuthorizeUi.scala
- modules/ui/src/main/ContentSecurityPolicy.scala
- modules/web/src/main/AssetManifest.scala
- modules/web/src/main/ui/layout.scala
- ui/.build/src/esbuild.ts
- ui/.build/src/parse.ts
- ui/bits/package.json
- ui/bits/src/bits.oauth.inline.ts
- ui/site/src/site.inline.ts
i have learned that iOS 9 does not like es modules, arrow functions, or anything else that makes javascript tolerable.
- Re-apply 'unsafe-inline' to CSP for the authorize endpoint as it was before we attempted offloading oauth script to a self-contained `bits.oauth.ts` module.
- inline the button-enabling script because iOS 9 does not support es modules either.
> allow inline-only modules, use it for oauth button

- app/controllers/Challenge.scala
```
[warn] 156 |        cookieOption.foldLeft(res)(_ withCookies _)
[warn]     |                                     ^^^^^^^^^^^
[warn]     |Alphanumeric method withCookies is not declared infix; it should not be used as infix operator.
[warn]     |Instead, use method syntax .withCookies(...) or backticked identifier `withCookies`.
[warn]     |The latter can be rewritten automatically under -rewrite -source 3.4-migration.
[warn] one warning found
```
> Fix withCookies warning

- modules/relay/src/main/ui/RelayUi.scala
Fixes #16855
```
Uncaught TypeError: Cannot read properties of undefined (reading 'readOutClocks')
at boardCommands (command.ts:36:29)
```
> Fix blindmode command menu in broadcasts

- ui/round/src/round.ts
- ui/round/src/view/replay.ts
To reproduce this minor bug:
- Go on a phone and play a game to at least 5 moves. Do not refresh the page at any point.
- Briefly change the phone's orientation to horizontal, and then back to vertical.
- The last one or two ply should be obscured from the notation.
> Don't hide any notation when a phone's orientation changes to horizontal and back to vertical

- ui/analyse/src/keyboard.ts
In the analysis board, the Shift+Space shortcut is used to pick the most common opening move when the opening database is visible.
Allow the same shortcut to play the topmost move from the tablebase (which looks like the opening database) in endgames.
It was probably intended that way, but rather than `.moves`, in the tablebase the HTML table is `<table class="tablebase">`, with a slightly different layout than `moves`.
Rather than looking either in `.moves` or in `.tablebase` (which would make for a very long query selector), simply look for whatever UCI move we find in the explorer box.
After all, there are no other `<tr>`s in there which happen to have `data-uci` attributes.
> Execute top move from tablebase with Shift+Space

- ui/.build/package.json
- ui/.build/pnpm-lock.yaml
- ui/.build/src/build.ts
- ui/.build/src/console.ts
- ui/.build/src/env.ts
- ui/.build/src/esbuild.ts
- ui/.build/src/hash.ts
- ui/.build/src/i18n.ts
- ui/.build/src/main.ts
- ui/.build/src/manifest.ts
- ui/.build/src/parse.ts
- ui/.build/src/sass.ts
- ui/.build/src/sync.ts
- ui/.build/src/task.ts
- ui/.build/src/tsc.ts
- ui/.build/tsconfig.json
- ui/README.md
- ui/analyse/package.json
- ui/bits/package.json
- ui/ceval/package.json
- ui/common/package.json
- ui/common/src/algo.ts
- ui/common/tests/algo.test.ts
- ui/site/package.json
- ui/voice/package.json
- actually fail build when sync or hash steps error
- recover and log exceptions rather than crash
- improve logging (no more duplicate errors from tsc on common imports)
- MOAR colorz
- standardize path conventions in package.json build objects and logs - /rooted paths are repo relative otherwise package relative
- ditch the various haphazard watch logics in favor of a common task harness
- handle directory changes on watched globs (previously, the list of files being watched were frozen when the glob was first run)
- many watch related bugfixes
> client build script improvements

- ui/analyse/src/ctrl.ts
- ui/ceval/src/ctrl.ts
Closes #11237 
What I did:
- In `AnalyseCtrl`: When the external engine is active, do not store the incoming cloud eval in the node, even if the node has no eval (it seems better to me to display "Calculating..." for a few tenth of a second rather than flash a cloud eval)
- In `CevalCtrl` : Do not stop the external engine when there is already a known cloud eval. This happens when the user has just switched from a local engine to an external engine
> Disable cloud analysis when using an external engine

- translation/source/study.xml
- ui/@types/lichess/i18n.d.ts
- ui/analyse/src/study/chapterNewForm.ts
When you paste a pgn with multiple games in a study, the max number is limited by the maximum 64 chapters in a study.
So I suggest we change the message: 
`Paste your PGN text here. Each game is a new chapter. The study can have up to %s chapters`
> More accurate help message when pasting pgn in study

- translation/source/study.xml
- ui/@types/lichess/i18n.d.ts
- ui/analyse/src/study/chapterNewForm.ts
In a lichess study, the PGN import functionality allows for 64 games to be imported in one go. However, the import description states 32 as the max. number.
> Show correct max. number of games for multi PGN import

- ui/analyse/src/study/studySearch.ts
E.g., if a chapter's title is `1...d5 vs 1.Nf3`, a search for 'd5' or 'Nf3' will now return it as a result.
> Enable searching for any non-space phrase in a chapter title

- modules/tree/src/main/ParseImport.scala
> Test for draw when parsing a pgn before assuming resignation

- build.sbt
Changing to this format shows the individual deprecation details in my local build as well as in the github action logs.
| - | - |
| ![image](https://github.com/user-attachments/assets/7440b7ba-56e5-4ed6-a039-ffe144d9a947) | ![image](https://github.com/user-attachments/assets/34bd70b7-7387-4f1e-b919-003c403e5cd3)
> tweak deprecation flag during build

- modules/tournament/src/main/JsonView.scala
Among other things, this is useful when updating the tournament, since entry conditions need to be set to the desired value when sending an update API call or they reset to their default value.
> Return bots and account age conditions in tournament API

- ui/round/css/_moves.scss
- ui/round/css/_user.scss
Issue: Username and text messages were selectable during gameplay.
Solution: Implemented `user-select: none;` in `_user.scss` and `_moves.scss`.
Fixes #17000 
Before:
After:
> Made right side panel unselectable during gameplay

- ui/ceval/src/view/main.ts
This PR is intended to only affect the evaluation shown by the running engine, and temporarily the evals given to moves in the notation (until refreshing). I could be wrong though.
For why we might want to consider this:
- Open a game you've played in the analysis board, and request a computer analysis.
- Once it's done, toggle on the SF 16 engine, and set the number of lines to at least 2.
- For many moves, you should see the main bold evaluation stay where it is for a few seconds, and then suddenly switch to the evaluation of the top line.
The reason for this is that the SF 17 server analysis is used for the main bold eval, until the client engine reaches 4 million nodes. But for the user this feels confusing; especially if they're using SF 16 on their end, the abrupt change in …
> Do not have the client engine use the server eval

- modules/core/src/main/irc.scala
- modules/irc/src/main/IrcApi.scala
- modules/ublog/src/main/UblogApi.scala
1. Remove the limiter: Often times blogs that need to be checked don't reach the team without going to /blog
2. Divide Tiers by Topic
- If the blog is High tier I can have some observations that I won't have in another tier
- Unlisted blog may have a second chance to be listed again
> ublogs IRC: Send separately by topic

- ui/analyse/src/study/practice/studyPracticeView.ts
This PR aims to fix the issue https://github.com/lichess-org/lila/issues/16948.
The reported bug is caused by the `studyPracticeCrtl.onVictory()` method calling the `goToNextChapter` method with a 1 second timeout, allowing a 1 second window for the user to click the "Success" button and manually triggering the `goToNextChapter` method again. This resulted in two chapters being marked as completed at the same time.
The fix simply replaces the "Success" button with a non-clickable `span` if the user has the "Load next exercise immediately" option checked to avoid the issue.
> Replace link with span on practice success if autoNext is enabled

- modules/tournament/src/main/JsonView.scala
The withdraw field shows if a participating player is currently withdrawn/paused in an ongoing tournament.
It can already be found via endpoint `/api/tournament/<id>?page=<n>`, which, among other data, serves standings in groups of 10 per page.
This commit adds the withdraw field also to the
`/api/tournament/<id>/results` endpoint, which serves standings as an x-ndjson stream.
The withdraw data is already available at server-side, so the addition of the field should "only" incur the extra cost of the size increase of the json-object for the players which are currently withdrawn/paused.
Example,
Yulia and Diego are playing an arena, and Diego withdraws/pauses.
```
curl -H "accept: application/x-ndjson" "http://localhost:8080/api/tournament/k7zm80gX/results"
```
Before commit:
```json …
```
> API: add withdraw field /api/tournament/id/results

- ui/analyse/src/plugins/analyse.study.tour.ts
1. go to a study page like [this one](https://lichess.org/study/whCVdUeM)
2. under board, click the last icon, the help "ⓘ"
3. with this PR, clicking it a 2nd time will close it instead of restarting the tour
> second click will close study tour

- modules/core/src/main/game/Game.scala
Should mainly fix issue #14363 for Web (not sure about the Android app), as I'm assuming challenges make up the majority of cases where clicking on `claim victory` does nothing.
> Victory claims in games from challenges

- ui/.build/src/sass.ts
With `capturedColors` outside the loop, colors that aren't defined for a theme were taken from any previously loaded theme where they were present, instead of always falling back to the default theme.
Specifically, this caused the transparent theme to incorrectly fall back to the light theme instead of the dark theme, among other things leading to bad contrast when the background is a color mix (from the light theme) but the text color is not (and therefore from the dark theme):
|--------|--------|
| <img width="345" alt="image" src="https://github.com/user-attachments/assets/b5c9b74a-9767-4bf8-bea4-61624ffff30e" /> | <img width="347" alt="image" src="https://github.com/user-attachments/assets/c6ad111d-b731-4e0b-b05d-ce4ff02e9dd1" /> |
> ui/build/sass: Fix theme color fallback when generating color mixes

- modules/core/src/main/fide.scala
I haven't hit a scenario yet with this character, but I guess it doesn't hurt to have the replacement ready for when it happens.
> Add replacement for Norwegian 'å' character

- ui/game/src/game.ts
- ui/game/src/view/status.ts
Note: this PR applies a fix for games whose `Source` is 'imported'. I'm not sure if a `Source` val of 'local' can also refer to games played off lichess; if so, they should be included in this PR too.
--------------------------------------
For Masters DB games, if the players agreed to a draw by mutual agreement, the game is incorrectly labelled as a draw claim by insufficient material. E.g.:
This is due to #17114, where I incorrectly assumed control flows reaching this point in the code could only be draws by insufficient material claims. However, imported games in the Masters DB aren't obliged to provide specific draw info, so they can also reach this point.
> Don't give draw claims as explanations for imported games

- modules/security/src/main/SecurityForm.scala
One user incorrectly entered their email into the username field in the close account form and the "Please log into your account first" error you currently get in response to that doesn't seem particularly clear.
There probably are better options than my new proposed message but it's the best I was able to come up with on the spot to indicate more clearly that it's about the username while hinting that the logged-in account is relevant and might have to be switched if another account should be closed.
> Improve username error message in close account form

- modules/tournament/src/main/Spotlight.scala
In case a tournament has been featured,
and a Lichess user is member in a team which is participating in the tournament, the tournament can show twice.
This commit removes duplicates.
> Avoid listing BBB twice

- ui/chart/src/chart.ratingHistory.ts
-  See for the full desc Issue #16759
- Works as expected for scroll/slider in both directions
- Fixes `SmoothDates()`
- Always includes the latest player rating into allDates, when bin size/end date clips, prevents duplication.
> Fix #16759: chart rating history clipping to always include the latest rating val

- ui/common/css/component/_board-menu.scss
some langauges have long translations for the options menu, causing it to overlap with the board and text wrapping was disabled 
closes #17202
**before:** 
**now:**
> fix(board-menu): allow text wrapping in option menu

- modules/core/src/main/irc.scala
- modules/irc/src/main/IrcApi.scala
- modules/mod/src/main/Modlog.scala
- modules/mod/src/main/ModlogApi.scala
Actions that are not findable on one's user profile, allowing for better mod coordination.
The zulip mod-log firehose was closed for being too heavy on zulip's server, but considering how few actions are logged, it's worth re-opening it for these forum actions.
> Forum mod actions: log to zulip

- pnpm-lock.yaml
- ui/analyse/package.json
- ui/analyse/src/study/relay/relayPlayers.ts
- ui/bits/package.json
- ui/bits/src/bits.clas.ts
- ui/bits/src/bits.cms.ts
- ui/lib/package.json
- ui/lib/src/tablesort.ts
- ui/lib/src/tablesortNumber.ts
- ui/mod/package.json
- ui/mod/src/mod.games.ts
- ui/mod/src/mod.search.ts
- ui/mod/src/mod.user.ts
- ui/site/package.json
Closes https://github.com/lichess-org/lila/issues/17259
The reason for the error is that `ui/analyse` was using `tablesort@5.5.0` and `ui/lib/tablesortNumber` was using `tablesort@5.3.0`. The extension was being applied, but it was being applied to a different module that was using 5.3.0 while the actual sorting was being done with 5.5.0.
To avoid these hassles in the future, I've put one tablesort helper function in ui/lib and that is the only place where tablesort is defined in any package.json
> one tablesort to rule them all

- ui/analyse/src/treeView/columnView.ts
📌 **Issue** #17103
There was an issue where comments were being rendered twice for mainline moves. This happened because the logic for rendering comments didn't correctly handle forced variations, leading to duplicate comment displays.
🔧 **Fix**
I modified the logic to ensure that mainline comments are only displayed for non-forced variations, preventing their duplication.
> Prevent duplicate rendering of comments for mainline moves forced as variation

- ui/lib/src/chat/note.ts
this one seems obvious since "E4" is not a word, but it's a PR in case i'm just unaware of the reason for it
> disable spellcheck in notes

- ui/puzzle/src/autoShape.ts
- ui/puzzle/src/ctrl.ts
- ui/puzzle/src/view/boardMenu.ts
how could i deny this eloquent entreaty: https://lichess.org/forum/lichess-feedback/best-move-arrow-is-irritating-in-puzzle-evaluation-afterwards
i cannot
> add toggle for analysis arrows in puzzle board menu

- ui/puzzle/src/autoShape.ts
- ui/puzzle/src/ctrl.ts
- ui/puzzle/src/view/boardMenu.ts
- reverts the board menu toggle added in #17299 and properly applies engine lines setting
> reuse existing (if non-obvious) UI to hide puzzle arrows

- ui/analyse/src/view/components.ts
partially fixes #17235 
renderResult in view/components relies on deps? that analyse.nvui.ts cannot provide (at least I don't know how)
> Display game status in study (nvui)

- COPYING.md
Explicitly licensing the list of puzzle themes XML file for use as a dataset: https://huggingface.co/datasets/Lichess/puzzle-themes
> License puzzle themes in COPYING.md

- ui/analyse/src/study/relay/relayChat.ts
- ui/lib/src/chat/ctrl.ts
only respect the `opts.persistent` flag when node removal originates from snab.
borrowed manual destroy() pattern from the rest of analyse to fix the dup chat issue.
> fix duplicate chats when switching variants in broadcasts

- modules/study/src/main/StudyPgnImport.scala
- modules/study/src/main/StudyPgnImportNew.scala
- modules/study/src/test/BsonHandlersTest.scala
- modules/study/src/test/Helpers.scala
- modules/study/src/test/JsonTest.scala
- modules/study/src/test/NewTreeCheck.scala
- modules/study/src/test/PgnRoundTripTest.scala
- modules/study/src/test/newTreeTest.scala
This PR adapts some changes related to `Tree` and `PgnImport` to `NewTree`/`PgnImportNew`.
So this fixes all the NewTree tests but also ignores them so it'll not affect CI.
> Fix & ignore all NewTree tests

- bin/deploy
make all deployments isolated to {deploy_dir}. this unifies testy, stage, and prod flows. it makes deploys safe for containers using isolated volume maps. any benefits we may have got from symlinking bin & lib are redundant with the version history available in github.
> dont symlink anything

- ui/mod/src/mod.activity.ts
https://github.com/lichess-org/lila/blob/0d7709f95a01bb9e270bceb43fa92d8f7b1deb78/ui/mod/src/mod.activity.ts#L104-L104
fix for problem, we need to ensure that the `merge` function does not allow prototype pollution. This can be achieved by:
1. Blocking the properties `__proto__` and `constructor` from being merged.
2. Ensuring that only own properties of the destination object are merged recursively.
We will modify the `merge` function to include these checks. Specifically, we will:
- Add a check to skip the properties `__proto__` and `constructor`.
- Ensure that the property being merged is an own property of the destination object.
Most JavaScript objects inherit the properties of the built-in `Object.prototype` object. Prototype pollution is a type of vulnerability in which an attacker …
> fix Prototype-polluting function mod.activity() code Injection

- bin/mongodb/ublog-similar-full.js
- bin/mongodb/ublog-similar-incremental.js
- modules/ublog/src/main/UblogApi.scala
- modules/ublog/src/main/UblogBsonHandlers.scala
- modules/ublog/src/main/UblogPost.scala
- modules/ublog/src/main/UblogRank.scala
- don't recommended posts with less than 4 common likers
- we could filter these in bin/mongodb/*.js scripts but with < 50k posts total, let's err on the side of storing more data in ublog_post.similar rather than less
- boost default (LOW) blog tier for a fighting chance at the lower half of community listing page.
lila can expect a few mongo exceptions while that's running
> require recommended ublog posts to share at least 4 common likers

- ui/analyse/src/plugins/analyse.nvui.ts
addresses part of #17234   
I made some videos to illustrate the same scenario [visual ](https://youtu.be/e20_2XPwTeQ)vs [non visual](https://youtu.be/lp7tdM2p-UQ)
In this video, the screen reader keeps reading from the start of the page ... I added an autofocus on the selection that triggers the new page. I think it make the experience better
> Broadcast group/round/game navigation for nvui

- modules/ublog/src/main/UblogApi.scala
- modules/ublog/src/main/UblogForm.scala
- modules/ublog/src/main/UblogPost.scala
it does complicate the lookup a smidge, but it might become useful to distinguish between the cases where similarity check has not even run (None) and cases where the check has run but found nothing (Nil).
mostly this change reduces exception spew in logs when a requested blog doesn't satisfy `{ $match: { live: true, 'likers.1': { $exists: true } } }` and does not get a similar field.
> mark ublog_post.similar as optional

- modules/title/src/main/ui/TitleUi.scala
Avoid confusion with players with titles.
> Leave “Public Account” disabled by default, and remove requirements that don't happen.

- app/controllers/Puzzle.scala
Closes #17178 
The client stores streak info in local storage under the key [`puzzle.streak.${data.user?.id || 'anon'`](https://github.com/lichess-org/lila/blob/47f5ab28e6bef70f06dbc4fadabe9bbec0795f48/ui/puzzle/src/streak.ts#L23). Since user ctx is never sent by the server, it is always set to anon and all users on that machine whether they are logged in or not use that same anon streak session.
> send user context in puzzle streak json

- ui/analyse/src/study/multiBoard.ts
closes #17399 
resets the page number when pagination is changed
> fix: reset page number when pagination is changed in brodcast

- ui/analyse/css/study/relay/_tour.scss
- ui/analyse/src/study/relay/relayPlayers.ts
Fix for #17389
- Use td for player name cell (th is semantically incorrect, I think it was chosen for the text alignment)
- Do not use data-sort-reverse (it fails to update aria-sort and sort icon)
On this screenshot, you see that the sort icon (triangle) is correct
More importantly, the aria-sort is correct
Although, this fixes the issue of having a sorted list with a correct aria-sort ... I did not manage to have the names sorted in ascending order when name header is clicked for the first time 
I think that is the issue @julien4215 was trying to solve using data-sort-reverse
EDIT:
After a chat with julien on discord, I understand the initial situation better
I think he is going to fix the issue in tablesort
> use td for table cell + do not use buggy data-sort-reverse

- app/controllers/Analyse.scala
- app/views/analyse.scala
- app/views/base/embed.scala
- app/views/study.scala
- modules/analyse/src/main/ui/AnalyseUi.scala
- ui/.build/src/manifest.ts
- ui/site/src/site.lpvEmbed.ts
- add structured argument passing to embedded contexts via lite loadEsm implementation in client manifest.js
- deleted more than i created. but i don't fully grasp the modules/ui/views/app separation logic. i'm sure you'll want to fix
> provide loadEsm for embeds

- ui/analyse/src/study/studyTags.ts
Fixes #17400 
Also allows for substitution of date values with '?' which is also valid as per PGN spec.
> conform study date tag input to PGN specification

- ui/analyse/src/study/chapterNewForm.ts
[User saying](https://lichess.org/forum/lichess-feedback/error-parsing-pgn-err_kings) that they used to be able to import pgns without kings before. I can reproduce that old behaviour and surprisingly even move replay works. They can't add more moves through the UI but they can go through whatever pseudo-legal moves they include in the PGN.
chessops cares about the bad setup but scalachess doesn't. In light of better error messaging work done recently by Thanh I am reverting #17362
> Revert PR #17362

- ui/analyse/src/view/components.ts
The Termination tag can sometimes give away important information about the end of the game, but it is currently very hidden, we will try to make it public.
It is not used much in broadcasts (except in some cases, sources), but it can be interesting for studies.
> If there is a `Termination` tag, show it

- .github/workflows/reviewable.yml
Tested on a [test PR on my fork here](https://github.com/fitztrev/lila/pull/8)
> Github action to ensure PRs are editable by maintainers

- ui/lib/src/nvui/chess.ts
addendum to #17416
I did not realise there were 2 different functions printing the moves.
Also competing for the smallest change in Lila's history.
> add punctuation to move to help screen reader

- app/controllers/RelayTour.scala
- conf/routes
- modules/relay/src/main/JsonView.scala
Add a new API endpoint to search broadcast tournaments that will be used by the mobile app (see https://github.com/lichess-org/mobile/issues/1321).
> Broadcast API search endpoint

- app/views/base/embed.scala
- app/views/base/page.scala
- conf/base.conf
- modules/core/src/main/config.scala
- modules/web/src/main/AssetManifest.scala
- modules/web/src/main/WebConfig.scala
- modules/web/src/main/helper/AssetFullHelper.scala
- modules/web/src/main/ui/layout.scala
- ui/.build/src/env.ts
- ui/.build/src/manifest.ts
always use `manifest.json` (no more `manifest.prod.json` or `manifest.dev.json`). server doesn't need netConfig.minifiedAssets.
also remove the data-dev attribute because i couldn't find it used anywhere.
if the client ever needs to know whether assets are minified, we could in future compile something into window.site.info to that effect (rather than tying to the server)
> remove useless manifest bifurcation and unused attribute

- ui/puzzle/css/_tools.scss
https://lichess.org/training
Initially, when the board is resized, the right sidebar also shrank, causing the menu bar to overflow. Since the left sidebar does not shrink with the board, I added `min-height: 70vh` to the right sidebar (matching the left sidebar). This ensures it won’t collapse too much and remains user-friendly.
Closes #17225
> fix(ui): prevent puzzle tools sidebar from shrinking (closes #17225)

- modules/round/src/main/Drawer.scala
We cannot just swap the color and check for `opponentHasInsufficientMaterial` because it's not only depend on pieces on the board, but also whose turn to play. Look at this antichess position: https://lichess.org/analysis/antichess/8/8/3N4/8/1n6/8/8/8_w_-_-_15_44 (from https://github.com/lichess-org/lila/issues/17536) whoever play can win the game so `pov.game.situation.copy(color = color).opponentHasInsufficientMaterial` is true for both sides, even though in real game only White can win.
Fix https://github.com/lichess-org/lila/issues/17536
> Don't auto draw as we're not sure about opponent has no mating material

- ui/lib/src/chat/discussion.ts
Essentially just undoes e0f9d8e, going back to the original value of 32 @schlawg used in e0f9d8e's parent commit (c3bdbba).
Screen recording showing current behaviour (the tab where I'm moving the scrollbar is for "John1"):
https://github.com/user-attachments/assets/8c6b24d4-90af-4f89-a742-7935778cd96a
> If the user manually scrolls to the bottom of a chat, enable autoscroll for future messages

- modules/activity/src/main/JsonView.scala
Return a Map instead of a Seq to be consistent with `ActivityView.games`.
> Tweak corresEnd activity JSON

- ui/lib/src/game/view/status.ts
Checking for pawns being present seems to be unnecessary, due to `if (/[prq]/i.test(pieces)) return false;` a few lines before.
> Do not check for pawns being present again.

- bin/ublog-automod.mjs
- modules/ublog/src/main/UblogAutomod.scala
- modules/ublog/src/main/UblogBsonHandlers.scala
1. deploy this
2. paste the latest [`ublog-system-prompt.txt`](https://github.com/lichess-org/sysadmin/blob/master/prompts/ublog-system-prompt.txt) into settings
3. run the [bin/ublog-automod.mjs](https://github.com/schlawg/lila/blob/blog-migration-prep/bin/ublog-automod.mjs) in this PR to upgrade our blog assessments
4. eventually deploy [blog-discoverability](https://github.com/lichess-org/lila/pull/17690) or something that resembles it
---
- this pr lets lila parse current and future automod documents while preserving legacy behavior
- the prompt and schema were simplified to improve language model performance and ease quality filtering
- all of this code is superseded by the blog-discoverability branch
> loosen UblogAutomod.Result db schema for migration

- ui/analyse/src/view/nvuiView.ts
In analysis board, when the board is flipped, arrows should also be flipped (so that up really means up)
> nvui - fix arrows when flipped

- ui/puzzle/src/ctrl.ts
- ui/puzzle/src/view/chessground.ts
Fixes #17180.
I think this should be the clean way to fix this bug? When I compared the puzzle UI to the analysis UI (the latter of which did not have this bug), the cgVersion approach seems to be the key to why the behavior is different.
(Note: I noticed that, generally speaking, flipped state is also maintained between puzzles - which was not what I expected but perhaps it is intended behavior. This patch does not seem to affect that so on that aspect it keeps things as they are.)
> Maintain flipped board orientation in puzzles when cancelling premove

- modules/web/src/main/ui/layout.scala
The link can be found by a new visitor and be skipped easily by a returning user.
Here is the new user experience with a link:
- New visitor opens lichess.org (with a screen reader)
NVDA start reading ...
- Control Home to go to the beginning of the page
NVDA announces
> button    button    Accessibility - Enable blind mode    -   link    Blind mode tutorial
- type k (for link)
NVDA announces
> Blind mode tutorial  visited  link  
- Hit enter and read the tutorial
Note: new link does not change the Enable/Disable Accessibility button behaviour
If accessibility is disabled, just go to the top of the page (control home) and hit enter
> Add a link to blind mode tutorial

- modules/tournament/src/main/ui/UserTournament.scala
- ui/lib/css/layout/_page-menu.scss
closes #17680 
created a new css class because the class `page-menu__content` is used throughout the codebase and changing it might break things for other pages copied the original class and removed the min-width property
> fix: table background color does not display properly when user has a long name

- ui/bits/css/ublog/_ublog.scss
fix https://github.com/lichess-org/lila/issues/17854
or is it safe to remove from `_btn-rack.scss`
https://github.com/lichess-org/lila/blob/adffe38350dd8af363868dd9daab06db6202f7c9/ui/lib/css/component/_btn-rack.scss#L16
https://github.com/lichess-org/lila/blob/adffe38350dd8af363868dd9daab06db6202f7c9/ui/lib/css/component/_btn-rack.scss#L27
> fix: remove light mode button text shadow in blog

- modules/forum/src/main/ui/PostUi.scala
At the moment, to discover forum posts, blind users rely on the links.
In details:
- Forum title is heading level 1 (good)
- Reply to this topic is heading level 2 (good)
- The rest is a mixture of links and plain text (bad)
The article element used for posts is not discoverable as a landmark because it is nested in the main landmark (screen readers don't support that)
Solution:
move the anchor #n to the beginning of the post and make it a heading level 2
That way, blind mode users can find and skip posts easily using h
instead of
> nvui - improve forum navigation

- ui/bits/css/_plan.scss
In https://lichess.org/patron, Changed which button handles margin from the 'Donate' button (which caused a misalignment issue when the user is not logged in) to the PayPal button.
This causes the donation button to be aligned in both scenarios, and keeps the space between the Donation button and the PayPal button for signed-in users.
**Before:**
**After:**
> Align "Donate" button for not logged in users

- app/controllers/PlayApi.scala
- modules/bot/src/main/BotPlayer.scala
- modules/core/src/main/round.scala
- modules/round/src/main/RoundAsyncActor.scala
- modules/round/src/main/RoundSocket.scala
Here's a implementation proposal for adding claim-draw via API when opponent has disconnected.  
The codebase already uses names like `Draw`, `DrawForce`, `DrawClaim` which seem to relate to "claim of Threefold Repetition", whilst this draw claim is about making the result a draw because the opponent has left - similar to claiming a win when the opponent has left.
This adds the name `DrawClaimForce` to the codebase... 😭   
Adds `/api/board/game/{gameId}/claim-draw`,
similar to already existing `/api/board/game/{gameId}/claim-victory`,
https://lichess.org/api#tag/Board/operation/boardGameClaimVictory
Resolves: lichess-org/api#501
<details>
<summary>ClaimDraw.jsh</summary>
```java
if (! Files.exists(Path.of("chariot.jar"))) Files.copy(URI.create( …
```
> Add API claim-draw for disconnected opponents

- modules/common/src/main/HTTPRequest.scala
- modules/core/src/main/net.scala
- modules/push/src/main/Device.scala
- modules/push/src/main/FirebasePush.scala
- modules/push/src/main/PushApi.scala
- modules/web/src/test/common/HTTPRequestTest.scala
Currently we are using a simple `boolean` to either send or not a Firebase push message to the mobile app.
In order to support the coming [Private messaging](https://github.com/lichess-org/mobile/pull/1981) feature (and other in the future) we need to also check the app version from the user agent to only send the messages to a supported app version.
So the `boolean` is replaced with an `Option[String]` which is compared with the version string in the UA.
The comparison function is quite simple and not robust but should work just fine as mobile versions strings always have same length.
> [Mobile] Use UA version to check if a firebase message should be sent

- ui/tournament/src/view/arena.ts
Tournaments with no streak bonuses should still have wins coloured green #17880
Issue:
When streaks are disabled, the "renderScoreString" function in "ui/tournament/src/view/arena.ts" wraps each score in a tag with no further differentiation. This means all wins are rendered with the neutral `<score>` tag (which appears grey by default) instead of the green `<streak>` tag.
Fix:
The fix made in my fork modifies the early return in this function (when streakable is not true) to tag wins as `<streak>`, instead of returning all scores as `<score>`. This means any score greater than 1 (i.e. 2 points for a win, or 3 points for a berserk win) in a `<streak>` tag even when streaks are disabled, resulting in a green display on the score sheet.
This does not affect the scoring, purely the visual …
> Fix for tournaments with no streak bonuses should still have wins coloured green 

- modules/bot/src/main/GameStateStream.scala
When a game state stream notices a game is finished, it closes the stream.  
In case the game is aborted, the stream doesn't close. This seems to be an omission.  
This Pull Request also checks if game is aborted, to also close the stream.  
Relates: tors42/chariot#22
> Close stream also if game is aborted

- ui/bits/src/bits.ts
After reporting a user, there is sometimes an option to block them. The button appears to work after being clicked, but it actually doesn't block the user. The reason is because `action` is not an attribute the button has.
> Fix bug with report block button

- modules/common/src/main/HTTPRequest.scala
This allows it to be accessed within a bridge network locally by using the name of the lila container in the prometheus config instead of "localhost" which wouldn't resolve
> don't redirectWrongDomain on prometheus route

- modules/user/src/main/ui/UserShow.scala
fixes #17956 
Note for @superuser-does 
There should be more context in crowdin (site.joinedX)
Look at the German version
EDIT: I fixed it on crowdin
> Fix timeago on user show

- ui/analyse/src/treeView/common.ts
fixes #18035 
Note: there is a similar problem on puzzle, but the cause is different: the autoscroll is not called at all when fast-backward
> Fix analysis scroll to top on fast-backward

- modules/common/src/main/HTTPRequest.scala
Redirect all `/account` routes to `/login` for unauthenticated users. Previously, only `/account/close`, `/account/delete`, and `/account/personal-data` were redirected to `/login`, the others to `/signup`.
The rationale behind this is that all `/account` routes already require authentication to access. It would make sense to redirect users to `/login` when they aren't authenticated, as it provides the option of using an existing account, rather than assuming they don't have one. 
This is essentially a UX improvement.
This may be needed to merge lichess-org/mobile#2145.
Closes #18070
> feat: redirect all `/account` routes to `/login` for unauthenticated users

- app/views/round/player.scala
- app/views/round/watcher.scala
- modules/chat/src/main/ChatUi.scala
- ui/lib/src/chat/discussion.ts
- ui/lib/src/chat/interfaces.ts
Reverts lichess-org/lila#18053
Sorry, that's not it. No UI widget should ever traverse all unrelated session objects. Who knows how many there are? This could add subtle and impossible to debug performance problems.
The idea to clean-up previous chat storages was good however, to avoid the proliferation of chat storage keys. But another implementation has to be found.
> Revert "Clears Message Input When Playing Against New Opponent: Issue  14602"

- ui/analyse/src/study/relay/deepLink.ts
- ui/analyse/src/study/relay/interfaces.ts
- ui/analyse/src/study/relay/relayManagerView.ts
- ui/analyse/tests/deepLink.test.ts
| - | - |
| <img width="491" height="150" alt="image" src="https://github.com/user-attachments/assets/1ab0c250-c9f7-43c8-8a23-567a51e75d81" /> | <img width="494" height="146" alt="image" src="https://github.com/user-attachments/assets/fe0d62e8-fddd-453a-a022-78bd0ff22d9d" /> |
The Broadcaster app now supports deep links. Clicking this link will start the app (or bring it to focus if already opened) and then navigate directly to that round.
> Add deep link to Broadcaster App from broadcast manager section

- modules/relay/src/main/RelayPlayer.scala
- modules/relay/src/test/RelayPlayerTest.scala
Corresponding removal in scalachess: https://github.com/lichess-org/scalachess/pull/748
Added further sorting:
* Sort players by:
1. Score (Descending)
2. Tiebreak points (compare each tiebreak in order, higher is better)
3. Player rating (Descending)
4. Player name (Alphabetical, ascending)
* Add tests for sorting (Copilot generated but checks out)
> Move tiebreak sorting to lila. 

- ui/chart/src/chart.ratingHistory.ts
this is a usability fix to allow mobile touch scrolling on the ratings chart in profile views. no idea if there's a better way. chartjs seems to set touch-action: none in an inline style, so maybe there's a config option to do this cleaner.
> dont filter touch scrolling

- ui/analyse/css/_round-underboard.scss
- ui/analyse/src/serverSideUnderboard.ts
https://lichess.org/forum/lichess-feedback/request-a-computer-analysis-feature-gone-from-mobile-chrome-users-android
not a bug, per se. but a confusing part of the app this person found that we can fix.
> dont hide request analysis button when fishnet toggle is off

- ui/bits/css/plan/_style-selector.scss
so that the background color fills the entire width of the selector for Safari 18. fix #18254
| | Before | After |
|--------|--------|--------|
| Safari | <img width="1172" height="498" alt="image" src="https://github.com/user-attachments/assets/e3552c6c-846c-4783-b85a-eb9e66cb604f" /> | <img width="1220" height="511" alt="image" src="https://github.com/user-attachments/assets/7a7c83e0-0695-4e7d-9047-e6a1ca05c5e8" /> |
| Chrome | <img width="1186" height="505" alt="image" src="https://github.com/user-attachments/assets/8e1c5e0b-ffa9-40c6-93e8-847628e5f591" /> | <img width="1180" height="494" alt="image" src="https://github.com/user-attachments/assets/4b9b8b80-e310-42de-b0fb-43773c2c55f8" /> |
| Firefox | <img width="1061" height="634" alt="image" …
> patron color selector: explicit width for tier name

- ui/opening/src/wiki.ts
Implemented the changes requested in #17957 about the truncation of descriptions from wikibooks in the opening explorer.
**What Changed**
I updated the api request not to have a max characters argument so it could fetch the entire page from wikibooks. I updated the `removeH1` function to work correctly (the format of the html was `<h1 data-mw-anchor=...</h2>`)
I removed the entirety of the Theory table section (and it's similar counterparts All possible Black's moves and All possible replies) since these tables aren't actually returned by the API requests so these sections were essentially empty. To do this, I used a regex search to match the header and then delete everything until the next header was encountered.
^^Empty Theory Table: Now this section is not shown
^^Header previously not …
> updated opening explorer wiki books display

- ui/analyse/src/wiki.ts
- ui/opening/src/wiki.ts
Same changes to wikibooks info as #18277 but for analysis. I also noticed that the All possible replies header was `h3` not `h2` so I updated that for both the opening explorer and analysis.
**What Changed (Copy and pasted from #18277 since they are the same changes in a different file)**
I updated the api request not to have a max characters argument so it could fetch the entire page from wikibooks. I updated the removeH1 function to work correctly (the format of the html was <h1 data-mw-anchor=...</h2>)
I removed the entirety of the Theory table section (and it's similar counterparts All possible Black's moves and All possible replies) since these tables aren't actually returned by the API requests so these sections were essentially empty. To do this, I used a regex search to match the …
> Updated wikibooks info for analysis page

- modules/ublog/src/main/ui/UblogUi.scala
- ui/lib/css/component/_ublog-card.scss
no need to re-fetch them after restarts or create a potential "must purge cloudflare" situation.
also, avoid using sass extensions when a better option exists.
> use hashed links for random blog backgrounds

- modules/search/src/main/LilaSearchClient.scala
to avoid
```
2025-10-02 08:18:11,832 ERROR p.c.s.netty.PlayRequestHandler Cannot invoke the action
scala.MatchError: java.net.SocketException: Connection reset (of class java.net.SocketException)
at lila.search.LilaSearchClient.search$$anonfun$1(LilaSearchClient.scala:24)
at cats.instances.FutureInstances$$anon$3.applyOrElse(future.scala:52)
at cats.instances.FutureInstances$$anon$3.applyOrElse(future.scala:52)
at scala.util.Failure.recover(Try.scala:242)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:487)
at scala.concurrent.BatchingExecutor$AbstractBatch.runN(BatchingExecutor.scala:134)
at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:163)
at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:146)
at …
```
> Logs all errors in search client

- project/Dependencies.scala
https://github.com/lichess-org/lila-search/releases/tag/v3.2.4
> Update lila-search client 3.2.4

- modules/core/src/main/lilaism/LilaLibraryExtensions.scala
- Add some typings for public values
- reuse `funit` for `fuccess(())`
> Some minor improvement for lila extensions

- ui/lib/css/component/_button.scss
- ui/lobby/css/_setup.scss
- ui/lobby/src/view/setup/modal.ts
fatten up the chin a bit, don't disappear the create game button, and don't resize the dialog to show the spinner. jank like this can creep in unknowingly because it all happens in a heartbeat on dev instances.
> reduce setup modal flakiness involving spinner

- ui/lobby/css/_setup.scss
it looks neat. but it also looks like a focus ring when that element has no focus. 
this is a PR rather than an issue as the bare button seems fine to me, but maybe you can find a way to style things so it still pops without suggesting keyboard focus. the outline remains on touch devices.
> remove green "create game" button outline from setup dlg on desktop

- project/Dependencies.scala
Reverts lichess-org/lila#18344
```
10:15:14.226 [error] akka.actor.OneForOneStrategy - 'java.util.Queue reactivemongo.io.netty.channel.epoll.EpollEventLoop.newTaskQueue0(int)'
akka.actor.ActorInitializationException: akka://reactivemongo/user/main: exception during creation, root cause message: ['java.util.Queue reactivemongo.io.netty.channel.epoll.EpollEventLoop.newTaskQueue0(int)']
at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
at akka.actor.ActorCell.create(ActorCell.scala:668)
at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
at akka.dispatch.Mailbox.run(Mailbox.scala:230)
at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
at …
```
> Revert "Update reactivemongo-shaded-native-linux-x86-64 to 1.1.0-RC18"
