lichess-org/lila

- public/stylesheets/user-show.css
Looks better when the star icon isn't underlined
> hide underline until hover on donor link

- app/views/user/mod.scala.html
- modules/evaluation/src/main/Group.scala
- modules/mod/src/main/AssessApi.scala
Test comparing games by diving SF analysis into groups of 5 moves.
> Scala evaluator

- modules/i18n/src/main/Contributors.scala
Add myself as contributor to Norwegian Bokmål translation
> Add self as contributor

- public/javascripts/chart2.js
forgot to restore it after trying training colors...
> atomic color

- public/stylesheets/common.css
http://i.imgur.com/D0PHOAU.png
> include border in sizes, fix when zoom >= 75%

- modules/security/src/main/DataForm.scala
> Stop VEVO accounts

- public/stylesheets/common.css
http://caniuse.com/#search=translate
> fixes vertical position in fp menu for safari #380

- app/templating/GameHelper.scala
- app/views/game/widgets.scala.html
- public/javascripts/big.js
- public/stylesheets/common.css
> make entire game widget clickable

- app/views/tournament/faq.scala.html
"This tournaments" => "This tournament"
> Fix pluralization

- public/stylesheets/analyse.css
- ui/analyse/src/view.js
> move blacks analyse comment borders right

- app/views/coordinate/home.scala.html
- public/javascripts/big.js
- public/javascripts/coordinate.js
- public/stylesheets/coordinate.css
- ui/opening/src/view.js
- ui/puzzle/src/view.js
Not sure about that last commit, feel hackish. Changes in view.js files is mostly retabbing because i surrounded it with divs alike regular game for bottom area centering and right area width.
> Training zoom

- modules/tv/src/main/Streaming.scala
similar to hitbox, twitch search breaks too often
> get twitch streamers titles instead of searching

- public/stylesheets/analyse.css
- public/stylesheets/common.css
stacked training difficulty buttons, fix for various languages
don't wrap text in menu for certain languages
margin between right marker & scrollbar in analyse
> Some ui changes

- public/stylesheets/board.css
- ui/analyse/src/promotion.js
- ui/round/src/promotion.js
Hides when not hovering board, scales when board is zoomed and pieces
appear over the pawn that is promoting.
> promotion: zoomable, hidable, relative to pawn

- ui/round/src/ctrl.js
> Explosion sound at en passent in Atomic

- public/stylesheets/home.css
Fixes #611
Screenshot: http://i.imgur.com/wcsy6yw.png
> Give unofficial tournaments a grey color

- public/stylesheets/board.css
- ui/round/src/clock/view.js
Some screenshots:
http://imgur.com/a/WczKO
> Add colors to clock bar, fixes #130

- ui/round/src/view/replay.js
> Don't switch channels when flipping board on TV

- public/stylesheets/board.css
- ui/game/src/view/user.js
- ui/round/src/view/table.js
Added tooltip for green player icon saying "Player is connected" while the tooltip for red player icon says "Player has disconnected". 
Tested this in anon vs anon, registered player vs registered player, registered player vs anon and registered player vs AI (all in FF on Ubuntu Desktop).
> adding tooltips for player connection status - closes #635

- public/sounds.html
Radio buttons for select sound set + one button per sound.
Also added a special button that will play all the countdown sounds from 10 to 0 with 1 second in between.
> adds a sound test page - closes #649

- app/templating/GameHelper.scala
- ui/game/src/view/status.js
> Make variant endings show up translated on profile

- public/stylesheets/tournament.css
- ui/tournamentSchedule/src/view.js
> display variant name in tournament schedule box - closes #627

- public/javascripts/big.js
Instead of constantly appending new ones.
> Recycle <style> elements for saving background data

- app/views/base/layout.scala.html
Well, I kinda missed this part in the last PR, second time's the charm!
> Reuse the same element in 6e4b28e

- app/templating/NumberHelper.scala
> Fix ranking in 3315b63

- public/javascripts/big.js
- ui/round/src/ctrl.js
These commits add desktop notifications (#184) for the following situations: when it's your move, when you got a new challenge, and when you got a new inbox message. The notifications also don't show up when you're already watching the page.
> Desktop notifications

- public/stylesheets/common.css
- public/stylesheets/dark.css
- public/stylesheets/transp.css
http://lichess.org/forum/lichess-feedback/dark-theme-notation-scroll-bar
> Adds theming for scroll bars.

- app/controllers/Monitor.scala
- app/controllers/Prismic.scala
- app/templating/I18hHelper.scala
- app/views/user/mod.scala.html
- bin/build-deps.sh
- bin/prod/restart
- conf/application-logger.xml
- conf/routes
- modules/analyse/src/main/PaginatorBuilder.scala
- modules/blog/src/main/BlogApi.scala
- modules/common/src/main/PlayApp.scala
- modules/forumSearch/src/main/Env.scala
- modules/forumSearch/src/main/Indexer.scala
- modules/gameSearch/src/main/Env.scala
- modules/gameSearch/src/main/Indexer.scala
- modules/monitor/src/main/Reporting.scala
- modules/search/src/main/ESClient.scala
- modules/search/src/main/ElasticSearch.scala
- modules/search/src/main/Env.scala
- modules/search/src/main/PaginatorBuilder.scala
- modules/search/src/main/model.scala
- modules/teamSearch/src/main/Env.scala
- modules/teamSearch/src/main/Indexer.scala
- project/Dependencies.scala
- public/oops/disabled.html
Apparently, elasticsearch IO threads went nuts. Will extract that stuff to another JVM.
> Solve August 2015 shitstorm

- public/stylesheets/common.css
> https://github.com/ornicar/lila/issues/875

- app/views/relation/actions.scala.html
- app/views/user/show.scala.html
- public/stylesheets/common.css
- public/stylesheets/user-show.css
renamed relation_actions to user_actions, and used relation_actions to
only wrap the affected buttons after following.
http://en.lichess.org/forum/general-chess-discussion/follow-somebodys-games#3
> fix buttons disappearing after follow

- ui/tournament/src/view/arena.js
http://i.imgur.com/eeEWOkR.png
> fix tournament win rate

- public/stylesheets/analyse.css
Unfortunately not supported by IE, can implement a fall back if really necessary.
http://caniuse.com/#feat=css-resize
fixes #859
> Resize vertical only

- app/views/setup/await.scala.html
- public/javascripts/big.js
- public/stylesheets/board.css
closes #470
Browser compatibility (http://caniuse.com/#feat=clipboard):
* Internet Explorer 5.5+
* Chrome 43+ (on April 2015)
* Mozilla Firefox 41+ (shipping ~September 2015 __!!!__)
* Opera 29+ (based on Chromium 42, on April 2015)
> Copy from await

- app/views/user/mod.scala.html
> Reverse "allows" with "blocks" properly.

- public/stylesheets/board.css
It was causing hover feedback to fail in obscure conditions.
> Change pseudo-element for koth decorations

- public/stylesheets/transp.css
> Give the ceval box a shade in background

- modules/tournament/src/main/GreatPlayer.scala
http://ja.lichess.org/forum/lichess-feedback/gm-surname-misspelled#1
> Fix GM surname

- app/views/base/layout.scala.html
- public/javascripts/big.js
- public/stylesheets/common.css
fixes #1071
expected behaviour ![](https://cloud.githubusercontent.com/assets/5595067/10223540/0e79ee9e-688c-11e5-804d-d7884b9d9db6.png)
> Changes display of notification counters.

- ui/coachMove/src/ctrl.js
- ui/coachOpening/src/ctrl.js
> fixes coach errors, probably

- public/stylesheets/analyse.css
- public/stylesheets/board.css
- public/stylesheets/boardEditor.css
- public/stylesheets/coach.css
- public/stylesheets/common.css
- public/stylesheets/coordinate.css
- public/stylesheets/dark.css
- public/stylesheets/home.css
- public/stylesheets/import.css
- public/stylesheets/monitor.css
- public/stylesheets/notFound.css
- public/stylesheets/simul.css
- public/stylesheets/tournament.css
- public/stylesheets/transp.css
- public/stylesheets/tv.css
- public/stylesheets/user-show.css
- public/stylesheets/video.css
> Improve code style.

- app/templating/UserHelper.scala
> Adds hover hint for donor star in powertip

- public/javascripts/user.js
> Hide extensive related users list and factorize "this" calls

- app/views/setup/timeMode.scala.html
- modules/game/src/main/BinaryFormat.scala
- modules/setup/src/main/AiConfig.scala
- modules/setup/src/main/ApiConfig.scala
- modules/setup/src/main/Config.scala
- modules/setup/src/main/FriendConfig.scala
- modules/setup/src/main/HookConfig.scala
- modules/setup/src/main/Mappings.scala
- public/javascripts/big.js
Note: needs https://github.com/ornicar/scalachess/pull/49 to be reviewed (and merged) first
http://en.lichess.org/forum/lichess-feedback/request-new-time-control-30-seconds0
http://en.lichess.org/forum/team-30-seconds--0-time-control/this-is-how-we-can-get-0-games
> Implemented 30second-games

- ui/tournament/src/view/button.js
> Make "join" button more noticeable in arenas

- app/controllers/I18n.scala
> Keep query string when switching language

- modules/api/src/main/RoundApi.scala
- modules/tournament/src/main/AutoPairing.scala
- ui/round/src/view/table.js
> Show correct time to do first move in tournament

- modules/security/src/main/Permission.scala
Hunter role already extends Beta.
> Inheritance resolution of the Beta perm

- app/controllers/Main.scala
- conf/routes
- modules/push/src/main/Device.scala
- modules/push/src/main/DeviceApi.scala
- modules/push/src/main/GooglePush.scala
- modules/push/src/main/PushApi.scala
I adapter server code a bit to match correct gcm message format. It handles only one device per user for now. Some more logic and http requests are required to handle multiple devices.
I could not test it because of cors issues, but I think we're at the point we get the notif on game end and turn change. 
I'm ready to test it when I can setup lila to not rewrite '192.168.1.13:9663' urls to 'fr.192...'
> Some work on push

- app/views/video/show.scala.html
> Allow the embedded youtube player to go fullscreen

- public/stylesheets/user-show.css
> Made top50 and top100 trophies more compact

- app/views/user/relatedTable.scala.html
instead of the "advanced search" for exports, since the user tab is there now
> Link "fav opp" to user's "advanced search" tab

- modules/quote/src/main/Quote.scala
See https://www.goodreads.com/quotes/3181925-most-of-the-gods-throw-dice-but-fate-plays-chess
> Fix Pratchett's quote

- modules/quote/src/main/Quote.scala
Popular quote by Jerry of [ChessNetwork] (https://www.facebook.com/ChessNetwork/)
> Add a quote by ChessNetwork.

- public/stylesheets/transp.css
> Blend quote decorator border in transp theme

- public/javascripts/chart2.js
> fix racing kings graph color for light themes

- bin/provision-vagrant.sh
fail early when subprocesses fail
> unparallize build script to catch errors

- bin/provision-vagrant.sh
> Fix grammatical error

- app/controllers/Page.scala
- app/views/game/variantLink.scala.html
- conf/routes
This commit links to the follow documents:
* pages about antichess, chess960, and horde
* a page about getting a master title on lichess
I wrote the last page by accident, as I was chatting with friends about it before starting the write. Let me know if you don't want it, I'll amend the PR.
Before merging this we need QA for the articles and publishing them.
> Adds several new pages - for #1501

- modules/security/src/main/Spam.scala
also shouldn't this be in master.
> add chess.com blacklist / replacement

- modules/user/src/main/Countries.scala
There is already a flag icon.
http://ja.lichess.org/qa/1026/faroe-islands
> Add Faroe Islands to list of countries

- public/javascripts/tournamentForm.js
previously, toggling private/public would reset time control and duration to default
fixes https://github.com/ornicar/lila/issues/260
> create tournament form does not reset fields

- public/stylesheets/transp.css
> Styling for analysis variant dropdown in transp

- modules/analyse/src/main/Advice.scala
Annotates my own games with surprising accuracy!  Perhaps there is a more concise or efficient way to code this.
> Resolve ornicar/lila#1494 using win rate-based annotation

- modules/i18n/src/main/Contributors.scala
> Add myself to Russian language

- README.md
Edited some of the wording so that it would read better. Also removed
commas when commas are not needed. There were a few commas before the
word 'and' when the word 'and' was not separating two independent clauses..
Added a License subheading at the bottom. The README didn't
mention which license is used. It should be mentioned in the README so
others don't have to click the License text file just to know what the
license is.
Added [more than] 80 languages on line 18 because lichess is now translated to 82 or 83 languages. It makes sense not to use an exact number since the translations are increasing.
Other minor edits regarding wordy sentence and what not.
> General improvements to the README file.

- app/views/account/kid.scala.html
These are making the text be something like left-aligned but we don't have such styling at all other pages.
> Remove useless <br />

- app/controllers/Account.scala
> Add nbFollowing to /account/info

- ui/analyse/src/explorer/explorerConfig.js
- ui/analyse/src/explorer/explorerCtrl.js
- ui/analyse/src/explorer/explorerView.js
Previously it would just display a "From position opening explorer" that has no games.
> explorer: query standard db for from position (fixes niklasf/lila-openingexplorer#45)

- ui/tournamentSchedule/src/view.js
The UTC fixes the real issue, it was resetting the time or something and
never continued. But also changed the looping too, it's more resiliant
and doesn't require the real fix to work.
> Fixes #1768 infinite daylight savings loop in fx

- modules/worldMap/src/main/Env.scala
regression from
https://github.com/ornicar/lila/commit/ce04b8ea8dfb3ff83e5f522ef1da5b2993dcf658#diff-07658aa52e35f7a1edc5fcd621377352
couldn't see any other copypaste mistake
> fix network map

- modules/quote/src/main/Quote.scala
Add quote from https://mattogpatt.no/2016/04/18/carlsen-it-was-a-very-big-thing-me-to-be-compared-to-karjakin/
Thanks to Cynosure for the idea.
> Add Magnus quote

- public/stylesheets/board.css
- ui/analyse/src/crazy/crazyDrag.js
- ui/analyse/src/crazy/crazyView.js
- ui/round/src/crazy/crazyDrag.js
- ui/round/src/crazy/crazyView.js
briefly tested in chrome, firefox, surf and internet explorer 11
> fix #1847 crazyhouse: static piece positions in hand

- app/templating/Environment.scala
- app/views/analyse/replay.scala.html
- app/views/board/userAnalysis.scala.html
- app/views/study/show.scala.html
- conf/base.conf
- modules/api/src/main/Env.scala
- ui/analyse/src/explorer/explorerCtrl.js
- ui/analyse/src/explorer/explorerView.js
- ui/analyse/src/explorer/tablebaseXhr.js
- ui/analyse/src/view.js
Using the new API and rebased on top of study. This should be complete, barring bugs I didn't find.
> Endgame explorer

- ui/round/src/clock/ctrl.js
- Do not play sound more than once every 20s
- Rearm at 1.5 times cutoff
> Decrease emergency sound frequency

- .gitignore
these files are automatically created by `sbt eclipse`
> Add eclipse generated files to gitignore

- modules/push/src/main/GooglePush.scala
> Fix notifications sound/light/vibration

- modules/fishnet/src/main/ClientVersion.scala
Bug fixes affecting the analysis/play results:
* v1.5.2 - rare issue with upperbound and lowerbound
* v1.3.6 - from position
> Bump fishnet min version to 1.5.2

- modules/quote/src/main/Quote.scala
source:
- https://www.youtube.com/watch?v=V6AwKoiAcqs
- https://books.google.fr/books?id=WiRmCgAAQBAJ&pg=PP15#v=onepage&q&f=false
> add Korchnoi quote (RIP)

- app/views/account/kid.scala.html
- app/views/account/layout.scala.html
- app/views/base/layout.scala.html
> re-localize kid mode translations in hover tooltips of the happy icon and other places

- modules/quote/src/main/Quote.scala
Source: [https://www.reddit.com/r/IAmA/comments/20t4pv/hello_reddit_im_magnus_carlsen_the_world_chess/](https://www.reddit.com/r/IAmA/comments/20t4pv/hello_reddit_im_magnus_carlsen_the_world_chess/)
> Added quotes from Magnus Carlsen AMA.

- modules/importer/src/main/DataForm.scala
- modules/importer/src/main/Importer.scala
- modules/importer/src/test/DataFormTest.scala
http://en.lichess.org/forum/lichess-feedback/import-game-trouble-with-termination and a bit more, basically a counterpart to https://github.com/ornicar/lila/blob/master/modules/game/src/main/PgnDump.scala#L80
> import: respect termination tag

- Vagrantfile
> Combine Vagrant fixes

- ui/analyse/src/actionMenu.js
- ui/analyse/src/autoplay.js
> Add autoplay with time based on CPL

- modules/message/src/main/Api.scala
- modules/message/src/main/Env.scala
> Allow trolls to communicate with followers

- ui/learn/src/stage/bishop.js
- ui/learn/src/stage/capture.js
- ui/learn/src/stage/check1.js
- ui/learn/src/stage/checkmate1.js
- ui/learn/src/stage/king.js
- ui/learn/src/stage/knight.js
- ui/learn/src/stage/pawn.js
- ui/learn/src/stage/queen.js
Plus some spelling corrections.
> Converted all puzzles to play as white

- modules/tournament/src/main/Schedule.scala
Add some increment time controls to crazyhouse tourney schedule.
This fixes #2099.
> Create crazyhouse inc tourneys

- app/views/forum/categ/show.scala.html
- app/views/forum/search.scala.html
This is a fix for the issue #2160
> Fix for issue #2160

- public/stylesheets/home.css
Games created by the user himself now are colored differently in the game graph. See issue # #2171 for more details & screenshots.
> Self-created game graph icon colored blue

- .gitmodules
- ui/analyse/src/ceval/cevalCtrl.js
- ui/analyse/src/ceval/cevalPool.js
- ui/analyse/src/ceval/cevalView.js
- ui/analyse/src/ceval/stockfishWorker.js
- ui/analyse/src/ceval/sunsetterWorker.js
- ui/analyse/src/ctrl.js
> [WIP] Local crazyhouse analysis

- public/stylesheets/chat.css
> Replace note height with flex-grow. Fix #2185.

- app/templating/SetupHelper.scala
- modules/fishnet/src/main/ClientVersion.scala
- modules/fishnet/src/main/UciToPgn.scala
- modules/game/src/main/Game.scala
- modules/setup/src/main/Config.scala
Enable crazyhouse for fishnet. This is blocked by two things:
* **Fishnet clients must be updated to 1.7.0 first**
* Buggy crazyhouse board validation: ornicar/scalachess#87
> Enable crazyhouse analysis and ai

- ui/analyse/src/ceval/sunsetterWorker.js
Same fix for the client side version
> Update sunsetter.js and fix score sign after forced move

- ui/analyse/src/autoShape.js
util import needed for util.sanToRole call, on line 20. The missing import is causing local sunsetter issues.
For #2216
> Fix autoShape imports

- public/stylesheets/home.css
> Fix minor CSS inconsistencies on homepage

- modules/security/src/main/CSRFRequestHandler.scala
* file:// can also appear on POST requests, not just websockets.
* Old and wierd browsers (e.g. Firefox <= 10) do not send an origin on
websockets.   The choice is to break support or not protect them.
Do the latter.
> refine csrf filter with lessons learned from log

- app/controllers/ForumPost.scala
- app/views/forum/topic/show.scala.html
- conf/routes
- modules/forum/src/main/BSONHandlers.scala
- modules/forum/src/main/DataForm.scala
- modules/forum/src/main/Post.scala
- modules/forum/src/main/PostApi.scala
- modules/forum/src/main/PostRepo.scala
- public/javascripts/forum-post.js
- public/stylesheets/forum.css
TODO:
- Not allow a post to be edited to be a length of the minimum required length of a post.
- Better CSS styling
> [WIP] Allow users to edit their forum posts

- app/controllers/Message.scala
- modules/message/src/main/Env.scala
- modules/message/src/main/JsonView.scala
As promised, a *very* early PR. Just the inbox api endpoint working so far, but I'm hopeful that the others will go faster now that I've got a compiling install and know how this tiny corner of the code base works. Comments welcome whenever convenient for you to review incrementally.
> Messaging API

- public/stylesheets/common.css
> fix margin of tv on homepage

- modules/user/src/main/User.scala
this way it can no longer conflict with the auto link, which runs before
> sharper boundaries for @ mentions (fixes #2195)

- public/javascripts/forum-post.js
Behaviour is:
- Always prefer forum thread participants when autocompleting.
- Fall back to all site users when characters typed is >= 3 and there are no matches in the thread participants.
> Forum autocomplete: Only use all site users if no forum participant usernames are matched.

- modules/plan/src/main/Patron.scala
- modules/plan/src/main/PlanApi.scala
- public/javascripts/main.js
- public/javascripts/util.js
- public/stylesheets/analyse.css
- public/stylesheets/common.css
- public/stylesheets/dark.css
- ui/analyse/src/actionMenu.js
- ui/analyse/src/autoShape.js
- ui/analyse/src/ceval/cevalCtrl.js
- ui/analyse/src/ceval/cevalDict.js
- ui/analyse/src/ceval/cevalPool.js
- ui/analyse/src/ceval/cevalView.js
- ui/analyse/src/ceval/pv2san.js
- ui/analyse/src/ceval/stockfishProtocol.js
- ui/analyse/src/ctrl.js
- ui/analyse/src/explorer/explorerView.js
- ui/analyse/src/util.js
- ui/analyse/src/view.js
- ui/notify/src/ctrl.js
Here's a 200 sloc SAN generator for all the variants. It shows checks and mates, but disregards pins in the move disambiguation.
TODO:
New TODOs:
> [WIP] Display PVs in ceval

- ui/analyse/src/ceval/cevalView.js
- ui/analyse/src/ceval/sunsetterProtocol.js
show a textual pv in crazyhouse. sunsetter does not support multipv.
> show a textual pv in crazyhouse

- modules/common/src/main/mon.scala
- modules/message/src/main/Env.scala
- modules/message/src/main/MessageApi.scala
- modules/message/src/main/model.scala
- modules/push/src/main/Env.scala
- modules/push/src/main/PushApi.scala
- project/Build.scala
This PR adds push notifications when a new message is received.
> Add push for messages

- public/javascripts/main.js
- ui/tournament/src/sound.js
To improve stability of tourney countdown.
> Preload countdown sounds

- app/controllers/Importer.scala
I'm improving the import feature in the app.
I didn't handle the `recover` case in the `sendGame` controller.
> Return game json from POST /import

- app/templating/AiHelper.scala
- app/templating/GameHelper.scala
- app/templating/SetupHelper.scala
- app/views/game/widgets.scala.html
- modules/fishnet/src/main/ClientVersion.scala
- modules/game/src/main/Game.scala
- modules/setup/src/main/Config.scala
- ui/lobby/src/view/playing.js
- ui/round/src/view/user.js
:warning: bumps fishnet min version to the newly released v1.11.0. instances should be updated before this lands.
> [ON HOLD] enable stockfish as crazyhouse ai

- modules/api/src/main/Env.scala
- modules/api/src/main/UserApi.scala
I couldn't compile after rebasing with last master (deps issue). Since the change is very small I'm creating the PR anyway.
> Add nb playing games and nb imports to user api

- ui/analyse/src/ceval/cevalCtrl.js
- ui/analyse/src/ctrl.js
Via https://github.com/ddugovic/Stockfish/issues/110#issuecomment-260598217
/cc @ianfab, @ddugovic
> update sf and enable ceval for antichess

- ui/analyse/src/explorer/explorerCtrl.js
6 piece tables complete and - for all I know - available for exploration for the first time in history
> Enable atomic tablebase

- modules/puzzle/src/main/Selector.scala
Lower the learn rate a smidge to extend standard intervals between revisiting puzzles.
> Lower learn rate from 1/5 -> 1/7

- modules/puzzle/src/main/Selector.scala
Because people can't be trusted.
> -10 no longer disables puzzles

- ui/round/src/view/button.js
> Analysis button should jump to move

- ui/round/src/view/button.js
> fix ply round->analysis for watchers too

- ui/analyse/src/explorer/explorerCtrl.js
- ui/analyse/src/explorer/explorerView.js
- ui/chess/src/main.js
tablebase.lichess.org now also serves 5 piece antichess tablebases. By the nature of the variant almost every game will reach tablebase land, so these should be useful.
If all goes well we will also have 6 piece tables in a couple of months.
> Antichess tablebases

- modules/common/src/main/WMMatching.scala
move class out of def (I think this matters)
> WMMatching perf tweak

- public/javascripts/chart/division.js
- ui/lobby/src/variant.js
Made "middlegame" consistent with "endgame", tweaked the formatting of the lobby variant.js
> Minor language tweaks

- app/controllers/Report.scala
- app/views/report/list.scala.html
- conf/routes
- modules/report/src/main/Report.scala
- modules/report/src/main/ReportApi.scala
Filtering by clicking the links: ![image](https://cloud.githubusercontent.com/assets/41573/21744478/b11a2824-d516-11e6-9872-063211335107.png)
> Adding possibility to filter user reports by reason to enable more efficient handling

- modules/quote/src/main/Quote.scala
> Fix Dawkings -> Dawkins in quotes

- public/javascripts/embed-analyse.js
- public/javascripts/main.js
User analysis, studies and embedded analysis were not initialized after the refactor in 9f156f9ac83f7fbc8ad0c8b0aac2e13d84ee6451.
> fix js error: LichessAnalyse is not a function

- public/javascripts/chart/advantage.js
* Better labels with `#3` or `+3.4` (#2516).
* Scale by winning chances (#2511).
> Improve advantage charts

- ui/puzzle/src/autoShape.js
because there is no crazyhouse this is only relevant for promotions
> fix hover glitch also for puzzles (#2473)

- ui/round/src/ctrl.js
- ui/round/src/promotion.js
Requires ornicar/chessground#34. Branch is based on #2539.
> [RFC] never auto promote when ctrl is pressed

- ui/analyse/src/ctrl.js
- ui/analyse/src/practice/practiceView.js
Still not correct in horde, racing kings, KotH, anti and atomic. (But that should not be a regression.)
> Improve client side game end detection

- modules/memo/src/main/Syncache.scala
Pass returned future to waitForResult.
> Safer ConcurrentHashMap usage

- ui/analyse/src/ctrl.js
- ui/ceval/src/stockfishProtocol.js
- ui/ceval/src/view.js
- ui/ceval/src/winningChances.js
- ui/puzzle/src/ctrl.js
Show local eval after it exceeds fishnet nodes or finds a better mate.
Fixes #2533
> Improve merge of local eval and fishnet 

- ui/analyse/src/moveView.js
- ui/ceval/src/view.js
To fix UI. Followup incoming to clean up organization.
> Use bestEval from treeView

- ui/ceval/src/stockfishProtocol.js
Remove setTimer based on idea from niklasf of
tracking max PV from early SF depth emits.
Set also: official-stockfish/Stockfish#981
> Improve stockfishProtocol

- ui/ceval/src/ctrl.js
- ui/ceval/src/stockfishProtocol.js
- ui/ceval/src/view.js
stockfish nps is nodes/elapsed, and safari's elapsed
time is usually a huge lie. Instead, calculate knps
by hand.
> Calculate nps by hand.

- modules/game/src/main/BinaryFormat.scala
Use binary search rather than a complicated case routine. This prepares:
- Better move time estimation reads
- More detailed move times with using 8 bits (256 buckets)
> Improve MoveTime write algorithm

- public/stylesheets/page.css
closes #2640 
my first PR, hope I didn't fuck anything up, feel free to edit the commit if I didn't do something right
before: 
after:
> fix bullet list style site-wide 

- ui/analyse/src/study/studyComments.js
```
https://www.youtube.com/watch?v=dQw4w9WgXcQ ok
youtube.com/watch?v=dQw4w9WgXcQ ok
youtu.be/dQw4w9WgXcQ ok
https://www.youtube.com/v/dQw4w9WgXcQ ok
https://www.youtube.com/astanehchess no
https://www.youtube.com/c/astanehchess no
https://www.youtube.com/channel/UCNB4vCw1iI8c-vMkgPZIz5w no```
> fixes commentYoutubeRegex with syntax closes #2715

- ui/round/src/atomic.js
pos2key([2,9]) will return a valid key, calc needs
to check bounds before calling pos2key.
> Fix atomic explosion calc

- ui/analyse/src/ground.js
- ui/learn/src/ground.js
- ui/puzzle/src/promotion.js
- ui/round/src/crazy/crazyView.js
- ui/round/src/ctrl.js
- ui/round/src/ground.js
- ui/round/src/promotion.js
Depends on ornicar/chessground#49
For #2158.
> Preview crazyhouse captures in round

- public/images/board/svg/blue.svg
- public/images/board/svg/brown.svg
- public/images/board/svg/green.svg
- public/images/board/svg/purple.svg
We could also add these to our svg-optimize script to minimize.
> Shrink board svgs

- modules/user/src/main/Env.scala
I forgot to subscribe the handling method to 'kickFromRankings
> Fix 'Kick from rankings'

- ui/site/src/util.js
> Simplify desktop notification code

- ui/round/src/title.js
Slow down to 1s, clean up code and avoid constant callbacks
during non-ticking periods.
Use focus instead of hidden to trigger flashing favicon,
similar to desktop notification.
> Improve favicon ticker

- ui/tournament/src/ctrl.js
- ui/tournament/src/view/arena.js
- ui/tournament/src/view/util.js
> Linkify usernames in tourney standings

- ui/ceval/src/ctrl.js
- ui/ceval/src/pool.js
* Two alternating workers should be enough.
* Do not rotate if the worker is already stopped/done (this will always be the case for go deeper) or can be stopped within 50ms.
* Go deeper for wasm :tropical_fish:
---
On stage
> let wasm stockfish go deeper

- ui/analyse/src/crazy/crazyView.js
- ui/analyse/src/ctrl.js
- ui/analyse/src/promotion.js
> Preview crazyhouse captures in analyze

- ui/editor/src/view.js
is undefined. This is sometimes necessary for touch end events.
> Track the last touch move position and use that when the event position

- ui/round/src/clock/view.js
remove Math.pows
I didn't profile this function but it seems reasonable we'd
want it as fast as possible.
> Clean up game clock fun

- app/views/analyse/replay.scala.html
- public/javascripts/chart/movetime.js
- ui/analyse/src/autoplay.js
In prep for more accurate times
> Movetime display improvements

- modules/game/src/main/Game.scala
> Improve movetime interleave

- modules/game/src/main/Rewind.scala
Drop the latest entry from the non-active color
> fix takeback clockhistory drop

- public/javascripts/chart/movetime.js
> use sqrt*log for movetime graph

- public/javascripts/chart/movetime.js
Use ln^2 function to avoid long things collapsing the whole chart.
20min will 5x height of 5s, previously was 10x height
Lower values are similar, in both:
- 2 min is ~3x height of 5s.
- 1 min is ~2.3x height of 5s
> Squash movetimes chart

- modules/game/src/main/BSONHandlers.scala
- modules/game/src/main/BinaryFormat.scala
- modules/game/src/main/Game.scala
- modules/game/src/main/GameDiff.scala
- modules/game/src/main/java/clockencoder/VarIntEncoder.java
- modules/game/src/test/BinaryClockHistoryTest.scala
Don't store 0 sec flagged times.
This fixes #2863
> Tweak Clock History format

- modules/fishnet/src/main/BSONHandlers.scala
- modules/fishnet/src/main/JsonApi.scala
- modules/fishnet/src/main/Player.scala
- modules/fishnet/src/main/Work.scala
This will allow fishnet to do time management.
> send clock state to fishnet

- public/javascripts/chart/movetime.js
And adjust scaling (again). Also use Math.log1p if browser
has it.
> Fix movetime centis math

- modules/slack/src/main/SlackApi.scala
Print longer notes and use rich formatting
> improve slack mod note api

- modules/slack/src/main/SlackApi.scala
Format link to match mod note style
> Improve slack "let's look at" hook

- ui/tree/src/tree.ts
Found this one while reading code for the typescript conversion.
> fix pathExists was always returning true

- ui/analyse/src/ctrl.js
- ui/ceval/src/pool.ts
- ui/ceval/src/types.ts
A blind attempt at fixing https://lichess.org/forum/lichess-feedback/engine-never-loads
> make ceval more robust for early pnacl crashes

- ui/ceval/src/pool.ts
- ui/ceval/src/stockfishProtocol.ts
Still trying to figure out https://de.lichess.org/forum/lichess-feedback/engine-never-loads
> continue to tweak and debug ceval

- ui/analyse/gulpfile.js
- ui/analyse/package.json
- ui/challenge2/gulpfile.js
- ui/chat2/gulpfile.js
- ui/editor/gulpfile.js
- ui/insight/gulpfile.js
- ui/learn/gulpfile.js
- ui/lobby/gulpfile.js
- ui/notify2/gulpfile.js
- ui/perfStat/gulpfile.js
- ui/puzzle/gulpfile.js
- ui/round/gulpfile.js
- ui/simul/gulpfile.js
- ui/tournament/gulpfile.js
- ui/tournamentSchedule/gulpfile.js
to ensure failing builds are failing
> only catch errors in watch mode

- ui/ceval/src/view.ts
I believe fishnet now calculates 4e6 nodes
> Update ceval fishnet cutoff

- modules/tournament/src/main/TournamentScheduler.scala
Add 3 ultrabullet hourlies per day.
+Minor cleanup of scheduling logic.
> Add UltraBullet hourlies

- .travis.yml
- bin/submodule-setup.sh
This will make it easier to stage multi-repo PRs.
> Modify travis to fetch ornicar PRs

- .travis.yml
- bin/submodule-setup.sh
Use our custom submodule script instead.
> Disable travis submodule command

- app/views/mod/communication.scala.html
- app/views/round/atom.scala.xml
- modules/api/src/main/GameApi.scala
- modules/db/src/main/BSON.scala
- modules/game/src/main/BSONHandlers.scala
- modules/game/src/main/Game.scala
- modules/game/src/main/GameDiff.scala
- modules/game/src/main/GameRepo.scala
- modules/game/src/main/Pov.scala
- modules/game/src/main/Query.scala
- modules/game/src/main/Rewind.scala
- modules/gameSearch/src/main/GameSearchApi.scala
- modules/history/src/main/HistoryApi.scala
- modules/perfStat/src/main/PerfStat.scala
- modules/playban/src/main/PlaybanApi.scala
- modules/round/src/main/Finisher.scala
- modules/round/src/main/PerfsUpdater.scala
- modules/tournament/src/main/AutoPairing.scala
Rename updatedAt field and make it required instead
of Option to simplify various logic.
> game.updatedAt -> game.movedAt

- modules/tournament/src/main/TournamentScheduler.scala
Just one per day for now.  Feedback is mixed but
it's been a frequent request. For the record, I think
30s is a dumb time control.
> Add a crazyhouse hyperbullet hourly

- modules/message/src/main/ModPreset.scala
added canned message about rating refunds, edited other messages to change instances of "i/we/lichess moderator"
> +rating refunds, more impersonal forms

- app/controllers/Practice.scala
- app/controllers/Study.scala
- modules/api/src/main/RoundApi.scala
- modules/api/src/main/RoundApiBalancer.scala
- modules/round/src/main/JsonView.scala
optional follow-up simplifications based on #3004
> userAnalysisJson no longer needs to be a future

- ui/round2/src/ctrl.js
- ui/site/src/ackable.js
Delay optional init by 200ms and play the sound outside
requestIdleCallback, because it might go over the 50ms
idle limit and get killed.
This fixes #2994 (probably).
> Attempted fix for missing game sounds

- .travis.yml
attempt to speed up the build (#3042): http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html#Caching
> cache ivy2 and sbt on travis

- .travis.yml
Parallelize testing of server and build of assets. Substantially speeds up builds (#3042).
> use build stages on travis

- .travis.yml
- ui/build
This should let jenkins build ui in parallel
> Use gnu parallel instead of prll

- project/BuildSettings.scala
> parallelize sbt tests

- app/controllers/Auth.scala
- app/templating/RequestHelper.scala
- app/views/base/layout.scala.html
- app/views/coach/reviewForm.scala.html
- ui/site/src/main.js
- ui/tournament/src/view/button.js
And return to it.
Also adds some validation: stuff like https://en.lichess.org/login?referrer=https://github.com/ornicar/lila/pull/3065 should not be working.
> remember the last page when logging in (#1084)

- modules/i18n/src/main/SubdomainKiller.scala
> use permanent redirects (301) for subdomain killer

- translation/source/site.xml
Gathering tweaks to the translation source which we can now do. Should already contain all of https://github.com/ornicar/lichess-crowdin/blob/master/fix.js.
> Trans source tweaks

- app/templating/StringHelper.scala
> fix regex dos

- app/templating/StringHelper.scala
> really fix regex dos

- modules/game/src/test/BinaryClockHistoryTest.scala
and clean up tests with a custom matcher
> Remove usage of Centis.abs

- modules/playban/src/main/PlaybanApi.scala
- modules/round/src/main/Finisher.scala
- Add Tournament to blameable sources.
- tweak threshold for sit detection
- save Outcome.Good when opp has a bad outcome.
> blame on NoPlay in tournaments

- app/views/user/mini.scala.html
- modules/user/src/main/Countries.scala
Show country text based on user+country length.
> Minor update to powertip display

- ui/round/src/view/user.ts
> remove relayUser from ui/round

- ui/ceval/src/ctrl.ts
- ui/ceval/src/pool.ts
- ui/ceval/src/stockfishProtocol.ts
- ui/ceval/src/view.ts
Will mostly be relevant in Crazyhouse. Closes #2464.
/cc @isaacl
> Ceval timelimit

- public/stylesheets/mobile.css
I was on the lichess mobile page and noticed that the links were a little tricky to see. I think this may help with that.
> Make links easier to see on the lichess mobile page

- app/templating/I18hHelper.scala
- app/views/base/layout.scala.html
- modules/i18n/src/main/JsDump.scala
- modules/i18n/src/main/JsQuantity.scala
- modules/i18n/src/main/Translation.scala
- modules/i18n/src/main/Translator.scala
- ui/lobby/src/view/tabs.js
- ui/site/src/index.js
- ui/site/src/trans.js
- ui/site/src/util.js
This is a first attempt at pluralization in JS.
> [RFC] Proper plurals on client side

- modules/common/src/main/LameName.scala
- modules/common/src/test/LameNameTest.scala
- modules/security/src/main/DataForm.scala
- modules/user/src/main/User.scala
- modules/user/src/test/UserTest.scala
Improve regexes
Improve LameUser patterns and remove duplicate prefix checks.
> Cleanup and refine username checks

- modules/socket/src/main/UserLagCache.scala
I was calculating common lags in millis, plain centis
are fine.
Also, increase cache duration to 15 minutes.
> Switch UserLagCache to Centis

- modules/study/src/main/StudyApi.scala
> Hide liking of private studies from timeline

- modules/challenge/src/main/JsonView.scala
- ui/challenge/src/interfaces.ts
- ui/challenge/src/view.ts
Hover tip not implemented yet.
> Add lag icons to challenge view

- ui/ceval/src/pool.ts
- ui/common/src/main.ts
Comparing with the code from https://gonativeclient.appspot.com/demo I found a race condition: `postMessage` may not be called before the `load` event. I could even reproduce the problem locally.
Might resolve https://lichess.org/forum/lichess-feedback/local-engine-doesnt-work-and-leads-to-a-weird-twitching-?page=2#12.
> fix race condition in pnacl initialization

- app/views/tournament/faq.scala.html
https://lichess.org/forum/lichess-feedback/how-is-the-winner-decided-text-below-upcoming-tournaments
> Arena FAQ: one answer didn't match the question

- app/views/user/mod.scala.html
- public/stylesheets/user-mod.css
This will let mods hover over reported users to see which have actually been marked as engines and get a quick estimate of reporter accuracy.
> Separate user links in the user page report list

- app/views/account/close.scala.html
- app/views/account/email.scala.html
#3146 
I think in the grand scheme of things it's probably worth opening another ticket to standardize forms across the site.  I could be misunderstanding but having passwdFormField.scala.html is strange and we should probably switch to using @base.form.input(... typ="password"), yes?
Let me know what you think of the pr and styling.  I've attached images of the fixes to close account and change email (although changing email gave me a 404 when I tried it on my dev box. )
> lila #3146 - Fixing broken styling

- ui/game/src/router.ts
- ui/round/src/boot.ts
- ui/round/src/ctrl.ts
- ui/round/src/keyboardMove.ts
- ui/round/src/socket.ts
- ui/round/src/util.ts
- ui/round/src/view/button.ts
- ui/round/src/view/main.ts
- ui/round/src/view/replay.ts
- ui/round/src/view/user.ts
- ui/round/tsconfig.json
- ui/types/lichess-jquery.d.ts
- ui/types/lichess.d.ts
requires chessground upgrade to get `MaterialDiffSide`
> less implicit any for ui/round

- bin/dev.default.windows.bat
'#' doesn't actually comment something out
> Fix comments on dev.default.windows.bat

- ui/analyse/src/util.ts
This would fix the issue with some confirmations beeing ignored. I am not sure if we should make this more explicit, though.
> automatically preventDefault() in bind

- app/views/activity/list.scala.html
- public/stylesheets/activity.css
- public/stylesheets/common.css
Fix for simul list in 'activity' part of user page.
> Fix for activity simul list

- public/stylesheets/dark.css
- public/stylesheets/team.css
From 
To
The border is the same color as most of the other borders for teams. (`#3d3d3d`)
> Change border of team requests

- modules/round/src/main/Round.scala
This will create lag graphs for players on app.
Adjust report logic to ensure AI lag isn't sent to grafana.
> Save reported game lag in UserLagCache

- modules/tournament/src/main/JsonView.scala
- modules/tournament/src/main/arena/ScoringSystem.scala
- color a lone Win as a StreakStarter until the next game result
arrives.
> Adjust tourney streak calculations

- modules/slack/src/main/SlackApi.scala
> Linkify usernames in mod notes

- ui/round/src/clock/clockCtrl.ts
Instead of jumping up during the delay interval.
> Pause clock during delay

- ui/round/src/clock/clockCtrl.ts
- ui/round/src/clock/clockView.ts
> Calculate emerg class each tick

- public/stylesheets/dasherApp.css
- ui/dasher/src/ping.ts
like the ones that other users see about you (and you see in other users powertips)
> replace ping led with signal bars

- public/javascripts/keyboardMove.js
> Allow zeros for castling in SAN notation

- app/views/forum/topic/form.scala.html
- app/views/forum/topic/show.scala.html
- app/views/qa/questionShow.scala.html
> Add "reply as mod" buttons

- modules/shutup/src/main/Dictionary.scala
Add cheat related words and clean up others.
> Update bad words dict

- modules/common/src/main/mon.scala
- modules/round/src/main/Round.scala
- Report to grafana once per player per game
- Record in UserLagCache every 30 moves.
> Send lag estimates to grafana

- modules/common/src/main/LameName.scala
- modules/common/src/test/LameNameTest.scala
> Remove 'shiz' from lame dict.

- doc/engine-interface.txt
> Fix doc/engine-interface.txt

- modules/common/src/main/Maths.scala
- modules/common/src/main/Stats.scala
- modules/common/src/main/Steroids.scala
- modules/common/src/test/StatsTest.scala
- modules/evaluation/src/main/Statistics.scala
- modules/fishnet/src/main/JsonApi.scala
- modules/mod/src/main/AssessApi.scala
- modules/tournament/src/main/LeaderboardApi.scala
Functional:
- Adjust noFastMoves cutoffs
Style:
- Add better stdDev impl, switch usage
- Simplify / rewrite maths funcs
- Remove dead code
> Statistics improvements

- app/views/mod/communication.scala.html
- modules/game/src/main/Game.scala
- public/stylesheets/mod-communication.css
> Mark direct paired games in comms

- app/views/base/layout.scala.html
- ui/site/gulpfile.js
> Add asset sha to console.

- modules/common/src/main/mon.scala
- modules/round/src/main/Round.scala
> Remove deprecated lag metric

- modules/common/src/main/HTTPRequest.scala
> Minor regex cleanup

- modules/common/src/main/String.scala
- modules/forum/src/main/MentionNotifier.scala
- modules/slack/src/main/SlackApi.scala
- ui/chat/src/enhance.ts
- support matches with neighboring symbots like (@foo)
- linkify in chat
- remove nofollow for internal links
> Update user link regex

- app/controllers/Auth.scala
- modules/common/src/main/mon.scala
And show notFound with token errors.
> Add kamon for password resets

- modules/hub/src/main/actorApi.scala
- modules/mod/src/main/Env.scala
- modules/mod/src/main/Modlog.scala
- modules/mod/src/main/ModlogApi.scala
- modules/round/src/main/Env.scala
- modules/round/src/main/Round.scala
- ui/build.bat
suggested at https://lichess.slack.com/archives/G0HL9GBHU/p1506511579000149
> Add mod log entries for games lost by cheat detection

- modules/push/src/main/OneSignalPush.scala
Should close this issue: https://github.com/veloce/lichobile/issues/455
> Increase ios badge on each notif received

- app/controllers/LilaSocket.scala
- app/controllers/Practice.scala
- app/templating/Environment.scala
- app/views/relay/widget.scala.html
- modules/common/src/main/LightUser.scala
- modules/common/src/main/Lilaisms.scala
- modules/common/src/main/PackageObject.scala
- modules/common/src/main/PimpedJson.scala
- modules/common/src/main/base/LilaException.scala
- modules/common/src/main/base/LilaTypes.scala
- modules/common/src/main/base/PimpedConfig.scala
- modules/common/src/main/base/PimpedFutures.scala
- modules/common/src/main/base/PimpedJsObjects.scala
- modules/common/src/main/base/PimpedPrimatives.scala
- modules/common/src/main/base/PimpedSeqs.scala
- modules/common/src/main/base/PimpedUtils.scala
- modules/insight/src/main/Indexer.scala
- modules/relay/src/main/RelaySync.scala
- modules/study/src/main/CommentParser.scala
- modules/study/src/main/StudyApi.scala
- project/Dependencies.scala
- public/stylesheets/relay-list.css
Massive refactor and cleanup of implicits
> Refactor lila implicits

- modules/common/src/main/base/PimpedPrimatives.scala
- modules/common/src/main/base/PimpedUtils.scala
- modules/playban/src/main/model.scala
And adjust ban durations and falloff.
> Scale playban linearly

- app/controllers/Editor.scala
- app/templating/AssetHelper.scala
- app/templating/JsonHelper.scala
- app/views/analyse/embed.scala.html
- app/views/analyse/jsI18n.scala.html
- app/views/analyse/replay.scala.html
- app/views/base/captcha.scala.html
- app/views/board/editor.scala.html
- app/views/board/userAnalysis.scala.html
- app/views/board/userAnalysisI18n.scala.html
- app/views/learn/index.scala.html
- app/views/lobby/home.scala.html
- app/views/lobby/jsI18n.scala.html
- app/views/practice/show.scala.html
- app/views/relay/show.scala.html
- app/views/round/jsI18n.scala.html
- app/views/round/player.scala.html
- app/views/round/watcher.scala.html
- app/views/simul/jsI18n.scala.html
- app/views/simul/show.scala.html
- app/views/study/embed.scala.html
- app/views/study/show.scala.html
- app/views/tournament/home.scala.html
- app/views/tournament/jsI18n.scala.html
- app/views/tournament/show.scala.html
- app/views/tv/index.scala.html
- app/views/user/show/activity.scala.html
- app/views/user/show/games.scala.html
- modules/common/src/main/String.scala
- modules/history/src/main/RatingChartApi.scala
> Ensure JSON is safe to embed in scripts and HTML

- modules/common/src/main/String.scala
- modules/common/src/main/java/StringUtils.java
jmh benchmarks show 20% imrovement for json
and 1.5 - 5x improvement for html escape,
depending on input.
> Rewrite string escapes in java

- app/controllers/Main.scala
- conf/routes
- modules/common/src/main/mon.scala
- ui/site/src/socket.js
Detect when a bulk message received after socket is running
handles multiple version messages (implying the previous
sends were not received).
> Monitor socket gaps

- app/views/mobile/home.scala.html
Updated link for Mithril JS Framework
> Broken Mithril JS link

- modules/playban/src/main/PlaybanApi.scala
PR because I'm not sure if my change will
break something.
> Don't record playban if in effect

- public/stylesheets/analyse.css
This aligns the analysis link with the other text.
I wasn't sure how to assign the issue to myself on Github btw (first time).
> Issue#3776

- ui/round/src/clock/clockCtrl.ts
- ui/round/src/clock/clockView.ts
- ui/round/src/ctrl.ts
Adjust setTimeout to callback when the clock will
need to be redrawn.
> Only redraw clock when needed

- app/views/report/list.scala.html
- app/views/user/userMarks.scala.html
- public/stylesheets/board.css
- public/stylesheets/report.css
- ui/round/src/clock/clockCtrl.ts
- ui/round/src/clock/clockView.ts
This will support fractions of widths and is a general
best practice for performance as well.
> Use transform.scale to display clock bar

- app/views/analyse/jsI18n.scala.html
- modules/i18n/src/main/I18nKeys.scala
- public/javascripts/chart/acpl.js
- public/javascripts/chart/division.js
- public/javascripts/chart/movetime.js
- translation/source/site.xml
- ui/analyse/src/boot.js
One of the last untranslated parts of the analysis page ...
> translate advantage and movetime charts

- app/controllers/User.scala
- app/views/user/mini.scala.html
- public/stylesheets/common.css
- Show any mod marks
- Don't hide stats on marked accounts.
- Highlight new accounts.
> Improve mini popup for mods

- modules/common/src/main/base/LilaTypes.scala
- modules/common/src/main/base/PimpedFutures.scala
And add the context to some other helpers.
> Restore DirectExecutionContext opts

- app/views/base/zoomStyle.scala.html
- ui/site/src/main.js
This fixes the misaligned highlights as long as there's
no browser zoom.
@niklasf
> Make cg width always multiple of 8px

- public/stylesheets/board.css
> Tweak clock separator

- project/BuildSettings.scala
which addresses the privilege escalation vulnerability
http://scala-lang.org/news/security-update-nov17.html
> apply recommended security update

- public/stylesheets/board.css
- ui/round/src/view/button.ts
This should help with the UX issues mentioned in #3828
> Animate rematch button when hidden/shown

- public/javascripts/search.js
> Hide unused search params during submission

- ui/puzzle/src/view/side.ts
turns 1,706 to 1706 in the rating chart
> remove thousands separator for sparkline

- public/javascripts/chart/common.js
e.g., turns rating 1 706 to 1706
> remove thousandsSep for highcharts labels

- ui/analyse/src/acpl.ts
- ui/round/src/view/user.ts
> Add remaining minus signs, closes #3926

- ui/lobby/src/boot.js
- ui/lobby/src/view/pools.ts
- ui/lobby/src/view/realTime/filter.ts
Fixes the screenshots provided.
> Use en dashes for rating ranges, closes #3926

- public/javascripts/embed-analyse.js
- ui/site/src/main.js
- ui/site/src/util.js
fixing board resize and embedded games in forums
pair programmed with [bufferunderrun](https://lichess.org/@/bufferunderrun)
> fix dispatchEvent on ie 11

- app/controllers/Setup.scala
- modules/lobby/src/main/SocketHandler.scala
- ui/game/src/interfaces.ts
- ui/game/src/main.ts
- ui/lobby/src/ctrl.ts
- ui/lobby/src/interfaces.ts
- ui/round/src/view/button.ts
This ~temporarily blocks~ avoids the previous opponent when clicking "New opponent".
* #3638
* https://lichess.org/forum/lichess-feedback/feature-request-new-opponent-is-not-rematch
* https://lichess.org/forum/lichess-feedback/new-opponent-option-after-each-game
> avoid same opponent on "New opponent"

- app/views/user/mini.scala.html
> Challenge to a game language in player card, closes #4128

- app/templating/SetupHelper.scala
- app/views/tournament/form.scala.html
Sorry for the dupe, put the wrong issue number.
> Tournament mode translation from form page, closes #3958

- app/controllers/Round.scala
Spectator key was `c`, and app is waiting for `chat` key.
> [mobile] Fix spectator chat key in game json

- translation/source/site.xml
> More specific rematch messages

- ui/analyse/src/explorer/explorerCtrl.ts
- ui/analyse/src/explorer/explorerXhr.ts
- ui/analyse/src/practice/practiceCtrl.ts
Essentially `tablebaseGuaranteed` depends on the specific variant beeing queried.
> fix variant tablebase usage in practice (closes #4287)

- modules/common/src/main/java/StringUtils.java
And prep for other regex improvements.
jmh benchmarks, 100 char str, ns/op:
safeJson
- java 8 dirty   730 => 513
- java 8 clean   383 => 318
- java 10 dirty  595 => 476
- java 10 clean  423 => 300
escapeHtml
- java 8 dirty   423 => 278
- java 10 dirty  417 => 305
> Optimize StringUtils methods

- app/views/streamer/menu.scala.html
Link to About page to avoid having to maintain a link to the latest version of the kit
> Link to download streamer kit

- public/stylesheets/chat.css
See #devs on Discord for more info
> Avoid "Zalgo text" in chats overlapping everything

- modules/security/src/main/IpTrust.scala
https://lichess.slack.com/archives/G0HL9GBHU/p1529435635000274
> Update IPTrust rule for GC

- ui/round/src/boot.ts
- ui/site/src/socket.js
Next shot at #4388, this time only during games.
> work around tcp delayed ack on windows

- public/stylesheets/tournament.css
Fixes create tournament layout bug
> Fixes create tournament layout bug #4416

- modules/common/src/main/String.scala
- modules/common/src/main/java/StringUtils.java
- modules/game/src/main/Game.scala
- modules/shutup/src/main/Analyser.scala
- modules/shutup/src/main/Dictionary.scala
- modules/study/src/main/MultiPgn.scala
- project/MessageCompiler.scala
Round two of misc regex micro optimizations.
> Moar string opts

- app/views/account/profile.scala.html
- modules/user/src/main/Links.scala
> "Github" to "GitHub"

- public/stylesheets/board.css
@isaacl Looks like you intended `transition` here, right?
> .cg-512 piece transform should have been transition

- app/controllers/Challenge.scala
- app/controllers/Relay.scala
- app/controllers/Round.scala
- app/controllers/Simul.scala
- app/controllers/Study.scala
- app/controllers/Tournament.scala
- modules/challenge/src/main/Socket.scala
- modules/challenge/src/main/SocketHandler.scala
- modules/relay/src/main/SocketHandler.scala
- modules/round/src/main/History.scala
- modules/round/src/main/JsonView.scala
- modules/round/src/main/Socket.scala
- modules/round/src/main/SocketHandler.scala
- modules/round/src/main/VersionedEvent.scala
- modules/round/src/main/actorApi.scala
- modules/simul/src/main/Socket.scala
- modules/simul/src/main/SocketHandler.scala
- modules/simul/src/main/actorApi.scala
- modules/socket/src/main/Historical.scala
- modules/socket/src/main/History.scala
- modules/socket/src/main/SocketActor.scala
- modules/study/src/main/Socket.scala
- modules/study/src/main/SocketHandler.scala
- modules/tournament/src/main/Socket.scala
- modules/tournament/src/main/SocketHandler.scala
- modules/tournament/src/main/actorApi.scala
- ui/site/src/socket.js
This reduces catch up by a full round trip.
We're detecting event gaps that I don't expect to occur and recovering using the backwards compat API.
> Push data immediately on websocket connect

- modules/evaluation/src/main/Statistics.scala
should reduce false positives of this kind
> move time streaks: 10 --> 15

- modules/evaluation/src/main/Assessible.scala
The move times there are usually a little flatter than other bullet games, and I've seen a false positive with this. Keeping the streaks though because those are much stricter.
> 0+1 games shouldn't count for highly consistent mt

- modules/socket/src/main/AnaDests.scala
- modules/socket/src/main/AnaDrop.scala
- modules/socket/src/main/AnaMove.scala
> tweak: avoid definitions within for-comprehensions

- modules/hub/src/main/SequentialActor.scala
- More efficient queue data structure (ArrayDeque)
- Convert idle / busy / fallback to val since they
are used for nearly every msg.
> SequentialActor optimizations

- app/views/user/mod.scala.html
- modules/evaluation/src/main/Assessible.scala
- modules/evaluation/src/main/Display.scala
- modules/evaluation/src/main/PlayerAggregateAssessment.scala
- modules/mod/src/main/AssessApi.scala
Mod view now indicates streaks, and the colors for move times are a bit adjusted. Before this, the 'def's in Assessible are replaced with lazy vals because several of them would be called multiple times.
> Improve mod view after cheat-improv

- modules/hub/src/main/Duct.scala
This is documented as more efficient.
Note that we could use AtomicReference instead
of STM here.
> Use ref.single instead of atomic

- app/views/base/fpmenu.scala.html
- public/stylesheets/fpmenu.css
https://github.com/ornicar/lila/issues/4558
Replace sign in form with a link. Preserve previous submit button styles for the link. 
Now it looks like:
Comments are welcome!
> issue-4558: remove login form from menu

- ui/lobby/src/boot.js
- ui/lobby/src/xhr.ts
- ui/site/src/socket.js
- btoa(<len 9 str>) can't have `=`, and replace to '_' instead of
chars already in btoa.
- guard crypto block with try/catch to be more resilient.
> Simplify socket sri regex

- modules/fishnet/src/main/Analyser.scala
As req.userId is an Option[String], isn't system always false here?
> Identify study analysis requested by lichess

- app/controllers/TournamentCrud.scala
- app/views/mod/menu.scala.html
- app/views/tournament/crud/index.scala.html
- app/views/tournament/crud/layout.scala.html
- conf/routes
- modules/tournament/src/main/TournamentRepo.scala
- modules/tournament/src/main/crud/CrudApi.scala
FischyVishy asked me about this because he wanted to see his older tournaments that were no longer visible. This should be resolved with Paginator and infinitescroll.
> Tournament manager: pagination

- modules/common/src/main/base/RawHtml.scala
- modules/common/src/test/RawHtmlTest.scala
alternative to using camo. goal is to
* avoid mixed content warnings. only load images over https
* not expose user ip to random websites (without requiring user interaction)
> only embed images from imgur

- public/stylesheets/board.css
- ui/round/src/view/main.ts
Fixes issue https://github.com/ornicar/lila/issues/4299
> issue-4299: hide opponent's crazyhouse piece bucket in blindfold

- modules/common/src/main/base/RawHtml.scala
> [WIP] don't expand urls which precede a quote char

- ui/site/src/main.js
removes some code duplication. still leaves room for improvement
also fixes https://github.com/ornicar/lila/issues/2543
> refactor friends list

- public/javascripts/login.js
- Fix `.token input` selector (no longer valid)
- Autofocus the input when showing 2FA form
> Fixes and tweaks to 2FA token input in login form

- conf/routes
- modules/round/src/main/JsonView.scala
> Report winner from PGN import

- modules/security/src/main/EmailAddressValidator.scala
Fixes https://github.com/ornicar/lila/issues/4872
> issue-4872: normalize emails before uniqueness check

- app/views/study/clone.scala
> Fix <strong> tag in clone study; closes #4881

- app/controllers/Account.scala
- app/controllers/Auth.scala
- app/controllers/Mod.scala
- modules/common/src/main/Iso.scala
- modules/common/src/main/model.scala
- modules/common/src/test/EmailTest.scala
- modules/db/src/main/Handlers.scala
- modules/security/src/main/EmailAddressValidator.scala
- modules/security/src/main/SecurityApi.scala
- modules/user/src/main/Authenticator.scala
- modules/user/src/main/User.scala
- modules/user/src/main/UserRepo.scala
Part 2/3: Adding `NormalizedEmailAddress` and changing the signatures on `UserRepo`. Type based refactoring from there. Again (almost) no functional change.
Related: #2509
> introduce NormalizedEmailAddress

- modules/user/src/main/User.scala
- modules/user/src/main/UserRepo.scala
Part 3/3: Also store email addresses exactly as entered and use them for sending. Closes #2509.
> store verbatim email (closes #2509)

- modules/round/src/main/RoundDuct.scala
Tested:
- Regular situation: Claim Victory gives you a victory
- Insufficient material: Claim Victory gives you a draw
> Claim Victory in unwinnable position results in a draw, for #4923

- ui/perfStat/src/glicko.js
http://www.glicko.net/glicko/glicko2.pdf requires in order to use Glicko-2, there must be a rating period.
> Remove incorrect caption until #4034 merges

- public/oops/servererror.html
Hi,
Just fixing this markup error on servererror page:
```
Bad value 1000px for attribute width on element img: Expected a digit but saw p instead.
```
Thanks for this project,
Laurent
> Move width and height to css

- app/templating/AssetHelper.scala
- app/views/base/form/datepicker.scala.html
- app/views/search/index.scala.html
- modules/gameSearch/src/main/DataForm.scala
- public/javascripts/search.js
- public/stylesheets/search.css
This will make it so that you are now allowed to (optionally) choose two dates to select a range of dates to query for.
Fixes #4241
> Advanced search: precise date fields

- app/Env.scala
- app/controllers/Dev.scala
- build.sbt
- modules/common/src/main/PackageObject.scala
- modules/common/src/main/base/LilaTypes.scala
- modules/common/src/main/mon.scala
- modules/rating/src/main/Env.scala
- modules/rating/src/main/RatingFactor.scala
- modules/rating/src/main/RatingRegulator.scala
- modules/rating/src/main/package.scala
- modules/round/src/main/Env.scala
- modules/round/src/main/PerfsUpdater.scala
- modules/user/src/main/RankingApi.scala
- ui/tournament/css/_layout.scss
- ui/tournament/css/_side.scss
rating regulator WIP
live settings to multiply rating gains with.
Aiming to restore median rating to 1500 for each variant
in the very long term (6+ months)
missing: monitoring (wip)
> Rating regulator

- README.md
Source: https://lichess.org/blog/XMvcJSwAADkA0hPE/lichess-v2-is-here
> Update list of supported browsers as per blog announcement of v2

- app/views/forum/bits.scala
This pull request sets an UTF-8 ellipsis character instead of three dot characters in the paginator.
> Use hellip character for paginator

- public/images/board/svg/blue.svg
- public/images/board/svg/brown.svg
- public/images/board/svg/green.svg
- public/images/board/svg/purple.svg
Explicitly draw each square so that corners align,
even in the presence of zoom.
> Update board svg

- modules/common/src/main/mon.scala
- modules/round/src/main/History.scala
- modules/round/src/main/RoundSocket.scala
- inc and hist for RoundSocket::addEvents
- fix duplicate hist in VersionCheck
- inc counter for getEventsSince
> Add metrics for RoundSocket::addEvents

- ui/round/src/plugins/keyboardMove.ts
> Fix command to read clock times (fix #5056)

- ui/round/src/ctrl.ts
When on latest move, emit ply event when
apiMove steps the board forward.
For #5203.
> Emit ply event in apiMove

- ui/analyse/tsconfig.json
- ui/ceval/tsconfig.json
- ui/challenge/tsconfig.json
- ui/chat/tsconfig.json
- ui/chess/tsconfig.json
- ui/cli/tsconfig.json
- ui/common/tsconfig.json
- ui/dasher/tsconfig.json
- ui/game/tsconfig.json
- ui/lobby/tsconfig.json
- ui/notify/tsconfig.json
- ui/nvui/tsconfig.json
- ui/puzzle/tsconfig.json
- ui/round/tsconfig.json
- ui/site/tsconfig.json
- ui/speech/tsconfig.json
- ui/tournament/tsconfig.json
- ui/tournamentCalendar/tsconfig.json
- ui/tournamentSchedule/tsconfig.json
- ui/tree/tsconfig.json
- ui/tsconfig.base.json
> Extend tsconfig from a base config

- modules/common/src/main/mon.scala
- modules/round/src/main/History.scala
- modules/round/src/main/RoundSocket.scala
- modules/round/src/main/SocketHandler.scala
- modules/round/src/main/actorApi.scala
server side corresponding to https://github.com/ornicar/lila/pull/5224
> also remove version check on server

- app/mashup/UserInfo.scala
- app/views/user/show/otherTrophies.scala
- bin/mongodb/create-trophy-kinds.js
- conf/base.conf
- modules/tournament/src/main/TournamentApi.scala
- modules/user/src/main/Env.scala
- modules/user/src/main/Trophy.scala
- modules/user/src/main/TrophyApi.scala
instead of hardcoding trophy kinds in the code, all of them go in a database collection 'trophyKind'
to initialize, run the create-trophy-kinds.js script
no changes to the 'trophy' collection will be needed whatsoever
> Rewrite trophy code: don't hardcode kinds

- modules/analyse/src/main/Advice.scala
For example https://lichess.org/nFvpvKNC#9 (atomic) - mate is imminent, although a faster mate was possible.
> Delayed checkmate is not an inaccuracy

- modules/analyse/src/main/Advice.scala
Based upon your most recent comment I simplified this code.
> Simplify MateAdvice-to-Judgment mapping

- app/controllers/Challenge.scala
> Case-insensitive Challenge.apiCreate

- ui/site/src/socket.js
Temporarily revert sri persistence to see if it fixes
user disappearing issue (#5263).
> Test revert of sri persistence

- ui/round/src/ctrl.ts
Reverts ornicar/lila#5258
Isaac noticed that he didn't hear my drops during my game against him. My patch just breaks sounds for all drops that aren't your own.
> Revert "Fix #5037 (should be no sound on zh illegal drop)"

- app/views/site/faq.scala
fixes #5286 
Didn't know what words you wanted so just put what seemed reasonable
> Added variants link to FAQ

- ui/common/src/throttle.ts
- ui/round/src/clock/clockCtrl.ts
- ui/round/src/corresClock/corresClockCtrl.ts
- ui/site/src/socket.js
- ui/site/src/standalones/util.js
- ui/tournament/src/sound.ts
Use performance.now() instead of Date.now()
for all interval checks.
> Switch to performance.now()

- ui/lobby/css/_about.scss
- ui/lobby/css/_lobby.scss
> Added hover animation on about links

- modules/round/src/main/JsonView.scala
Analysis board does not currently respect
the move input preference.
> Send moveEvent pref for analysis board

- ui/lobby/css/_table.scss
This pull requests changes the colour of the lobby counters (players online, games in play) to $c-link when hovered.
> Add colour change on hover of lobby counters

- ui/tournamentSchedule/css/_side.scss
Before the commit:
After the commit:
> Tournament leaderboard title css

- ui/speech/src/main.ts
> Updated speech synthesis hackFix() function

- modules/simul/src/main/Simul.scala
> Simul can't be spotlight if limited to team

- ui/lobby/css/_box.scss
Adds a transition to the lobby box more button.
> Transition on lobby box more button

- ui/lobby/css/_support.scss
This pull request fixes the slightly jumpy animation of the support buttons on the home page. It also simplifies the CSS a bit.
> Fix the lobby support buttons

- ui/speech/src/main.ts
Want to make C and F lowercase regardless of whether they occur at the start of the string or not.
> Changed regular expressions

- ui/tournamentSchedule/css/_side.scss
Makes tournament schedule links coloured blue on hover and c-font on not hover...
> Tournament schedule links color

- app/views/lobby/home.scala
This commit only shows the "More" button on the timeline if there is actually a timeline to show.
> Only show more button if timeline exists

- ui/chat/css/_tab.scss
This pull request styles the checkbox on the chat.
> Style the checkbox on the chat

- app/Env.scala
- app/controllers/Mod.scala
- modules/hub/src/main/actorApi.scala
- modules/message/src/main/ModPreset.scala
- modules/mod/src/main/Env.scala
- modules/mod/src/main/ModApi.scala
- modules/playban/src/main/Env.scala
- modules/playban/src/main/PlaybanApi.scala
At -10: warning
At -20: closure
> Automatic warning and closure based on sit counter

- modules/lobby/src/main/Hook.scala
- modules/pool/src/main/MatchMaking.scala
- modules/pool/src/main/PoolActor.scala
- modules/pool/src/main/PoolApi.scala
- modules/pool/src/main/PoolMember.scala
See the two commit messages and the code comments for clarification
> Pool matchmaking: bonuses/maluses based on sit counter

- ui/round/src/socket.ts
Idea for #5659: Use throttle with exponentially increasing delay.
Factor 1.1:
n | delay
--- | ---
0 | 500
1 | 550
2 | 605
... | ...
5 | 805
... | ...
10 | 1297
> exponentially increasing throttle (#5659)

- build.sbt
- conf/base.conf
- modules/push/src/main/BlockingIO.scala
- modules/push/src/main/Device.scala
- modules/push/src/main/Env.scala
- modules/push/src/main/FirebasePush.scala
- modules/push/src/main/PushApi.scala
- project/Dependencies.scala
To download the service-account.json file, go to https://console.firebase.google.com/ -> "Project Settings" -> "Service Accounts" tab -> "Generate new private key".
Contrary to onesignal, firebase does not support stacking of messages. For now, every message will be a separate notification. This is not an issue on android 7+ which will collapse automatically.
> Firebase cloud messaging

- ui/cli/css/_clinput.scss
- ui/common/css/base/_form.scss
Since the spec does not guarantee anything about the color, I believe the correct thing to do is set our own color globally.
> globally set ::placeholder color (fixes #5584)

- app/controllers/LilaController.scala
- app/controllers/Puzzle.scala
- app/controllers/Relay.scala
- app/controllers/Study.scala
- app/controllers/UserAnalysis.scala
> set coop/coep headers for multi-threaded stockfish (closes #5784)

- modules/game/src/main/BSONHandlers.scala
- modules/game/src/main/PgnStorage.scala
- modules/round/src/main/Finisher.scala
- modules/round/src/main/RoundDuct.scala
- project/Dependencies.scala
* `game.variant.insufficientWinningMaterial(game.board, opponentColor)` -> `game.situation.opponentHasInsufficientMaterial`
* `chess.Clock.halfMoveClock` is now independent of `positionHashes`
Test failure expected, because this requires https://github.com/ornicar/lila-maven/pull/6 (cannot merge myself)
> update to scalachess 9.2.0

- modules/playban/src/main/RageSit.scala
Depends upon the latest scalachess.
> Calculate antichess material imbalance ornicar/scalachess#186

- app/views/activity.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/activity.xml
I didn't bother launching a stream in dev or anything to test.
I put the `a` within the URL because some languages have gendered articles.
> Translate 'hosted a live stream'

- modules/tournament/src/main/Condition.scala
https://lichess.org/forum/lichess-feedback/how-could-i-make-tournament-with-max-writing-control-800-1100-1250
> Enable creation of U1100 events

- modules/analyse/src/main/Advice.scala
as discussed in https://lichess.org/forum/lichess-feedback/x-was-the-best-move-vs-the-best-move-was-x-vs-x-was-best
The strings in this file are not in the localization files afaik, I guess they should be, but I don't know how to do that right now.
> Change in a string as per discussion

- ui/common/css/vendor/chessground/_board-2d.scss
- ui/common/css/vendor/chessground/_chessground.scss
> better color for move square

- modules/game/src/main/GifExport.scala
not hard to implement, but way too slow in long games
> gif with frame delays based on real move times

- app/controllers/Main.scala
- app/views/site/dailyPuzzleSlackApp.scala
- conf/routes
A Slack app made by @arex1337. Let's give it an official landing page under lichess.org.
Old: https://lichess-slack-app-public.s3-eu-west-1.amazonaws.com/index.html
New: https://lichess.org/daily-puzzle-slack
> daily puzzle slack app landing page

- app/controllers/Mod.scala
- app/views/mod/search.scala
- app/views/user/mod.scala
- conf/routes
- modules/security/src/main/SecurityApi.scala
> Allow mods to IP-ban a single IP

- app/controllers/Auth.scala
- app/controllers/Mod.scala
- app/views/search/bits.scala
- app/views/study/list.scala
"Collateral damage" of me trying to run scalafmt on just one file for my other PR, but turning out to run it on all files.
> Run scalafmt on all files

- modules/round/src/main/Takebacker.scala
> Double takeback when you offer on your move

- ui/ceval/src/view.ts
Lichess uses daily builds of stockfish, so we might as well increment the version displayed in the ui.
> Changed engine name from stockfish 10+ to 11+

- ui/round/css/_control.scss
Fixes https://github.com/ornicar/lila/issues/5183
Probably not the final solution but it fixes the exploit for now.
> Change position of draw accept/decline buttons

- app/views/site/faq.scala
since this is a pretty common support question
> Add new FAQ question about getting back rating points for losing by disconnection

- bin/ci-deploy.py
Current status: Synchronizes a local database of GitHub workflow runs. Finds matching workflow runs for the current commit and determines the URL of the corresponding build artifact. Connects with SSH to a server and uses `wget` to download the build artifact (ZIP with the compiled assets).
> deploy from ci

- ui/common/css/vendor/chessground/_chessground.scss
> fixes low contrast moves on green boards

- modules/tournament/src/main/TournamentScheduler.scala
The atomic community has been asking for the Daily Atomic to be at a more friendly time for people in Europe.
> Swap Daily Atomic and Three Check

- modules/tournament/src/main/TournamentScheduler.scala
> Make Weekly/Monthly Variants consistent with Dailies

- ui/@types/lichess/index.d.ts
- ui/challenge/src/ctrl.ts
- ui/challenge/src/main.ts
- ui/dasher/src/background.ts
- ui/dasher/src/board.ts
- ui/dasher/src/piece.ts
- ui/dasher/src/sound.ts
- ui/dasher/src/theme.ts
- ui/notify/src/ctrl.ts
- ui/site/src/main.js
Another step towards a better offline experience.
> lichess.announce failed xhr

- modules/tournament/src/main/Condition.scala
Allows users to create u900 and u800 events
> new max ratings - closes #6302

- app/templating/SetupHelper.scala
- app/views/setup/filter.scala
- modules/lobby/src/main/Hook.scala
- modules/setup/src/main/FilterConfig.scala
- modules/setup/src/main/FormFactory.scala
- ui/lobby/src/filter.ts
Needs https://github.com/ornicar/scalachess/pull/194
Works as expected in dev
> Add ability to filter seeks by increment, closes #6150

- app/views/setup/filter.scala
- ui/lobby/css/app/_hook-filter.scss
> save horizontal space for lobby filter settings

- ui/analyse/css/study/panel/_server-eval.scss
Close #6346 
A small fix in position the text in the box within the study page.
> fix text positioning in study

- modules/evaluation/src/main/Assessible.scala
- modules/evaluation/src/main/PlayerAggregateAssessment.scala
- modules/evaluation/src/main/Statistics.scala
results: https://lichess.slack.com/archives/C87SMPSA3/p1587391181420100
> More /module/evaluation updates

- modules/tournament/src/main/TournamentApi.scala
> Don't ignore tournament mode change on update form

- modules/tournament/src/main/Condition.scala
> New Tournament Minimum Ratings

- app/controllers/Analyse.scala
- modules/fishnet/src/main/FishnetApi.scala
both #6368 and https://github.com/lichess-org/talk/issues/43 are about slow system analysis, which is still a thing (although much better). if only system analysis was requested, still show the button, which then raises priority to user
> show analysis button to raise priority to user (fixes #6368)

- app/views/user/show/header.scala
Making it consistent with biography
> Hide real name if u.marks.troll

- ui/site/css/_blog.scss
> apply max-width to widgets in blog (fixes #6467)

- modules/mod/src/main/AssessApi.scala
(reason: https://lichess.slack.com/archives/G0HL9GBHU/p1588144923334600)
> Switch two conditions in onAnalysisReady

- .github/workflows/server.yml
- app/Env.scala
- app/views/site/help.scala
- ui/site/gulpfile.js
* Link commits to GitHub
* Also show asset version
> improve lila version info

- translation/source/site.xml
> Fix translation source

- modules/pref/src/main/JsonView.scala
I want to add this settings to the mobile app to close this issue: 
https://github.com/veloce/lichobile/issues/1206
> Add rookCastle pref for mobile

- modules/evaluation/src/main/PlayerAggregateAssessment.scala
A bit too many reports without enough certainty otherwise
> Use unweighted values on reportable

- app/views/lobby/home.scala
- app/views/site/help.scala
- app/views/site/lag.scala
- bin/trans-dump.js
- build.sbt
- modules/i18n/src/main/I18nKeys.scala
- translation/source/faq.xml
- translation/source/lag.xml
Part of #3382 
Translates the lag page.
> Translate lag page

- ui/round/src/plugins/nvui.ts
> case insensitive nvui commands

- ui/round/src/plugins/nvui.ts
> Revert "case insensitive nvui commands"

- .gitignore
- ui/site/css/coach/_show.scss
fix #6596
Not sure if there's a better variable for the magic `320px`!
Before: 
After:
> Improve coach view styling on mobile.

- ui/lobby/css/app/_hook-chart.scss
- ui/lobby/src/view/realTime/chart.ts
addresses #1579 (from >4 years ago!)
Not sure if anybody ever uses this feature, but hey!
Looks the same as before, except the bottom part is clickable to accept the game.
> clickable graph popup

- modules/quote/src/main/Quote.scala
> Fix typo in Timman's name

- public/javascripts/study/tour.js
Fixes a bug where clicking the tour button multiple times in a study opens multiple shepherds.
> Fix multiple shepherds bug

- ui/build
> Remove reference to Travis in ui/build

- modules/forum/src/main/PostApi.scala
>  I just want to be able to post the same answer to the same questions
> remove spam protection when replying as a mod

- ui/build
- ui/puzzle/gulpfile.js
- ui/puzzle/package.json
- ui/puzzle/rollup.config.js
- ui/site/src/main.js
- yarn.lock
lichess.puzzle.min.js 136157 -> 125954 bytes (93%)
> switch ui/puzzle from browserify to rollup

- public/javascripts/chart/ratingHistory.js
Like https://github.com/ornicar/lila/pull/6854 but on the client
I don't think charts work in dev (Highcharts license?), but results from node REPL seem encouraging:
```
var oneDay = 86400000;
function smoothDates(data) {
if (!data.length) return [];
var begin = data[0][0];
var end = data[data.length - 1][0];
var reversed = data.slice().reverse();
var allDates = [];
for (var i = begin-oneDay; i <= end; i+=oneDay) {
allDates.push([i])
}
var result = [];
for (var j = 1; j < allDates.length; j++) {
var match = reversed.find(function (x) {
return x[0] <= allDates[j];
})
result.push([allDates[j], match[1]])
}
return result;
}
var serie = {};
var singlePerfName = undefined;
serie.points =   [ [ 2020, 3, 10, 1000 ], [2020, 3,15, 900], [ 2020, 4, 1, 1500 ], [ 2020, 4, 2, 1800 ] ];
var …
```
> Smooth dates in JS, for #6743

- public/javascripts/chart/ratingHistory.js
Agree with the [comments](https://github.com/ornicar/lila/issues/6743) here that the markers don't add much and even stranger now that we fill in missing dates.
> Disable markers in ratings graph, for #6743

- ui/tournamentCalendar/src/main.ts
- ui/tournamentCalendar/src/view.ts
- ui/tournamentCalendar/tsconfig.json
Enabled `noUnusedParameters` and `noUnusedLocals`.
> Cleanup for tournament calendar TS

- app/views/mod/communication.scala
> Fix notes permissions

- ui/round/src/plugins/sanWriter.ts
> Types for ui/round for #6939

- ui/nvui/src/command.ts
- ui/round/src/plugins/nvui.ts
for https://github.com/ornicar/lila/issues/6401
> tweak blind mode commands

- modules/mod/src/main/Modlog.scala
- modules/mod/src/main/ModlogApi.scala
https://lichess.slack.com/archives/C4R6GQ6P7/p1594915488145600
> Log lichess actions again

- app/controllers/Report.scala
- modules/report/src/main/ModReportFilter.scala
- modules/report/src/main/ReportApi.scala
This should allow some mods to quickly peak past the veil and to continue working there as much as they want without causing the other mods heart attacks.
> Allow mods to provide a ?score=X to temporarily override the threshold

- modules/common/src/main/WMMatching.scala
TraversableIsh was replaced by Iterator.
Scalafmt was fixed by removing extra paren in
` (blossomLeaves(bv).find(x => label(x) != 0)).foreach(...`
> WMMatching: scala 2.13 and fix scalafmt

- modules/common/src/main/WMMatching.scala
- modules/common/src/test/WMMatchingTest.scala
- move matching algorithm implementation to private class Impl (less stack pressure)
- fix performance bug in fullGraph (wrong parameter in sizeHint call for weights)
- blossom id allocation
- add hand tests from original Python code
> WMMatching: code refactoring

- modules/tournament/src/main/PairingRepo.scala
- modules/tournament/src/main/WaitingUsers.scala
- modules/tournament/src/main/arena/PairingSystem.scala
- remove list sorting in WaitingUsers.evenNumber
- remove list to set convertion in lastOpponents
> WaitingUsers optimizations

- app/views/dev.scala
- modules/evalCache/src/main/Env.scala
- modules/evalCache/src/main/EvalCacheApi.scala
> allow dropping variant eval cache from cli

- modules/common/src/main/String.scala
call replace on truncated string, use the fact that replace doesn't change text length
> String.shorten tweak

- modules/pool/src/main/MatchMaking.scala
reduce number of arithmetic operations for forbidden pairs,
assumed that old code malus constant 9000 is equivalent to +infinity
> pool PairingScore tweak

- app/controllers/Tournament.scala
I haven't tested the code yet.
> [mobile] Add tournament chat json

- modules/evalCache/src/main/EvalCacheUpgrade.scala
- modules/evaluation/src/main/Statistics.scala
- modules/fishnet/src/main/JsonApi.scala
- modules/fishnet/src/main/Monitor.scala
- modules/lobby/src/main/HookRepo.scala
- modules/lobby/src/main/LobbySocket.scala
- modules/relay/src/main/RelayApi.scala
- modules/report/src/main/Report.scala
- modules/streamer/src/main/Stream.scala
- modules/streamer/src/main/Streaming.scala
- modules/study/src/main/StudyApi.scala
- modules/swiss/src/main/SwissScoring.scala
- modules/tournament/src/main/PairingRepo.scala
replace filter followed by map, flatMap or foreach by withFilter
when filtered sequence isn't option
As a scala compiler do for guards in for loops
> withFilter tweak

- ui/msg/src/view/enhance.ts
- ui/site/src/expand-text.ts
Add 'timeline' to "notGames"
https://lichess.org/timeline
Relates #7234
> Add 'timeline' in notGames

- modules/mod/src/main/Gamify.scala
https://lichess.slack.com/archives/C013YPTJ3C6/p1599729851118000
> Tweak Gamify.scala

- app/templating/GameHelper.scala
- ui/game/src/view/status.ts
Per this comment: https://github.com/ornicar/lila/pull/7306#issuecomment-691656806
Bullet is already used in similar code https://github.com/ornicar/lila/blob/master/app/views/game/side.scala#L12
> Change timeout draw separator

- app/views/dgt.scala
- ui/site/css/_dgt.scss
- ui/site/package.json
- ui/site/src/dgt/play.ts
Hi, It took a while to find the proper way to stream Board API events using fetch instead of axios but I finally got it working. WebSockets to DGT's LiveChess should be easy, the one I think will take some time is migration from chess.js to chessops
The code works so far, a lot of warnings since there a plenty unused variables that are needed for code that I have not migrated yet.
The idea of this commit is to receive early feedback before moving forward.
> DGT support

- app/views/dgt.scala
- ui/dgt/src/play.ts
Fixed the compilation errors for DGT board integration on play.ts . Now ready to test on dev some more. Added a "Limitations" section to dgt.scala with info that is useful, it can remain there or it can be moved to a help section or whatever.
> Fixed TypeScript compilation errors

- conf/base.conf
- modules/security/src/main/Env.scala
- modules/security/src/main/Ip2Proxy.scala
- modules/security/src/main/SecurityConfig.scala
make some of the security options configurable because they are usually not needed when developing
> making security services configurable

- ui/dgt/src/play.ts
Fixed two issue both related to castling and UCI and UCI_960 format.
Added version on start screen, the one with ascii art
Also noticed a new event named gameFinish that is not being handled, added that as a TODO, just want to fix the castling issue first
> Fix problem with UCI and UCI_960 castling

- ui/dgt/src/play.ts
- ui/site/css/_dgt.scss
Mostly fixing a problem with DGT Board sending the same moves several times. Added css for table to show cleaner debug info. Tested on my machine and duplicates are skipped fine.
> DGT - Fix issue with duplicated moves received from DGT Board LiveChess

- ui/analyse/src/ctrl.ts
- ui/analyse/src/plugins/nvui.ts
- ui/analyse/src/serverSideUnderboard.ts
- ui/challenge/src/main.ts
- ui/common/src/complete.ts
- ui/dasher/src/background.ts
- ui/dasher/src/board.ts
- ui/insight/src/ctrl.js
- ui/lobby/src/setup.ts
- ui/notify/src/ctrl.ts
- ui/round/src/promotion.ts
- ui/round/src/socket.ts
- ui/round/src/xhr.ts
- ui/site/src/checkout.ts
- ui/site/src/clas.ts
- ui/site/src/forum.ts
- ui/site/src/infiniteScroll.ts
- ui/site/src/teamBattleForm.ts
- ui/swiss/src/xhr.ts
- ui/tournament/src/xhr.ts
To avoid hiding logic errors in f. Might help debug random page reloads
reported by some users.
> xhr().then(f).catch(g) -> xhr().then(f, g)

- ui/dgt/src/play.ts
A loop was added to handle when two or more moves are received on the same message from DGT Board LiveChess array of san moves. I had no knowledge of this prior to today.
This can also help improve duplicates prevention since san is ambiguous and for example O-O could men local player just castled or is adjusting for opponents castling.  This scenario happens for example when a piece is taken and then re-taken on a short period of time, LiveChess was sending one event with both moves. Fix was tested and during tests I found other bug with adjusting for castling that is also fixed on this PR.
At this moment I have not knowledge of any bug or pending improvement related to move detection.
> DGT - Fix problem when more than one move is received from DGT Board

- ui/dgt/src/play.ts
An edge case happens when LiveChess see a position and calculate that two moves were played to reach that position but the calculated move is incorrect since some pieces are still in the air. Once the pieces are back on the board it calculates the correct move but it may be already too late if the wrong move is sent to lichess first. So this suspicious moves will be quarantined for 2.5 seconds. If before the 2.5 seconds the right move is received, then it is sent immediately and the quarantined move is ignored, so actually there was no delay. If the move is not received, then the suspicious move is sent as received. The threshold may need to be set to 3 or 4 seconds if this becomes an issue or a different solutions needs to be implemented. At this moment is seems sufficient.
> Quarentine moves that may be incorrect for 2.5 secs

- ui/dgt/src/play.ts
Did a fix with text decoder to support FireFox, and also made the logging functions to return a promise so the string concatenation does not lag sending the moves, specially on verbose where the on screen log can get pretty big.
> Firefox Support and Logging Improvement

- ui/dgt/src/play.ts
DGT Board
Before only one open game was supported, now the board will attach to the open game that matches the position on lichess, with the added benefit that if the board does not match the position on lichess it will warn the user, even if there is only one game.
This will allow the board to be used for a correspondance game while playing other games online.
Also minor stuff like improved TTS and Lighter logging.
> Support for multiple open games

- ui/@types/lichess/index.d.ts
- ui/analyse/src/socket.ts
- ui/analyse/src/study/studyCtrl.ts
- ui/analyse/src/study/studyTags.ts
> more types for ui/analyse

- ui/dgt/src/play.ts
Made the keywords lowercase when sent to tts to avoid a bug where the 'b' in black was replaced by "bishop'
> DGT - Fixed small bug with tts

- app/views/irwin.scala
Fix irwin's monitoring URL to the new Grafana URL.
> Fix irwin's monitoring URL

- app/views/account/passwd.scala
Server-side validation (as in password reset)
> display error when passwords dont match

- app/controllers/Mod.scala
- app/controllers/Simul.scala
- app/views/user/mod.scala
- modules/security/src/main/Permission.scala
based on commit 7f8f510d539702c8bac2cee2e326f1c60446fadf
tested
> Tweak mods perms

- modules/irwin/src/main/IrwinApi.scala
> Increase irwin report score to 60

- modules/report/src/main/ReportApi.scala
for https://github.com/lichess-org/talk/issues/53. The game is casual anyway
> Don't autoreport already marked players for boosting

- ui/analyse/src/moveView.ts
I think this is the right place to put the conversion, but I’m not sure.
> Use minus sign for evaluations

- app/templating/GameHelper.scala
- app/views/game/mini.scala
- app/views/round/jsI18n.scala
- ui/lobby/src/view/realTime/list.ts
- ui/round/src/view/user.ts
https://github.com/ornicar/lila/issues/7695
Translate "anonymous" in lobby listings and games
> Translate anonymous

- app/views/plan/features.scala
- ui/ceval/src/pool.ts
- ui/ceval/src/view.ts
- ui/site/package.json
- yarn.lock
might be wise to hold this back until after we know that #7719 works for everyone, to ease potential debugging
> update ceval to sf12+

- app/controllers/UserAnalysis.scala
- modules/api/src/main/RoundApi.scala
> Add forecast to mobile analysis response

- app/controllers/Mod.scala
- app/views/user/mod.scala
- conf/routes
- modules/mod/src/main/ModApi.scala
- modules/mod/src/main/Modlog.scala
- modules/mod/src/main/ModlogApi.scala
- modules/security/src/main/Permission.scala
close https://github.com/lichess-org/talk/issues/68
> set Kid mode

- app/views/board/bits.scala
Fixed issue #7641 ... hopefully in the right place in the code 😃
> never flip mini board for king races

- translation/dest/site/en-US.xml
- translation/source/site.xml
Changed wording to make it more accurate when users use consecutive hyphens or underscores
> Issue #7749

- app/views/account/pref.scala
- app/views/puzzle/bits.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/preferences.xml
- translation/source/puzzle.xml
- ui/puzzle/src/view/side.ts
close https://github.com/ornicar/lila/issues/7785
> more strings translatable for preferences and puzzles

- app/views/auth/login.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/tfa.xml
Found during https://github.com/veloce/lichobile/pull/1470 :)
> I18n TFA help message

- ui/@build/rollupProject/package.json
- ui/chess/package.json
- ui/common/package.json
- ui/common/src/defer.ts
- ui/dgt/src/play.ts
- ui/game/package.json
- ui/nvui/package.json
- ui/palantir/package.json
- ui/puzzle/src/interfaces.ts
- ui/site/package.json
- ui/site/src/infiniteScroll.ts
- ui/tree/package.json
- yarn.lock
Looks like the nvui issue was caused by https://github.com/rollup/plugins/issues/743. Could maybe use some stage testing in case there are other issues.
> update to typescript 4.1.x (attempt 2)

- ui/challenge/src/view.ts
Related to #7893. Adds label to create challenge button in the topnav. 
It looks like someone did this before, but may have accidentally put it outside of the snabbdom `attrs` property. 
I'm unsure if I also need to add a parameter for `title` in [app/views/base/topnav.scala](https://github.com/ornicar/lila/blob/master/app/views/base/topnav.scala#L29). If so, feel free to add it.
> Add title to create challenge "+" button

- app/views/base/layout.scala
- ui/site/src/component/top-bar.ts
for all working clients, https://github.com/ornicar/lila/blob/0b1beba04e915bd929acd01d423ed922f829a1f5/ui/site/src/component/top-bar.ts#L30 should prevent it from being used
> make /logout the fallback href for dasher toggle (fixes #7899)

- ui/common/css/abstract/_extends.scss
> add font fallback to sans-serif

- app/views/mod/inquiry.scala
- app/views/mod/publicChat.scala
- app/views/user/show/header.scala
- modules/common/src/main/String.scala
- modules/common/src/main/base/RawHtml.scala
> Do not expand images for mods

- ui/ceval/src/view.ts
An attempt to fix #7988. I apologize in advance if this is not okay: I have very little experience with TypeScript and JavaScript in general, and absolutely zero experience in Lichess code.
> (Attempt to) fix #7988

- ui/dgt/src/play.ts
Just saw one typo while I was poking around and figured I'd take a look over the whole file.
> Fix typoes in play.ts

- modules/round/src/main/Rematcher.scala
This PR fixes https://github.com/ornicar/lila/issues/8262.
Obviously, I didn't go through all the frontend/backend round system yet, but I identified where enpassant square information drops.
`Rematcher.returnGame` converts `FEN` to `Game` (then later `GameRepo.insertDenormalized` converts `Game` to `FEN`), but during this process `History.lastMove` doesn't seem to be restored correctly (only castling right state is kept there).
EDIT:
After greping `Forsyth.<<<` (and `Forsyth.<<<@`), I found similar patterns and other places seem to handle enpassant square correctly. For example, `ChallengeJoiner.createGame` instantiates `chess.Game` directly from `SituationPlus` without manupilating `History`. Maybe I should borrow/refactor some code from there. What do you think?
> Fix enpassant square in from-position rematch

- ui/lobby/src/setup.ts
Fixes https://github.com/ornicar/lila/issues/8277
> Fix incorrect url parameter to /setup/validate-fen

- modules/quote/src/main/Quote.scala
Two quotes displayed author as "Francois-Andre Danican Philidor" while only one displayed author as "Philidor". This PR fixes the inconsistency.
> Fixed Philidor inconsistency

- modules/common/src/main/ThreadLocalRandom.scala
- modules/socket/src/main/RemoteSocket.scala
looks like negative ints work just as well, in the only place it's used
> simplify away nextPositiveInt (closes #8411)

- public/javascripts/inquiry.js
Also keep it when going to another page.
> Sync inquiry notes across tabs.

- translation/source/site.xml
Now hosts can choose to start with black pieces with random colors.
> Fix simul source

- modules/common/src/main/model.scala
- modules/common/src/test/IpAddressTest.scala
- modules/security/src/main/Firewall.scala
looks like `!IpAddress.blockable` can never happen in prod
> simplify away IpAddress.blockable

- modules/report/src/main/ReportApi.scala
After discussion we think it's closer to their real values.
> Lower autocomm report scores

- modules/msg/src/main/MsgCompat.scala
> Exclude deleted threads from unread count

- modules/common/src/main/HTTPRequest.scala
> remove file:// from csrf whitelist (fixes #7243)

- app/controllers/Team.scala
- app/views/team/form.scala
- app/views/team/show.scala
- modules/team/src/main/Team.scala
- modules/team/src/main/TeamApi.scala
- modules/team/src/main/TeamForm.scala
https://github.com/ornicar/lila/issues/6627
> Adding options to hide team members and team forum

- app/views/puzzle/bits.scala
> Tweak translation keys sent in `Streak` mode

- app/views/simul/form.scala
- modules/simul/src/main/Simul.scala
- modules/simul/src/main/SimulApi.scala
- modules/simul/src/main/SimulForm.scala
- modules/simul/src/main/SimulRepo.scala
- modules/user/src/main/User.scala
> Hide "featureable" toggle for `lameOrTroll`s' simuls since they can't be featured anyway

- ui/tsconfig.base.json
improve tsconfig options
"strict": true,
"strictBindCallApply": false,
"strictFunctionTypes": false,
"strictPropertyInitialization": false,
in future delete 
"strictBindCallApply": false,
"strictFunctionTypes": false,
"strictPropertyInitialization": false,
and resolve compile time errors
> use strict mode

- ui/editor/src/view.ts
- ui/puzzle/src/view/side.ts
> small bug fixes

- app/views/puzzle/bits.scala
- ui/puzzle/css/_side.scss
- ui/puzzle/src/view/side.ts
closes #8552.
Screenshots will be added once complete.
> Adds zen button below difficulty on Puzzles page

- app/templating/ForumHelper.scala
- app/views/forum/categ.scala
> Hide author if post deleted in forum categs

- .eslintrc.json
- ui/@types/cash/index.d.ts
- ui/analyse/src/study/interfaces.ts
- ui/analyse/src/study/relay/relayCtrl.ts
- ui/chat/src/enhance.ts
- ui/common/src/resize.ts
- ui/lobby/src/interfaces.ts
> switch on ban-types

- ui/analyse/src/autoShape.ts
- ui/puzzle/src/moveTest.ts
> Move annotation on the right square when castling

- translation/source/site.xml
Following a confused user on discord #support, I think added featured on TV will help people realize this is not time spent watching, but being watched on TV.
> Added "featured" to time on TV

- modules/swiss/src/main/SwissApi.scala
Someone on discord reported this wording, and some people agreed it should be tweaked to be less harsh.
> Less harsh wording

- app/controllers/Notify.scala
- app/controllers/Report.scala
- app/controllers/Team.scala
- app/views/analyse/replay.scala
- app/views/team/show.scala
- app/views/tv/embed.scala
- app/views/userTournament/upcoming.scala
- modules/common/src/main/LameName.scala
- modules/evaluation/src/main/GameAssessments.scala
- modules/evaluation/src/main/PlayerFlags.scala
- modules/irc/src/main/DiscordApi.scala
- modules/msg/src/main/MsgPreset.scala
- modules/racer/src/main/package.scala
- modules/storm/src/main/StormForm.scala
- modules/storm/src/main/package.scala
looks like some people haven't been doing it
> run sbt scalafmtAll

- app/controllers/Swiss.scala
- app/controllers/Tournament.scala
- conf/routes
Adressing #8591
API doc update: https://github.com/lichess-org/api/pull/98
> Add /api/tournament/id/terminate endpoint

- modules/fishnet/src/test/UciToPgnTest.scala
fixes error caused by these commits
> fix test in UciToPgnTest.scala

- app/views/account/profile.scala
- modules/user/src/main/Profile.scala
- modules/user/src/main/UserForm.scala
closes #8626
I did not know what the min and max for RCF rating system was (couldn't find it online), so I left it at 0 and 3000 like ECF.
> add rcf rating to profile

- app/views/account/profile.scala
- modules/user/src/main/Profile.scala
- modules/user/src/main/UserForm.scala
> add cfc rating to profile

- public/javascripts/inquiry.js
fix https://github.com/lichess-org/tavern/issues/100
> inquiry: fix clearing note when submitting it

- modules/shutup/src/main/Dictionary.scala
en: merging where possible and makes sense, removing redudant plurals (since all strings are auto-pluralized), removing redudant leetifying, tweaking poop-related similarly with noob
fr: removing redundant plural
> improve dictionaries format

- ui/site/css/forum/_post.scss
This makes the CSS for the report button in forums follow the same pattern as the delete button for a forum post.
> make CSS consistent with report button in forums

- modules/shutup/src/main/Dictionary.scala
Removing redundant plural, removing redundant filter, loser matches any amount of "o", fixing format consistency in a filter, adding 2 terms
> tweak dict

- ui/chat/src/discussion.ts
> Fix chat persistence

- modules/user/src/main/Profile.scala
fixes https://lichess.org/forum/lichess-feedback/cfc-rating-shows-up-as-rfc#4
> Typo in Profile.scala

- app/views/swiss/home.scala
- modules/push/src/main/FirebasePush.scala
- modules/push/src/main/PushApi.scala
To fix: https://github.com/veloce/lichobile/issues/1228
> Update iOS badge upon move/game end notification

- app/views/coordinate.scala
- ui/site/css/_coordinate.scss
- ui/site/css/build/_coordinate.scss
- ui/site/src/coordinate.ts
> adds zen mode to coordinate

- ui/analyse/src/main.ts
this removes a circular dependency (found by following the steps in #6939 )
> removed an unused import of boot.ts from main.ts in ui/analyse

- app/ui/scalatags.scala
- app/views/appeal/tree.scala
- app/views/dgt.scala
- public/oops/diagnostics.html
- ui/ceval/src/view.ts
- ui/ceval/src/winningChances.ts
- ui/common/css/abstract/_uniboard.scss
- ui/common/css/component/_tagify.scss
- ui/dgt/src/play.ts
- ui/site/src/component/socket.ts
Hello,
This is a trivial PR fixing some typos in the code and comments. I used `codespell` to find them.
Note: in `bin/mongodb/analysis2.js` I left `splitted` (correct word would be `split`) because I couldn't find a better word, being unfamiliar with the string being split (using `split` would be weird with `split.split()`). But `splitted` should ideally not be used ;).
Note2: `information` never takes a final `s`. It's a typical error french do ;) :fr: . Same with `data`, as it's already plural (singular is `datum`).
Side note: there are 426 branches on this repo, with branches that have not been updated in the past 6 years, maybe a little cleaning wouldn't do harm ;)
Best,
~Nico
> Fix some typos in the code and comments

- ui/analyse/src/main.ts
Reverts ornicar/lila#8728
Breaks game analysis
> Revert "removed an unused import of boot.ts from main.ts in ui/analyse"

- ui/learn/src/ground.js
- ui/learn/src/level.js
- ui/learn/src/map/mapMain.js
- ui/learn/src/run/runCtrl.js
- ui/learn/src/scenario.js
- ui/learn/src/timeouts.js
> Learn: Cancel timeouts on route change

- ui/learn/src/timeouts.js
Could have sworn I tested this ...
But I guess that must have been before changing it to an ES6 module or something ...
> Learn: Fix infinite recursion

- ui/learn/src/scenario.js
> Learn: Add missing import

- ui/common/src/richText.ts
> Fix username autolinks getting surrounded by single quotes

- app/views/tournament/form.scala
- ui/tournament/src/ctrl.ts
- ui/tournament/src/view/battle.ts
- ui/tournament/src/view/button.ts
> support passwords for team battles

- app/controllers/Appeal.scala
- app/views/mod/inquiry.scala
- conf/routes
- modules/appeal/src/main/Appeal.scala
- modules/appeal/src/main/AppealApi.scala
- modules/appeal/src/main/Env.scala
close https://github.com/lichess-org/tavern/issues/95
tested snoozing appeals and reports, it works
> Snooze appeal

- translation/source/site.xml
> Precise translations for tournament conditions

- ui/common/src/richText.ts
> Fix user-mention auto-link ignoring uppercase names

- app/controllers/Puzzle.scala
- modules/common/src/main/Maths.scala
- modules/puzzle/src/main/PuzzleDashboard.scala
- modules/puzzle/src/main/PuzzleReplay.scala
Issue was happening when putting a number of day that was not part of `dayChoices = List(1, 2, 3, 7, 10, 14, 21, 30, 60, 90)`.
Other option that I though of was returning 404.
> Fallback on a correct replay day when entering an incorrect one

- ui/analyse/src/study/practice/studyPracticeCtrl.ts
> Changed auto jump to only occur in 'practice vs computer' chapters

- app/controllers/Mod.scala
- app/views/base/layout.scala
- app/views/mod/menu.scala
- modules/mod/src/main/Gamify.scala
- modules/security/src/main/Permission.scala
Also let those who can see the `publicChat` page access it easily via the mod eye (new perm not to dox anybody in case of stream)
> Timeout mods on leaderboard

- ui/analyse/css/_action-menu.scss
- ui/analyse/src/actionMenu.ts
- ui/analyse/src/autoShape.ts
Resolves issue https://github.com/ornicar/lila/issues/8837
- Allows number of engine lines to be 0
- Allows Multiple Lines slider to be moved to 0 (all the way to the left)
> Allow number of engine lines to be 0

- modules/security/src/main/Permission.scala
Let them access mod leaderboard again, following #8916
> fix hunter perms

- app/views/account/profile.scala
- modules/user/src/main/Profile.scala
- modules/user/src/main/UserForm.scala
This is following a request on Discord for the ability to show the German rating.
> Add DSB rating to user profile

- app/views/analyse/help.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/study.xml
- ui/analyse/src/keyboard.ts
Resolves #8618:
I've added shortcuts for next and previous chapters in study and also updated the help screen.
> Shortcuts for next/prev study chapters: resolves #8618

- ui/puzzle/src/ctrl.ts
> fix for puzzle streak infinite tries bug

- ui/analyse/src/ctrl.ts
- ui/site/src/component/sound.ts
> Don't preload sounds for music set

- ui/analyse/src/ctrl.ts
> Fix board orientation in Racing Kings correspondence analysis

- modules/playban/src/main/model.scala
addressed in https://github.com/lichess-org/tavern/issues/78
sorry if this isn't the right way. first time trying this.
> change ragesit threshold

- ui/@types/lichess/index.d.ts
- ui/puzzle/src/speech.ts
- ui/round/src/speech.ts
- ui/site/src/component/sound.ts
- ui/speech/src/main.ts
Alternative would be to say it with the correct language but that would be kinda weird
> Use correct language for translated speechSynthesis text

- ui/ceval/src/view.ts
> Fix pvboard after reinstanciating ceval

- ui/analyse/src/pgnExport.ts
> Analyse: Export full PGN

- app/views/setup/filter.scala
- ui/lobby/src/view/realTime/filter.ts
> Fix lobby anon filter

- ui/analyse/src/keyboard.ts
- ui/analyse/src/study/gamebook/gamebookPlayCtrl.ts
- ui/analyse/src/study/gamebook/gamebookPlayView.ts
- ui/analyse/src/study/interfaces.ts
- ui/analyse/src/study/practice/interfaces.ts
- ui/analyse/src/study/practice/studyPracticeCtrl.ts
- ui/analyse/src/study/practice/studyPracticeView.ts
- ui/analyse/src/study/studyCtrl.ts
> Fix study next chapter button

- app/views/coordinate.scala
- ui/site/css/build/_coordinate.scss
- ui/site/src/coordinate.ts
Resolves #8931.
The handler works but I can't seem to find a way to send the user's prefs to this module. I think they need to be added in `app/views/coordinate.scala`?
> Add resize handler to coordinates board

- ui/site/src/captcha.ts
This fixes captchas being broken when opening a post in the background (i.e. via "Open in new tab").
Pretty sure this is caused by the (new?) mechanism in chrome that limits timers to something like every 5 seconds in background tabs.
> Retry captcha setup when cg hasn't been setup yet

- modules/puzzle/src/main/PuzzleFinisher.scala
> One-line fixes to #9036

- ui/round/src/ctrl.ts
> Hide opponent's name from notifications in zen mode

- ui/learn/src/level.js
- ui/learn/src/run/runCtrl.js
> Learn: Store progress immediately on completion

- ui/analyse/src/treeView/inlineView.ts
> Hide inline best-moves in retrospective

- modules/game/src/main/Game.scala
- ui/nvui/src/chess.ts
- ui/round/src/plugins/nvui.ts
1. 'l' would not trigger lastMove() with Orca
2. Possible moves only worked with white
> NVUI bugfixes & improvements

- app/views/mod/inquiry.scala
Display it again for mods without `NotifySlack` perm
> fix snooze dropdown

- ui/learn/src/run/runCtrl.js
> Learn: Avoid showing stage intro on restry after failure

- ui/learn/src/level.js
> Learn: Calculate score before saving it

- app/controllers/Swiss.scala
- modules/swiss/src/main/SwissForm.scala
Like arenas, swiss tournament titles should not contain Lichess. Also, TOS marked users and BOTs cannot create swiss tourns, also like arenas.
> Swiss fixes

- app/controllers/Setup.scala
- app/controllers/Swiss.scala
- app/views/puzzle/ofPlayer.scala
- app/views/setup/filter.scala
- app/views/setup/forms.scala
- modules/fishnet/src/main/JsonApi.scala
- modules/forum/src/main/MentionNotifier.scala
- modules/game/src/main/Game.scala
Runs `scalafmtAll` and `yarn run format` to format the code.
> scalafmtAll and yarn run format

- ui/analyse/src/study/chapterNewForm.ts
Closes #8909 together with ornicar/scalachess#222
> Study: Perform basic client-side FEN validation

- public/javascripts/chart/movetime.js
- ui/analyse/src/serverSideUnderboard.ts
Original issue (already closed): #4860
> Show total time in movetime chart

- app/views/streamer/edit.scala
- ui/site/css/streamer/_form.scss
- ui/site/css/streamer/_header.scss
> Streamer: Always show image on edit page

- app/templating/GameHelper.scala
- app/views/challenge/bits.scala
- app/views/game/bits.scala
- app/views/game/side.scala
- app/views/game/widgets.scala
- app/views/swiss/side.scala
- app/views/tournament/side.scala
- app/views/tv/side.scala
> Link Correspondence FAQ in games and cleanup variantLink

- ui/analyse/css/study/_player.scss
> Study: Limit displayed name length client-side

- ui/analyse/src/explorer/explorerCtrl.ts
> Always open explorer when clicking on the navbar entry

- ui/learn/src/level.js
Hopefully the last bug created by #9059 ...
> Learn: Store progress in 'nextButton' levels

- modules/forum/src/main/TopicApi.scala
- modules/forum/src/main/TopicRepo.scala
> prevents duplicate forum topics

- public/javascripts/chart/movetime.js
- ui/analyse/src/serverSideUnderboard.ts
> Show total time in movetimes chart (this time not for mods though)

- ui/common/css/component/_board-resize.scss
|Before|After|
|:-:|:-:|
|![before](https://user-images.githubusercontent.com/19309705/121561217-93a4a980-ca18-11eb-9f40-1dfd4646378d.png)|![after](https://user-images.githubusercontent.com/19309705/121561221-96070380-ca18-11eb-8252-5d7f3de7ddbd.png)|
> Force cg resize handle on top with z-index: 10

- ui/analyse/src/autoShape.ts
> Fix blunder annotation on long castle with check

- public/javascripts/chart/acpl.js
- public/javascripts/chart/movetime.js
- ui/analyse/src/serverSideUnderboard.ts
This seems like the best way to solve this without creating a mess.
Haven't tested it yet though since my lila isn't running atm but it should work ™
> Fix movetime chart select

- modules/forum/src/main/PostApi.scala
fixes #9041
I believe the duplicate numbers was because the code to calculate the anchor number was just adding 1 to the last post in the database, so if the post was deleted and then a while later the next post was posted then it would count off of the last non-deleted post rather than the deleted post. This is what I believe to have caused the issue, but I could be wrong. I am also uncertain if my fix is too unclean/intensive, but I think it should be good?
> fix post anchor number duplication

- public/javascripts/chart/movetime.js
i.e. don't always just set it to 0 even if it wasn't actually a timeout and display it in the tooltip as well
> Movetime chart: Set last total time properly

- app/views/user/download.scala
Since ongoing games can no longer be downloaded
> remove "ongoing" from download form

- public/javascripts/chart/movetime.js
> Fix last move time calculation

- ui/site/css/user/_search.scss
Broken by d5a02f63033f87714692202abb2d97d5b6392faa
> Fix user search style

- ui/common/css/form/_cmn-toggle.scss
|Before|After|
|:-:|:-:|
|![before](https://user-images.githubusercontent.com/19309705/123182107-09842880-d48f-11eb-9f98-4b57aaceaab1.png)|![after](https://user-images.githubusercontent.com/19309705/123182108-0a1cbf00-d48f-11eb-8cbb-9a9f4c693489.png)|
> Fix cmn-toggle occasional off-by-1

- ui/analyse/src/serverSideUnderboard.ts
> Fix aclp chart when resizing with analysis off

- app/views/simul/form.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/site.xml
Adding all missing simul form translations
> adding missing simul form translations

- app/views/mod/inquiry.scala
> Add a link to Appeal in the inquiry bar

- ui/analyse/src/nodeFinder.ts
> Include missed mates in under 3 in learn from your mistakes

- modules/evalCache/src/main/EvalCacheApi.scala
> Fix eval cache move number calc

- public/javascripts/chart/acpl.js
> Fix acpl chart select

- ui/round/css/_moves.scss
> Show game result in zen mode

- app/views/learn.scala
btw, learn is also still using an old chessground version and ofc still plain JS and using mithril
Thoughts about rewriting it in TS and probably with snabbdom?
> Learn: Don't load chessground twice

- app/controllers/OAuth.scala
- app/views/oAuth/app/authorize.scala
- conf/routes
- modules/oauth/src/main/AccessTokenRequest.scala
- modules/oauth/src/main/AuthorizationApi.scala
- modules/oauth/src/main/AuthorizationRequest.scala
- modules/oauth/src/main/Env.scala
- modules/oauth/src/main/LegacyClientApi.scala
- modules/oauth/src/main/Protocol.scala
A minimal bc layer is not as complex as I thought. Should allow unblocking follow ups to #9214 before full removal.
> implement bc for legacy oauth flow

- modules/game/src/main/BSONHandlers.scala
Fixes #8758
Requires ornicar/scalachess#226
Alternative would be to just force-reset the half move clock when creating a new game which would at least make the FEN displayed when analyzing afterward correct. I guess the legitimate use cases for this are rather few.
> Fix half move clock being ignored in FromPosition

- app/views/appeal/tree.scala
fix https://github.com/lichess-org/tavern/issues/92
> Implement appeal for rankbanned accounts

- ui/analyse/css/gamebook/_common.scss
- ui/analyse/css/gamebook/_edit.scss
- ui/analyse/css/gamebook/_play.scss
- ui/analyse/src/study/gamebook/gamebookPlayCtrl.ts
- ui/analyse/src/view.ts
- Fix analyse toggle button styling for non-contributors
- Allow scrolling through moves when in analysis mode
- Display end UI when leaving analysis mode after having made some custom moves instead of crashing
> Various gamebook fixes

- app/views/storm.scala
- ui/puz/css/_side.scss
- ui/storm/css/_storm.scss
- ui/storm/css/_zen.scss
- ui/storm/css/build/_storm.scss
- ui/storm/src/ctrl.ts
- ui/storm/src/xhr.ts
Closes #9269.
I've added zen mode to puzzle storm:
> Add zen mode to storm

- ui/analyse/css/_action-menu.scss
> Analysis action menu: Prevent scrolling bc of overflow

- ui/analyse/css/_action-menu.scss
|Before|After|
|:--:|:--:|
|![before](https://user-images.githubusercontent.com/19309705/123777609-ab14db00-d8d0-11eb-984d-b4280c1f5b09.png)|![after](https://user-images.githubusercontent.com/19309705/123777612-abad7180-d8d0-11eb-9c64-87a4cb4ebbad.png)|
> Give analysis action menu range inputs marign-left

- public/javascripts/chart/movetime.js
> prettier: movetime.js

- app/views/challenge/bits.scala
- modules/coach/src/main/CoachApi.scala
- modules/coach/src/main/CoachPager.scala
- ui/challenge/css/_challenge.scss
- ui/challenge/src/view.ts
> Add color to outgoing and incoming challenges

- app/Env.scala
- app/controllers/Coach.scala
- app/views/coach/show.scala
- modules/api/src/main/Cli.scala
- modules/coach/src/main/BsonHandlers.scala
- modules/coach/src/main/Coach.scala
- modules/coach/src/main/CoachApi.scala
- modules/coach/src/main/CoachPager.scala
- modules/coach/src/main/Env.scala
- modules/hub/src/main/actorApi.scala
- modules/irc/src/main/IrcApi.scala
- modules/mod/src/main/ModApi.scala
> Remove coach approved field

- modules/challenge/src/main/ChallengeGranter.scala
I think this covers all the ways I know to get a game against yourself.
Though there's also still #8895 which honestly seems extremely weird. I really don't see how this would be possible looking at the code. Do we just want to leave it be given that it doesn't really seem to ever happen or should the pairing algorithm also check for this?
> Block self challenges

- modules/insight/src/main/JsonQuestion.scala
Couldn't test without required insights data locally.
> should fix https://github.com/ornicar/lila/issues/8407

- app/controllers/Clas.scala
- app/controllers/Coach.scala
- app/controllers/Streamer.scala
- app/controllers/TwoFactorReminder.scala
- modules/msg/src/main/MsgPreset.scala
> Two-factor auth notifications

- app/views/user/perfStat.scala
change duplicate link in perfStat, close #7215. simpler and cleaner approach than the previous PR
> change duplicate link in perfStat, close #7215

- ui/site/css/streamer/_show.scss
Otherwise, there's no way to find the Lichess profile of a streamer on mobile.
> Always show streamer services links

- modules/team/src/main/TeamApi.scala
Attempt to fix: https://github.com/ornicar/lila/issues/8493
The root cause is that when the team creator is closed, the `team.leaders` still contains this creator. My proposed solution is that we use the `validLeaders`, which haven't been deactivated yet to check the removing condition.
> fix: ability to remove closed leaders

- app/views/plan/indexStripe.scala
- app/views/plan/thanks.scala
- ui/site/src/checkout.ts
> Preserve patron plan settings on currency change

- ui/round/src/view/button.ts
> Block rematch on aborted rated game

- app/controllers/Challenge.scala
- conf/routes
> API: List challenges

- ui/analyse/css/embed/_layout.scss
- ui/common/css/abstract/_extends.scss
- ui/msg/css/_convoMsgs.scss
- ui/site/css/_blog.scss
- ui/site/css/forum/_post.scss
- ui/site/src/expandText.ts
https://lichess.org/forum/lichess-feedback/iframe--embed-bug
> Fix embed layout on mobile

- modules/game/src/main/UciMemo.scala
- modules/study/src/main/ServerEval.scala
Actually fixes #7582
Requires ornicar/scalachess##231
> Always use 960 UCI notation for analysis

- ui/analyse/src/view.ts
> Show result in tree based on PGN tags

- modules/bot/src/main/GameStateStream.scala
- modules/game/src/main/actorApi.scala
- modules/round/src/main/Drawer.scala
- modules/round/src/main/Takebacker.scala
Closes #9431
Should the general game API be updated as well?
I guess at least the tv stream doesn't need it?
> Update game stream on takeback

- app/controllers/ForumTopic.scala
- app/views/forum/post.scala
- app/views/forum/topic.scala
- ui/site/css/forum/_post.scss
- ui/site/src/forum.ts
Closes #9392
1. Style lines starting with `>` as quotes
2. Add button to copy post text as quote and insert "xxx said...`
Embeds don't get copied when using the quote button (due to how `innerText` works) but that's probably a good thing.
It also doesn't handle nested quotes.
> Forum quoting

- modules/clas/src/main/ClasMarkup.scala
Reported here: https://lichess.org/forum/lichess-feedback/markdown-headers-stopped-working#1
> Fix class' news markdown.

- bin/mongodb/create-trophy-kinds.js
- modules/tournament/src/main/TournamentApi.scala
- modules/user/src/main/Trophy.scala
- ui/site/css/user/_trophy.scss
Not sure how this works with the db? I guess you'll have to manually insert it and probably update the order of `#1 survivor`.
> Add marathon top 500 trophy

- ui/site/src/coordinate.ts
Fixes #9480
Requires ornicar/chessground#198
> Only block touch scrolling on coordinate training

- ui/@types/lichess/index.d.ts
- ui/common/package.json
- ui/common/src/wakeLock.ts
- ui/round/src/ctrl.ts
- yarn.lock
Request that screen lock be disabled on delayed init. Closes #9486.
> Add WakeLock

- app/controllers/Team.scala
- app/views/team/show.scala
- conf/routes
> Team: set mod view to default user by default

- app/views/mod/communication.scala
- public/javascripts/inquiry.js
- ui/site/css/mod/_communication.scss
Making it easier easier and faster for mods to make notes.
The client code could easily be refractored to be a standalone `site` plugin, to only load it on the relevant page, but given the size of it and the fact it's only used in combination with inquiry I've put it in `inquiry.js` for now.
> Click to note in communication page in inquiry

- modules/forum/src/main/PostApi.scala
- modules/forum/src/main/TopicRepo.scala
Log was using the topic id wrongly assuming it is equal to the topic slug.
> Fix topic when logging anon mod posts

- app/controllers/Editor.scala
- app/views/board/bits.scala
- app/views/board/editor.scala
- ui/@types/lichess/index.d.ts
- ui/analyse/src/actionMenu.ts
- ui/analyse/src/study/chapterNewForm.ts
- ui/editor/src/chessground.ts
- ui/editor/src/chessops.ts
- ui/editor/src/ctrl.ts
Also removes the server-side processing of the FEN which doesn't seem to be used anyway.
> Keep variant when opening editor

- ui/analyse/css/_tools.scss
- ui/common/css/abstract/_uniboard.scss
- ui/learn/css/_layout.scss
- ui/puz/css/_puz.scss
- ui/puzzle/css/_tools.scss
- ui/round/css/_constants.scss
- ui/site/css/_coordinate.scss
Closes #9434
I've edited a couple variables but I'm not able to figure out if they've had side effects elsewhere.
> Increase prev/next button sizes on mobile

- ui/tournament/src/ctrl.ts
> fix translation key

- ui/dasher/css/_board.scss
- ui/dasher/css/_dasher.scss
- ui/dasher/css/_link.scss
- ui/dasher/css/_piece.scss
- ui/dasher/src/background.ts
- ui/dasher/src/board.ts
- ui/dasher/src/links.ts
- ui/dasher/src/piece.ts
- ui/dasher/src/sound.ts
- ui/dasher/src/theme.ts
- ui/dasher/src/util.ts
> Use real button elements in dasher

- ui/swiss/src/ctrl.ts
- ui/swiss/src/pagination.ts
- ui/swiss/src/search.ts
- ui/swiss/src/xhr.ts
Like #9551 but for swiss. No \# prefix.
> Search for players by rank in swiss tournaments

- modules/db/src/main/CursorExt.scala
- modules/mod/src/main/ModlogApi.scala
- modules/security/src/main/Store.scala
> `CursorExt` tweak

- ui/swiss/src/xhr.ts
Tested on swiss tournaments with and without passwords.
> fix swiss join request

- public/javascripts/inquiry.js
Note is conserved when closing and reoping an inquiry about the same user consecutively, but lost as soon as an inquiry about another user is made.
> Make inquiry note `user` dependent.

- app/views/user/perfStat.scala
- modules/common/src/main/Maths.scala
Resolves #9605
See https://github.com/ornicar/lila/issues/9605#issuecomment-903310278
> Round down in perf stats

- ui/analyse/src/ctrl.ts
- ui/ceval/src/ctrl.ts
- ui/ceval/src/types.ts
- ui/ceval/src/view.ts
Instead of detecting the engine crash I tried to validate the position before allowing analysis on the position as suggested in the comments of the issue, please let me know if I need to make any changes to my code. Thank you!
Fixes #8912
> validate position before client side evaluation

- ui/analyse/src/study/chapterNewForm.ts
> study: Validate game URLs for new chapter

- app/controllers/Pref.scala
- modules/api/src/main/Context.scala
- ui/common/src/resize.ts
- ui/dasher/src/board.ts
Fixes #9442
Not quite sure about the maxAge. As far as I understand, it will use the session cookie baker with it's configured max age (default 10 years)?
> Move zoom pref to separate cookie

- modules/quote/src/main/Quote.scala
https://lichess.org/forum/lichess-feedback/wrong-spelling-in-tournament-motto
> fix `Robert Hübner` name.

- app/views/storm.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/storm.xml
- ui/storm/src/view/end.ts
translating "Failed puzzles" and "Slow puzzles".
closes #9692
> missing storm translations, closes #9692

- modules/tournament/src/main/Schedule.scala
5 rated classical games for now, should prevent absolutely `clueless` ratings as well as other issues.
> add entry requirements for classical arenas

- ui/@types/lichess/index.d.ts
- ui/analyse/src/study/studyChapters.ts
- ui/chat/src/view.ts
- ui/palantir/src/main.ts
- ui/round/src/boot.ts
- ui/swiss/src/view/main.ts
Fixes #9643 
I don't know if the types are specific enough, this is my first pull request here.
> Basic types for window + fix capitalization typo in ui/chat

- app/views/board/userAnalysisI18n.scala
> Send disabled ceval trans key in game analysis

- ui/site/css/ublog/_markup.scss
|Before|After|
|:--:|:--:|
|![Screenshot 2021-09-09 014033](https://user-images.githubusercontent.com/19309705/132599523-23cfc805-48a6-48cf-b593-31935f7d6cae.png)|![Screenshot 2021-09-09 014018](https://user-images.githubusercontent.com/19309705/132599516-f14e6bd2-eb73-43ab-90e4-917dc466373f.png)|
> ublog/css: Fix nested lists

- ui/analyse/src/ctrl.ts
- ui/analyse/src/study/commentForm.ts
- ui/analyse/src/study/interfaces.ts
- ui/analyse/src/study/studyCtrl.ts
In its current form, it doesn't work for collaborative editing anyway. And I guess that use case should probably just disable sync and isn't even very common in the first place.
> study: Remove sticky comment behavior

- app/controllers/Ublog.scala
close https://github.com/ornicar/lila/issues/9788
> Fix `blog/friends` page for anon

- app/views/board/userAnalysisI18n.scala
> Translate "x didn't move" in embeds

- ui/site/css/_page.scss
- ui/site/css/ublog/_markup.scss
|Before|After|
|:--:|:--:|
|![before](https://user-images.githubusercontent.com/19309705/133929360-79357baf-e117-4f63-8861-d7b4bed92b0c.png)|![after](https://user-images.githubusercontent.com/19309705/133929367-ffd9a3e9-eaa4-49d3-9634-b409a5f2dec8.png)|
> css: Reduce page h2 line-height

- bin/trans-dump.js
Refactored the `trans-dump.js` file by replacing redundant code, requiring only necessary methods and improving readability.
> refactor(bin): apply optimizations

- app/views/tournament/bits.scala
- modules/tournament/src/main/Schedule.scala
> Fix the tournament names after translating

- modules/forum/src/main/Categ.scala
Before the topic count was only correct after denormalising `Categ` (for example when a post is deleted).
> Fix topic count
