ui/analyse/src/data.js

moveTimes was null on http://en.l.org/analysis or when pressing analyse on board editor and analysing from a fen string

fix analysis action menu for unsaved/fen games

---

app/views/user/show.scala.html

When I just joined Lichess, I was a bit confused by the color of the icon next to the username. Later I found out it indicates whether someone is online or not. To reduce confusion, this commit adds a tooltip that says "Online" if the user is online, else, "Offline".

Add a "Online"/"Offline" tooltip on user page

---

ui/round/src/replay/ctrl.js

To reproduce: click Prev then Next replay buttons, do a move or wait for
opponents move, now the prev button/(or that move in movelist) is stuck
because it thinks it is still displaying that move (from the Next
click).

fixes replay getting stuck

---

ui/round/src/view/button.js
ui/round/src/view/table.js

It helps with remebering which button is which when you always can
see them and they aren't moving around depending on gamestate.
http://i.imgur.com/AiEN7JV.png (left = before, right = this commit)
Also changed button.standard to allow overiding onclick's default

show disabled game controls instead of removing

---

app/views/base/chatDom.scala.html

When posting a chat message, you get an error if it's longer than 140 characters. When giving it a maxlength, users can see when they reached the maximum length.

Add maxlength attribute to chat input

---

public/javascripts/big.js

Tested on lichess.org/player/online
Powertip supports multiple targets in the same call. End of each call
they are saved to a collection that gets uniqueSorted with slow comparison,
this sorts one time instead of 1000 on that page.
Only code-change is indentation and removal of
623: .each(function() {
624:    $(this)
641: });

reduce page load, 8s to 240ms when 1k powertips

---

app/views/tournament/faq.scala.html

The lichess forum post linked from #515 points out to "fix a mistake - 30 seconds to 15 seconds in the tournaments description (Other important rules.)" This commit does that.

Fixes the Tournament FAQ: 30 seconds -> 15 seconds

---

app/controllers/LilaController.scala
app/controllers/Tournament.scala

fixes #561, fixes #396
Different browsers set different content-type when posting without data,
content-type shouldn't matter without data.
tested tournament/simul in chromium/firefox/surf(webkit)

support xhr POST requests without data

---

public/javascripts/big.js

autoscrolls within 1 message from bottom and also when completely at top
tested in firefox and chromium

only autoscroll chat when at bottom, fixes #503

---

public/stylesheets/tournament.css
ui/tournamentSchedule/src/view.js

It bubbles them up until it hits an official
I don't want them mixed with the
officials but this reuses the bottom lanes better when there is lots of
future official tourney lanes. Also hour-mark has solid lines.

allow user tournaments to reuse bottom free lanes

---

app/views/user/show.scala.html

Verified to work in English and Norwegian. Will not make it pluralizable.

use existing translated string for 'puzzles' in rating list - closes #639

---

modules/game/src/main/Game.scala

The original reason to make it not analysable were Stockfish crashes with illegal or impossible positions.
I tested the following scenarios with https://github.com/ddugovic/Stockfish:
* Impossible castling rights (filtered out before they reach Stockfish)
* Excess pawns
* Excess pieces
* Opposite side check
The result is: If the game starts when "playing vs a friend", then analysis works fine. Additionally you can not play excess pawn and piece positions vs the machine, although it could handle those just fine.
Of course there could still be edge cases with specifically crafted positions, that I would not have found in my tests. (Looks unlikely to me.)

make FromPosition variant analysable

---

app/views/game/search.scala.html
modules/gameSearch/src/main/Query.scala
public/stylesheets/search.css

- Added explanatory mouseover tooltips (can be added for all)
- Removed annoying off-center 'vs'
- Added localization for some labels whose translations already exist (I can add support for all other missing translations if wanted)
Before:
After:
What do you think?

Minor search form cosmetic improvements

---

public/javascripts/chart2.js

The Move Times chart said "0 second" instead of "0 seconds".

Move times: fix pluralization mistake

---

public/javascripts/big.js

Key is `"Decline"`, not `"decline"` in `lichess_translations`.
See dialogue on joining a challenge:

Fixes localization of string "decline" in big.js

---

public/javascripts/big.js

How it works:
- For challenge desktop notifications, the code stores the desktop notification for the latest challenge ID to localStorage. When a new challenge comes in, it checks whether the ID of this challenge is the same as in localStorage. Yes? Then the notification is a duplicate and shouldn't be shown.
- For inbox notifications, the code stores the number of unread inbox messages in localStorage after it shows a desktop notification. And before it shows a notification, it checks whether the new amount of unread messages equals the amount in localStorage. Yes? Then the notification would be a duplicate and should not be shown. When you click on the Inbox icon in the top bar, the number in localStorage gets reset.
Fixes #854.

Prevent duplicate desktop notifications

---

modules/socket/src/main/WithSocket.scala

There is a name conflict going on:
```
[info] Loading project definition from /home/niklas/Projekte/lila/project
[info] Set current project to lila (in build file:/home/niklas/Projekte/lila/)
[info] Compiling 3 Scala sources to /home/niklas/Projekte/lila/modules/chess/target/scala-2.11/classes...
[info] Compiling 12 Scala sources to /home/niklas/Projekte/lila/modules/chess/target/scala-2.11/classes...
[info] Compiling 2 Scala sources to /home/niklas/Projekte/lila/modules/socket/target/scala-2.11/classes...
[info] Compiling 1 Scala source to /home/niklas/Projekte/lila/modules/opening/target/scala-2.11/classes...
[info] Compiling 2 Scala sources to /home/niklas/Projekte/lila/modules/puzzle/target/scala-2.11/classes...
[info] Compiling 2 Scala sources to …
```

explicitly use Channel from play.api.libs.iteratee.Concurrent

---

public/stylesheets/user-show.css

Previously overridden in non-light themes by `body.dark div.user_show div.content_box_top>span`.

Increase specificity of '.staff' in user-show.css

---

modules/tournament/src/main/Schedule.scala
modules/tournament/src/main/Scheduler.scala
modules/tournament/src/main/TournamentRepo.scala

Daily tournaments are scheduled on lichess peak activity hours,
which match the Western world day.
Therefore nightlies are targetting the Oriental world.
- Why not call them nightlies?
because it's not night for those who play them
- Why not call them dailies?
because they won't be very successful, and I don't want
a half-empty tournament to be called "daily".
It would look bad to have weak daily tournaments.
This is a proposition, please discuss.

rename Nightly tournaments to Oriental

---

public/worldMap/app.js

This commit makes the sound button work on the World Map page.
Although, the noise is pretty annoying since so many moves are happening at once. It may be better to just remove the button altogether.

Fixes SOUND button in World Map

---

app/views/mod/communication.scala.html

Rationale:
1. Like chat messages, replies provides context for why the user's attitude changes by a huge tangent, to assist making decisions on whether the behaviour in the response is disruptive and unreasonable.
2. The communication report of the other user can already be navigated to. There's no real need to add that minor inconvenience - It's not like moderators don't know not to use the knowledge to stir up trouble - especially when the other report may be missing the fragment of the message we're looking for (since the size is limited) and make it difficult to judge.
3. There are a lot of insult-type reports daily. Appending the information makes it easier to commit a reliable decision quicker, hence enhancing effectiveness of reviewing.

Unhide inbox replies

---

app/views/i18n/contribute.scala.html

The "What about these ones?" message is out of context when the "Do you know these languages?" message isn't displayed.

show "What about these ones?" only on suggestions

---

public/stylesheets/board.css

An alternative is with `pointer-events: none;` if it's important to insist its existence for purposes like a screen reader or printing, but I doubt it.
http://ja.lichess.org/forum/lichess-feedback/lazy-implementation-of-the-chat-room-checkbox

Hide hidden chat instead of making it non-opaque

---

app/views/base/layout.scala.html

The icon is visible when not in focus.
It disappears when brought in focus.
Setting the color attribute to something non-white ought to fix this.
[See also.] (https://developer.apple.com/library/prerelease/ios/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html)
To quote:
> You can improve the visibility of your icon by avoiding a light color, such as white, bright yellow, or light gray.

Change mask-icon colour.

---

public/javascripts/big.js

In the code for generating the I18n dropdown items, the generated HTML contained a quote which didn't have to be there.

Removed orphan quote in big.js

---

.gitignore
Vagrantfile
bin/build-deps.sh
bin/provision-vagrant.sh

The developer onboarding process is now:
1) Run `vagrant up`. Wait an hour or so depending on your network and CPU to compile.
2) Follow instructions (these have been slightly modified in this PR):
3) Enjoy development lichess:
If the PR is accepted, I'll update the wiki.

Add Vagrant support for development

---

ui/puzzle/src/ctrl.js
ui/puzzle/src/puzzle.js

note: untested because i can't figure out how to get mock puzzles (is that ok?)
- only play move sounds when stepping forward/back
perhaps stepping back should have a different kind of sound?
and jumps to the beginning/end of the puzzle?

add capture sounds when reviewing puzzle solution

---

ui/analyse/src/ceval/cevalCtrl.js
ui/analyse/src/ceval/cevalWorker.js

We can safely cut off the move list before the latest castling move. Stockfish only needs the move for repetition detection, and this can not occur anyway.
Doing that, we can avoid to actually parse the FEN and look at the position (in order to correctly `fixCastles` in all cases).

add chess960 support for local eval (fixes #1586)

---

modules/challenge/src/main/Challenge.scala

Not sure if this is the right place to fix it. However I don't see any issue with it, the fen is ignored anyway when creating the actual game unless it's FromPosition.

fixes #1717, use variant fen if not initial, for challenges

---

conf/base.conf
modules/security/src/main/Env.scala
modules/security/src/main/Recaptcha.scala

I've seen at least 2 new devs getting stuck on this in irc, registering doesn't work without the private key.
Make sure to turn in on in server conf. This doesn't disable the client
UI; to verify it is verifying try registering with random stuff in
the textarea named g-recaptcha-response.

disables server verification for recaptcha in dev

---

app/views/user/list.scala.html

Sometimes I need to search a user. It would be easier if I can type right when I get to the page where the search is and not to click this field.

Make user search field autofocusing

---

ui/round/src/view/table.js

fixes
http://en.lichess.org/qa/1255/why-cant-we-choose-to-forfeit-if-an-enemy-disconnects
Thought about adding a button with text similar to the others, but it would need more code and probably support confirmation... lazily went with less code and just kept the regular buttons

show resign button even when opponent left

---

app/views/tv/stream.scala.html
modules/tv/src/main/Stream.scala
modules/tv/src/main/Streaming.scala

The link is useful when you want to watch the stream in other
applications, like youtube-viewer or mpv

link title to stream service, and fix hitbox filter

---

ui/analyse/src/ctrl.js

Using niklasf/lila-openingexplorer@c7b52cbefedd44de66b214f9406e492967efa851 we now also show underpromotions in the opening explorer. However when clicking an underpromotion in the move list, it always promotes to a queen, instead.
Example: http://en.lichess.org/QJCL1oJ6/black#13 (Lasker trap)

allow clicking underpromotions in explorer

---

ui/analyse/src/explorer/explorerView.js

cc @ddugovic
Also displaying one of `Capture` or `Pawn move` instead of `Zeroing`, so we have one less term to explain.

Improve explanations of DTM and DTZ

---

app/templating/StringHelper.scala

Todo: Fix the bloody word boundary matching

Turn usernames prefixed in '@' into link to user profiles

---

app/templating/StringHelper.scala

based on https://github.com/ornicar/lila/blob/master/modules/security/src/main/DataForm.scala#L34-L44
it now asserts that the username length is exactly 2-20 correctly, as well that the first letter isn't a digit, and does it without backtracking. (It's probably even more performant than before, despite that it's longer)
tested with a throwaway ideone script, haven't actually compiled and tested it
doesn't check for https://github.com/ornicar/lila/blob/master/modules/common/src/main/LameName.scala but I think running that every time is an overkill?

Improve username regex

---

ui/analyse/src/ctrl.js

Sound should only be played when the path has really been changed.
Aditionally, always reset justPlayed and compare only the origin square (or the entire drop). This makes justPlayed independent of the castling representation (to empty square or to rook). Two consecutive moves can never have the same origin square anyway.

Fix duplicate sound playbacks in analysis (fixes #1901, fixes #1912)

---

ui/analyse/src/ctrl.js
ui/analyse/src/view.js

The issue:
Open a study with a long game in two browser windows A and B. In A, scroll down in the move list and jump to move 20.
In B, the new move gets the `.active` class, but is not centered.
In A, jump to move 40.
In B, move 40 gets the `.active` class, but only now is move 20 centered.
The fix: Defer auto scrolling until after the new `.active` class is in the rendered DOM by calling it from the config callback.

Fix auto scroll when other user jumps in study

---

ui/analyse/src/ctrl.js

Fixes a subtle issue with the castling animation: When clicking O-O or O-O-O in the opening explorer, the king moves first to the a or h file, then to its target square.

Fix animation when clicking O-O in explorer

---

app/views/user/show.scala.html

not just URLs
fixes #1986
note that the profile link regex is ran after, otherwise the url regex would catch urls added by the profile link regex pass, so the order is kinda specific here

add user profile text links with @ mentions

---

public/javascripts/socket.js

Good news: We can continue to configure port forwarding. Production firewall needs to be configured before deployment. Stage firewall is configured for testing.

Bring back alternative WS ports for http and https

---

bin/provision-vagrant.sh

* `/ai/` is gone for a while, now.
* `socket.{lang}.l.org` has been moved to `socket.l.org`.

[UNTESTED] Update Vagrantfile with recent config changes

---

conf/base.conf

Problem: We can't us protocol relative URLs with WS.
Reported here: https://de.lichess.org/forum/lichess-feedback/cant-access-imported-games#3
Example: https://en.stage.lichess.org/import/master/v1thiEGv/white?fen=rnbqkb1r/pppppp1p/5np1/8/5P2/6P1/PPPPP2P/RNBQKBNR%20w%20KQkq%20-%200%203
Stacktrace:
```
[error] application - 
! @70cfdoaoo - Internal server error, for (GET) [/import/master/9CizUxa6/white?fen=rnbqkbnr/pp1p1ppp/8/2p1p3/2P5/6P1/PP1PPP1P/RNBQKBNR%20w%20KQkq%20-%200%203] ->
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: scheme]]
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.6.jar:2.4.6]
at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191 …
```

Fix import of master games

---

public/javascripts/main.js
public/stylesheets/board-3d.css

`div.lichess_ground` itself should not have an explicit height, so it inherits the height from the sourrounding `div.lichess_game`.
For reflowing charts, also see http://api.highcharts.com/highcharts#Chart.reflow

Resize move list and charts when using 3D board (fixes #1706)

---

bin/provision-vagrant.sh

This doesn't work with PredictableNetworkInterfaceNames, no need trying to be smart when it's hardcoded in Vagrantfile

hardcode vagrant ip in instructions

---

Vagrantfile

vagrant up
"The box 'boxcutter/ubuntu1504' could not be found or could not be accessed in the remote catalog."
"URL: ["https://atlas.hashicorp.com/boxcutter/ubuntu1504"] Error: The requested URL returned error: 404 Not Found"
End of life for Ubuntu 15.04
Ubuntu Server 15.04 (Vivid Vervet) daily builds [END OF LIFE - for Archive reference only]
https://cloud-images.ubuntu.com/vagrant/

udpate vargant box ubuntu version

---

Vagrantfile

This is the first version that can deal with the new predictable network
interface names on Ubuntu: https://github.com/mitchellh/vagrant/pull/7253

Require at least Vagrant 1.8.3

---

modules/security/src/main/DataForm.scala

Currently, if you try to register with an invalid username the resulting error message
will ask you to use "letters, numbers and dash" characters. However, the underscore `_`
character is also valid, as determined by the username regex: `^[\w-]+$`

Add the underscore character to the invalid username error message

---

public/javascripts/main.js

Before this commit, the game setup dialog did not show your rating when selecting 'Crazyhouse' as variant. This fixes it.

Show rating when selecting crazyhouse in game setup

---

public/stylesheets/chat.css

The chat message padding in safari is broken due to to the display mode of the outer container. This should fix #2039.
Before & After:

Fix chat message padding CSS in Safari (#2039)

---

modules/quote/src/main/Quote.scala

The quote, "When you are lonely, when you feel yourself an alien in the world, play chess. This will raise your spirits and be your counselor in war." is attributed to Aristotle, but probably isn't a genuine quote since Aristotle (died 322 BCE) pre-dated chess (c. sixth century CE)

Removed Aristotle quote

---

public/stylesheets/chat.css

Prevent users from the resizing the text area beyond the size of the container.
Before & After:

Disable resize for the note textarea.

---

app/views/user/mini.scala.html

In the mini user view, sometimes the country name will not be displayed if the username is too long. To keep up with the fun of discovering new countries, this change lets you hover the flag to see the name of the country it belongs to.

Show country name as alt and title of flag image

---

ui/analyse/src/view.js

Basically, chrome crashes when doing a mousedrag over an element with css content (the icon) if some parent has their number of children changing in amount (toggling the menu) at the exact same moment; or something like that. This will only generate normal mousemove events with the mouse button released.

chrome crash workaround, fixes #2051

---

public/stylesheets/board.css

In version 47 and 48, after switching tabs back and forth twice (or
maybe after a delay), and when dropping a piece on the board it would
not clear the areas around it from the hovering piece. This seems to be
solved in firefox 49 and 50.

Fixes firefox buggy rendering

---

public/stylesheets/analyse.css

not needed with custom styled scrollbars

revert analysis note margin

---

modules/common/src/main/LilaCookie.scala

In the current configuration an attacker could steal the session cookie in a MITM attack if they get the user to connect lichess.org via plain HTTP (say `<img src="http://lichess.org/?asdfghjk">` on their site).
`play.http.session.secure = true` can be used to force all cookies to be HTTPS only, but this is too much for old versions of the app.
Instead let's upgrade to secure cookies if nginx indicates the user connected via https.
(`X-Forwarded-Proto` still needs to be configured next to the exisiting `X-Forwarded-For`: `proxy_set_header X-Forwarded-Proto $scheme`).

Use secure cookies on HTTPS connections

---

ui/notify/src/view.js

The expected 'type' value for the forum mention notification was out of date (was 'mentioned', is now 'mention')
Fixes #2123

Fix forum mention notification regression

---

app/views/base/fpmenu.scala.html

Despite it being a rather important document, a link to it appears very rare. This commit adds a link to the privacy policy in the full-screen menu (that menu that you can open with the hamburger icon in the top bar).

Add link to privacy policy in full-screen menu

---

ui/tournament/src/sound.js

Calculate the best countdown sound on the fly
rather than relying on a prompt timeout callback.
Fixes sound weirdness in chrome when tab is not in foreground.
Tested extensively on Chrome, but should be safe for all browsers.
Possible further improvements:
- send ms for start time, to improve countdown accuracy
- use Howl _onend callback to schedule the countdown sound.

Improve countdown sound logic

---

ui/analyse/src/explorer/explorerCtrl.js
ui/analyse/src/util.js

Debouncing
```
.........X            .......................................X
```
is more appropriate for the explorer than throttling:
```
.........X            .........X.........X.........X.........X
```
Let's do that and with a much smaller delay.

Debounce explorer xhr instead of throttling

---

modules/tournament/src/main/Schedule.scala

Feedback for 4+1 was largely positive. However some pointed out that 4+1
is a shorter time control than 5+0 and crazyhouse doesn't have any 10+0
tourneys like standard chess. So bring back a slow tourney, the +2 gives
a very different feel for zh where games last until they are done.
Also add 3+1, which has been suggested a couple times. The logic is setup
to avoid 2 consecutive increment tourneys.

Adjust crazyhouse increment schedule

---

app/templating/SetupHelper.scala
modules/game/src/main/Game.scala
modules/setup/src/main/Config.scala
ui/analyse/src/ceval/cevalWorker.js
ui/analyse/src/ctrl.js

Update stockfish.js and enable Horde and RacingKings for local analysis, fishnet analysis and play against the ai.
There have been lots of improvements lately and I am pretty confident that Stockfish is a strong opponent in these variants.
cc @ddugovic, @ianfab

Enable horde and racing kings ai

---

ui/analyse/src/ceval/sunsetterWorker.js

Improve sunsetter output and behavior, especially in
positions close to mate.
- fix eval sign in "analyze" mode, which is
used after sunsetter plays a forced move
- enter analyze mode if sunsetter quickly picks an obvious move
without fully evaluating. For example, if alternatives allow
mate in 1, sunsetter might move with only depth 1 evaluation,
giving the best move but an incorrect eval score.
- approximate depth when sunsetter finds mate but doesn't give
a depth.
Fixes #2198 and #2199.

Sunsetter improvements

---

app/views/forum/topic/show.scala.html
modules/forum/src/main/Post.scala
public/javascripts/forum-post.js
public/stylesheets/forum.css

Some follow up improvements for forum post editing /cc @Happy0 
Most importantly allow users to edit their original raw text. (Currently line breaks will be dropped from the text when opening the edit form.) This is done by rendering hidden forms on the server side.
A couple of CSS and styling improvements included also.

Forum edit improvements

---

app/Global.scala
modules/common/src/main/mon.scala
modules/puzzle/src/main/Selector.scala
project/Dependencies.scala

Should be good to go.
---
Just working:
* Tor.isExitNode
* Geo IP lookup
* ipintel
* Log on profile
Support added in:
We only ever have to deal with addresses in their standard form, no compressed addresses (like ::1), no leading zeros in components (like 0:0:0:0000:0:0:0:0).
/ref lichess-org/sysadmin#20

IPv6 support

---

app/controllers/Importer.scala

One legit use case that popped up in the CSRF logs: http://spawk.fish/play/ allows to import a game. Proposed solution: Allow filling in the form via a GET parameter (but let the user confirm the submission).

Allow filling in the import form via GET

---

ui/analyse/src/ceval/sunsetterProtocol.js

Switch sunsetter to analyze mode. This fixes a number
of issues and improves analysis strength. Also fix
the parsing of Sunsetter 9 mate score.
Possible further improvements, pending engine changes:
- Can we use currentFen instead of initialFen + moves?
One blocker on this: georgvonzimmermann/Sunsetter#11
- Mate *much* better, but off by 1/2 move.
georgvonzimmermann/Sunsetter#9
- Use set depth 'sd' option. Blocked by bugs such as
georgvonzimmermann/Sunsetter#10

Sunsetter: use analyze mode

---

COPYING
LICENSE
README.md
modules/rating/src/main/java/glicko2/LICENCE.txt
ui/analyse/package.json
ui/challenge/package.json
ui/chat/package.json
ui/editor/package.json
ui/game/package.json
ui/insight/package.json
ui/learn/package.json
ui/lobby/package.json
ui/notify/package.json
ui/opening/package.json
ui/perfStat/package.json
ui/puzzle/package.json
ui/round/package.json
ui/simul/package.json
ui/tournament/package.json
ui/tournamentSchedule/package.json

We can switch to the AGPL as soon as we hear back from the contributors.
I reviewed all the used libraries for GPL compability and added an [exception](https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs) for Highcharts.
Usually it's considered safest to include a copyright clause at the top of every file. This PR takes a less intrusive approach: "Any file in this project that does not state otherwise and is not listed as an exception below is copyright (c) 2012-2016 the lila authors. [...]".
This is accompanied by a very conservative list of exceptions. We should now or later see if we can make any of the board, piece and sound themes available under the AGPL as well.

Switch to AGPL

---

ui/tournament/src/sound.js

- squeeze timeout interval so numbers don't sound weird.
- start sounds .1s before clock tick to sync better.

Adjust tourney countdown

---

ui/analyse/src/explorer/explorerCtrl.js
ui/analyse/src/explorer/explorerView.js
ui/analyse/src/explorer/openingXhr.js

I have rewritten the tablebase server based on @ddugovic's Stockfish: https://github.com/niklasf/tbserve
New:
* It can show transitions from 7 piece endgames and endgames with castling rights
* Support for atomic tablebases (not yet enabled, still generating the tables on my private server)
* Preperations for suicide tablebase support
expl.lichess.org is already configured. The new endpoint is https://expl.lichess.org/tablebase/standard (base.conf does not change, variant appended dynamically) instead of https://expl.lichess.org/tablebase. Once lila is updated I can remove the old endpoint.

Switch from Fathom to tbserve

---

modules/api/src/main/UserGameApi.scala

(and remove duplicate `opening` field)
It would be nice to have players title as well, for the coherence with the website and the rest of the app. But I leave that to you since user infos are not yet present in this api.

Add source to UserGameApi JSON

---

public/stylesheets/coordinate.css

Tested with http://csslint.net
File: https://lichess1.org/assets/stylesheets/coordinate.css?v=1239

fix syntactical error in coordinate.css

---

modules/gameSearch/src/main/Query.scala

I was curious about how many games with the 45 min / 45 sec increment clock settings had been played on the site and what their durations were.
I noticed that you can't currently ask about such games in the advanced search view.

Advanced search: 45 min / 45 sec increment options in clock dropdown menus.

---

modules/relation/src/main/RelationActor.scala

Sometimes when people are playing 45/45 games the green TV on the friends list disappears as the game duration goes beyond an hour.
This pull request increases the expiry time so that this is very unlikely to happen.

Increase relation onlinePlayings expiry

---

ui/tournamentSchedule/src/view.js

As usual there was too much code in the code.
All userTours are put into the same lane now,
and uses same splitOverlaping as systemTours.

remove tournament schedule holes

---

public/stylesheets/board.css
ui/round/src/crazy/crazyView.js
ui/round/src/ctrl.js
ui/round/src/ground.js

- Clear drop when new move is received. As a result,
the guard for ply is not needed.
- Don't clear droppedPiece in sendMove.
- Highlight pocket used for predrop.

Clean up crazyhouse drop preview

---

app/views/message/inbox.scala.html
public/stylesheets/message.css

Also remove dropdown menus for marking/deleting messages when inbox is empty. Fixes #2438

Add padding to "no new messages" text

---

README.md

It currently 404s, cursory google suggests it was removed.

Remove broken link to removed opening trainer feature.

---

modules/round/src/main/Drawer.scala

Scenario: You do a move and want to claim threefold repetition, but your opponent made a premove (or moved very fast otherwise).
To reliably claim, just offer a draw before making the move.
This is similar to OTB chess. There you claim a draw and then demonstrate that you can play a move that repeats for the third time.

auto claim threefold after offering a draw (fixes #883)

---

ui/analyse/src/explorer/explorerConfig.js
ui/analyse/src/explorer/explorerCtrl.js
ui/analyse/src/explorer/explorerView.js
ui/analyse/src/explorer/openingXhr.js

Given the number of antichess players you were not very exited about hosting Watkins antichess solution, especially if it takes 6 GB of RAM. I worked on it anyway, for the fun of it, reducing that requirement to 128 MB: https://github.com/niklasf/antichess-tree-server
API endpoint: https://tablebase.lichess.org/watkins?moves=e2e3
Integration with the explorer is barely noticable in the minified size (but of course adds a bit of complexity).
Watkins proof trees end in tablebase land, which makes for a nice transition.

Add Watkins antichess solution to explorer

---

app/controllers/Report.scala

This will enable me to handle more communication reports before the entire queue is filled up by only engine reports.

Increasing the max number of reports displayed on the reports list page from 50 to 200

---

conf/base.conf
modules/security/src/main/EmailConfirm.scala
modules/security/src/main/Env.scala
modules/security/src/main/PasswordReset.scala

This should be ready to deploy. Tested using https://www.google.com/webmasters/markup-tester and self-sending. (It's orthogonal to other improvements like #1543.)
Action links won't (normally) show in gmail yet. We'll have to ask approval once it is on prod.
---
Based on #1268 by @Unihedro.
* Use ViewAction: The link is valid indefinitely and logs the user into
lichess. (ConfirmActions run in the background and only once, status
200 expected.)
* Actually use properties as markup.
* Add organization information and Reply-To.

Add schema.org action to activation mails

---

ui/round/src/ctrl.js
ui/round/src/ground.js
ui/round/src/promotion.js

Premove a pawn to the eighth rank.
Previously: Wait for the reply. Then the promotion dialog pops up.
Now: You select the promotion piece type and it gets played once there
is a reponse.

[RFC] Support pre promotions

---

modules/security/src/test/SpamTest.scala

With the removal of $in in ecb55568a1b38081e6409b31f752 tests were failing.

update SpamTest after removal of in

---

modules/analyse/src/main/Info.scala
ui/analyse/src/autoShape.js

Encountered while debugging #2307: It would show the promotion when streaming analysis in progress, but not after a page reload.

do not drop promotion type of fishnet analysis

---

ui/analyse/src/autoShape.js
ui/analyse/src/explorer/explorerCtrl.js
ui/analyse/src/explorer/explorerView.js
ui/ceval/src/ctrl.js
ui/ceval/src/view.js

Put data from mouse events in the context of their FEN. Then render hovering arrows iff `hovering.fen === ctrl.vm.node.fen`.

fix ceval and explorer hover glitch (closes #2473)

---

ui/tournament/src/view/finished.js
ui/tournament/src/view/pairings.js

Show box after tourney is finished, regardles of whether
pairings or a specific player is being viewed.
Note: while this patch should be safe, I have not thoroughly
tested it. In particular, I am not sure if `undefined`
is safe to return in a mithril render list.

Improve logic for displaying next tourney box

---

ui/round/src/ctrl.js
ui/round/src/promotion.js

Previously: Make a pre promotion. The dialog pops up. Your opponent moves. The dialog closes.
Now: The dialog only closes if the promotion move is no longer possible.
Follow up for #2515.

keep pre promotion dialog (closes #2532)

---

ui/ceval/src/ctrl.js
ui/ceval/src/stockfishProtocol.js

- Cleaned up regex to avoid backtracking
- Organized regex extraction logic
- Fixed bug where opts.multiPv was not evaluated correctly.
- Removed lowerbound/upperbound messages for now. Their PVs are
bad and their evals are not suitable for the eval box.
This patch prepares possible enhancements such as:
- Heuristics to avoid changing the displayed PV / best move too
frequently, or to avoid replacing a good PV with a worse PV.
- Using lowerbound/upperbound scores to indicate uncertainty in
the eval bar.
@niklasf

Stockfish Protocol improvements.

---

ui/analyse/src/ctrl.js
ui/puzzle/src/ctrl.js

This fixes a bug where longer PVs are never shown because
stockfish prints the normal PV first.
This will also show the mixed depth PVs stockfishProtocol now
emits (i.e. PV 1 depth 21, PV 2 depth 20). These are categorized
as min(depth of PVs), so would not override the depth 20
emit.
@niklasf

Update PVs to latest emit with equal depth

---

ui/analyse/src/autoShape.js

The slicing was not working for drops. Also move initialization of `color` before usage.

Fix practice hint auto shapes for drops

---

ui/analyse/src/explorer/explorerConfig.js

Just saw on @ddugovic's stream that the antichess solution is not available for analysis of games. This is because `game.initialFen` (incorrectly) has castling rights.
This PR does not fix the [root cause](https://github.com/ornicar/scalachess/blob/master/src/main/scala/variant/Antichess.scala#L10), but should be a reasonable workaround for existing games.

workaround initial antichess fen bug for watkins

---

public/stylesheets/blog.css

Ugly indentation before:
After:

tweak style of bullet lists in the blog

---

modules/evaluation/src/main/Assessible.scala

One inline comment incorrectly stated that it was for high accuracy and
moderate blurs. It was changed to moderate blurs and highly consistent
move times
Also, one case was a subset of another case with the same output.
Removing the more specific case results in no change in functionality.

Fixed inconsistencies in cheat detection

---

doc/sf-benchs

From a benchmark install upgrade from stockfish 5 to 6. Obviously not still being used if we're on stockfish 8

Created years ago and useless

---

ui/analyse/src/explorer/explorerCtrl.js
ui/analyse/src/explorer/openingXhr.js

Watkins proof trees do not support transpositions, so do not use the FEN as the cache key there.

fix transpositions in watkins explorer

---

ui/analyse/src/gameEnd.js
ui/tree/src/tree.js

Found by @isaacl:
> analysis board is detecting checkmate even though it's not.  but when I import the position into a study or as a fresh pgn, it calcuates the move as normal
>
> ![image](https://cloud.githubusercontent.com/assets/402777/23201927/13b16c98-f8dc-11e6-8174-85b73f9c264f.png)
> https://en.lichess.org/jXTPa1HQ/black#32 in the computer line
The difference is that there is a fishnet pv in the original game and drop information did not get merged properly with the existing nodes.
Also removes the unused `gameEnd.js`.

fix zh game end in fishnet pv

---

public/stylesheets/study.css

Slightly lower the study overboard in order to prevent it from overflowing

---

public/stylesheets/home.css

Before: <img width="1087" alt="screen shot 2017-02-28 at 12 04 14 am" src="https://cloud.githubusercontent.com/assets/542245/23393617/af2c9dd4-fd49-11e6-8900-05f0d6ab66f5.png">
After: <img width="1075" alt="screen shot 2017-02-28 at 12 04 02 am" src="https://cloud.githubusercontent.com/assets/542245/23393619/b09ceb1a-fd49-11e6-81f7-77ad2f12136b.png">

Slightly lower game config overboard so it doesn’t overflow when setting up a game from a position.

---

ui/analyse/src/ctrl.js
ui/ceval/src/ctrl.js
ui/ceval/src/pool.js
ui/ceval/src/view.js

The binary format for WebAssembly `0x1` has been frozen. [Support will arrive in mainline browsers soon](https://lists.w3.org/Archives/Public/public-webassembly/2017Feb/0002.html). Until then it can be seen in nightlies of Firefox and Chromium.
The build only differs in flags and a small wrapper, otherwise it uses the same code adjustments as stockfish.js.
&nbsp; | ASMJS | WASM | PNacl
--- | --- | --- | ---
file sizes | 1140K | 476K + 164K [1] | **484K**
gzipped | 260K | **144K + 44K** | 412K
[1] The wrapper script will become smaller in the future.
In terms of speed WASM beats ASMJS several times over. PNaCl is still 5-10% faster. More importantly WebAssembly does not yet support threading, so if available PNaCl will be preferred for a while. This also means WASM requires the same hack …

add webassembly support for ceval

---

README.md

Adding the missing `/api` to `curl --data "legend,lovlas" 'https://en.lichess.org/users'`

Fixing an incorrect URL example in README

---

public/javascripts/main.js

- Record end time instead of remaining seconds.
This avoids drift when callbacks are slower than expected.
- Clean up formatting. Don't pad leading unit with zeros.

Clean up countdown clock

---

public/javascripts/main.js
ui/tournament/src/sound.js

- Round countdown clock to nearest second instead of truncating millis
This better aligns with countdown sounds which are also rounded.
- Call Howler functions to resume WebAudio context.
Use this 'warmup' for tourney countdown to ensure smooth start.
- General cleanup (new Date().getTime()  -->  Date.now())

Countdown tweaks

---

app/controllers/Mod.scala
app/views/user/mod.scala.html
conf/routes
modules/hub/src/main/actorApi.scala
modules/mod/src/main/ModApi.scala
modules/mod/src/main/Modlog.scala
modules/mod/src/main/ModlogApi.scala
modules/security/src/main/Permission.scala
modules/user/src/main/Env.scala

Use case: yesterday I wanted to kick opperwezen's second account from the Top 10 because he had two accounts there. I had no proper way to do this, so I had to mark as booster and immediately as un-booster to trigger rankingApi.remove.
This new 'Kick from ranking' button will trigger rankingApi.remove to exclude a user from the next ranking calculation (because by my observation, .remove does not invalidate the cache, and I suppose that's by design).

Allow mods to kick a user from rankings

---

ui/site/gulpfile.js

Previously the build was failing with:
```
[13:24:11] Building without AB file
[13:24:11] Using gulpfile ~/Projekte/lila/ui/site/gulpfile.js
[13:24:11] Starting 'jquery-fill'...
[13:24:11] Starting 'ab'...
[13:24:11] 'ab' errored after 160 μs
[13:24:11] Error: Invalid glob argument: undefined
at Gulp.src (/home/niklas/Projekte/lila/ui/site/node_modules/vinyl-fs/lib/src/index.js:20:11)
at Gulp.<anonymous> (/home/niklas/Projekte/lila/ui/site/gulpfile.js:24:15)
at module.exports (/home/niklas/Projekte/lila/ui/site/node_modules/orchestrator/lib/runTask.js:34:7)
at Gulp.Orchestrator._runTask (/home/niklas/Projekte/lila/ui/site/node_modules/orchestrator/index.js:273:3)
at Gulp.Orchestrator._runStep (/home/niklas/Projekte/lila/ui/site/node_modules/orchestrator/index.js:214:10)
at …
```

fix ui/site gulp build without ab file

---

bin/prod/compile-client
ui/site/gulpfile.js

* My previous noop() was actually silently failing.
* `bin/prod/compile-client` needs `bash`

Fixup site build

---

public/stylesheets/mobile.css

mobile.css: fix list style for long bullet points

---

ui/round/src/blur.js
ui/round/src/ctrl.js

Track 'focus' event instead of blur, and only count
blurs which include a focus at least 1s after
opponent moves.

Improve blur detection

---

modules/i18n/src/main/LangList.scala

"Cymraeg" is the correct translation of Welsh.

Correct translation of Welsh

---

.gitignore
.gitmodules
ui/ceval/src/ctrl.js
ui/site/gulpfile.js
ui/site/package.json

Now we have automated builds for `stockfish.pexe` and `stockfish.js/wasm`. Travis CI attaches the files to the release tag, so the binaries are kept out of Git history :tropical_fish: 
The automatically built `stockfish.nmf` and `stockfish.wasm.js` use SHAs in the internal URLs, so we don't have to manually increment the versions.
I suggest downloading them using a gulpfile.

download ceval sf from github releases

---

ui/analyse/src/crazy/crazyView.js
ui/analyse/src/ctrl.js

The signature of sendMove recently changed and now takes a captured
piece as the third argument. Call it accordingly.

fix playUci for underpromotions (closes #2822)

---

modules/common/src/main/Centis.scala

Let's have some more utilities. The clocktimes-v2 tests need them.

make Centis ordered and provide abs

---

modules/game/src/main/BSONHandlers.scala
modules/game/src/main/Game.scala
modules/game/src/main/GameDiff.scala

Properly calculate if the current color's last move
had inc applied, which affects movetime calc.

Fix movetime calculations for games with inc

---

.gitmodules

I cant find any module that uses this now. For example in learn it is installed from `github:ornicar/chess.js#learn` instead.

remove chessli

---

public/javascripts/chart/movetime.js

This change moves the plot, avoiding the concave
section of the curve. There's a bunch of free params
so it's hard to find the right balance but I think
this is an improvement...
blue = current, red = new.

movetime chart: translate to improve 1s moves

---

modules/playban/src/main/model.scala

Increase max playban to 18hrs -- this won't be reached without
repeated violations.
Degrade penalty slowly instead of resetting after 3 days.

Increase max playban and degrade slower

---

modules/playban/src/main/PlaybanApi.scala

A blameable NoPlay should be very rare for a considerate
player, seems reasonable to ding people's completion rate
if they do this a lot.

Record incomplete game for NoPlay sits

---

modules/hub/src/main/actorApi.scala
modules/relation/src/main/OnlineDoing.scala
modules/relation/src/main/RelationActor.scala
modules/study/src/main/StudyApi.scala
modules/study/src/main/actorApi.scala
modules/studySearch/src/main/Env.scala

1. It didn't disappear on study deletion. Now it does.
2. If you were watching a study (as a Member without contributing power) and were added as contributor, it did not make the friend study icon disappear (because online.isStudying would only work if you already were a contributor). This is fixed now.

Two fixes related to study icon

---

modules/tournament/src/main/Schedule.scala
modules/tournament/src/main/TournamentScheduler.scala

This replaces the 5+0 hourly, which is unpopular. Multiple
blitz speed crazyhouse tournaments remain, including the 5+0
daily, and the 4+2 hourly.

Create a 2+0 crazyhouse hourly

---

modules/tournament/src/main/Schedule.scala

For Hourly Variant tourneys, drop the word 'Hourly'
and instead include the time control.

Include time control in variant tourney names

---

modules/tournament/src/main/Schedule.scala
modules/tournament/src/main/TournamentScheduler.scala

Because Hippos are large, or as a more memorable
misspelling of the hypo prefix.
Thanks to lightsss for thinking up this cute name.

HippoBullet, the 2+0 time control

---

bin/prod/wsmon-away.js
ui/analyse/src/study/studyForm.js
ui/ceval/src/stockfishProtocol.ts
ui/ceval/src/types.ts
ui/chat2/src/moderation.ts
ui/common/src/throttle.ts
ui/site/src/ackable.js
ui/site/src/main.js
ui/site/src/socket.js
ui/site/src/util.js
ui/tournament/src/xhr.js
ui/tournamentSchedule/src/view.js

Date.now() is faster and more readable when
used in arithmetic. Remove safari workaround fixed by
niklasf/stockfish.js#4

Replace 'new Date()' with 'Date.now()'

---

app/views/analyse/replay.scala.html
app/views/analyse/replayBot.scala.html
app/views/round/watcherBot.scala.html
public/stylesheets/analyse.css

For some reason FF was ignoring the double `<br>` between headers and movetext: https://github.com/ornicar/lila/issues/2989#issuecomment-298311623

fix pgn line breaks in firefox (#2989)

---

modules/study/src/main/PgnDump.scala

How about making the `Annotator` a URL like this?

[SUGGESTION] make default study annotator a url

---

modules/game/src/main/PgnDump.scala

`Round` is one of the seven mandatory PGN tags. Let's provide it for imported games (including games from the opening explorer).

provide round to complete seven tag roster (#2989)

---

app/controllers/Editor.scala
app/controllers/UserAnalysis.scala
modules/common/src/main/String.scala

1. open a three-check analysis board: https://lichess.org/analysis/threeCheck
2. try to edit the check counts in the fen input field
3. press enter
`java.net.UrlDecoder.decode` decodes the `+`-signs to spaces, parsing fails and the check counts are reset to `+0+0`.
` play.utils.UriEncoding.decodePath` is the right decoder.

fix double decoding of 3check fens

---

modules/game/src/main/Game.scala

Fixes this issue: On the crazyhouse analysis board, paste a fen with a pocket like
```
rnbqkbnr/pppp1ppp/8/4N3/8/8/PPPPPPPP/RNBQKB1R/P b KQkq - 3 2
```
The import works but the PGN is displayed as:
```
[Variant "Crazyhouse"]
[FEN "rnbqkbnr/pppp1ppp/8/4N3/8/8/PPPPPPPP/RNBQKB1R/ b KQkq - 0 2"]
```
(i.e. without the pocket)

remember crazyhouse pockets when pasting fens

---

app/controllers/Practice.scala
app/controllers/Study.scala
modules/api/src/main/RoundApi.scala
modules/round/src/main/JsonView.scala

Fixes the following issue: On the analysis board paste a PGN like:
```
[Variant "Crazyhouse"]
[FEN "rnbqkbnr/ppp1pppp/8/3P4/8/8/PPPP1PPP/RNBQKBNR/P b KQkq - 3 3"]
3. e6
```
It mostly works, but the `initialFen` in the analysis JSON is sent as the standard starting FEN.
The PGN is then incorrectly displayed as:
```
[Variant "Crazyhouse"]
3... e6
```
---
There is also an opportunity to refactor things, because `userAnalysisJson` no longer has to be a future. But it's probably best to keep this PR small.

fix pasting of variant pgns with fen tag

---

ui/round2/src/blur.ts

Count move 0 focus as a blur if it occurs more than 10s after game starts.

catch first move blur

---

public/javascripts/keyboardMove.js

This change works on my lila instance, allowing `Bxc4` to be different from `bxc4`.

Allow SAN moves to be case-sensitive or case-insensitive. Fix #3035

---

ui/round2/src/promotion.ts

See #2839 for a detailed description of the issue.

fix pre-promotions interrupted by opponents move (closes #2839)

---

public/stylesheets/fpmenu.css
ui/site/src/main.js

- Remove blurriness from anon sign in fpmenu
- Load fpmenu only once - this avoids duplication of dom generated by mouseover and click. Duplicate dom is visible with current  styles when you have browser size less than 970px

Blurriness and duplication of fpmenu

---

app/views/auth/login.scala.html
app/views/auth/signup.scala.html

It seems the GET parameter `referrer` is used instead.

remove unused _referrer fields

---

translation/source/site.xml

So it appears like a number again. This was decided on Slack for stuff like "%s" forum post because "One forum post" broke the links a bit, and I believe it makes most sense to use the number 1 consistently.

Translation source: replace 'One' with '%s' parameter

---

bin/trans-dump.js
modules/i18n/src/main/I18nKeys.scala

Having this date will cause merge conflicts every time. We should use Git to look it up, if needed.

remove date from trans dump

---

modules/i18n/src/main/SubdomainKiller.scala

Does not matter a lot, but I saw some exceptions when `Host` was empty in my dev env.

use safe string indexing in SubdomainKiller

---

ui/round/src/blur.ts
ui/round/src/ctrl.js

If a user reloads the page during their move after
move 1, count it as a blur.
This fixes #3075.

Track page reloads as blurs

---

ui/round/src/ctrl.js
ui/site/src/socket.js

Previously they were usually 0s unless a player was
on a slow computer.
We were using Math.floor to ensure premoves were usually
0 time, but now that they're special cased, use Math.round
for conversion instead.

Hard code premoves to 0s client time.

---

app/controllers/LilaController.scala
app/controllers/Main.scala
app/views/base/authFailed.scala.html
modules/common/src/main/mon.scala
public/stylesheets/authFailed.css

The current 403 page returns a plain "no permission" text, this change adds a
styled 403 page to match the 404 page. Related to #2225
I tried to emulate the `notFound` function, but have a feeling it came out wrong? 😅
```scala
def notFound(implicit ctx: Context): Fu[Result] = negotiate(
html =
if (HTTPRequest isSynchronousHttp ctx.req) Main notFound ctx.req
else fuccess(Results.NotFound("Resource not found")),
api = _ => notFoundJson("Resource not found")
)
```
* There's no mini-game embedded on this.

Add a styled unauthorized page (403)

---

modules/game/src/main/Event.scala
ui/round/src/clock/ctrl.js

- change server value to centis, which is what js was expecting and
the accuracy is useful.
- filter lagEst key if it's 0.
- js lag default of .01s.

Fix lag estimate code

---

modules/tournament/src/main/TournamentScheduler.scala

- more hyperbullet and ultrabullet hourlies
- stagger thematic tourneys and cycle through featured
opening list consistently.
Fixes #3171

Update tourney schedule

---

app/templating/UserHelper.scala
app/views/game/widgets.scala.html
app/views/user/show.scala.html

Everywhere except ui/round and left sidebar. (These can also be done, but might be more controversial since the titles are quite bright, especially in the dark theme.)

consistently highlight player titles (#2864)

---

ui/editor/src/chessground.js

It seems to be `1` in Firefox, even for `mousemove` events.

avoid using e.which in board editor (fixes #3135)

---

ui/dasher/src/board.ts

I think changing 2d/3d is rare enough to warrant a page reload. Alternative ideas:
* Add an event to globally upgrade chessgrounds to `addPieceZIndex`.
* Try and optimize `addPieceZIndex` so that it can be always on. But there's probably some unavoidable cost.

reload to apply 3d (fixes #3049)

---

app/views/account/layout.scala.html

Makes sure the Patron link is more visible in the /account menu

Highlight Patron link in the /account preferences menu

---

modules/game/src/main/Namer.scala
ui/round/src/view/user.ts

Consistent title highlighting for ui/round. I had skipped this in #3188. You can check if it's too bright or good on stage.

highlight titles in sidebar and round (fixes #2864)

---

modules/shutup/src/main/Analyser.scala
modules/shutup/src/main/Dictionary.scala
modules/shutup/src/test/AnalyserTest.scala

English suffixes -s, -d, -es, -ed, and -e (typo of -es/-ed) are common.
Code golfed dictionary a little bit.

Add more English profane plural and -d/-ed suffixes

---

project/BuildSettings.scala

In sbt 1 Project.apply will only take 2 parameters.

Use less of Project.apply

---

modules/irwin/src/main/Env.scala
modules/irwin/src/main/IrwinApi.scala
modules/user/src/main/Cached.scala

Since [we no longer prioritize tournament requests over leaderboard requests](6b5247bafdbde96052194d7defb91470becab3ba), for performance reasons let's consider filtering leaderboard requests based upon online players rather than based upon all leaderboard players.

Do not generate leaderboard assessments for offline users [RFC]

---

app/controllers/Mod.scala
app/views/user/mod.scala.html
conf/routes
modules/mod/src/main/ModApi.scala
modules/mod/src/main/Modlog.scala
modules/mod/src/main/ModlogApi.scala
modules/report/src/main/ReportApi.scala
modules/security/src/main/Permission.scala
modules/user/src/main/User.scala
modules/user/src/main/UserRepo.scala
public/stylesheets/user-mod.css

Based on recent discussion in #tavern. Paranoid members aren't always abusive, and abusive strong players may still make good reports. A 'reportban' is like a shadowban except it only affects reporting, and with this pull request, shadowbans no longer affect someone's ability to report.
This pull request consists of 3 commits: please see their full commit messages to see what they do exactly.

Add mod action 'reportban'

---

app/templating/ForumHelper.scala
app/templating/UserHelper.scala
app/views/forum/topic/form.scala.html
app/views/forum/topic/show.scala.html
app/views/qa/answerList.scala.html
app/views/qa/questionShow.scala.html
modules/forum/src/main/CategApi.scala
modules/forum/src/main/DataForm.scala
modules/forum/src/main/Post.scala
modules/forum/src/main/PostApi.scala
modules/forum/src/main/TopicApi.scala
modules/qa/src/main/DataForm.scala
modules/qa/src/main/QaApi.scala
modules/qa/src/main/model.scala
public/stylesheets/common.css

Closes #754. Closes #1092. Partial #931.
This is possible for forum posts (also the first post of a topic) and Q&A
answers (not questions, because that doesn't seem useful at all).
Above the 'Submit' button, there is a checkbox to tell if you want to
display a moderator icon next to your name.
If a non-PublicMod tries to add this checkbox himself, the `modIcon`
Option[Boolean] is still set to None and no icon will appear.

Option for public mods to display icon in forum/qa

---

app/views/mod/inquiry.scala.html
public/stylesheets/inquiry.css

Usually when someone is reported for cheating, it's related to games they played with the reporter. This will let mods quickly find those games even if they're not explicitly linked in the report.

Link to games between reporter and reportee in inquiry bar

---

app/views/tournament/enterableTable.scala.html
public/stylesheets/home.css
ui/site/src/main.js

A step towards #3218. Idea: Use color to encode tournament ratedness (which seems to be the only usage of the `trans_me` hack).

[RFC] avoid global translations using trans_me

---

modules/common/src/main/Maths.scala
modules/game/src/main/Event.scala
modules/game/src/main/JsonView.scala
modules/perfStat/src/main/JsonView.scala
modules/slack/src/main/SlackApi.scala

This is safer and more efficient than truncating
doubles and hoping the result is representable.

Use BigDecimal for json precision

---

modules/round/src/main/TreeBuilder.scala

Use clock limit instead of first value from clock history.
Fixes #3326, fixes #2943 and improves #2954.

Fix initial analysis clocks

---

modules/shutup/src/main/Dictionary.scala

"negro" is Spanish for "black", causing at least one false positive I've seen appear a few times in the report queue, in the context of black pieces.
I don't remember seeing a true positive for this keyword, so we can consider removing it.

Remove 'negro' from shutup dictionary

---

modules/round/src/main/Player.scala

During lag comp rewrite the AI lost its hard coded lag
adjustment, making it easier to flag. Give it back some
lag comp, hard coded to .05s per move.

Restore AI lag comp

---

public/stylesheets/board.css

Idea: Also hide the logo and user menu on devices that can hover (most likely with a mouse). On touch screens this would probably not be a good idea, because users could get stuck in Zen mode.

complete zen mode (closes #3301)

---

app/views/tv/index.scala.html

we have this translation key that's unused so far but available for lots of languages. only downside is that it does not mention the channel name

use previouslyOnLichessTV translation key

---

modules/user/src/main/Countries.scala

Also note that Monaco's ISO 3166 two-letter code is "MC", which is included in the pull request.

Add Monaco to countries list

---

ui/ceval/src/ctrl.ts
ui/site/src/util.js

Reduce processing and arrow draw rate to 500ms, using leading edge throttling.
This throttling reduces redraw during piece animation (when navigating analyze with arrows, for example), and ensures evals stay visible for at least 500ms to make the display feel more solid.

Improve ceval emit throttling

---

public/stylesheets/material.form.css

Make material dark theme <option>s more readable on FireFox

---

public/stylesheets/user-show.css

Removing this line properly wraps text in my Chrome (Chromebook).

Fix #3553 Use normal word wrap for user notes

---

modules/simul/src/main/SimulApi.scala
modules/simul/src/main/SimulPlayer.scala

In simuls, the displayed ratings for blitz or classical controls can be inaccurate. [For example](https://lichess.org/simul/f6MLFfr7) the game widgets show classical ratings (which are often 100-200 points higher than blitz ratings), even though it is a blitz simul. In the candidates list, it [displays blitz fire icons](https://youtu.be/aNdwh1FbHw0?t=6474) instead of the classical hourglass icons.
So in blitz simuls, classical ratings are displayed, and also in some instances blitz ratings are shown in classical simuls. I think both of these cases can be misleading/confusing to the host and players, so I attempted a code fix to separate blitz and classical cases from each other.
Apologize ahead of time for inexperience with lila and scala, but very happy to contribute to this amazing …

Fix/update simul rating display. Fixes #3185

---

ui/round/src/clock/clockCtrl.ts
ui/round/src/ctrl.ts
ui/round/src/interfaces.ts
ui/site/src/socket.js

Send lag when clock is not running to
improve lag estimates for move 1.
Send lag position when move timer isn't
trusted to still given user a bit of comp.

Send lag est in some circumstances

---

ui/ceval/src/pool.ts
ui/site/src/util.js

Keep the storage perf fix, use a new value to ensure
listener gets triggered. The only other listener is
for ceval.fen and the same fen getting published twice
is unlikely to occur and might be a false flag anyway,
so the behavior of only triggering listener when value
changes is acceptable.

Better fix for ceval multitab toggle

---

public/stylesheets/team.css

Works in my Chrome 60.0 browser.  Hat tip: [Stack Overflow](https://stackoverflow.com/a/7410812).

Improve text wrapping of team description in team search

---

conf/base.conf
modules/security/src/main/CSRFRequestHandler.scala
modules/security/src/main/Env.scala

Reviewing the CSRF handler after months and months of monitoring:
* There should be no need to disable CSRF protection *ever*.
* `isXhr` beeing safe gave me a break for a moment until I remembered the reason. Put a comment.
* Referer to Origin conversion is somewhat tricky and the regex has a performance problem due to backtracking found by @isaacl. It turns out we can just drop it anyway.
Once this is deployed and we got some more monitoring data, we can potentially flip the decision on missing Origin headers to a safer default.

simplify csrf handler

---

CONTRIBUTING.md

Some mobile-specific issues ([e.g.](https://github.com/ornicar/lila/issues/2923)) have been mistakenly opened here. Either CONTRIBUTING or README should indicate that they should be reported to the mobile app repo instead.

Link to lichobile in bug report instructions

---

app/views/user/mod.scala.html

Because it's both IP and Print. Putting both in there would make it a bit long though, so "similar user(s)" is shorter but accurate

Fix inaccurate "user(s) on these IPs"

---

build.sbt

Leave for test so that test compiles all projects and runs all tests.
This speeds up sbt run and sbt compile.

Disable sbt aggregation for most tasks

---

modules/playban/src/main/PlaybanApi.scala
modules/playban/src/main/model.scala

- save 30 outcomes instead of 20
- for players with long history, trigger with 12 bad outcomes
out of 30, instead of 10 bad outcomes in 20.
- reduce sitting cutoff to 5s per minute of initial clock.
- reduce initial playban to 10 min

Adjust playban cutoffs

---

public/stylesheets/user-show.css

`#3893E8` is the same link color used on the /mobile page. Closes #3768

Make links in notes more visible 

---

public/javascripts/confetti.js

Looks the same and uses about 25% less CPU at codepen.io.

Remove redundant divide-by-1 and multiply-by-1

---

modules/user/src/main/Links.scala

It seems like Twitch has made a full transition from twitch.com to twitch.tv so as a user, if I type http://www.twitch.com/chessbrah into my browser the end URL I copy and paste in would be https://www.twitch.tv/chessbrah since they automatically redirect users and their browser URL bar changes.
My reasoning is one of user experience, I'd suspect most people are just copying and pasting their URL right in, so using the correct ultimate domain seems to make the most sense, otherwise when I paste https://www.twitch.tv/chessbrah into lichess currently, it ends up rendering "www.twitch.tv" on my profile which is ugly compared to the expected "Twitch" output.
Please consider this pull request if this is the appropriate way to contribute.

Updated Twitch domain to match new format.

---

public/stylesheets/common.css

This fix re-introduces outlines for all button-classes. This is extremely important for accessibility.

Remove outline:0 to go back to default browser behavior

---

ui/dasher/src/board.ts

Make the zoom slider go in steps of 8px (1.5625%) instead of 5.12px (1%). This makes highlighted squares on the board pixel perfect *if there is no browser zoom*.
If we chose to apply this we would potentially revert it once we've got a subpixel perfect solution or another solution that works with browser zoom.
See also: https://github.com/ornicar/chessground/issues/51
cc @isaacl

scale board in steps of 8px

---

ui/@types/lichess/index.d.ts
ui/chat/src/enhance.ts
ui/learn/src/util.js
ui/site/src/util.js

https://jsperf.com/html-escaping
https://jsperf.com/html-escaping-2
https://jsperf.com/optimistic-html-escaping
- Remove duplicate escapeHtml implementations.
- Using the VDOM to escape is ~4x slower than chained regex
replacements.
- An optimistic check is very cheap even on long strings.

optimize escapeHtml

---

modules/rating/src/main/Glicko.scala

Before this change, the floor is only applied [before](https://github.com/ornicar/lila/blob/9c17d8702baa0fc6a049c6633322418ecd7de8d2/modules/rating/src/main/Perf.scala#L54) the rating adjustment, which means your rating can still end up <800 if you lose. This leads to weird inconsistencies like #1574

Apply rating floor after Glicko calculation

---

ui/round/src/promotion.ts

Horde has pawns on the last rank, and premoves would pass the first condition.

Fix horde promotion bug; closes #3997

---

public/stylesheets/board.css

@isaacl was reporting dropped frames when dragging pieces. @veloce found out the whole page is beeing repainted whenever `div.over` is changed.
Optimization idea: There is already a style for `most-dest:hover`, but it does not work for dragging because the piece will be in front of the move-dest. `pointer-events: none;` makes the piece transparent to mouse events, so now `div.over` is no longer needed. I confirmed with devtools that only the affected squares are beeing repainted.

use move-dest:hover instead of div.over

---

build.sbt
modules/common/src/main/base/PimpedPrimatives.scala
modules/mod/src/main/Env.scala
modules/mod/src/main/RatingRefund.scala

Cap refunds to 50 above best rating, and adjust
logic when current rating is higher than rating
during unfair game.
This closes #4073.

Adjust rating refund logic

---

conf/base.conf

return tick-rate to default 10s and add percentiles for histograms.

adjust kamon ticks

---

modules/shutup/src/main/Dictionary.scala

I got auto-insultreported for helping someone set up a Lichess bot - I guess that this line is better ignored now we have BOT accounts.

Remove "bot" from shutup dictionary

---

ui/ceval/src/stockfishProtocol.ts

This reverts commit 065d76e4a8bc281f2c8f90ab4be83bcb85117b03.
@ornicar Do you remember what this was about, and if you were seeing this in standard chess? `mate 0` seems to be intended at least in antichess (#4248).

Revert "ignore #0 at ceval client level"

---

ui/editor/src/chessground.js

When deleting a piece on the board editor while on a mobile device, e.srcElement maps to the entire chessground. It used to only map to an individual piece. This results in the entire chessground disappearing.
Reworked this to hide the current draggable piece, restoring the functionality.

Fix Piece Deletion for the Board Editor on Mobile Devices

---

public/stylesheets/tournament.css

Tested on desktop via devtools on both Chrome and Firefox with no issues.

Use SVG rather than PNG for 1st place tournament trophy

---

public/stylesheets/tournament_leaderboard.css
public/stylesheets/tournament_shields.css

The Community 'Tournament winners' & 'Shields' tabs are misaligned when active:
_(Bad)_
_(Good)_
Suggest setting the position of the main content box relative.
After the code is added:
_(Fixed)_
Tested on Chrome, Firefox, Edge

Misaligned tabs under Community

---

modules/user/src/main/TotpSecret.scala
modules/user/src/main/User.scala
modules/user/src/test/TotpTest.scala

jmh shows string formatters are ridiculously slow, accounting for about
half of the compute time. The hand coded toString compute is negligable
compared to the hash computation.
Also:
- use ByteBuffer to avoid some bit math.
- calc tokens as needed in verification function

Perf optimization for otp

---

app/views/base/layout.scala.html
app/views/mod/permissions.scala.html
public/javascripts/study/tour.js
ui/site/src/main.js

These onclick handlers were broken:
* Onclick of `#reconnecting` moved to `main.js`.
* Onclick of clear in `permissions.scala.html` moved into `@embedJs`.
* Fixed study tour, and removed an onclick handler there.

csp: replace inline onclick handlers

---

ui/build.bat

1. preceed yarn command with call to avoid it exiting the script
2. pass the non-interactive flag to yarn instead of the compiler

fix windows ui build script

---

app/controllers/Team.scala
app/views/team/changeOwner.scala.html
app/views/team/edit.scala.html
app/views/team/showContent.scala.html
conf/routes
modules/mod/src/main/Modlog.scala
modules/mod/src/main/ModlogApi.scala
modules/notify/src/main/BSONHandlers.scala
modules/notify/src/main/JsonHandlers.scala
modules/notify/src/main/Notification.scala
modules/security/src/main/Granter.scala
modules/team/src/main/Env.scala
modules/team/src/main/Notifier.scala
modules/team/src/main/TeamApi.scala
modules/team/src/main/TeamRepo.scala
ui/notify/src/renderers.ts

Functionality that I wished to have available a few months ago during some drama in a major variant team, and I finally got around to writing the code.
1. **Team owners can be changed by the team owner.** Owner changes are mod-logged.
2. **Admins have access to team settings.** All admin actions on teams (edit, kick, and owner change) are mod-logged. (Apparently SuperAdmins used to be able to access them already but now there's also a link to easily open it, and the permission level is lowered, which imo makes sense if logging is available, which it now is).
**Concern:** the "createdBy" field on Team now no longer necessarily indicates who created the team, as it was always used as the owner field as well. Can the createdBy field somehow be renamed to owner (with or without major database …

Team settings enhancements: change team owner + admin access

---

public/stylesheets/swag.css

The fix for [issue-4378](https://github.com/ornicar/lila/issues/4378).
I'm not very satisfied with the solution, because I use external CSS id name to overwrite default behavior and id name may be changed in the future by spreadsheets developers, and after that additional fix will be needed. But it may not happen at all :) 
@ornicar you have mentioned about iframes. Do you want to display the whole page or just a shop part?

fix we use cookies positioning over online friends

---

app/views/qa/ask.scala.html
app/views/qa/edit.scala.html
app/views/qa/questionForm.scala.html

Hi! I have added to qa form. (https://lichess.org/qa/ask)
Error message for capcha is not displayed on qa form.
Cancel button is under "Post or update your question"
**Note:** we use inline css margin-left:20px in many places. Probably we should define a class for all c"cancel" buttons :)

fix capcha error display and buttons aligment on qa page

---

modules/common/src/main/String.scala
modules/common/src/test/HtmlTest.scala
modules/forum/src/main/MentionNotifier.scala
modules/user/src/main/User.scala

Major performance speedups and much improved handling
of urls embedded in surrounded text. Combine url and @username
shorthand parsing to ensure they don't parse each other.
Many new test cases.

Rewrite lila URL parser

---

modules/tournament/src/main/Schedule.scala
modules/tournament/src/main/TournamentApi.scala

identity creates a lambda closure that has a gibberish toString
method, making it difficult to read the Plan case object.

Make plan.build optional

---

ui/@types/lichess/index.d.ts
ui/analyse/src/explorer/explorerCtrl.ts
ui/analyse/src/practice/practiceCtrl.ts

Currently if `node.tbhit` is `undefined` the tablebase was not yet queried. Now additionally set it to `null` if it was queried but failed. In that case recover by using ceval.
Also treat successful requests with unknown outcome as errors. This allows us to use the partially complete 7 piece tablebase today.

Tablebase robustness for practice

---

ui/site/src/socket.js
ui/site/src/util.js

- Use crypto library when available for better entropy
- Save sri across page reloads so server can eject old connection
faster.
Session storage is persisted across page reloads but individual to
each browser tab.

Better js sri generation

---

modules/tournament/src/main/Condition.scala
modules/tournament/src/main/Schedule.scala
modules/tournament/src/main/Tournament.scala
modules/tournament/src/main/TournamentApi.scala
modules/tournament/src/main/TournamentScheduler.scala

- Use actual durations when looking for conflicts with saved
tournaments
- Restrict overlap to require same minRating, maxRating and titled
entry conditions
- Misc optimizations

Tournament scheduling rewrite

---

modules/evaluation/src/main/Assessible.scala

too many 1+0 games getting evaluated as :( or >:( because of this. so let's only keep that for games slower than 1+0, where it actually is useful

disable highly consistent move time/streaks to 1+0

---

app/views/base/form/checkbox.scala.html

There is a problem with checkboxes. They always unselected because we insert "checked" as a string to html. Will fix search.

fix checked ability

---

modules/evaluation/src/main/Statistics.scala

Had a chat with isaac about this today. This could be the reason for the many bullet false positives. At least it's not needed for blitz and slower (and could even be harmful if you play very fast in Blitz).
This might allow for re-enabling of bullet high consistency mt detection later, but more testing on that will be needed.

Up all values by 0.1s instead of 0.5s

---

modules/evaluation/src/test/StatisticsTest.scala

#4555 broke this test case - which is actually fine because the algorithm just got a bit stricter

Fix StatisticsTest

---

app/controllers/UserAnalysis.scala
modules/challenge/src/main/Joiner.scala
modules/game/src/main/Game.scala
modules/game/src/main/IdGenerator.scala
modules/game/src/main/NewGame.scala
modules/importer/src/main/DataForm.scala
modules/importer/src/main/Importer.scala
modules/lobby/src/main/Biter.scala
modules/pool/src/main/GameStarter.scala
modules/round/src/main/Rematcher.scala
modules/setup/src/main/AiConfig.scala
modules/simul/src/main/SimulApi.scala
modules/simul/src/main/SimulPairing.scala
modules/tournament/src/main/AutoPairing.scala
modules/tournament/src/main/Pairing.scala
modules/tournament/src/main/Player.scala
modules/tournament/src/main/arena/PairingSystem.scala

Introduce a wrapper `NewGame` around newly created games. In places:
* where we don't care get the underlying game with `sloppy (NewGame => Game)`
* where we want a unique id use `withUniqueId (NewGame => Fu[Game])`
* where we have an externally generated id use `withId (NewGame => Game)`

Prevent game ID collisions (closes #4300)

---

modules/game/src/main/IdGenerator.scala
modules/game/src/main/Player.scala

Player id collisions are also expected to happen regularly: Keyspace is only 58^4 = 11 316 496. As far as I know this is only relevant if it happens on the same game, so we can use a trick to prevent collisions: Make the ID depend on the color.

prevent player id collisions

---

modules/evaluation/src/main/Assessible.scala

They don't appear to be useful at all, but they can still color a dot orange in Display.scala.

Get rid of moderate move time streaks

---

modules/report/src/main/ReportScore.scala

Because posting a link is now required. However automatic cheat/boost reports should still be amongst the top-scored reports (which would before be ensured by this textScore) so now they just get a 20-point bonus.

Remove textScore in ReportScore

---

modules/common/src/main/base/RawHtml.scala
modules/common/src/test/RawHtmlTest.scala

Links suggest to the user that additional information is available
by clicking through. But on expanded images, the link goes to the
exact same content as the inline image. So instead the user has to
remember that image links aren't going somewhere helpful.
Users can still right click -> view image to get to the image.

Don't linkify expanded images.

---

public/stylesheets/dasherApp.css
ui/dasher/src/dasher.ts
ui/dasher/src/links.ts
ui/round/src/ctrl.ts

PR for issue https://github.com/ornicar/lila/issues/4580
Here I change dasher on toggleZenMode via jquery. 
I am little bit worrying about _userLinks(): VNode._ 
It is not a good thing to change via jquery, if it works like React virtual dom.
The main **purpose of PR** is to discuss the main question. Do we need an active state of this user menu toggle item? It seems that menu is not displaying when in zen mode and not playing users don't see it.

change dasher zen mode item on zen mode toggle

---

app/views/base/layout.scala.html
public/stylesheets/board.css
public/stylesheets/common.css

fix https://github.com/ornicar/lila/issues/4468
make display: none in zen mode more explicit (we can make it implicit by defining additional rules for '#reconnecting and #network_error selectors', but for me, explicit is better)
remove unnecessary css and html class.
As always comments and questions are welcome.

fix #4468: display network error and reconnection status in zen mode

---

app/controllers/User.scala
app/views/user/perfStat.scala.html
public/javascripts/chart/ratingHistory.js
public/stylesheets/user-perf-stat.css

On each perfStat page, a rating graph is drawn for the specific perf (in the same color as its line on the complete profile rating graph). If there is no data for a certain perf, `lichess.ratingHistoryChart` will take care of hiding the assigned `<div>` as to not have a big white space on top of the perfStat page.
`ratingHistoryChart` also takes care of filtering out the non-perf lines -- this cannot happen on the server side because the rating graph cache contains all graphs.
See it live on stage (not anymore): https://listage.ovh/@/ProgramFOX/perf/threeCheck

Rating graph on perfStat page, closes #2425

---

public/javascripts/chart/ratingHistory.js

Colors are kept, but the styles are a bit adjusted.
Advantages:
* No more ambiguous lines in the rating chart (Bullet and Zh, Rapid and Ultra)
* Fixes #4615

Unique style for all perfs in chart

---

ui/editor/src/view.js

When a variant is selected on the board editor, the 'Continue from here' button is disabled, but it can still be clicked

Actually disable 'Continue from here' button

---

modules/tournament/src/main/DataForm.scala
modules/tournament/src/main/crud/CrudApi.scala
modules/tournament/src/main/crud/CrudForm.scala

When editing a tournament using the CRUD form, the variant selector would reset to 'Standard' because the option tags have the variant IDs as their value, whereas the CrudApi would pass the string keys. This adjusts the CRUD form to work with the IDs entirely.
Maybe related to #4592.

Tournament CRUD form: retain variant

---

modules/common/src/main/base/RawHtml.scala
modules/common/src/test/RawHtmlTest.scala

For links like https://en.wikipedia.org/wiki/Talk:Lichess: Let the trailing `:` not be part of the link, like on GitHub or Slack. `:` inside of URLs should be allowed.
cc @isaacl

do not linkify trailing colon (closes #4622)

---

ui/puzzle/src/moveTest.ts

Puzzles were accepting altCastles even when the piece that moved was not the king, leading to a position where no legal move was accepted (#4617).

use altCastles only for castling (fixes #4617)

---

app/controllers/Auth.scala

The status code change from 401 to 400 in a5053e2d41e717 is not compatible with mobile
(yet). It will be after veloce/lichobile#910.

partially revert a5053e2d41e717 to fix mobile 2fa

---

app/controllers/Analyse.scala
app/views/analyse/replay.scala.html
modules/fishnet/src/main/FishnetApi.scala
modules/fishnet/src/main/FishnetRepo.scala
modules/fishnet/src/main/Work.scala

I've been using the 'import' feature a bit recently ( https://lichess.org/paste ) for analysing games I've played against people in another chess program ( ssb-chess, if you must know - I'm not a traitor - honest! it's just a wee side project to explore the scuttlebutt stack :P.)
I've found it mildly irritating that when I click the 'Request a computer analysis' on the `/paste` page, I get redirected to the analysis page but the analysis isn't shown as being in progress until I refresh the page.
I believe this is because the `Analysis` controller checks to see if an analysis is *in progress* when rendering the analysis view ( https://github.com/ornicar/lila/blob/143e98d5b68e6bd6c472a14d6283930aa5346ae3/app/controllers/Analyse.scala#L36 ). This  is only the case if a fishnet worker has …

Bug fix: Analysis not shown as in progress until refresh after PGN import

---

conf/base.conf

I think enough clients have updated that we can reject analysis like https://lichess.org/forum/lichess-feedback/sawtooth-evaluation-back-again (that one was produced by fishnet v1.15.6
with Stockfish 2018-07-25 64 BMI2 Multi-Variant).

fishnet: require analysis contempt fix

---

bin/trans-sanity-check.js

Working prototype of the translation sanity check script asked for in #3453. 
I think it still needs some work, but I wanted to get some eyes on it as soon as possible.
What I have so far:
- Checks if "Lichess" and "lichess.org" are properly translated
- Checks if "O-O", "O-O-O", "%s", and "%1$s" (Also "%2$s", etc.) are properly translated
- Prints to the console if one of these conditions is not met. This behavior can be changed to return a list of incorrect terms or simply True/False, depending what we want

Create translation sanity check script

---

ui/round/src/clock/clockView.ts

Resolves https://github.com/ornicar/lila/issues/4556 by mentioning in tooltip that there is no increment in berserk mode.

Mention no increment with berserk mode

---

public/stylesheets/puzzle.css

Fixes https://github.com/ornicar/lila/issues/4445

Override rating canvas width for small screens

---

modules/game/src/main/Namer.scala

fixes bug where bot title formatting is incorrect

---

modules/puzzle/src/main/JsonView.scala
ui/puzzle/src/view/main.ts

Players can reference the move list to figure out piece locations (assuming a standard start position).
Currently deployed at http://dugovic.mooo.com/training/1

Enable blindfold mode for puzzles #4776

---

ui/site/src/main.js

Fixes #2864 
btw, I'm wondering why don't we use [template strings](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/template_strings)? It seems to me that it could make our code look more cleaner & easier to write (especially in multi-line expressions).

title label in user search results

---

ui/site/src/standalones/coordinate.js

The coordinate training overlay overlaps the chess board when the board is large.
Mouse events don't pass through the score, so in the screenshot above it's very tricky to click the C2 square.
The overlay will correctly reposition itself if you resize the board _while you are on the page_, but once you refresh the problem reappears.
There is an attempt to reposition the overlay in `coordinate.js` by emitting the `reset_zoom` event, but the [subscriber to this event](https://github.com/ornicar/lila/blob/3036e34154796f387027cc69c7ed03905303d6a0/ui/site/src/main.js#L450) is bound slightly later due to it being added in a `requestIdleCallback`.
This change just raises the event slightly later as well by also emitting in a `requestIdleCallback`.

Fix coordinate training overlay overlapping large boards

---

app/controllers/Practice.scala

I'm pretty sure StreamConfig is not the correct permission to change Practice configuration.
(After this, StreamConfig can just be removed, right? There don't seem to be any other uses, I think this permission comes from the time where all streamers were stored in that big list)

Fix permission in configSave in Practice controller

---

build.sbt
modules/history/src/main/HistoryApi.scala
modules/puzzle/src/main/Env.scala
modules/puzzle/src/main/Finisher.scala

Why?
---
I have been talking to @c-mac for a few weeks about adding a training line to the rating chart on the profile page. We looked back at issues and found that others had asked for the same feature (oldest one I could find was https://github.com/ornicar/lila/issues/77, but more recently https://github.com/ornicar/lila/issues/4540).
How?
---
Let me start off by saying I've never written any Scala before, so I am totally open to this being the wrong approach. I noticed that the rating chart drew from the history collection, and that it was already attempting to pull puzzle entries off of that table, but there were none! I'm not sure when that change got made, but since the infrastructure was all there I thought that the easiest way to make this change would be to write to the history …

Track training progress on rating chart

---

app/controllers/Account.scala
app/controllers/Auth.scala
app/controllers/Mod.scala
modules/common/src/main/model.scala
modules/common/src/test/EmailTest.scala
modules/mod/src/main/UserSearch.scala
modules/security/src/main/EmailAddressValidator.scala
modules/security/src/main/SecurityApi.scala

Split email normalization and validation and add some types to show where normalization happens. Just a refactoring, almost (see comments) no functional change.
Before:
```
EmailAddressValidator.validate: EmailAddress => Option[EmailAddress]
```
After:
```
EmailAddress.normalize: EmailAddress => EmailAddress // infallible
EmailAddressValidator.validate: EmailAddress => Option[Acceptable(normalized: EmailAddress)]
```
Related: #2509, #4877

split email normalization and validation

---

public/stylesheets/board.css

Possible and easiest fix for #4890 
If rematch button height is required to stay 54px, let me know :)

issues-4890: increase rematch button height to fix blinking

---

app/mashup/TeamInfo.scala
app/views/team/showContent.scala.html
modules/user/src/main/UserRepo.scala

Naive attempt to exclude users without `standard` perfs recorded from team's `Best players` section.
I'm not yet familiar with the codebase and not sure if this would be enough or more checks are needed. Like checking `Perf.latest` not to be older than some threshold or doing something similar to https://github.com/ornicar/lila/blob/master/modules/rating/src/main/Glicko.scala#L21
Please ping me if extra changes are needed here.
Refs #721

Ignore provisional ratings when displaying team's 'Best players'

---

ui/round/src/keyboardMove.ts
ui/round/src/plugins/keyboardMove.ts
ui/round/src/promotion.ts

Fixes #4621 
Keyboard inputs like `b8=Q` or `b8=N` will now be valid. A user can force the selection dropdown to appear by typing for example `b8` and then pressing `ENTER`.
Update: inputs like `axb8=B` and `cb8=R` now also work

Promotion keyboard support

---

modules/common/src/main/base/RawHtml.scala
modules/common/src/test/RawHtmlTest.scala

This change will allow users to make posts with giphy images on forums by supplying a link in any of these formats:
- https://giphy.com/gifs/some-optional-tags-TheGifID
- https://giphy.com/gifs/TheGifID
- https://media.giphy.com/media/TheGifId/giphy.gif
Fixes #4888

Make giphy images embeddable in forum posts

---

app/views/team/form.scala.html

This will also include global errors on the form for team creation. Now users will correctly by notified their chosen team name already exists.
Perhaps a better solution would be to not have this be a global error but a field error related to the 'team name' field.
Fixes #4958

Include global errors on team creation form

---

ui/common/css/vendor/chessground/_chessground.scss

This fixes edge artifacts (at least at 4k) of the dot
Before
After

Improve move-dest dot

---

modules/security/src/main/SecurityApi.scala

n chosen such that (10 + 26 + 26)^n >= 2^128, as recommended by [owasp](https://www.owasp.org/index.php/Insufficient_Session-ID_Length)

session ids with 128 bits of entropy (fixes #5033)

---

public/oops/disabled.html
public/oops/scheduled-maintenance.html
public/oops/servererror.html
public/oops/timeout.html
public/oops/toomanyrequests.html

PR to address issue #5034 
This PR makes the nginx error pages (contained within public > oops) responsive using the viewport meta and css media queries, making them readable without zooming or scrolling. The queries also include some logic to hide the _Chess Pursuit_ game for when the display is not wide enough (in the case of mobile displays), but remains visible for tablet displays.

Make nginx error pages responsive

---

ui/speech/src/main.ts

Closes #5094.
Hacky fix to prevent a bug where SAN such as `R1e5` has its substring `1e5` being parsed by the `SpeechSynthesiser` as a number in scientific notation.

Fix text-to-speech bug 

---

modules/round/src/main/History.scala
modules/round/src/main/RoundSocket.scala

Add case classes to getEventsSince to make the function more
readable. This also prepares for additional monitoring and
other refactors.

Add types to round History

---

app/controllers/Dev.scala
build.sbt
modules/round/src/main/Env.scala
modules/round/src/main/History.scala
modules/round/src/main/RoundSocket.scala
modules/socket/src/main/Env.scala
modules/socket/src/main/Socket.scala
modules/socket/src/main/SocketTrouper.scala

- Create a new runtime setting for socket debug info
- When setting is active, bad VersionCheck messages will send additional
info. The client can then report this info together with their current
version. Client reporting not implemented yet, but will be a simple
GET or json post.

Add socket debug info

---

ui/round/src/title.ts

When a game is aborted, document.title is "Waiting for opponent" (doesn't matter whose turn it is). It should be "game over".
(I couldn't get lila to build - apologies if the change is wrong.)

Fix document.title when a game is aborted

---

modules/study/src/main/CommentParser.scala
modules/study/src/test/CommentParserTest.scala

This change allows users to import pgn with fractional seconds ` [%clk 0:09:59.45]`
fractional seconds are rounded to centiseconds
Fixes  #5074

pgn import to accept fractional seconds

---

ui/round/src/plugins/keyboardMove.ts

Sorry @niklasf , I lost this `clear();` between coding and testing iterations.  Adding it clears the input text.

Clear input after reading clock times (fix #5056)

---

modules/socket/src/main/Handler.scala
modules/socket/src/main/SocketMember.scala
modules/socket/src/main/SocketTrouper.scala
modules/socket/src/main/actorApi.scala

Improve our reconnect race bandaid. The first version
of the bandaid uses a boolean flag which might not have been
set yet, because the new Socket might be in a message queue
instead of fully initiated. With the first version, we could
end up queueing a Quit message that gets processed after
the socket is reconnected.
This version does the check on the actor thread.

Fix Quit data race

---

modules/round/src/main/History.scala
modules/round/src/main/package.scala

Switch underlying data structure from List to java ArrayDeque,
which allows fast insert and deletion from head. Store events
in chronological order, consistent with the order on disk.
This change allows us to remove a bunch of reverse() calls. Once
we upgrade to scala 2.13 we could migrate to scala's ArrayDeque.
The other motivation for this patch is that I would like to store
more Events (changing History thresholds), to give clients a
better chance to catch up, especially on popular boards. This means
the events list gets larger and the choice of data structure becomes
more important.

Store history events in ArrayDeque

---

ui/site/src/socket.js

Scala patch to follow. Our logging confirms this mechanism is not
needed or helpful.

Disable VersionCheck on client

---

modules/rating/src/main/java/glicko2/RatingCalculator.java

Rating deviation decay hasn't been working because the constant value was 0

Fix rd decay constant

---

modules/common/src/main/LameName.scala

https://www.adl.org/education/references/hate-symbols/1488

Add '1488' to LameName

---

app/controllers/User.scala
app/views/user/mod.scala
modules/playban/src/main/PlaybanApi.scala
modules/playban/src/main/model.scala

Not used for anything else than mod zone display at the moment, if the value seems usable then it can be used in the punishment code.
The counter gets +1'd if you disconnect or sit in a winning position (material imbalance >= 5) and -1 of you disconnect or sit in a losing position (material imbalance <= -5).
The idea is that abusers will get a highly negative score and people with an unstable connection will have a score around zero.

Keep track of what positions people tend to sit or disconnect in

---

modules/round/src/main/JsonView.scala

Fixes #4362
Because watcherJson doesn't have onGame data, spectators would always see the players as offline after a 'reload' event, such as a takeback.

Add onGame to watcherJson

---

ui/site/src/main.js

On Chrome, it sometimes (and irregularly) happens that the AudioContext is not allowed to start on the first sound. It has to be explicitly resumed after a "user gesture" (such as a click) on the page.
If we don't have any resume() calls, then a silenced Chrome page would just stay silenced. Attempting to resume whenever the AudioContext is suspended will ensure that a blocked AudioContext can still start after a user clicks on the page.

Resume Howler's AudioContext when suspended

---

ui/site/src/main.js

Fixes #5295
If Howler.ctx is undefined or null, just play the sound -- that was also the behavior prior to the introduction of the resume() call.

Only attempt to resume suspended Howler.ctx if it already exists

---

ui/chat/src/main.ts
ui/round/src/ctrl.ts

- add Escape to unfocus round chat
- don't bind esc/enter unless submit move is on.  this bind
breaks escape in the command box so avoid it when possible.
The escape added for chat is scoped to the container so will not
break other escape binds on the page

Keyboard shortcut fixes

---

app/views/mod/publicChat.scala
public/javascripts/public-chat.js

It has been broken for a while, since the $("#lichess") selector started returning null.
The #comm-wrap div is needed because not introducing a new element but using an existing one as replacement for $("#lichess") always resulted in a wrong layout after an auto-refresh. (The Git diff for publicChat.scala looks complicated but all it really does, is adding a #comm-wrap around #communication + reformat)
I'm seeing a Content Security Policy error every time .load happens. I don't think this is a big deal (everything works), but just mentioning it in case.

Fix auto-reloading of mod/public-chat

---

modules/tournament/src/main/Schedule.scala
modules/tournament/src/main/TournamentScheduler.scala

There have been over 50 of them now, all made official through the tournament manager - but manually. This commit automatically schedules Elite Zh arenas for every Saturday.

Automatic scheduling of elite crazyhouse arenas

---

modules/playban/src/main/PlaybanApi.scala

In all other variants, it's fair enough to use material difference for a rough win estimate. In Antichess or Horde, it makes little sense.

No sit counter for Antichess or Horde

---

ui/lobby/css/_box.scss

Changed the colour of the names of the open tournaments and open simul exhibitions to bold $c-font on the home page, and when you hover over them they become $c-link.

Changed the colour of the names of the tourneys and simuls on homepage

---

ui/round/src/crazy/crazyCtrl.ts

Watch for cases where focus shifts and we won't
get the keyup events. Cancel drop mode.
Yes, it's a hack.

Fix crazy drop mode getting stuck on

---

modules/evaluation/src/main/Assessible.scala

Anything caught by this line would be also caught by the line right below. I'm not an expert in cheating behavior, but also seems unlikely that all flags are true at once.

Remove redundant cheat assessment

---

modules/tournament/src/main/Schedule.scala

Reduce Daily and Eastern precondition to same as Hourly (15 -> 10)
Increase Weekend precondition to same as Weekly (0 -> 15)
I hope as cheat detection improves, preconditions can be reduced to make the site more friendly to new players.

Simplify Rapid game requirement preconditions

---

ui/lobby/css/app/_hook-list.scss

Currently, when hovering over the "Variants" subheading in the lobby hooks list, it shows the cursor as if it is a clickable link when it is not. This commit makes it so when hovering over the subheading, it shows the default cursor.

Make cursor the default when hovering variants title in the hook list

---

modules/playban/src/main/PlaybanApi.scala

A considerate player doesn't frequently abort or provoke their opponent (into aborting).
Unscheduled maintenance causing aborts should be infrequent.
https://lichess.org/forum/lichess-feedback/again-blocked-9-minutes-by-lichess-because-i-refuse-to-play-with-people-not-ending-their-games

Record incomplete game for Abort

---

ui/chat/src/discussion.ts

Work around ornicar/chessground#109.

Ensure chat loses focus on board click

---

modules/rating/src/main/Glicko.scala
modules/rating/src/main/Perf.scala
modules/user/src/main/RankingApi.scala

As @ProgramFOX points out, most players on the leaderboard already have an RD of 60.
Leaders who play like https://lichess.org/@/EpicEffects/search?perf=6 or https://lichess.org/@/Zaffelare/search?perf=11 (1 game per week against a much lower-rated opponent) or new accounts who boost like https://lichess.org/@/TheRacingApprentice will have to earn established ratings, just like anyone else on the leaderboard.

Reduce established (leaderboard) RD threshold

---

modules/study/src/main/StudyRepo.scala

Dollar sign probably accidantely removed in
https://github.com/ornicar/lila/commit/f2ba2bfd26c86c9f6e86a7f9a4e24c89d7b42101#diff-698058f35f5250d276e8b4172b5f43a2L182.

fix projection in countLikes

---

ui/ceval/tsconfig.json
ui/chat/tsconfig.json
ui/chess/tsconfig.json
ui/common/tsconfig.json
ui/game/tsconfig.json
ui/nvui/tsconfig.json
ui/tree/tsconfig.json
ui/tsconfig_module.base.json

Inline sources allows browserify to sourcemap
back to original typescript. If you add the ui
folder to chrome, you can then edit ts files
and set ts breakpoints directly in the browser!

Improve typescript sourcemaps

---

modules/rating/src/main/Glicko.scala

There was a reminder in Slack to "lower RD floor to 50". I don't really remember the context. Does this make sense to you, @cyanfish?

lower rd floor to 50

---

ui/lobby/css/_box.scss

Fixes the fact that the top of the Leaderboard and Tournament winners box is out of line with the rest of the box.

Fix leaderboard and winners box top text align

---

ui/analyse/css/_explorer.scss

This pull request removes unnecessary arguments from the "@include transition();" commands in the scss files.

Remove unnecessary transition args

---

ui/round/src/boot.ts

Currently, when ratings are updated dynamically (without refreshing) in the TV, the format of the updated ratings is different than the format generated by the backend.
E.g. check Rapid, Antichess, Bullet, and Bot ratings on the screenshots below:
Before refresh | After refresh
--- | ---
Note that I haven't tested if the PR actually works, but it seemed simple enough.. :smiley:

Fix ratings showing differently in TV when updated dynamically

---

app/views/site/faq.scala

Because Lichess is open-source, some users have created their own open-source sites based off aspects of Lichess. This pull request adds a question to the FAQ linking to examples of these derivatives.
I see two benefits for Lichess users:
- These sites _supplement_ Lichess features. Although they are not part of Lichess, they might nevertheless be useful to certain Lichess users. (For example, _Blitz Tactics_ takes Lichess puzzles, and adds additional timing options.)
- Programmers might be inspired to create similar sites based off Lichess if those sites would not fit the core theme of Lichess at present. (For example, other more esoteric chess variants.)
I do not think Lichess would be hurt by linking sites like these in the FAQ, or see a reduction in users. In the future, if more …

Add question to FAQ linking to Lichess derivatives

---

ui/site/src/main.js

Adds a space after "Anonymous" in the tournament watching chat list, so that instead of "Anonymous(1)" it becomes "Anonymous (1)"

Add space after anonymous in watching

---

ui/speech/src/main.ts

If the replace function is removed, the if statements for adding "check" and "checkmate" to the string are no longer required.  Also, changed "promotion" to "promotes to".  I thought "f8 promotes to queen" sounded better than "f8 promotion queen".
Sorry for so many edits to this file!  I hope this will be the last one it needs for a long time.

Updated renderSan()

---

ui/common/css/theme/_default.scss
ui/lobby/css/app/_app.scss
ui/lobby/src/view/realTime/filter.ts

This removes the filter numbers from the hooks list in the lobby and colours the settings icon as c-accent when there are games being filtered instead.

Remove filter numbers and colour the filter button icon instead

---

modules/analyse/src/main/Advice.scala

Hi guys. My name Abe, I love lichess, use it everyday, and I hope to become a contributor. This change I don't think is ready to go to prod yet. I have a few issues with my change that I was hoping someone with greater experience could answer:
1. I copied the winning chance formulas from ui into Advice.scala. This seems like the wrong place for them to be and also does not adhere to DRY (Do Not Repeat Yourself) principles. Would it be better/possible for the UI and Server to share the winning chance formulas somehow? Should the formulas be copied to somewhere else and imported?
2. I have not created automated testing for this change. I checked the project structure. There is no test package for the analyse module which is why I skipped making automated tests for the change. (Some modules …

server analysis determines judgements based on winning chances

---

ui/site/css/user/_sub-rating.scss

This pull request fixes the fact that the arrows in the sub-ratings list on the user page aren't animated when hovered while the sub-ratings icons are.

Fix the animation of the arrow in the sub-ratings list

---

ui/lobby/css/_box.scss

This pull request fixes the top of the box alignment, just like #5375 except this time it actually does what I said it would do.

Fix the top box alignment

---

ui/tournamentSchedule/css/_side.scss

On the tournamentSchedule page, titles are a darker colour due to the opacity being set to 0.7 for the title. It doesn't make sense for it to be like this, and it should be the same as it is everywhere else.

Makes the titles colour the actual colour of c-brag

---

app/views/setup/filter.scala
ui/common/css/abstract/_extends.scss
ui/lobby/css/app/_hook-filter.scss

This pull request styles the checkboxes. The before and after pictures are shown below. This only styles the checkboxes in the lobby hooks-filters because I couldn't find the other files which I needed to change (i.e. to style the "Show Chat" checkbox), but you only need to add
```scss
.checkbox-class {
@extend %checkbox;
}
```
to the CSS where `checkbox-class` is the class of the checkbox. Any changes to the styling you want, feel free to tell me and I can make the changes but for now I've just styled them how I would have them. P.S. the following "before" photos are system-dependent, due to them inheriting the system theme.
**Before**
**After**
**Before**
**After**

Style the checkboxes

---

ui/analyse/src/view.ts

When spectating a game from Black's point of view, going to analysis board and hitting "back to game" changes point of view to White.
Fix that.

backToGame orientation

---

modules/rating/src/main/Glicko.scala
modules/rating/src/test/GlickoTest.scala

This isn't the highest-priority ratings issue (perhaps tuning tau and/or volatility so it isn't so easy to hit the RD minimum might be a good idea), but seems easily understood:
A player who hasn't played any rated games in a year should have a provisional rating.  (We just reduced the rating floor from 60 -> 50 but this parameter wasn't updated.)

Inactive player should become provisional in 365 days

---

ui/lobby/css/_box.scss

My previous pull request regarding the alignment of the lobby boxes (#5414), while aligning the Leaderboard and Tournament Winners boxes, actually misaligned the Open Tournaments boxes. I have since worked out what the actual cause for the misalignment in the Leaderboard and the Tournament Winners boxes was (it was that the user-links had padding on the left) and now in this commit it is **actually** fixed.

Fix the box alignment without breaking other boxes

---

ui/tree/src/tree.ts

On the analysis board, if the first child of a node has `forceVariation`, this change allows "Promote variation" and "Make main line" to work as expected.

Allow a node with `forceVariation` to be promoted when it's first child

---

app/views/user/mod.scala
modules/evaluation/src/main/PlayerAggregateAssessment.scala

Currently averages in summary mod assessments can be based on very few games (in extreme cases even only one game) or games with very high variation. This may not be immediately obvious to an unsuspecting mod.
Adding simplistic normal-based confidence intervals is certainly better than the current state, even though
- assuming normality is fairly simplistic (as stated above)
- these values are confounded by variant and especially time control
so these numbers will still have to be interpreted with care.
Additionally, I admit to not having tested this code much, since my local lichess installation lacks users and games.

Add a simplistic normal-distribution based CI to mod assessments

---

ui/analyse/src/study/multiBoard.ts

3D miniboard piece offset looks wrong, for example https://lichess.org/broadcast/2019-fide-world-cup-round-2-tiebreaks-game-1/rJsuL3We

Apply 2D style to miniboard

---

modules/message/src/main/ModPreset.scala

By popular moderator demand. Purpose: for manual warnings when the counter was already under -10 before automatic warnings were added, and for variant players where the counter is disabled.

Update ModPreset to add stalling warning

---

modules/rating/src/main/Glicko.scala

Since a game has only 3 possible results (win, loss, draw), perhaps 15 significant digits are unnecessary.

Reduce Glicko.Result precision to 7 significant digits

---

ui/site/css/forum/_table.scss

If the browser zoom is over 100% (or using userstyles which affect font width), a 5-digit view count wraps the 5th digit to a successive line.
Looking at the commit history, I don't see why this `word-break` is useful.  I wonder if in some browser long subjects failed to word wrap?

Do not word-break view count

---

app/views/streamer/show.scala

There's just a dropped 's' in the uBlock Origin box on the left on the streaming page.

Fixed a single character error in streamer view.

---

modules/insight/src/main/PovToEntry.scala

There's already a cap because evaluations are clamped between -10 and +10. Clamping at 1000 makes ACPL in insights inconsistent with ACPL reported elsewhere on the site (#5617).
Not pushing directly, in case there was a deeper reason for https://github.com/ornicar/lila/commit/67fb0820e65542921c5661fbb3abd44295833cb4 (`insights: cap eval diff to 10 (so going from +10 to -5 is still 10)`).

remove cpl cap in insights (fixes #5617)

---

bin/trans-lint.py

Fixes: https://github.com/ornicar/lila/issues/5691. Adds rules for the following cases:
Error:
- leading newlines
Warning:
- leading whitespaces
- trailing whitespaces
- tabs
- double spaces
- more than one successive empty line

Add bin/trans-lint.py rules to detect invalid whitespaces

---

modules/rating/src/main/Glicko.scala
modules/rating/src/main/Perf.scala
modules/user/src/main/RankingApi.scala

Variant players in the feedback forum are getting unruly again... and while in my opinion having rating leaderboards is strange, also strange is featuring players who infrequently play (RD > 60 except for Rapid/Classical; perhaps also RD thresholds for Bullet and Blitz should be reduced?):
https://lichess.org/forum/lichess-feedback/unfair-behavior

Exclude inactive players from variant leaderboards

---

.gitignore
ui/ceval/src/ctrl.ts
ui/ceval/src/pool.ts
ui/ceval/src/types.ts
ui/ceval/src/view.ts
ui/site/gulpfile.js
ui/site/package.json
yarn.lock

It seems impossible to do reliable feature detection for PNaCl, now, leading to bugs like #5755 and #5729.
We could remove it and just be done with it.
(As of now, support would otherwise end January 29).

remove pnacl support (fixes #5755, fixes #5729)

---

public/javascripts/account.js
public/oops/diagnostics.html
ui/@types/lichess/index.d.ts
ui/analyse/src/study/chapterNewForm.ts
ui/analyse/src/study/interfaces.ts
ui/analyse/src/study/studyCtrl.ts
ui/analyse/src/study/studyXhr.ts
ui/ceval/src/ctrl.ts
ui/ceval/src/main.ts
ui/ceval/src/pool.ts
ui/lobby/src/boot.js
ui/lobby/src/ctrl.ts
ui/lobby/src/hookRepo.ts
ui/lobby/src/xhr.ts
ui/notify/src/ctrl.ts
ui/round/src/cevalSub.ts
ui/site/src/socket.js
ui/site/src/standalones/util.js

Safari sometimes fires the StorageEvent in the same document as well.
Move lichess.StrongSocket.sri to lichess.sri and use the unique id to
filter events.

make localStorage pubsub more robust (fixes #5832)

---

app/views/account/close.scala

I don't think that part is localized (yet?).
Seems to match the typo here:

Fix minor typo

---

app/templating/AssetHelper.scala
app/views/base/layout.scala
conf/base.conf
modules/common/src/main/config.scala
ui/site/src/socket.js

In order to use new failovers (https://github.com/lichess-org/sysadmin#websocket-failovers).
```diff
- socket.domain = "socket.lichess.org"
+ socket.domains = [ "socket.lichess.org", "socket1.lichess.org", "socket2.lichess.org", "socket3.lichess.org", "socket4.lichess.org", "socket5.lichess.org" ]
```
---

generalize to list of socket domains

---

app/views/site/faq.scala

This change keeps the FAQ in sync with constant **Glicko.rankableDeviation**.

Generate leaderboard deviation answer

---

modules/tournament/src/main/Duel.scala
modules/tournament/src/main/TournamentApi.scala

When the tournament ends with ongoing games they are never cleared from the DuelStore, effectively createing a memory leak: TournamentApi.finishGame does not select finished tournaments, and thus never calls duelStore.remove for those games.

Remove finished tournaments from the duelstore explicitly

---

app/views/msg.scala
modules/i18n/src/main/I18nKeys.scala
translation/source/site.xml
ui/msg/src/view/search.ts

Works in dev. I believe this is the only untranslated text in `/inbox`

translate /inbox UI, closes #5986

---

modules/security/src/main/DisposableEmailDomain.scala

Seems a legit domain per a [Yahoo help article](https://safety.yahoo.com/CA/SafetyGuides/Mail/index.htm): `Yahoo email address: Your Yahoo email address is your Yahoo ID followed by "@yahoo.ca."`
It could resolve the linked issue.

Whitelist yahoo.ca, for #5989

---

modules/common/src/main/model.scala

ProtonMail addresses are handled exactly like Gmail's (dots don't
matter, has support for the `+something`) so they can be
normalized in the same way.

Normalize ProtonMail addresses

---

modules/round/src/main/JsonView.scala

#6025 insists that on their tablet, there should be a way to disable square highlights in blindfold mode.  This seems complicated because there are views where a move list is not visible and moves aren't spoken, but a player could change their highlight preference...?
https://lichess.org/forum/lichess-feedback/highlight-bug-feature-by-thibault#8

Consider user preference when highlighting squares in blindfold mode

---

ui/tournament/src/view/finished.ts

This fixes #5866.
This is my first PR for Lichess! :tada: Let me know if I need to sign a CLA or something.
I was surprised that no tests for the UI are present. Maybe I just couldn't find them? Are they in a different repo? If not, I will consider making another PR to set up test infrastructure for the UI. I tested this manually, which was very tedious.

Remove Berserk Rate percentage from tournaments that do not allow berserk

---

app/views/stat/ratingDistribution.scala

This change adds the percentage sign in the rating distribution view, as mentioned in Issue #6072.
This way it matches the way the users percentile is shown in the users /perf/blitz view.

Added percentage sign for players percentile [Issue #6072]

---

ui/puzzle/src/view/side.ts

Probably a rare case, but with puzzle rating >2700 it starts being not unusual to solve a puzzle and gain 0 rating points. When that happens, there's no user feedback about the fact that the server updated your rating, unlike the normal case where you see the +5 or -25 show up next to your puzzle rating.
First contribution and I didn't see contribution guidelines on the README or the Wiki, so please let me know if there is anything I should do for testing etc. Thanks maintainers for the great project.
Edit: Ok found the contribution guidelines but I still didn't see much with regards to PRs haha

Show +0 rating change in puzzles

---

ui/common/css/vendor/chessground/_chessground.scss

fixes an issue with pr #6085 for issue #5776

adds !important to highlight a premoved square on low contrast boards

---

app/controllers/Export.scala
app/views/analyse/replay.scala
conf/routes
modules/game/src/main/GameRepo.scala
modules/game/src/main/GifExport.scala
modules/game/src/main/Pov.scala

I thought this was close, but hitting this:
Basically we'd substitute `Pov` instead of `Game`. For simplicity we could always pass the color in the URL even if white (i.e. `http://localhost:9663/game/export/gif/7drGFmRk/white.gif`).
Feel free to push more commits if you'd like, or I can address feedback.

Use Pov in GIF export, for #6102

---

modules/clas/src/main/ClasApi.scala
modules/rating/src/main/Glicko.scala
modules/rating/src/main/Perf.scala
modules/user/src/main/Perfs.scala
modules/user/src/main/UserRepo.scala

In many places in the existing code, there are ways to default the rating if it doesn't exist in the database. Many of them are inherently unaware of user attributes ([example](https://github.com/ornicar/lila/blob/master/modules/user/src/main/Perfs.scala#L215)) and thus we don't know whether to show standard defaults or student defaults. So I believe the best path forward is to write the default student ratings to the db when a student account is created.
I am only doing this for non-variants and for puzzle (the ratings that show up on the profile page).
Previously the code assumed rating was empty if `nb == 0` but I changed to `latest.isEmpty` and wrote a timestamp for the ratings I wanted to save to the db.
Things look ok in profile page, in game seeks, in a game, and rating update …

Force write class student initial ratings to db, closes #6100

---

app/templating/AssetHelper.scala
conf/base.conf
modules/common/src/main/config.scala

Mostly for `og:image` / `og:twitter`, because some clients (including Twitter itself) seem to have issues with protocol relative URLs.
:warning: New configuration variable `net.asset.base_url`, that needs to be set before deploy.

absolute (instead of protocol relative) asset urls

---

public/javascripts/signup.js

Calling `.submit()` directly skips validation (e.g. required fields).
PR, because I do not fully understand how reCAPTCHA works here.

do not skip signup form validation (fixes #6106)

---

modules/round/src/main/RoundDuct.scala

Ref. bug: https://github.com/ornicar/lila/issues/6067
Now lila will check if both players have moved before start the force resign counter. Tested in bullet, blitz, rapid, and classical tournaments. Does not affect normal games and challenges where the counter was not appearing anyway.

Start forceResign only if both players have moved

---

public/oops/diagnostics.html
ui/site/src/socket.js

Note: `tryOtherUrl` could randomly chose the same address again, but that should be fine.
---
:warning: Before deploy, we could move and test failovers first, while few people use alternative addresses.

connect to a random socket server and stick to it

---

app/views/study/bits.scala
ui/analyse/src/study/studyView.ts

Fix #6057
- Title in study list will be shown when hovering on overlay
- Title in study view will include chapter name.

Add study title

---

ui/round/css/_app-layout.scss
ui/round/css/_control.scss
ui/round/css/_icon.scss
ui/round/src/view/table.ts

Solves https://github.com/ornicar/lila/issues/5896
Changes the old order of: 
1. move list controls
2. [move list]
3. resign/draw/takeback buttons
4. **offers**
To:
1. move list controls
2. [move list]
3. **offers**
4. resign/draw/takeback buttons
Which stops the problem of accidentally clicking on resign when navigating the game without move list:
Also change the buttons size to make them full height. What's your opinion?
On mobile:

Re-order UI control panel in games to avoid abuse + tweaks

---

ui/@types/lichess/index.d.ts
ui/analyse/css/build/_analyse.base.scss
ui/analyse/css/build/_analyse.embed.scss
ui/analyse/src/ctrl.ts
ui/analyse/src/explorer/explorerCtrl.ts
ui/analyse/src/explorer/explorerView.ts
ui/analyse/src/explorer/explorerXhr.ts
ui/analyse/src/explorer/interfaces.ts
ui/analyse/src/socket.ts
ui/analyse/src/study/studyCtrl.ts
ui/analyse/src/view.ts
ui/chess/css/_opening.scss
ui/puzzle/css/build/_puzzle.scss
ui/puzzle/src/ctrl.ts
ui/puzzle/src/socket.ts
ui/puzzle/src/view/main.ts
ui/tree/src/tree.ts

This is a step towards replacing sockets with dests/moves computed on the client side. But how is opening information obtained without storing the entire dictionary on the client?
* Puzzles: Remove the opening box.
* Analysis: Fetch opening information from the explorer. This means it's only available when the explorer is used, so move the element in the UI to reflect that.

let explorer provide opening info

---

app/views/site/faq.scala

Currently the FAQ does not mention that the RD is different to apply for variants leaderboards, and variant players are misled and think there is a bug or that the FAQ is outdated:
https://lichess.org/forum/lichess-feedback/no-rank-in-chess960
https://lichess.org/forum/general-chess-discussion/why-do-i-not-have-an-rk-rank?page=1
This PR adds the missing information

Add RD requirements for variant leaderboards in FAQ

---

ui/chess/src/main.ts
ui/chess/src/ucicharpair.ts
ui/puzzle/package.json
ui/puzzle/src/ctrl.ts
ui/puzzle/src/interfaces.ts
ui/puzzle/src/main.ts
ui/puzzle/src/socket.ts
ui/site/src/main.js

Proof of concept: Handle puzzle socket on client side, to check if all required features are implemented in `chessops`.
Does not increase asset size, because chessops was already pulled in for ceval.
The current patch reimplements the socket communication exactly, including unnescessary serialization. Does not yet take advantage of the fact that dests are available synchronously.

client side puzzle socket

---

modules/tournament/src/main/Tournament.scala

This (or something like it) should help a lot to alleviate the spike of pairings and game page loads at exactly every full hour.
Edit: Checked that doing this for official scheduled tournaments does not lead to duplicates, because the scheduler checks for overlaps, not precise start time.

slightly randomize tournament start times

---

modules/api/src/main/LobbyApi.scala
ui/lobby/src/view/playing.ts

Instead of letting the time tick, check if the player has moved. Now it shows 'Your turn'.
Link to issue: https://github.com/ornicar/lila/issues/6260.

Prevent play timer ticking in lobby, when player has not moved

---

modules/tournament/src/main/TournamentScheduler.scala

This moves the weekly Chess960 tournament to Sunday since there isn't a weekly standard chess tournament on Sunday, and adds a weekly Three Check tournament on Monday.

Add Weekly Three Check

---

app/Env.scala

New developers would hit something like `Missing: base.conf @ file:/Users/gfinley/fun-repos/lila/target/scala-2.13/classes/base.conf: 69: No configuration setting found for key 'app.version'`.
I knew how to resolve because I saw your commit making this thing, but we should just let it be blank if this file doesn't exist. Adding a step to dev onboarding or some hack to add a dummy file that is later gitignored seems worse.

Silently allow missing app.version

---

app/views/team/admin.scala

At the current stage of lichess you have to copy the arena urls manually, when sending the All-PM. I think it is an improvement to have a button, that copies the url.

Copy URL button for each tournament in pm all

---

modules/lobby/src/main/Hook.scala

I had made Yes=0 and No=1 in my original PR but the refactoring away from Scalachess `Increment` flipped it. I suppose 1 is a more sane value for Yes anyways, so just flip the definition.

Fix increment mapping

---

ui/common/css/component/_friend-box.scss

Removing bottom border so that user can drop mouse to the edge of monitor and still click friends box. As of right now last 1px of border avoids click to toggle friends list.
Container bottom border still remains visible after change.

Removing bottom border on friends box

---

app/views/user/show/otherTrophies.scala
modules/tournament/src/main/Tournament.scala
modules/tournament/src/main/TournamentApi.scala
modules/tournament/src/main/arena/OrnicarPairing.scala
modules/tournament/src/main/arena/PairingSystem.scala
modules/user/src/main/Trophy.scala
modules/user/src/main/TrophyApi.scala

Fixes #4179
I spun up a local instance and tested that back filling the url for summer15 (via `marathon-trophies.js`) worked.
I did not try to create and run a new marathon tournament to verify the code in `modules/tournament/src/main/TournamentApi.scala`

Add Tournament url to Marathon Trophies

---

app/views/team/bits.scala
app/views/team/request.scala
app/views/team/show.scala
modules/i18n/src/main/I18nKeys.scala
translation/source/team.xml

Add translations to `/team/<name-of-the-team>` from the leader point-of-vue and fix the title of `/team/requests`.

Various translation improvements for teams

---

modules/user/src/main/RankingApi.scala

For example, the 1500 percentile should include all players in previous buckets (up to 1500), but not the current one (1500-1525).

Fix monitoring rating percentile calculation

---

modules/common/src/main/base/RawHtml.scala
modules/common/src/test/RawHtmlTest.scala

This fixes #6382.
I have lila set up locally but there seem to be no default topics I can comment on in the forum, so I've only verified that this works via unit tests.
Also, I'm not sure how to test whether the micro-optimization in `nl2br` is actually needed, any suggestion there?
---
Side note, I didn't find any guideline on contributing PRs, let me know if there's something I haven't done right.

Sanitize more than 2 consecutive line breaks

---

modules/mod/src/main/ModlogApi.scala

It's pretty unusable right now. This hides selfCloseAccount and
modMessage by lichess.

Cleaner recent mod log

---

ui/analyse/src/plugins/nvui.ts
ui/nvui/src/chess.ts
ui/nvui/src/command.ts
ui/round/src/plugins/nvui.ts

https://lichess.org/forum/lichess-feedback/suggestions-concerning-accessibility#3
> The output of the Scan command has already changed: blank squares on a file or rank are ignored, but screenreader doesn't read the squares on which certain pieces and pawns are  standing.
Actual result: Scan 1 = 'white rook white queen white rook white king' 
Expected result: Scan 1 = 'a1 white rook d1 white queen e1 white rook g1 white king'
Included in #6401 
It compiled but I couldn't test to check.

Add coordinates to the scan command

---

app/views/site/faq.scala
bin/trans-dump.js
build.sbt
modules/i18n/src/main/I18nKeys.scala
translation/source/faq.xml

Hello,
This PR translate the FAQ page, as listed in #3382 
Generally I've tried to keep the answers in one string because I think it will be easier to maintain (it can be split again if this is not wanted). As a result, some translation strings are quite long, and some answers are also *slightly* thicker (see before/after)
I don't have translated titles and trophy names.

Translate FAQ page

---

translation/source/patron.xml

From crowding
> Not keen on the wording 'downgraded to free', I feel it misrepresents the nature of patronage. What about 'will revert to a regular account'? Please consider revising the wording.

Source translation Fix

---

ui/analyse/src/ground.ts
ui/analyse/src/view.ts
ui/common/css/vendor/chessground/_coords-colors.scss
ui/common/src/coordsColor.ts
ui/common/src/coordsColour.ts
ui/dasher/src/theme.ts
ui/editor/src/chessground.ts
ui/puzzle/src/view/chessground.ts
ui/puzzle/src/view/main.ts
ui/round/src/ground.ts

Close #5809 and close #5820 
This PR adds alternate colours for all inline boards, using ts. I've mainly kept the colours proposed by JimiRecard.
A few examples:
Old
New
Old
New
Old
New

Add coloured inline coords to all boards using ts

---

ui/analyse/src/treeView/inlineView.ts

Close #6419. First time contributor here :wave:.
Hides annotation glyphs from the inline move tree when the computer is disabled. This updates the inline view to match the existing behaviour of the [column view](https://github.com/ornicar/lila/blob/39a7134149e0b0f2e0d3b5fee9980d5b7acb995e/ui/analyse/src/moveView.ts#L38).
This change is only intended to affect the post-game analysis board feature. Studies remain configured to always show glyphs (since they can mix computer-created and human-created glyphs).
Before: 
After:

Analysis Board: Hide Inline Annotations when Computer Is Disabled

---

ui/chess/css/_blindfold.scss

Resolves https://github.com/ornicar/lila/issues/6450.
In blindfold mode when the king is in check, suppress only the `background-image`.  The red `background-image` representing "check" will remain hidden, while the `background-color` representing square selection will now be visible.
Before (King square not highlighted at 0:19): https://vimeo.com/412988808
After (King square highlighted at 0:19): https://vimeo.com/412990317

Show selected square in blindfold mode even when king is in check

---

ui/site/css/_perf-stat.scss

`%flex-center` contains `align-items: center;`, which caused the issue.

exchanged `%flex-center` with `%flex-wrap`. Fix: #6386

---

ui/nvui/src/chess.ts

> I've just noticed, that whenever scan command is used and the file or rank requested is currently empty, we get a negative outpood instead of getting 'blank' message for example.
Actual result: scan a = 'invalid command: scan a' (only if the a file is empty)
Expected result: scan a = 'blank'
Current behaviour 
After the patch

NVUI: return `blank` instead of an error when line/rank empty for `scan`

---

modules/evaluation/src/main/PlayerAggregateAssessment.scala

I didn't know that this happened -- but, this may cause false positives or very borderline cases, and otherwise it's confusing that tweaking `reportable` also affects this. Either way it gives too much importance to `exceptionalDif`, imo, and with the improved `markable` it also should no longer be needed, and just having these as a report is fine.

Remove "reportable && exceptionalDif" condition

---

modules/msg/src/main/MsgPreset.scala

Stating that the profile text also can't imply a specific titled player unless it is legitimate.

updating impersonation preset message

---

app/views/learn.scala

Keys were not sent to the frontend, resulting in the raw keys being displayed.
Before
After

Load i18nKeys to learn

---

modules/api/src/main/GameApiV2.scala
modules/game/src/main/GamesByUsersStream.scala

As discussed in discord, if you heavily filter games for a player with a lot of games, there will be periods where nothing is sent for over 75s, which is the play timeout for connections. 
This PR takes the same approach as the previous game-stream fix by sending empty messages every 70 seconds.  In the case of the PGN format, this is an empty line. In the case of the `application/x-ndjson` version this is an empty json object.

Send empty games every 70 seconds to keep the connection alive.

---

ui/chat/src/discussion.ts

Fixes: #3490
This PR adds sessionStorage to discussion.ts, which loads and saves messages on reloads, tourney redirects, tv redirects, and any links the user inputs/follows.
Ex:
A debatable aspect of this branch is that all chat boxes are treated equally, leaving a game with an incomplete message and joining another will have the input box restored and ready to type in with the old unsent message. Since it is saved in sessionStorage, this does not work across tabs or through closing the browser

Load and save incomplete messages

---

public/javascripts/login.js

- Fix `.focus()` on 2FA input when form is initially shown
- [`$.fn.show()` is overriden](https://github.com/ornicar/lila/blob/a9285b36fcd3727ff8e927abb9d11580759c51e7/ui/site/src/jquery.fill.js#L28) and its code is run in a `requestAnimationFrame`.
- We need to delay our 2FA input logic until after `.show()` runs.
---
Let me know if there's a better way to do this. I saw that `.show()` will accept a callback, but I can't find any other usages of that parameter so I kept it simple and left this code using the public jQuery API.

Move 2fa clear/focus into raf to match .show()

---

ui/chess/src/main.ts

Previously, evaluation renderings included at most one digit after the
decimal point, but omitted it if it would be zero: so, `+1.2`, but `+1`.
This is unambiguous, but a little confusing at a glance because `#1`
means “mate in one” while `+1` merely means “advantage to white”, and
the symbols are similar. This patch causes the decimal point to always
be included, so that it’s easier to immediately read the evaluation.
Test Plan:
After `cd ui/chess && yarn compile && cd dist`, checked in a Node shell:
```
> [0, 10, 90, 100, 105, 666, 6666, 66666].map(require("./main").renderEval)
[ '0.0', '+0.1', '+0.9', '+1.0', '+1.1', '+6.7', '+66.7', '+99.0' ]
```
wchargin-branch: ui-render-fixed-point-eval

Render decimal point in evaluations

---

translation/source/faq.xml

The actual threefold repetition explanation doesn't include that when you want to claim a threefold repetition draw by offering draw before playing the move that makes the position repeats for third time it doesn't matter if your opponent rejects the draw or makes a premove. This pull request add this explanation on the FAQ appropiate section.

Udapte threefold repetition claiming explanation

---

modules/streamer/src/main/Stream.scala
modules/streamer/src/main/Streaming.scala
translation/source/streamer.xml

Half of chess on Twitch is Lichess anyway, so instead of doing many
requests for channels that are probably offline, query for chess then
filter by channel.
Even at peak time there are usually less than 200 streamers, so all can
be fetched with only two requests:
https://dev.twitch.tv/docs/v5/reference/streams#get-live-streams

Query live Twitch streams by game instead of channel ids

---

ui/@types/lichess/index.d.ts
ui/analyse/src/acpl.ts
ui/analyse/src/autoShape.ts
ui/analyse/src/ctrl.ts
ui/analyse/src/explorer/explorerView.ts
ui/analyse/src/moveView.ts
ui/analyse/src/nodeFinder.ts
ui/analyse/src/practice/practiceCtrl.ts
ui/analyse/src/promotion.ts
ui/analyse/src/socket.ts
ui/analyse/src/study/chapterEditForm.ts
ui/analyse/src/study/gamebook/gamebookPlayCtrl.ts
ui/analyse/src/study/interfaces.ts
ui/analyse/src/study/inviteForm.ts
ui/analyse/src/study/multiBoard.ts
ui/analyse/src/study/practice/sound.ts
ui/analyse/src/study/studyCtrl.ts
ui/analyse/src/study/studyForm.ts
ui/analyse/src/study/studyGlyph.ts
ui/analyse/src/study/studyMembers.ts
ui/analyse/src/util.ts
ui/chess/src/main.ts

On a lark, I toggled on `noImplicitAny` for `ui/analyse` (in retrospect, not the best one to start with).
I added about half the types and made the rest `any`.
I think will not break anything but did not know how to fully test it.

Add types to ui/analyse

---

modules/swiss/src/main/SwissApi.scala

I couldn't get a Swiss tourney running in dev, so this is speculative. But I'm thinking maybe Swiss ranking is 1-indexed and Arena ranking is 0-indexed. Instead of rewriting Swiss rankings in the db, probably best to just account for it in the `pageof` method?
```
scala> def rank(rank: Int) = (Math.floor((rank -1) / 10) + 1).toInt
rank: (rank: Int)Int
scala> rank(1)
res0: Int = 1
scala> rank(0)
res1: Int = 1
scala> rank(10)
res2: Int = 1
scala> rank(11)
res3: Int = 2
scala> rank(20)
res4: Int = 2
scala> rank(21)
res5: Int = 3
scala> rank(30)
res6: Int = 3
```

Nudge Swiss pageof index, closes #6841

---

ui/analyse/package.json
ui/ceval/package.json
ui/challenge/package.json
ui/chat/package.json
ui/dasher/package.json
ui/editor/package.json
ui/lobby/package.json
ui/msg/package.json
ui/notify/package.json
ui/nvui/package.json
ui/puzzle/package.json
ui/round/package.json
ui/swiss/package.json
ui/tournament/package.json
ui/tournamentCalendar/package.json
ui/tournamentSchedule/package.json
yarn.lock

Afaict the reasons for forking were:
* Removing unused boolean attributes: List no longer exists
* Removing SVG: But was restored
* **Removing support for comments**
* Drop hero: But has no code size or runtime cost (only type signatures)
* Allow undefined/null/string children: Upstream followed

update to official snabbdom 0.7.4

---

README.md

Both Firefox and Chromium raise a warning when trying to visit TypeScript url because www is missing.

Fix TypeScript url

---

ui/analyse/src/ctrl.ts
ui/analyse/src/explorer/explorerUtil.ts
ui/analyse/src/explorer/explorerView.ts
ui/analyse/src/fork.ts
ui/analyse/src/retrospect/retroCtrl.ts
ui/analyse/src/socket.ts
ui/analyse/src/study/gamebook/gamebookButtons.ts
ui/analyse/src/study/gamebook/gamebookPlayView.ts
ui/analyse/src/study/practice/studyPracticeView.ts
ui/analyse/src/study/relay/relayIntroView.ts
ui/analyse/src/study/relay/relayManagerView.ts
ui/analyse/src/study/studyCtrl.ts
ui/analyse/src/study/studyMembers.ts
ui/analyse/src/study/studyTags.ts
ui/analyse/src/study/studyView.ts
ui/analyse/src/util.ts
ui/analyse/src/view.ts
ui/analyse/tsconfig.json

`noImplicitReturns` is `true` is the global config but was overridden in `ui/analyse`. If you'd rather keep the code less verbose, feel free to reject this PR.

noImplicitReturns in ui/analyse

---

ui/puzzle/src/ctrl.ts
ui/puzzle/src/moveTest.ts
ui/puzzle/src/promotion.ts
ui/puzzle/src/view/tree.ts

Solved as much as I could in `ui/puzzle`.
There's not too much remaining in `ui/puzzle`. Below are some examples:
```
function eventPath(e): string {
return e.target.getAttribute('p') || e.target.parentNode.getAttribute('p');
}
```
Seems like `e` should be `Event`, but if you do `if (e.target) return e.target.getAttribute...` doesn't seem like `getAttribute` is a valid key.
```
function puzzleInfos(ctrl: Controller, puzzle): VNode {
return h('div.infos.puzzle', {
attrs: dataIcon('-')
}, [h('div', [
h('a.title', {
attrs: { href: '/training/' + puzzle.id }
}, ctrl.trans('puzzleId', puzzle.id)),
h('p', ctrl.trans.vdom('ratingX', ctrl.vm.mode === 'play' ? h('span.hidden', ctrl.trans.noarg('hidden')) : h('strong', puzzle.rating))),
h('p', ctrl.trans.vdom('playedXTimes', h('strong', …
```

Types for ui/puzzle, for #6939

---

.gitignore
ui/ceval/package.json
ui/chat/package.json
ui/chess/package.json
ui/common/package.json
ui/game/package.json
ui/nvui/package.json
ui/tree/package.json

For just building these in `ui/build`:
```
apps1="common"
apps2="chess ceval game tree chat nvui"
```
... seems marginally faster.
Before:
`ui/build  31.85s user 2.59s system 352% cpu 9.774 total`
After:
`ui/build  27.74s user 2.38s system 362% cpu 8.314 total`

Incremental compile ts

---

modules/shutup/src/main/Dictionary.scala

The word "cheated" keeps appearing in forum posts and likely elsewhere.

Accusing other players is rude

---

ui/lobby/css/app/_hook-chart.scss

When hovering over a hook bordering the bottom of the lobby graph, a
scrollbar appears, probably because the icon grows in size to expand
below the box.
I have not tested my change other than adding the style to lichess.org website from Firefox's developer tools

Hide the scrollbar on the lobby graph

---

ui/tournament/src/view/arena.ts

Didn't test it, but [this previous similar PR](https://github.com/ornicar/lila/pull/6032) shows that `berserkable` is a key of the `TournamentData` type.

Remove berserk rate in podium if not berserkable, closes #7034

---

modules/tournament/src/main/PlayerRepo.scala
modules/tournament/src/main/TeamBattle.scala

avoid recomputations of RankedTeam.magicScore during sorting

tiny perf opt: bestTeamIdsByTour #6793

---

modules/evalCache/src/main/EvalCacheApi.scala
modules/evalCache/src/main/EvalCacheEntry.scala

In the aftermath of #7086, we should probably flush the eval cache.
Unfortunately there is no good way to find entries that are affected by the bug, other than *usedAt* after 1e5543eac7898e67819e883f5eb28aaf97e27d57, which is basically all entries.
Should we remember the time entries were written, to have a better way to recover from future bugs?

[RFC] add EvalCacheEntry.updatedAt (to recover from future bugs)

---

app/controllers/Round.scala
app/controllers/User.scala
conf/routes

but never actually link to it, because these URLs may break
when we add root-level URLs or when a game ID is generated.

redirect /username to /@/username when possible

---

ui/round/src/view/user.ts

image worth more than a thousand words, maybe:
everywhere else seems to be using the correct `utitle`, except for this instance.

change instance of "title" to "utitle"

---

ui/round/src/plugins/keyboardMove.ts
ui/round/src/plugins/nvui.ts
ui/round/src/plugins/sanWriter.ts

Fixing types for https://github.com/ornicar/lila/issues/6939
1. Added new type `SanToUci`
2. Renamed variable `sans` to `legalSans` because the object only contains legal moves.
3. First time contributor. Hi!
Note: Now the last remaining violation of noImplicitAny for ui/round is importing the ab module.

Types for ui/round for ornicar#6939

---

ui/ceval/src/ctrl.ts
ui/ceval/src/main.ts
ui/ceval/src/pool.ts
ui/round/src/cevalSub.ts

* Fixes #5528
* No more `round.ongoing` event, racing to disable ceval in time
* Previously ceval would only be automatically disabled if it was enabled at page load. Now once disable it no matter what
cc @lakinwecker

ceval always off by default (fixes #5528)

---

modules/study/src/main/ChapterMaker.scala
ui/analyse/src/study/chapterNewForm.ts

New try to close #7227.
The ChapterMaker.Data class now includes `isDefaultName` flag so the chapterNewForm can check if the user changed or not the name input. Avoids using Chapter.isDefaultName regex (that only worked in english) when adding a new chapter.

isDefaultName flag on newChapter

---

ui/tournament/css/_team-battle.scss

It's inside the `.tour__team-standing` block, so the CSS rule shouldn't "leak" somewhere else.
before:
after:

Fix #7389: minor (sass) - making the horizontal padding smaller for TDs

---

ui/puzzle/src/view/side.ts

Puzzle rating graph was [too flat](https://lichess.org/forum/lichess-feedback/puzzle-solving-graph-is-not-changing-its-linear-always-3) due to this issue: https://github.com/fnando/sparkline/issues/17
before:
after:

Fix sparkline puzzle rating

---

ui/round/src/plugins/keyboardMove.ts

Keyboard input promoting pawn, h8=q should be the same as h8=Q
- allow upper case as promotion moves as well
- do not consider inputs containing a '=' as wrong

Allow more promotion move inputs (#7326)

---

ui/site/src/userComplete.ts

Currently when you search for a bot, it shows the old orange color that's used for titles.
This changes it to the purple that's used for the bot titles.

Added color to BOT title in search.

---

README.md

Since the `thanks` page has been restored, this reverts changes done to close #7396 in commit https://github.com/ornicar/lila/commit/a74cf1cacd7b9a4a3093b24522cfce52d051b5cc.

Add lichess.org/thanks link back to README

---

ui/common/css/component/_board.scss
ui/common/css/vendor/chessground/_chessground.scss

appears to be a fix, but could use some more cross-browser testing. it's on stage

"display: table" for .cg-wrap (maybe fixes #7435)

---

ui/dgt/src/play.ts

The new variables introduced on the last fix needs to be reset after game is over and before new game is started, otherwise moves are not detected until page is refreshed. One line of code.

DGT Reset some variables after game is over

---

ui/cli/src/main.ts
ui/site/src/component/top-bar.ts

Unifies the various ways in which the search box can be opened and
closed to always correspond to the focus state.

tie clinput toggle directly to focus (fixes #7586)

---

ui/round/src/ctrl.ts
ui/round/tsconfig.json
ui/round/types/ab.d.ts

Type declaration unfortunately contains unknown types because an ambient type declaration cannot reference
a module with a relative path (RoundController)
Checks out ui/round for #6939

chore: add ambient declaration for ab stub  module

---

modules/explorer/src/main/ExplorerIndexer.scala

After ornicar/scalachess@2bfee0516515da20ba1fa290233aa54f86597462 tags like
[Variant Standard]
would no longer be accepted. Instead of reverting or tweaking the regex, lets just update the format to the usual
[Variant "Standard"]

update fast pgn tag format

---

app/views/plan/features.scala
conf/base.conf
modules/fishnet/src/main/JsonApi.scala
ui/analyse/src/serverSideUnderboard.ts

* Stockfish 11 -> Stockfish 12 for server analysis
* Lower node target for NNUE, based on same time taken on x86-64-sse41-popcnt. Still wins Elo. More efficient on newer hardware. Before this is deployed, fishnet 2 will lie about nodes (factor 1.8x) in order to avoid being flagged as weak.
* Remaining todo: Monitor only NNUE nodes/nps

server side analysis now using sf 12 nnue

---

modules/security/src/main/AutomaticEmail.scala

At the moment, the Fishnet API keys are visible in the inbox message preview (at least on my browser): see [image](https://i.imgur.com/kzhW8cE.png). This seems like a (fairly minor) security issue, because it’s easier for somebody else to see it. The most straightforward way to get around this is probably just to change the message so the key is at the bottom. I’ve done that here.
It probably needs a bit more rewording, because it reads slightly awkwardly now. I was reluctant to adjust it much myself because it’s from ‘The Lichess team’, which I’m not sure I’m entitled to speak on behalf of!

Move Fishnet key to end of message

---

modules/common/src/main/mon.scala
modules/fishnet/src/main/BSONHandlers.scala
modules/fishnet/src/main/Client.scala
modules/fishnet/src/main/JsonApi.scala
modules/fishnet/src/main/Monitor.scala

some monitoring is obsolete with fishnet 2:
* python version (ce5de77d90c0f1ff03beb324d74b1ed3899e1f6f)
* engine version (implied by fishnet version)
* hash (not configurable, implied by fishnet version)
* threads (always 1)

simplify monitoring after fishnet 2

---

app/controllers/Team.scala
app/views/team/request.scala
modules/team/src/main/TeamForm.scala

Hi,
Note about this PR for issue #7706 
I'm not 100% sure how the bindrequest error should be handled (although I think it should never be called for the time being)
`err => BadRequest(html.team.request.requestForm(team, err)).fuccess`
I'm having a look issue #7524 where handling this error will be necessary

remove captcha on team join request

---

ui/ceval/src/ctrl.ts
ui/ceval/src/main.ts
ui/ceval/src/pool.ts
ui/round/src/cevalSub.ts

off by default via c7bb57a621043bbc5bc75bae0ed06bacce11541a (fixing #5528), but a small paper cut remains, especially because actions on the same page can cause ceval to be reinstanciated.
the idea is to have a shared local storage `ceval.disable` that gets set to a random value if ceval is automatically disabled.
then each tab has a local storage `ceval.enabled-after`, that stores an acknowlegement of the previous disable. it is set only if the user explicitly toggles analysis on.
when (re)opening analysis or reinstanciating ceval, analysis is only enabled if the latest disable has been acknowledged. to avoid a mostly theoretical race condition in self-reporting, self reports are only emitted if the current disable has been acknowleged.

remember ceval state in session storage

---

modules/fishnet/src/main/Limiter.scala

we should have the capacity, and it's the number of users, not so much individual users, that's responsible for the daily peak

slightly increase fishnet limit again (closes #7613)

---

ui/common/css/vendor/chessground/_chessground.scss

The move spots currently have a difference of 1% (between 19 and 20) across their gradient, which smooths them a little bit. This PR adds the same to the capture marks. See [before](https://i.imgur.com/2Vuf4Wc.png) vs [after](https://i.imgur.com/bOrXVD3.png).

Add slight gradient to capture indicators

---

modules/api/src/main/ReferrerRedirect.scala
modules/api/src/test/ReferrerRedirectTest.scala

fixes #7858
Verified that the updated unit test passes after change, and not before the change.

allow '+' in referrer redirects

---

bin/mongodb/fix-normalized-emails.js
modules/common/src/main/model.scala

Getting users by email assumes that the email is stored normalized, but it isn't, for some users. Maybe we just forgot to run a database migration at the time.
The regex query matches 4409 users in prod, as of now. If this number grows, there is a bug somewhere. The normalization function is tested. The update part of the query is **not** tested. Please review and run :)

fix normalized emails in database (fixes #7848)

---

modules/round/src/main/JsonView.scala

Another tweak to unblock https://github.com/veloce/lichobile/issues/374 : the mobile client needs to know the POV player ID, not just the user ID, in order to construct the URL to save forecasts.

Include player POV ID for owner analysis

---

conf/base.conf

2.1.3 is the oldest 2.x release that does not have the variant analysis bug
(https://github.com/niklasf/fishnet/issues/147).
I also wrote emails to the last remaining contributors on 1.x.

bump fishnet min version to 2.1.3

---

ui/analyse/css/_action-menu.scss

Changed the padding from the local analysis range input selectors so that it stops giving the illusion that you can select more than it's allowed.
Before
After
This change makes the selectors feel right to me. I don't know if it's intentional that they have padding on the right side. Feel free to decline if reasonable.

Removing the illusion that the range selector does not reach the max selection

---

modules/tournament/src/main/TournamentScheduler.scala

This rotates zh/960 and anti/atomic instead of just having zh and then an anti/atomic/960 rotation.

Rotate zh/960 and anti/atomic tournaments

---

app/templating/GameHelper.scala
app/views/user/show/header.scala
modules/user/src/main/JsonView.scala
ui/site/css/user/_profile.scss

not displaying any mark may be better than displaying the wrong wording. after this, fixed wording and the renaming should land in a future lichobile version

hide broken tos wording in lichobile, tweak class name

---

modules/shutup/src/main/Dictionary.scala

After seeing people calling others noobs, I decided to check if it was in the shutup dictionary, and it wasn't, so here's the PR.

add noob to shutup dictionary

---

bin/gen/timeago-to-scala.py
ui/@build/rollupProject/index.js
ui/analyse/css/_tools.scss
ui/puzzle/css/_tools.scss
ui/tsconfig.base.json

Safari 10 appears to be the only browser preventing us from targeting ES2017 (matching recently bumped lib ES2017), and it's not supported anyway according to our list (https://github.com/ornicar/lila#supported-browsers).

stop supporting safari 10

---

ui/ceval/src/ctrl.ts

Hi,
I found this small issue while playing on lichess.org, and being a software developer myself, I decided to dig into the code and try to offer a fix.
The thing is, I found the "go deeper" button on the analysis board page sometimes starting analysis on some other previously viewed position of the game instead of the current one. Specifically that occurs when the analysis of a position (calling it p1) was already finished, then one selects a position where analysis still needs to run (p2), and then going back to p1 and clicking "go deeper" there. Then it analyzes p2 instead of p1.
I think this happens because the goDeeper routine in CevalCtrl uses the stored position "lastStarted", but that variable is not updated to reflect selection of a different position when there is no need to …

Fix ceval 'go deeper' button analyzing a different position than the currently viewed one

---

ui/analyse/src/ctrl.ts

This fixes https://github.com/ornicar/lila/issues/8098
My analysis of this issue is that when the user is in interactive study mode (aka. `gamebookPlay`), chessground's `movable` configuration is always fixed to `bottomColor`, which becomes opposite of `turnColor` when board is flipped.
In this PR, I changed it so that it always choose `turnColor` to be the `movable`.
So far, I only manually tested some small example locally and it seems to be working as I expected,
but, of course, I might be missing some other cases (for example, I really haven't followed what `embed`, `dests`, etc.. does, or what happens when in chess variant), so I greatly appreciate code review. Thanks a lot!

Fix board flip in interactive study

---

ui/lobby/css/_spotlight.scss

Some icons in the lobby spotlight have a blue shadow, some don't. This fixes the inconsistency.

fix spotlight icons shadow

---

.gitignore

After a clean install of lila, and setting up the bloop server, I was left with these changes already
and I hadn't even contributed anything yet. I believe these files should be added to the .gitignore as to avoid pushing them to git.

update gitignore to ignore bloop build files, metals build files, and vscode files

---

modules/round/src/main/RoundNotifier.scala

When a correspondence game I play in ends (for example my opponent checkmates me),
and I am not present at the game (I have some other page open),
a notification is sent to me.
The game id is a short id,
so when clicking on the notification - I'm directed to a "spectator" view of the game.
This commit updates the notification from short game id to full game id.
Clicking the link will now go to "first person" view of the game,
so I can say "Thanks for the game" in the chat, for instance.

Include full game id in notification

---

ui/analyse/src/treeView/treeView.ts
ui/analyse/src/util.ts

Allows to manage variations using touch devices by invoking the contextual menu on tap & hold. Supposedly doesn't break anything.

iOS contextual menu fix

---

app/views/plan/index.scala

Would something like this maybe be sufficient for the final point of lichess-org/talk#73?
On the flipside, it might also prevent the occasional unintended anon donation.

clarify anon/public donation (hopefully closes lichess-org/talk#73)

---

ui/site/css/practice/_icons.scss

It seems prettier tool broke one of tricky css classes in practice page.
See small demo at prettier playground [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AOugzATgAQBsAMgJYBWA7AO4ASew6UeeARgIZgDWA5gE4QBXKABMAtCQC2bbnCR5J3UQN4AbABQByAA68OMEmDgB6CQIDOnODFRmAbtw0BKANyMAvo0ZGAVHh1X9OF5xbigIXjg8byNGDGx8YnJqOgYmVg4efiExSWlZeQlFZXVtXTB9QxNzS2s7Bxd3Tyg43DxMLAI8UkpaekZmdi4+QRFxKRk5BSVVTR09A2NTCysbeydXKA8oEAAaEAgtfWgzZFA2Xn4qAAVzhBOUNhUqNgBPE72WMpqAZS0OEig3GQMF4AjgezgEhYcGEwhhRDYgIEeQAYuEpDB9IDkCA2AIYBBdiAABYwCQqADqxJI8DMf0M3zuNJIthpLxxYDM7xAALMQRgV103CkyAAZo8+XsyGYAB4AIS+Vm+bAkcFIUDgYol4JA0pl3wB3BUcAAigIIPAtSpJSA-rw+bwOVyiToATAKSRhDBicgABwABj2OggfIpui0OP8Dtsmr2AEdzfBBQd7rizKINTCYUSIgmSBFBdIRUhxdadXyJCRgaDy4bjWaLZqS9q9jA2CwPV6fUgAEyt3QkFSGgDCEAkxZAcDMAFYieY4AAVdv3Us22xggCSIgQMG+YF4JEO …

Fix practice icon

---

.gitignore
ui/ceval/src/ctrl.ts
ui/ceval/src/pool.ts
ui/ceval/src/types.ts
ui/ceval/src/view.ts
ui/site/package.json
ui/site/rollup.config.js
yarn.lock

EDIT:
As par the discussion at https://github.com/niklasf/stockfish.wasm/pull/30#issuecomment-782651525, now `stockfish-nnue.wasm` points to an npm package from this repository https://github.com/hi-ogawa/Stockfish.
Hi guys.
I've made an experimental integration of Stockfish NNUE.
On niklasf's stockfish.wasm repo, there is a corresponding on-going PR https://github.com/niklasf/stockfish.wasm/pull/30, but I thought I would integrate it into lichess for easier testing.
For now, npm package `stockfish-nnue.wasm` directly points to my fork https://github.com/hi-ogawa/stockfish.wasm/tree/nnue-wasm-simd--publish (EDIT: now it changed to https://github.com/hi-ogawa/stockfish.wasm/tree/demo) where I just pushed build artifacts directly.
Since WASM SIMD feature itself is not stable stage, I would …

Ceval with Stockfish NNUE

---

modules/common/src/main/MultiKeyMap.scala
modules/common/src/test/MultiKeyMapTest.scala
modules/lobby/src/main/HookRepo.scala

Hooks (i.e. realtime seeks on lobby) have 2 unique keys:
id, the hook identifier
sri, the websocket identifier
there can't be 2 hooks with the same id or sri.
the previous hook repo did a lot of traversing of a Vector[Hook]
to look them up by id or sri.
This attempts to index the hooks.

MultiKeyMap for HookRepo

---

ui/common/css/base/_elements.scss

This Pull Request fixes #7465 by indicating the browser what theme is currently using the webpage, with the `color-scheme` property. In Chrome/Chromium, this makes the browser use dark scrollbars when using lichess' dark theme.

Add color-scheme property, fixes #7465

---

ui/analyse/src/autoShape.ts

Fixes https://github.com/ornicar/lila/issues/8273

Disable move annotation when computer analysis is disabled

---

ui/learn/css/_screen.scss

Vertically (as well as horizontally) center learn screen overlay. The "Let's go" button is barely visible in some levels, as shown in
https://lichess.org/learn#/16
Before
After
Also if height is too small, it will become scrollable.

Minor css fix: Vertically center learn screen overlay

---

ui/round/src/view/button.ts

Closes https://github.com/ornicar/lila/issues/7866.
This bug seems due to a typical error of `Event.target` and `Event.currentTarget`. I actually couldn't reproduce "disabled" state locally, but I saw `event.target` being `<span>Rematch</span>`, which doesn't have any classes.

Fix disabled rematch button

---

ui/chat/src/enhance.ts

so, e.g. one could write in the chat "17. ♔a1" instead of "17. Ka1"

Extend movePattern regex to match unicode piece characters

---

ui/analyse/src/actionMenu.ts
ui/analyse/src/ctrl.ts
ui/ceval/src/ctrl.ts
ui/ceval/src/types.ts

This PR adds option to disable nnue ceval, reflecting some report where engine failed to start on some device and also for some mobile users who want to avoid downloading 10mb https://github.com/ornicar/lila/issues/8284, https://github.com/ornicar/lila/issues/8309.
I know It's better to fix the engine bug on my end https://github.com/hi-ogawa/Stockfish/issues/2, but I need more time on it.
This bool switch actually requires reloading page to apply change so it's a bit mis-leading, but I think user will be fine doing it for this case.

Add "Enable NNUE" bool setting

---

ui/ceval/src/ctrl.ts
ui/site/package.json
yarn.lock

Closes https://github.com/ornicar/lila/issues/8284 and https://github.com/ornicar/lila/issues/8309.
The new version fixes spontaneous engine crash, which was investigated here https://github.com/hi-ogawa/Stockfish/issues/2.

Update stockfish-nnue.wasm 0.0.2

---

ui/analyse/src/study/commentForm.ts

Didn't mean to dig up the closed issue (https://github.com/ornicar/lila/issues/8220) but I found one case where a bug is reproducible and identified the code responsible for it.
The bug is from https://lichess.org/forum/lichess-feedback/new-comments-disappearing-in-my-studies?page=3#21, which says:
> Put a longish (17 lines) comment before the first move. REC button was green. Clicked it twice. Now green. Edited the comment to have one more line. Clicked REC twice. Now the line I just added is in the move window (Inline notation is on) but missing from in the comment window below the board!
As far as I can tell, this is due to the prop `CommentForm.current: Prop<Current | null>` holds a stale `Tree.Node` object after a user clicks REC button twice. The prop is updated by …

Fix study comment form

---

ui/ceval/package.json
ui/ceval/src/cache.ts
ui/ceval/src/ctrl.ts
ui/ceval/src/worker.ts
yarn.lock

~~Edit: It seems there are much clearner wrappers than localForage, so I think I will try them. In the mean time, I'll keep this as a draft PR.~~
Edit: For IndexedDB wrapper, I initially used [localForage](https://github.com/localForage/localForage), but I switched to [idb-keyval](https://github.com/jakearchibald/idb-keyval) since the code is much simpler.
---
I added explicit caching (i.e. not relying on browser cache) for nnue wasm binary with IndexedDB. Using local storage wasn't option because its size limit is 10M (also saving 20MB synchronously on UI thread would be a bit disastrous).
~~I used  [localForage](https://github.com/localForage/localForage) wrapper library for managing IndexedDB. The code looks a bit bloated but probably it would still be better than writing wrapper …

ceval: Cache wasm binary via IndexedDB

---

ui/analyse/src/study/chapterNewForm.ts

Currently the board editor tab in the "create new chapter" modal on a study page always initially displays with white orientation, even if the "Orientation" select input below shows black. I believe the desired behavior is to initialize the editor view to the current orientation of whatever is currently displayed in the study.
Example of current behavior:
Repro steps:
1. Create a study, or navigate to an existing study
2. Configure the view to have a black orientation
3. Click on "Add a new chapter" and navigate to the editor tab

Ensure board editor in study new chapter modal initializes with existing orientation

---

ui/ceval/css/_pv.scss
ui/ceval/src/view.ts

I implemented multiline wrapping toggle for PV move display. All logic/state is in css, so the change is rather simple (other changes are mostly refactoring).
As revoof mentions here https://github.com/ornicar/lila/issues/8271#issuecomment-791929729, the usefulness of those shallow pv move is questionable, but I guess it's not bad to be able to show them anyway (for example, it can show mate in 8).
Here is the screenshot of current design (just triangle mark and some padding):

ceval: Implement pv line wrap toggle

---

translation/source/faq.xml

On the [FAQ page](https://lichess.org/faq#trophies).
It seems to be wrong in some other languages as well, e.g. the German translation is roughly "berserk and win 100% of the an hourly bullet arena games" but I suspect that should be fixed on crowdin.

Fix 'a hourly' -> 'an hourly'

---

ui/ceval/css/_pv.scss

I don't know if the current behaviour is intended, but even if it was, please consider this as a proposal.
Seeing an upward pointing triangle at the end of the non-expanded variation didn't make me clear that it was an actual button to expand the variation.
I personally find the change in this PR to be more intuitive: when the variation is not expanded, the button is a downward pointing triangle, which suggests a downwards expansion of the variation, just like any drop-down list. When the variation is expanded, the upward pointing triangle suggests a collapse of the variation.

Change direction of triangle

---

app/controllers/Racer.scala
app/controllers/Storm.scala
ui/puz/css/_puz.scss

Looking at the code never showing coords was intentional but from what I have tested (all coords setting from both white and black perspective for Storm, on laptop), they are displayed fine.

Show coords on `Storm` and `Puzzle Racer`

---

conf/base.conf
modules/common/src/main/ThreadLocalRandom.scala
modules/common/src/main/config.scala
modules/security/src/main/Env.scala
modules/security/src/main/Store.scala

don't think we need this in prod. if listress needs fake ips, it can just send `X-Forwarded-For: fake-ip` in the test environment.

simplify away net.ip config

---

modules/common/src/main/String.scala
modules/common/src/test/StringTest.scala

Random id of a tournament contained the substring `btc`, which triggered the regex, updating it to avoid that

Update prize regex

---

modules/pref/src/main/RequestPref.scala

This is currently only possible for `bg` and `theme`. With this change URLs like this are possible:
[http://localhost:9663/analysis?bg=dark&theme3d=Classic-Blue&pieceSet3d=CubesAndPi&is3d=true](http://localhost:9663/analysis?bg=dark&theme3d=Classic-Blue&pieceSet3d=CubesAndPi&is3d=true)

Add query param overrides for all UI preferences

---

bin/gen/piece-update

While coding in lishogi I have encountered a not found error when running ./bin/gen/piece-update since the double brackets ( [[ ]] ) syntax is not recognized in all sh implementations but is fine with bash.
https://serverfault.com/questions/52034/what-is-the-difference-between-double-and-single-square-brackets-in-bash
> [[ is not as compatible, it won't necessarily work with whatever /bin/sh points to. So [[ is the more modern Bash / Zsh / Ksh option.

In /bin/gen/piece-update, replace with #!/bin/bash

---

ui/notify/src/renderers.ts

Fix correspondence alarm opponent display
Could not test but it's like it was before translating: https://github.com/ornicar/lila/blob/37c7cfbec5a5c5d6cdde1feef2b78ebcb698ae56/ui/notify/src/renderers.ts#L133

Fix correspondence alarm display

---

app/controllers/Auth.scala
app/controllers/LilaController.scala
app/views/appeal/tree.scala
app/views/base/layout.scala
modules/common/src/main/HTTPRequest.scala
modules/security/src/main/Granter.scala
modules/security/src/main/MagicLink.scala
modules/security/src/main/PasswordReset.scala
modules/security/src/main/SecurityApi.scala
modules/security/src/main/model.scala
modules/user/src/main/Authenticator.scala
modules/user/src/main/User.scala
modules/user/src/main/UserContext.scala
modules/user/src/main/UserMark.scala

The auth is only in heap, lasts at most 7 days or until the next deploy.
Only requests which path start with `/appeal` are authorized.
Websockets are considered anonymous.

allow marked closed accounts to login for /appeal only

---

modules/common/src/main/LameName.scala

Fixes #8564.
This change changes the lameTitlePrefix regex to include characters before it. This has a consequence that no new players will be able to have "fm", "gm", "wlm", etc. in their name at all. However, it stops usernames such as "The_GM_Kasparov". You need to choose what you'd prefer, I suppose.
Examples of names that are no longer allowed:
The_GM_Kasparov
xGm_Kasparovx
yFMy
I_Am_A_FM_Definitely
zFM_I_Like_Piez
almamater
asdnmasdf
elmolovesyou

fix regex to check for titles in names (#8564)

---

ui/racer/css/_home.scss

Fix racer main button text wrapping

---

modules/simul/src/main/Simul.scala
modules/simul/src/main/SimulApi.scala
modules/simul/src/main/SimulForm.scala
modules/simul/src/main/SimulRepo.scala

Actually makes it possible to update whether a simul is featured and correctly displays the current featured status in the settings.
For some reason, this also seems to fix a current bug where titled players can't update their simuls after creating them, at least not when the simul is set as featureable (at least that seems to be what's causing the issue).
I assume it's related to [this part of the code](https://github.com/ornicar/lila/pull/8537/files#diff-e6e9a3250fb6ce30c70426d60fc1ea60ddc20de2572fa6b9010cf2ea0a19a131L130).

Fix simul editing for titled players

---

modules/forum/src/main/Granter.scala

According to #8582, some patrons aren't happy that they can't post in the forums without having played games (to prove they aren't a bot?). If they have donated, they are very likely not a bot and should be able to post in the forums. This PR allows patrons to post in the forums.

allow patrons to post in forums

---

modules/common/src/main/LameName.scala
modules/common/src/test/LameNameTest.scala
modules/user/src/main/User.scala

Related: #8567 (caused test failure)
This implements the check discussed in the above PR but this time properly.
The changes to the `User` regexes are only stylistic since I find the regexes a bit clearer this way but I can revert them if you want.
Also, is there a reason for the `newUsernameChars` check? It seems like `newUsernameLetters` should already cover that and they both produce the same error message.

Actually fix username contains title check

---

app/views/base/layout.scala

When in zen mode, the green button in the very top left is currently not translated. This PR translates it.

adds translation for zen mode on green button

---

ui/common/css/form/_cmn-toggle.scss

close https://github.com/ornicar/lila/issues/7667
I tried two version, putting the one I prefer first: 
Older version:
Feedback welcome, I'm not a css expert

Add a noncolor indicator to `cmn-toggle`

---

app/ui/scalatags.scala
app/views/analyse/replay.scala
app/views/user/show/header.scala
ui/analyse/src/study/studyShare.ts
ui/swiss/src/view/main.ts
ui/tournament/src/view/finished.ts

In order to silence Chrome warning: "Resource interpreted as Document but transferred with MIME type application/x-chess-pgn"
Though, according to [caniuse](https://caniuse.com/download), it doesn't seem to have support for moderately old Safari on iOS. Not sure whether that's relevant. If it is, it seems using `target="_blank"` is a (somewhat weird) alternative.
Also, I found a weird discrepancy between GIF downloads. Using the GIF share on an old game's analysis opens the GIF in a new tab (the link has `target="_blank"` and no `content-disposition` header is sent with the response).
However, GIF downloads in studies send `content-disposition: attachment` and don't have a `target` attribute which results in the GIF getting downloaded immediately and also triggers the above warning in …

Add 'download' attribute to PGN download links

---

app/controllers/Report.scala
app/views/forum/post.scala
modules/report/src/main/ReportForm.scala

for closing https://github.com/ornicar/lila/issues/6869
Ideally it would auto populate with the post text or the post link but I couldn't work out how to edit the form pre-fill.
I looked at appeal for inspiration where the preset message was just an argument passed to the render function but wasn't sure where to start with modifying form3.textarea.

added report forum post shortcut (reports user)

---

ui/common/css/form/_form3.scss

hovering over text should show a text cursor
this PR makes it so.

change cursor on form-label to text

---

app/views/user/show/side.scala
modules/user/src/main/User.scala
ui/site/css/user/_sub-rating.scss

As opposed to just a gap between the standard ratings and variant ratings (that is **always** there, even if you don't have a variant rating) and between the variant/standard ratings and the puzzle ratings (that is **always** there, even if you are a bot and don't have puzzle ratings), I propose adding a line separator.
The gap is very hard to see (I only just noticed it) so it clearly doesn't serve it's purpose of separating the ratings. It is also currently displayed **always**, as noted above. Instead, a line should be added (this also helps visually-impaired people) to separate the ratings.
The lines also only appear when you have a variant rating for the top separator and when you aren't a bot for the bottom separator.
**Before**             |  **After** …

adds a separator between ratings on profile page

---

ui/site/src/coordinate.ts

It also complains about [this](https://github.com/ornicar/lila/blob/master/ui/racer/src/ctrl.ts#L216) ... always true expression?
And the async [here](https://github.com/ornicar/lila/blob/master/ui/ceval/src/worker.ts#L83) but that requires a bit more thought to resolve.

Fix eslint

---

app/views/swiss/home.scala

Seperating late join and pause to make clear that late-join does not reduce the number of rounds  and only pausing can; The new explanation of how late-join works should be more clear, and added an example too.

Improve swiss-arena comparison and address  #8613

---

ui/@types/lichess/index.d.ts
ui/analyse/package.json
ui/analyse/src/plugins/studyTopicForm.ts
ui/analyse/src/study/topics.ts
ui/analyse/tsconfig.json
ui/common/css/component/_tagify.scss
ui/site/package.json
ui/site/src/coachForm.ts
ui/site/src/teamAdmin.ts
yarn.lock

Tested on all the pages where it's used. I also made sure to keep the important custom adjustments to the CSS.
4.x doesn't actually have any breaking changes for the non-React API.
Also fixes this weird bug in Chrome:
| :------: | :----: |
|![Screenshot 2021-04-18 181724](https://user-images.githubusercontent.com/19309705/115152685-5a803680-a072-11eb-9b51-2c431cb136d2.png)|![Screenshot 2021-04-18 140536](https://user-images.githubusercontent.com/19309705/115152558-e0e84880-a071-11eb-9424-919a28c7b87b.png)|

Update tagify to 4.0.5 and type it

---

README.md

This PR is a minor document update that achieves the following:
- Fix BrowserStack link visibility for dark mode
**Before Fix**
**After Fix**

Fix BrowserStack link in Readme (for dark mode)

---

modules/bot/src/main/BotPlayer.scala

Closes #8745
Fixes that you currently can't accept a draw offer via the API when you aren't able to send one. i.e. if you send a draw offer, the opponent declines but then sends their own offer during the next few turns you can't accept it via the API.
Side note: Looking at [RoundSocket.scala](https://github.com/ornicar/lila/blob/master/modules/round/src/main/RoundSocket.scala#L106), it looks like similar checks are only performed client-side when not playing via the API (i.e. via websockets)?
Would it be worth unifying this with the API code?

Fix accepting draw via API when not able to send draw

---

app/views/tournament/side.scala
ui/tournament/css/_side.scss

https://github.com/ornicar/lila/issues/8702
When all conditions are met:
When one or more conditions are NOT met:

Improve clarity of met/failed tournament requirements

---

README.md

Looks like Prettier doesn't really handle HTML in Markdown properly. But at least it shuts up the lints.

Prettier README.md

---

app/views/swiss/home.scala

The answer to the question *"Can players late-join?"* was missing the number for the second example. 
The change adds "7 " to match the style of the previous example.

Add round number to Swiss tournament documentation

---

modules/security/src/main/AutomaticEmail.scala

When there is a new reply from a mod.
Some players didn't find it otherwise.

clarify appeal notification message

---

modules/mod/src/main/SandbagWatch.scala

Closes #8757
It might make sense to avoid sending warnings in more cases or maybe even never send them at all to bots? But at least this gets rid of some obvious false positives.

Don't send sandbag warnings when ratings didn't change

---

ui/lobby/src/boot.ts
ui/lobby/src/setup.ts
ui/lobby/src/view/correspondence.ts

Closes #8761
1. Don't reload the page when clicking "New game" in the correspondence tab
2. Immediately switch to the correct tab when creating a game
3. Properly disallow rated unlimited time games in the lobby in the UI
4. Respect preselected `timeMode` from server
5. Remove preselected `timeMode` after modal is closed

Several small fixes for the "New game" button on the homepage

---

ui/build

Since quite a few people have had issues lately because they tried building with `node` 16.
I guess at some point we should try to find out why it doesn't work and fix it (probably requires updating some dependencies?) but for now this is a simple solution to prevent any more people running into this problem.

ui/build: Check node version

---

ui/learn/css/_screen.scss

Also adjusts the light mode styling a bit:
| Before | Light | Dark
|:--:|:--:|:--:|
|![prev](https://user-images.githubusercontent.com/19309705/116197365-fa098d00-a734-11eb-90b1-2b1307192b44.png)|![light](https://user-images.githubusercontent.com/19309705/116197383-ffff6e00-a734-11eb-8b59-782ead0a714c.png)|![dark](https://user-images.githubusercontent.com/19309705/116197404-042b8b80-a735-11eb-8f21-b0cc9c3f45fd.png)|
(Click images for a full resolution preview)
Closes #8762

Learn: Completion modal dark mode

---

app/views/swiss/side.scala
app/views/tournament/side.scala
ui/swiss/css/_side.scss
ui/tournament/css/_side.scss

Closes #8799
Changes:
- Add `nbsp` before postfix symbol
- Make everything red for anons
- Make swiss tournaments consistent with arenas
For anons, it seems pretty weird that all conditions are considered true. Seems like it's because rejected conditions need a reason but as far as I can tell that reason is actually never used for Swiss tournaments and for arenas it's only used when you press the join button without meeting one but it should always be disabled anyway in that case.
So maybe we should just remove the rejected reason and everything related to it? Or I guess if we want to keep the code around, we might as well use it and display it, e.g. as tooltips. But if we keep them, we should probably reject all conditions for anons and just use something like "You are not a registered …

Improve tournament requirements display

---

ui/learn/css/_screen.scss
ui/racer/css/_home.scss
ui/racer/css/_race.scss
ui/site/css/practice/_side.scss
ui/storm/css/_play-again.scss

On this commit the start/end animation of any chess basic (like how to move a piece), also the golem animation on the side. The blink animation for the boost of the car in the puzzle racer home and in a race has been removed. And the last one is the storm on the button play again of the storm race. All these animation can be removed if the user want by setting "ui.prefersReducedMotion"

Use of prefers-reduced-motion to skip some animation if the user want (https://github.com/ornicar/lila/issues/8764)

---

ui/common/css/form/_cmn-toggle.scss

Closes #7667
Closes #6534
Basically the same as #8584 but I hope it stays positioned correctly now. At least it seems consistent for me in Chrome and FF on any zoom level.

Add non-color indicator to cmn-toggle

---

translation/source/site.xml

They aren't rendered anyway. (Those messages are used for notifications and are always in a separate row with the initiating user in the header so the leading space is auto-stripped by the browser.)
Is there some way to automatically update all other languages on crowdin?

i18n: Remove leading spaces

---

translation/source/site.xml

Never seen it with dots in between. Cambridge Dictionary, Wikipedia, etc. all use "FAQ". Also avoids wrong "missing punctuation warnings"

i18n: 'F.A.Q.' -> 'FAQ'

---

app/templating/GameHelper.scala
ui/round/src/ctrl.ts

Closes #3861
That status stuff was unused and as far as I can tell wouldn't display anything anyway.
Maybe a slightly robuster alternative to doing this via cash would be to reload the side via xhr as is done when the game ends but at the cost of an extra request for each spectator?

round: Auto-update berserk icon next to username

---

translation/source/faq.xml

Don't think there's a nice way to phrase this in English with proper grammar otherwise.
Only way I can see is "win 100% of games of an .. arena." which sounds a bit odd with the double "of".

u18n[faq]: '100%' -> 'all'

---

ui/site/css/team/_show.scss

Images in team descriptions are not fully shown; a good example is here: https://lichess.org/team/offerspill-sjakklubb

fixes images in team descriptions 

---

ui/analyse/src/ctrl.ts

Part of a fix for https://github.com/ornicar/lila/issues/8852 (which also needs an updated version of Howler https://github.com/ornicar/howler.js/pull/4).
Currently the first time a sound is played on mobile safari it needs to have been unlocked by a user interaction. In order for Howler to do this it needs to have attached various touch event listeners to the page, and if does this when creating a new Howl for the sound file, which Lila does when loading a sound for the first time.
Note that `lichess.sound.play` calls `loadStandard` the first time a sound is played, but by then it's too late to be part of the interaction, so the first move sound isn't played. We have to preload to solve this.

Fix missing first move sounds on mobile devices

---

modules/game/src/main/Event.scala
ui/round/src/atomic.ts
ui/round/src/ctrl.ts
ui/round/src/interfaces.ts

Fixes #8559
Tested in Stanard, Atomic, and Crazyhouse with and without move confirmation.
I'm a bit unsure about removing the server-side event but I searched the whole repo and `lila-ws` for "enpassant" and didn't find anything else using it so I guess it should be removed.

Handle en passant client-side

---

modules/tournament/src/main/Schedule.scala

To avoid this:
Pretty sure there shouldn't be any other change since no such tournaments overlap otherwise.

Remove overlapping hyper/ultra bullet tournaments

---

app/views/lobby/home.scala
ui/lobby/css/_layout.scss

Fixes #8730
Would also be possible with only CSS e.g. like this:
```css
:not(lobby__simuls) + lobby__forum {
grid-area: simuls;
}
```
But that seems a bit too janky since it relies on the element's order.

Remove gap on lobby when no simuls

---

ui/common/css/form/_cmn-toggle.scss
ui/site/css/team/_show.scss

Make the toggle greyed out, remove the hover effect and change the cursor when it's disabled. Mainly for the token creation page since I don't think disabled toggles appear much elsewhere.
Also reverts a small margin change made in #8834

cmn-toggle: Add disabled styling

---

ui/@build/rollupProject/index.js
ui/analyse/rollup.config.mjs
ui/challenge/rollup.config.mjs
ui/chat/rollup.config.mjs
ui/cli/rollup.config.mjs
ui/dasher/rollup.config.mjs
ui/dgt/rollup.config.mjs
ui/editor/rollup.config.mjs
ui/insight/rollup.config.mjs
ui/learn/rollup.config.mjs
ui/lobby/rollup.config.mjs
ui/msg/rollup.config.mjs
ui/notify/rollup.config.mjs
ui/palantir/rollup.config.mjs
ui/puzzle/rollup.config.mjs
ui/racer/rollup.config.mjs
ui/round/rollup.config.mjs
ui/serviceWorker/rollup.config.mjs
ui/simul/rollup.config.mjs
ui/site/rollup.config.js
ui/speech/rollup.config.mjs
ui/storm/rollup.config.mjs
ui/swiss/rollup.config.mjs
ui/tournament/rollup.config.mjs
ui/tournamentCalendar/rollup.config.mjs
ui/tournamentSchedule/rollup.config.mjs

Caused by d523aeff8b59aae8df7e51f391b9f2982b0c1e9c
ES rollup config modules on Node 13+ can only import the default export from commonJS modules it seems. See also: https://rollupjs.org/guide/en/#using-untranspiled-config-files
And bc `ui/site` is still a commonJS module we also can't switch `@build/rollupProject` to an ES module.

Fix rollup build import

---

app/views/simul/form.scala
app/views/simul/show.scala
modules/simul/src/main/Simul.scala
modules/simul/src/main/SimulApi.scala
modules/simul/src/main/SimulForm.scala
modules/simul/src/main/SimulRepo.scala
ui/simul/css/build/_simul.form.scss
ui/simul/src/interfaces.ts

Add an optional estimated start time for Simuls, in case the host wants
to create a simul some time in advance.
Previously the only way to indicate start time (unless immediate...) was
to write a start time in the Simul description. One problem with such a
solution is that the start time from the text won't be displayed in
users local time zones.
This commit adds a field, which is optional, which can be used to give
an estimate of at what time the host intends to click the Start button.
Here's an example "problematic" Simul which was created in advance with a start time in the description,
https://lichess.org/simul/PtXmjQql
The chat was filled with questions about when it would start... :sweat_smile: 
Sidenote,
this Pull Request was a way for me to take a chance to get familiar with the …

Add optional estimated start time for Simuls

---

ui/ceval/src/view.ts

Fixes #8873
`e.preventDefault()` on `touchstart` blocks the `mouseover` event. Hovering on touch doesn't work properly anyway and never opening the board avoids the issue that it can't be closed. It also blocks the `mousedown` event so there's no duplicate event.

Fix analysis lines hover chessboard on touch

---

ui/round/css/_app-layout.scss
ui/round/css/_constants.scss
ui/round/css/_material.scss
ui/round/css/_user.scss
ui/round/css/_zh.scss

To avoid losing vertical space, the material difference is shown below the user name next to the clock in the same way as in lichobile. The downside of this is that it may look a bit awkward when there is no material difference to show as the user name isn't vertically centered then. It would probably look better if the user name was shown in exactly the same way as it is now when there is no material difference. I haven't found a way to do this using only CSS, however. If there are ideas/pointer on how to do this, I would gladly implement this in this PR.
Since the pocket for Crazy House was using the same grid-area as the material difference, and this grid-area is now moved below the user name, this commit adds new grid-areas just for the pockets in 1-column mode. The mobile view for …

Show material difference in 1-column view

---

ui/analyse/css/_context-menu.scss
ui/analyse/src/treeView/contextMenu.ts
ui/analyse/src/treeView/treeView.ts
ui/analyse/src/util.ts
ui/tree/css/_tree.scss

Fixes #8851
Looks like browsers send `mousedown` events when a touch ends (i.e. on `touchend`).

Fix touch on analysis treeView

---

translation/source/puzzleTheme.xml

Correct misleading definition of "quiet move"

---

app/views/storm.scala
ui/puz/src/run.ts
ui/storm/src/ctrl.ts
ui/storm/src/view/main.ts

Resolves #8906. 
I've added the option to flip the board in puzzle storms but I'm not sure if it's the best implementation though. Let me know what you think.

Add option to flip the board in puzzle storm

---

ui/chess/css/_control.scss
ui/common/css/abstract/_extends.scss
ui/common/css/form/_cmn-toggle.scss
ui/round/css/_moves.scss

Closes https://github.com/ornicar/lila/issues/8857 (which is driving me insane :)
This is nearly identical to ornicar's initial fix (https://github.com/ornicar/lila/commit/3d010e47e1d6faf76a9e78d5a3617acf9c4f3da0) which was reverted since it stopped drag/drops on the board itself.
This PR applies the fix to the control elements other than the board itself.  Tested on an iPad.

Prevent safari from zooming in on double-tap

---

app/controllers/Mod.scala
app/views/simul/form.scala
app/views/user/perfStat.scala
modules/plan/src/main/Patron.scala
modules/plan/src/main/PlanApi.scala
modules/simul/src/main/SimulForm.scala
modules/simul/src/main/SimulRepo.scala
modules/user/src/main/Plan.scala
translation/source/activity.xml

Fixes #8244
Fixes #7584
Fixes #5010
Closes #5297
Currently, the month never increases because it always first updates the `lastLevelUp` and then checks again whether a level up is possible to decide whether to update the months.
Rest is mostly scalafmt, some cleanup, and making the activity entry more consistent, i.e. also show it for first-time patrons and use the correct month count.

Fix patron levelup

---

ui/analyse/src/plugins/nvui.ts
ui/chat/src/discussion.ts
ui/nvui/src/notify.ts
ui/round/src/plugins/nvui.ts

Fixes #8941.
- `aria-atomic` now uses string values instead of boolean values, so the resulting html is correct.
- In div.lastMove, every other ply gets a space added to the end, so consecutive move notations are always different by at least one space. Without this, the voice-over doesn't seem to happen on identical moves.
Tested with macOS 10.14 VoiceOver, Firefox 88, Chrome 90.

Fix missing voice-over of identical moves

---

app/controllers/Setup.scala
app/views/setup/bits.scala
app/views/setup/forms.scala
ui/lobby/css/_setup.scss
ui/lobby/src/setup.ts

Fixes #8600
Fixes #8886
Fixes #9002
Changes:
- Respect last selected time mode if not forced by setup
- Disable color buttons instead of hiding them to make it a bit clearer it's intentional
- Fix the bug where having 0+0 selected didn't allow FromPosition games after switching to unlimited time

More lobby setup fixes

---

app/views/puzzle/bits.scala
app/views/racer.scala
ui/puzzle/css/_side.scss
ui/puzzle/src/ctrl.ts
ui/puzzle/src/interfaces.ts
ui/puzzle/src/keyboard.ts
ui/puzzle/src/view/side.ts
ui/racer/src/ctrl.ts
ui/racer/src/view/main.ts

Added flip board + `f` hotkey for puzzles, streak and racer.
Wasn't sure where to put the button for puzzles + streak so I went with this in the end:
[![flip.png](https://i.postimg.cc/rF7NKg9Z/flip.png)](https://postimg.cc/mtNHnYJ7)
(also changed zen mode link from simple text to a button)

Add flip board for normal puzzles, streak and racer

---

modules/game/src/main/GameRepo.scala
modules/importer/src/main/Chess960.scala
modules/importer/src/main/ImporterForm.scala

Fixes #8485
And also more generally a bug where any PGN import for a variant with a non-standard starting position gets messed up because the final board position is used as the initial FEN.
That piece of code generally seems a bit sketchy but it seems to be necessary to get the initial FEN for FromPosition games in a few places. In those cases they are all new games though so it doesn't matter that it takes the final position.
I don't think it's ever needed for non-FromPosition games though and importing those without a FEN at least doesn't make sense anyway. But if I'm missing something, I guess the alternative would be to add something like  `initialFen | game.variant.initialFen` [here](https://github.com/ornicar/lila/blob/master/modules/importer/src/main/Importer.scala#L18).

Fix no-FEN imports

---

ui/round/src/ctrl.ts
ui/site/src/component/sound.ts

Fixes https://github.com/ornicar/lila/issues/8993.
The iPad (along wither other devices) requires an interaction to play a sound.  By preloading the sounds Howler will do it's best to unlock them on an interaction before they're needed.

Preload sounds when starting a game

---

ui/round/css/_app-layout.scss
ui/round/src/view/main.ts

It is now rendered at the same location as other negotiation controls (e.g., takeback and draw offers). It is also more consistent with the way lichobile renders move confirmation. This also prevents a vertical shift down of the board when the move confirmation was shown before this commit.
It is [unclear](https://github.com/ornicar/lila/commit/24ce308845c604380bce3c5a7b2ef3447a062701#commitcomment-51007078) why the move confirmation was put at the top of the screen in the first place. The only reason I can see why putting it below the board might hurt, is when using a screen with a very low height. This could cause the move confirmation to not be visible (as would be the case with the other types of negotiations today). I guess the only way to make sure it will always be visible, is to …

Render move confirmation below the board in 1-column view 

---

ui/tree/css/_tree.scss

Since some people were complaining about not being able to select and copy variations anymore.
I originally changed this because `clearSelection()` wasn't enough to always prevent all selections on touch long-presses but it looks like the remaining `user-select: none` on the context menu is enough to handle those cases.

Make moves user-selectable again

---

ui/site/src/userGamesDownload.ts

A day should be added to date-until but not to date-since if no time is specified.
If a user specifies a date range of 01.01.2021-02.01.2021 without specifying a time, it should result in a timespan of 01.01.2021 00:00:00 - 03.01.2021 00:00:00, so that all games played on 01.01.2021 and 02.01.2021 are downloaded, which is the expected behaviour.

Fix date range in userGamesDownload

---

ui/analyse/css/_training.scss

Fixes #5196
|Before|After
|:--:|:--:|
|![before](https://user-images.githubusercontent.com/19309705/120056125-9972b600-c03a-11eb-9bd6-6ae989185cc6.png)|![after](https://user-images.githubusercontent.com/19309705/120056126-9c6da680-c03a-11eb-9772-c054c9547d8d.png)|

Fix 'Learn from mistakes' being cut off on small screens

---

ui/learn/src/run/runCtrl.js

i.e. when clicking the big green area on the right quickly after completing the last level of a stage

Learn: Fix double sound when clicking 'next level' at stage end

---

app/views/team/tournaments.scala
modules/i18n/src/main/I18nKeys.scala
translation/source/team.xml

This is partly resolving #8492 by enabling translation for "Upcoming tournaments" and "Completed tournaments" - see screenshot 2.

missing translations, partly address #8492

---

modules/user/src/main/Links.scala

It appears to be commonly used, by streamers and not only, so it would be good to add it.

add instagram to user links

---

app/views/puzzle/bits.scala
app/views/puzzle/ofPlayer.scala
modules/i18n/src/main/I18nKeys.scala
translation/source/puzzle.xml

Adding missing translations related to /training/of-player. At some point in the future it may be good to move `class:lichessUsername` translation key to `site` but I will leave this to someone who has done it before.

Add missing puzzle translations, closes #9060

---

ui/analyse/src/explorer/explorerCtrl.ts

**Description:**
`OpeningData` is not fetched for moves after 25 as games are not indexed beyond this point.
As a side-effect, the opening name was also not displayed for all moves after 25.
So adding the additional opening info for all such moves.
**Before:**
**After:**
Closes #8989

Show opening name even after move 25

---

app/controllers/Dasher.scala
modules/i18n/src/main/I18nKeys.scala
translation/source/site.xml
ui/dasher/src/links.ts

Making "coach manager" and "streamer manager" translateable.

Missing dasher translations

---

ui/analyse/src/crazy/crazyView.ts

Closes #8911
Not sure whether this is actually necessary since there now hopefully shouldn't appear any more standard games with zh pockets anymore in the future after ornicar/scalachess#222 but I guess it still doesn't hurt just in case for the few games that are already in the DB.

ui/analyse: Force-hide zh ui if variant != zh

---

ui/analyse/src/explorer/explorerCtrl.ts

Fixes #8903
Setting `loading(true)` before redrawing avoids creating a move-arrow on hover. The old entries still flash for a moment but avoiding that without creating move-jank e.g. by simply resetting `lastShown` every time seems way too annoying.

Explorer: Fix stuck move-arrow after changing db

---

public/javascripts/chart/movetime.js

Feedback appreciated. To see how it looks on the site without spinning up lila, you can use the overrides feature in Chrome to override `movetime.js` with the version from this PR.

Remove space between movetime chart columns and make them look a bit nicer

---

public/javascripts/chart/movetime.js

To avoid tooltips flipping back and forth between black and white. I thought this makes sense to make both the line and bar highlight at once but it hardly makes a difference and the flipping back and forth is really annoying.

Make movetime chart tooltip unshared again

---

app/ui/scalatags.scala
app/views/coordinate.scala
ui/site/css/_coordinate.scss
ui/site/src/coordinate.ts

Fixes #9065
The issue isn't just relevant to very small board. Since currently coordinate font-sizes and positions are constant - coordinates are relatively small on bigger board and enormous (and overlapping) on smaller board.
I've reworked it with SVG so that font sizes and positions are scaled based on the board size.
| Board size | Before | After |
| -------------- | --------- | ------ |
| 200px      | ![200-before](https://user-images.githubusercontent.com/66057996/121790182-6e18cb00-cbe5-11eb-9a84-992da18c214f.png) | ![200-after](https://user-images.githubusercontent.com/66057996/121790183-707b2500-cbe5-11eb-8eaa-664bfa97688c.png) |
| 440px      | ![440-before](https://user-images.githubusercontent.com/66057996/121790185-72dd7f00-cbe5-11eb-9974-1d2ec96cf7cd.png) | …

Adjust coordinate size and position according to board size

---

app/views/coordinate.scala

Fixes #9063 
This is indeed a "feature" of Firefox. Firefox remembers form input values after reloading the page.
The solution is to set the `autocomplete` attribute to `off`.
Note from MDN:
> Note: The autocomplete attribute also controls whether Firefox will — unlike other browsers — persist the dynamic disabled state and (if applicable) dynamic checkedness of an `<input>` element, `<textarea>` element, or entire `<form>` across page loads. The persistence feature is enabled by default. Setting the value of the autocomplete attribute to off disables this feature. This works even when the autocomplete attribute would normally not apply by virtue of its type. See bug 654072.
[The HTML autocomplete attribute - HTML: HyperText Markup Language | …

Reset coordinate color preference after reload in Firefox

---

modules/game/src/main/Game.scala

Fixes #9072
I'm a bit unsure about this but as far as I can tell this check doesn't actually do anything (other than causing this bug)? I tested it and pool games are still aborted and arena tournament games are lost if either player doesn't make their move at the start. And as far as I can tell it shouldn't trigger anyway in basically all other situations.

Fix timeout after takeback on first move

---

ui/ceval/css/_pv.scss

When clicking the little arrow.

ceval: Avoid empty pv collapsing (i.e. after checkmate)

---

ui/round/src/ctrl.ts

Related: #9207, #9216, #9217
As per #9207, there should be no zen mode as spectator but people are still able to toggle it using the preferences page.

Disallow zen mode when spectating

---

modules/user/src/main/UserRepo.scala

btw, should `filterEngine` (used for striking swiss top3s) be changed to also check for other ToS marks since that's what most other things on Lichess do now? Seems a bit weird for this case but on the other hand, it's one of the remaining ways to identify that a mark is for cheating.

Remove unused UserRepo.isEngine

---

ui/analyse/src/autoShape.ts

Fixe #8604
This begs the question, how far do we want to go with ceval > server eval?
The main two things I see that are still not overwritten are the inline annotations (at least removing "lost checkmate" ones when ceval finds there's still a checkmate and possibly updating the "best move" for mistakes) and the eval graph.

Prefer ceval arrow over server eval

---

ui/analyse/css/_player-clock.scss
ui/analyse/css/study/_player.scss
ui/analyse/src/ground.ts
ui/chess/css/_promotion.scss
ui/puz/src/view/chessground.ts
ui/puzzle/src/view/chessground.ts
ui/round/src/ground.ts

Fixes #6874
It's a bit hacky but not sure if there's a much better way.
Also, I noticed that there's a lot of duplication with the promotion stuff. I didn't look at it too closely but it seems at least some of them could be combined into a shared file?
Is there something preventing that? And if not, what would be a good location for such a file? Just `common`?

Fix promotion overlay and study player alignment

---

ui/puzzle/src/ctrl.ts

Fixes #7847 making behaviour consistent with the analysis tool

Hide eval bar after checkmate in puzzles

---

ui/site/src/user.ts

Reload profile when switching to activity tab after clicking on `Advanced search`
Match behavior with all the games button (all, rated, etc.)
screen of the bug

Fix rating graph not showing

---

ui/puzzle/src/plugins/nvui.ts

In blind mode for puzzles, the arrow keys to move around the board don't work because they use keypress instead of keydown, and arrow keys aren't printable. This PR fixes that (my) mistake.

Fix arrow keys for navigating the board in puzzles in blind mode

---

modules/user/src/main/UserRepo.scala

BOTs should not be included in the aforementioned leaderboard which should be for human players only, there are other pages for BOTs. This commit prevents them from being included in "active players"

exclude BOTs from "active players" leaderboard

---

ui/chat/src/util.ts
ui/common/css/component/_mini-game.scss

Fixes #9219
| Before | After
|:--:|:--:|
|![after](https://user-images.githubusercontent.com/19309705/123155422-66b8b380-d468-11eb-8ae2-da4cae099699.png)|![before](https://user-images.githubusercontent.com/19309705/123155428-67e9e080-d468-11eb-866e-82af3eeea03e.png)|
Same in the chat where it also now uses "..." instead of just cutting it off.

Display overlong names better

---

ui/common/package.json
ui/game/src/interfaces.ts

`ui/common/richText` already uses `snabbdom` so it should be listed as a dependency. Not sure why it even worked without it.

Two random small fixes

---

ui/analyse/src/plugins/nvui.ts

Fixes three things:
- Last move board command doesn't work because the relevant element has className `position` instead of `lastMove`
- Board commands produce no output because `div.boardstatus` does not exist
- "c: announce last move's captured piece." This documentation exists, but c does nothing, since `lastCapturedCommandHandler` isn't used.

Fix nvui analysis commands

---

public/javascripts/chart/movetime.js

At least Firefox 61-72, Safari 11-12.

Fix movetime chart for legacy browsers.

---

app/controllers/RelayRound.scala
app/controllers/Study.scala
conf/routes

Unlike `/study/{studyId}.pgn`, this supports CORS and reading private
studies using the `study:read` OAuth scope.

provide study pgn api (lichess-org/api#119)

---

ui/ceval/package.json
ui/chat/package.json
ui/chess/package.json
ui/common/package.json
ui/game/package.json
ui/nvui/package.json
ui/puz/package.json
ui/tree/package.json

As yarn doesn't understand the paths like `../../node_modules/typescript/bin/tsc` on Windows, we have to remove the folder from the path to build on Windows so yarn finds itself `tsc` which is also in the folder `node_modules\.bin`. This should also work on UNIX systems so with this PR we can build the UI in all systems including Windows.

fix ui build on windows

---

bin/gen/timeago-to-scala.py
ui/@build/rollupProject/index.js

Hello, now that you removed the dirty hack for chrome in #9197 which caused a display bug on iOS 10 (issue #7525), do you have any reason left not to enable iOS 10 support?
If no, I prepared this PR which should be enough for lichess to be playable on iOS 10.
If you still don't want to enable this support, you should also say that you don't support safari 11, as from what I saw [there](https://terser.org/docs/api-reference.html), the minified JS bug is also present on safari 11.

support safari 10/11 in terser

---

app/ui/scalatags.scala
app/views/coordinate.scala
ui/site/css/_coordinate.scss
ui/site/src/coordinate.ts

Fixes #9337
There is a known issue with the `translate` CSS function in WebKit. 
A working fix is to wrap a `<text>` element in a `<g>` element and apply transform style there.
[183237 – Nested CSS transforms on SVG elements not updated after page load](https://bugs.webkit.org/show_bug.cgi?id=183237)
[CSS transform on SVG text element not working in Safari - Stack Overflow](https://stackoverflow.com/questions/58230668/css-transform-on-svg-text-element-not-working-in-safari)

Fix coordinate positions in WebKit

---

bin/trans-clean.py

I know they will be removed by crowdin eventually but it's still annoying to always have trans lints failing until then and can obscure some other new issues in PRs.

Add trans-clean.py to remove old trans keys

---

ui/analyse/src/study/studyView.ts

Accessing chapters tab in an empty round is occasionally useful for broadcasters, like when adding already finished rounds from a downloaded PGN, or in cases like [here](https://lichess.org/broadcast/katara-bullet-2021-finals/round-1/Pu3b4Rqc). It may also be useful under other circumstances I cannot think of right now - on the other hand making it visible for study members seems quite harmless.

always allow broadcast contributors see chapters tab

---

ui/round/src/view/button.ts

Fixes #3889. Fixes #9187.
**Current behavior:** When your opponent is away from the game, the rematch button will send a challenge instead of initiating or accepting a rematch request.
For normal games, this is desirable behavior because both players should be online to play. But for correspondence and unlimited games, this feels bad. If your opponent has already challenged you to a rematch, accepting should launch the game right away as they don't need to be around for the game to start.
**New behavior in correspondence and unlimited games:**
- When initiating a rematch:
- If your opponent is still at the game, no challenge is sent. Instead, a rematch is offered.
- If they are away, a challenge is sent,\* and in addition, a rematch is offered.
- When accpeting a rematch:
- Instead of …

Fix rematch behavior in correspondence and unlimited games

---

modules/tournament/src/main/ApiJsonView.scala

`hasMaxRating` is now useless since `maxRating` is only added when there is a limitation. I've left it for now for BC but should it be removed? Edit: since this endpoint is used internally it will need some frontend changes.
PR to update docs incoming

add `maxRating` and `minRating` to `api/tournament`

---

modules/challenge/src/main/ChallengeMsg.scala
modules/msg/src/main/MsgApi.scala

It also skips the empty message check but at least for the API messages, that's checked before anyway.
And besides the bulk API it also applies to challenge accepts via the API but that seems equally unproblematic.

Ignore msg security for Challenge API messages

---

ui/analyse/css/_explorer.scss
ui/analyse/src/explorer/explorerConfig.ts
ui/analyse/src/explorer/explorerView.ts
ui/analyse/src/plugins/nvui.ts

Years ago, the opening explorer existed in blind mode (#4882). I'm assuming it got removed when the original sidebar got removed. Would it be a welcome (re)addition?
The config span couldn't be detected by screen readers, so I made it a real button along with the other clickable spans.
Caveats:
- Clicking on table rows isn't very discoverable. There are multiple solutions (add hidden buttons, tabindex, keyboard shortcuts, shortcuts + `role="grid"`, or just document clicking behavior), but they all add code, and it isn't clear which is best, so I left the explorer as-is.
- The opening explorer isn't affected by move notation settings because it reuses the existing explorer implementation.

Add opening explorer & tablebase to blind mode

---

ui/analyse/src/ctrl.ts
ui/ceval/src/types.ts
ui/ceval/src/view.ts
ui/puzzle/src/ctrl.ts
ui/puzzle/src/interfaces.ts

Closes #5493. A duplicate issue is linked there, but for completeness, this feature has also been mentioned in #4164 which isn't otherwise linked.
My initial attempt at implementing this was to just call `playUci` in a loop. This works great for puzzles but fails in analysis because the moves sent to the server get interpreted as variations of the same ply instead of sequential moves. To solve this, I stored the moves to be played in a queue and sent the next move after every "node" response from the server.
From a user's perspective, hovering over local analysis lines works the same as before. But now, when they click on the line, instead of playing the first move and discarding the rest of the line, the moves up to and including the move that they clicked will all be played.
Since the …

When clicking on a specific move in a local analysis pv, skip to that move

---

ui/analyse/src/modal.ts
ui/common/src/modal.ts
ui/site/src/site.ts
ui/tournament/src/view/battle.ts

Addresses a point raised back in #1621.
> - Once we activate the link, the focus is not taken to the \#create a game -- it took me some time to realize that a section were added to the page.
> - suggestion: set the focus to be the start of the web page section that selects the game configuration.
When opening a new modal, focus now jumps to the first focusable element of the modal's content.
This PR also implements a couple of other keyboard accessibility features to make modals more ergonomic:
- Focus looping/trapping: tabbing or shift tabbing out of the modal will bring the focus back to the start or end.
- The close button for modals is now labeled for screen readers and acts like a button in response to keyboard input.

Improve keyboard navigation of modals

---

modules/api/src/main/GameApiV2.scala

See https://github.com/ornicar/lila/pull/5466
Swiss tournaments were added since the pull request above, and they would also be convenient in game JSON for determining performance in Atomic World Championship.

Expose swiss ID in game API

---

app/views/racer.scala
ui/racer/css/_race.scss
ui/racer/css/_racer.scss
ui/racer/css/_zen.scss
ui/racer/css/build/_racer.scss
ui/racer/src/ctrl.ts

There are [some people requesting for this](https://lichess.org/forum/lichess-feedback/feature-request-zen-mode-in-puzzle-racer) but I'm not sure if it is necessary. I thought I'd make a PR anyway to let you decide.
Hiding all elements on racer kinda defeats the purpose of a race. So I've only hidden the cars and the combo/controls area.
The tracks being visible is probably not very elegant but I've left it visible so users can see other people's scores.

Add zen mode to puzzle racer

---

ui/common/css/vendor/chessground/_board-3d.scss
ui/site/css/_coordinate.scss

Fixes #5049
`overflow-x: hidden` doesn't seem to work but it works with `clip` (and still avoids scrolling on mobile). As far as I understand, `hidden` always automatically applies to both axis.

Fix clipping of 3d pieces at the top

---

ui/site/css/user/_activity.scss
ui/site/css/user/_number-menu.scss

A couple css issues were reported [on the forums](https://lichess.org/forum/lichess-feedback/transparent-background-issues).
In both cases, the elements have the same background color as their containers, but since that color is translucent, extra opacity gets added. This PR removes the background css rule so that the backgrounds are transparent instead.
NB. The section under the username has class `number-menu`. That class shows up in two other places, but in those places, a different rule overrides the background, so the rule is safe to delete.
- [A](https://github.com/ornicar/lila/blob/8b403a6ee2f1e8b7fb1e87f9ed251208f9469d42/app/views/user/show/gamesContent.scala#L23) The `#games` tabs, where the rule is overridden by [`$c-bg-low`](https://github.com/ornicar/lila/blob/6048f3c4e223357ea …

Make transparent theme more consistent with light & dark themes

---

app/views/mod/inquiry.scala

fix inquiry engine button css

---

ui/round/src/plugins/nvui.ts

The resign text command in nvui searches for an older class which no longer exists.
The "resign-confirm" class comes from 2015 in db9d559. 84216b0 is the commit that removed "resign-confirm" and began using "act-confirm" instead. The nvui command for resigning comes from 420c9a9.
The current button for resigning is "button.resign", and it doesn't need confirmation when in nvui mode, so triggering a click on it correctly resigns.
Related #9529.

Fix resign command in nvui

---

ui/site/css/_search.scss

before
after
dark mode look the same (new)

fix download page css for light mode

---

ui/analyse/css/gamebook/_play.scss
ui/analyse/src/study/gamebook/gamebookButtons.ts
ui/analyse/src/study/gamebook/gamebookPlayView.ts
ui/common/css/abstract/_extends.scss

Makes progress on #9509. Also one step closer to maybe making fully-featured practice in nvui.
The clickable divs in gamebookEdit.ts were not changed because if I make them buttons, the flash of unstyled content as the css loads can become really unpleasant, particularly in dark themes.
`align-items: normal;` was added to `%button-none` to deal with Chrome's user agent style on buttons.

Use real button elements in gamebook

---

ui/analyse/css/_player-clock.scss
ui/analyse/css/study/_player.scss
ui/analyse/src/ctrl.ts
ui/analyse/src/study/playerBars.ts
ui/analyse/src/view.ts
ui/common/css/component/_material.scss
ui/game/src/interfaces.ts
ui/game/src/material.ts
ui/game/src/view/material.ts
ui/round/css/_material.scss
ui/round/src/interfaces.ts
ui/round/src/util.ts
ui/round/src/view/main.ts

Closes #9466, closes #206 
- Tested on games with and without a clock
- Tested in Chrome, Firefox, and Safari

Add material diff to analysis and study pages

---

ui/puzzle/css/_puzzle.scss

while building ui using ./ui/build, the following error occurs:
```
Error in plugin "sass"
Message:
puzzle/css/_tools.scss
Error: Undefined variable: "$mq-col1".
on line 139 of puzzle/css/_tools.scss
from line 7 of puzzle/css/_puzzle.scss
from line 18 of puzzle/css/build/_puzzle.scss
from line 2 of puzzle/css/build/puzzle.dark.scss
>>   @include breakpoint($mq-col1) {
```

fixing undefined variable error from #9435

---

ui/tournament/src/ctrl.ts
ui/tournament/src/pagination.ts
ui/tournament/src/search.ts
ui/tournament/src/xhr.ts

> [It would be useful to be able to search a player by their rank in a tournament, especially when there are a lot of players like in this 2021 Summer Marathon (20,000+ players). For example, I would just need to write #500 and I can see the top 500 player instead of scrolling down and pressing on the "next" button many times.](https://lichess.org/forum/lichess-feedback/feature-request-search-players-by-their-rank-in-a-tournament)
The \#number syntax is nice. It avoids sending user autocomplete xhr because of the existing [regex](https://github.com/ornicar/lila/blob/322dea6eb34e2a4880f155941dbec756fa319e88/ui/site/src/userComplete.ts#L67).
I also made escape dismiss the search input.
In the code, pages and ranks are 1-indexed. Rows within a page are 0-indexed.

Search for players by rank in tournaments

---

ui/analyse/src/autoShape.ts
ui/analyse/src/explorer/explorerView.ts
ui/analyse/src/explorer/interfaces.ts

This is my first time contributing to this repo and first PR for an open-source project in general so any feedback is appreciated! These changes resolve #8847 by showing the win rate statistics for the current board position in the opening explorer. The necessary statistics for the current position were already being pulled from the API call that is made to get information for the opening explorer. However, this information was not previously being propagated to the UI functions responsible for showing the opening explorer table. I tested these changes by trying different cases locally.

Show current position stats in opening explorer

---

ui/analyse/src/study/topics.ts

In my editor, if I use the "hover" mode to see the "type" of the `Tagify` object, it returns `any`, but if you look at the real type https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yaireo__tagify/index.d.ts#L351 it requires as it's first arg a: `input: HTMLInputElement | HTMLTextAreaElement,` but we are suggesting that it can be any `HTMLElement` which is not technically assignable to the above argument without a cast. 
I think we should also try and figure out why typescript wasn't picking this up to begin with, but I don't know why that is.  Regardless, I think this is the correct fix.

Fix typing for Tagify constructor.

---

ui/insight/src/view.ts

TIL the difference between changing classes via attributes and changing classes in the selector. Doing it via attributes avoids rerendering the entire div when the class changes, thus fixing the regression where selecting a filter option would close the options list.
Addresses the second part of #9567.

Fix filter regression (insights)

---

ui/insight/src/chart.ts

The type annotation for categories is wrong; dates should be numbers, not strings.
This fixes the format of dates in tooltips, and it fixes the issue of dates not showing up beneath the x-axis. Address part of #9567.

Fix date disappearance (insights)

---

ui/insight/src/filters.ts

> Another minor issue I've come across is the clear button on filters. It shows the correct insight upon clearing but the filter itself still says 12 of 14 selected with variant filtering for example.
Closes #9567. 
- Clear filters by calling `multipleSelect('uncheckAll')` instead of reinitializing multipleSelect.
- Only clear filters when `ctrl.vm.filters` is `{}`, which only happens after clicking on the clear button. They used to get cleared on every redraw if a dimension had no active filters. This fixes an issue where deselecting the final checkbox of a dimension recreated the list of checkboxes and made them disappear from underneath your mouse. It also saves a bit of computation.
- Set `selected` to false instead of undefined. This fixes an edge case where all checkboxes of a …

Fix clearing insights filters

---

modules/tournament/src/main/ColorHistory.scala
ui/analyse/src/view.ts

Fixing issue with commit https://github.com/ornicar/lila/pull/9481/commits/1b1d0964488feaa6fb01c18602b8ac248ae6bb21 where material imbalance is displayed on the opposite side when a study chapter's orientation is set as black.

fixing issue where material imbalance is displayed on the opposite side when a study chapter's orientation is set as black.

---

ui/analyse/css/study/_index.scss

In https://lichess.org/study:
There's some weirdness in the height calculation + inconsistent centering that's causing this misalignment. As it so happens, removing the [flex gutter hack](https://github.com/ornicar/lila/blob/011adde3659561f4fb41b6fc68fe52c0d7b05d2b/ui/analyse/css/study/_index.scss#L10) (370417/lila@ec4ffbd4300dbe58950402980e37b3cba8262865) corrects the misaligment by fixing the height calculation of `.box__top`. But support for column-gap isn't that comfortably widespread yet ([caniuse](https://caniuse.com/mdn-css_properties_column-gap_flex_context)), notably missing one third of iOS users and missing Chrome ten-versions-ago and Firefox 61/62. So this PR is an alternate little fix using `align-items: start`.

Fix study .box__top alignment

---

ui/analyse/src/moveView.ts
ui/analyse/src/study/studyCtrl.ts

Indicator not showing immediately but only afters when going to another move, and deleting the shape would not remove the indicator until page reload.
before
after
Didn't find a way to only redraw the move column, or a better place for `redraw`

Study: Fix shape indicator in moveview

---

ui/analyse/css/_explorer.scss
ui/analyse/src/explorer/explorerView.ts

This is my proposal for a clearer presentation of the opening explorer's awesome new feature.
- Color the background, reduce text contrast, and reduce the row height to associate it more closely with the table header.
- Dim and flatten the White / Draw / Black bar as if it were a disabled button.
Our brains like to gravitate towards the first element of a list, so I wanted to reestablish the top move as the first element of its group of visually similar elements. That helps users click on what they want to click on. The Current/All row still looks similar enough to the others that it's clear what it represents.
- Change "Current" to "All" following lichess.org/@/InfiniteFlash's suggestion. I think this fits better with the other cells in the column. "All" represents all the moves that …

UI proposal for the explorer's current move stats

---

modules/study/src/main/StudyApi.scala
ui/analyse/src/study/chapterNewForm.ts

before
after
The underlying issue was an offset in all chapters `order` created when creating the first chapter of a study.
When a study is created it's populated with an empty (`initial` in the codebase) chapter, but it's hidden by the UI which shows to the user the form to create the first one. When doing so, the `initial` one is removed. However the `order` of the user-created chapter was computed before erasing the initial one, resulting in an offset.

Study: fix chapter number when importing multiple chapters at once.

---

ui/site/css/forum/_reactions.scss

On the forum, reaction images have a right-margin intended to separate them from the number of reactors. When no one has reacted, this margin throws the reaction image off-center, so this PR hides the margin when it is not needed.
Before/after:

Center reactions

---

ui/analyse/src/view.ts
ui/game/src/view/material.ts
ui/round/src/view/main.ts

Recently, there have been a few bugs that rendered the material difference on the wrong side of the board. For example, in #9573 the material diff was on the wrong side in studies that started from black's orientation. This was fixed in #9583 but this [introduced the same bug for normal analysis boards](https://github.com/ornicar/lila/pull/9583#issuecomment-900275310).
The interface of `renderMaterialDiffs` was rather confusing and error-prone as it had a `flip` argument and it wasn't entirely clear what this was supposed to do with respect to the `player` and `opponent` arguments, especially in the case of studies (what is the interpretation of player and opponent here?).
Since `renderMaterialDiffs` doesn't care about players and flipping but only cares about which color is shown on …

Make the interface of renderMaterialDiffs less error-prone

---

ui/ceval/src/ctrl.ts
ui/ceval/src/view.ts
ui/site/package.json
yarn.lock

Hi guys, it's been a while since the last contribution, but recently I got back to wasm simd stockfish port and updated the package, which now includes features from Stockfish 14.
This means that the size of `stockfish.wasm` increased quite a lot due to the new neural network (47MB originally and 27.6MB after compression), so I'm not sure how easy it is for Lichess to actually deploy this one as it is.
For this version of my port, I added a feature to load .nnue file separately from .wasm file itself, so this might help in some way.
Please let me know if you guys have any considerations about this and feel free to ask me any questions about the new version (as before, you can find my repo here https://github.com/hi-ogawa/Stockfish).
Thanks!

Update stockfish-nnue.wasm 1.0.0

---

ui/analyse/css/_analyse.base.scss
ui/analyse/css/_analyse.round.scss
ui/analyse/css/_layout.scss
ui/analyse/src/view.ts

Since #9481 the material difference is shown in analysis mode. However, when there are no clocks, the material difference disappears. This is unfortunate as there is no material difference as soon as you move a way from the mainline.
This PR simply reverts 18633dde5a81a63fd871fc12529ebac4aedff129 which disables material difference when there are no clocks. This seems to work perfectly but since I don't understand the purpose of that commit, I might be missing something.

Show material difference in analysis even when there are no clocks

---

ui/site/css/forum/_post.scss

fix `edit` button color in forum posts

---

ui/chat/css/_discussion.scss

before:
after (tested on Safari and FireFox):

Center vertically report/timeout icon in chats

---

ui/analyse/src/study/studyForm.ts

Someone [on the forums](https://lichess.org/forum/lichess-feedback/i-delete-a-study-but-it-doesnt-work) had trouble deleting a study on their phone but succeeded on their laptop. There's a decent chance the problem had the same root cause as veloce/lichobile#1806, where phones add trailing spaces to words. Trimming the user input accounts for this extra space.
I also call `trim` on the name of the study because javascript's `trim` removes non-breaking spaces but scala's doesn't seem to. Otherwise, a study with leading or trailing nbsps would be impossible to delete unless you rename it first.

Trim spaces when deleting studies

---

app/views/tv/games.scala
ui/site/src/tvGames.ts

Related: #9646.
Finished games don't have the data-live attribute on initial load, so I took the game id from the href instead.
I also found out about Cash's `replaceWith`, so there's no need for the wrapper div I was originally using.

Replace games in /games even if they load already finished

---

bin/mongodb/indexes.js

Adding record to mongodb script to add index for cache collection. Should be useful for new installations of lila as number of features rely on it.

add index to cache collection in mongodb

---

ui/analyse/src/serverSideUnderboard.ts
ui/cli/src/main.ts
ui/round/src/socket.ts

The modal CSS expects a wrapper div for scrolling purposes:
https://github.com/ornicar/lila/blob/c6554780966e39ff117af33c2002f2c7b8565420/ui/common/css/component/_modal.scss#L17-L21
That CSS is currently applied to each `div.command` of the /help modal, which puts padding in the wrong place and makes scolling impossible on small screens.
There are two other modals I found which are missing a wrapper div:
https://github.com/ornicar/lila/blob/master/ui/analyse/src/serverSideUnderboard.ts#L139
https://github.com/ornicar/lila/blob/master/ui/round/src/socket.ts#L156

Wrap modals in divs

---

ui/build
ui/chess/package.json
ui/chess/tsconfig.json
ui/common/package.json
ui/common/tsconfig.json
ui/game/package.json
ui/game/tsconfig.json
ui/nvui/package.json
ui/nvui/tsconfig.json
ui/puz/package.json
ui/puz/tsconfig.json
ui/round/src/view/button.ts

To avoid all the clutter from the build output in the module base directories.
Bumps the minimum node version to >=12.20 or >=14.13 because of the export maps (which are what allow moving the output while still allowing rollup to find them correctly without explicitly specifying the `dist` directory in the import) but that hopefully shouldn't be an issue.
The `typeVersions` stuff is a bit weird but that seems to be the only way to get TS to find the stuff for now until it gets proper support for export subpaths.

Move all tsc output to dist subdirectories

---

ui/common/css/abstract/_uniboard.scss
ui/round/css/_app-layout.scss

Closes #9522
The idea is pretty simple:
Calculate the maximum available space for the board by calculating the max height (as before) and the max width (100vw - everything left and right of the board if it's as small as possible). The board shouldn't be larger than the smaller of those two. This is our 100% scaling and everything else is just scaled from there. By moving the scaling to the outside, it's not really necessary to have an extra minimum since the scaling is already capped at 30%. Although I guess in theory, an extra minimum could be added.
On most screens (all wide ones) it should look pretty much the same. On 100% scaling it's actually exactly the same but since the scaling is now outside, it's not quite the same on lower scalings.

Fix uniboard max size on vertical screens

---

app/views/user/show/side.scala

I'm not sure it was intended that others can see the difference between 'no puzzle rating' and 'dubious puzzle rating', because the former has the question-mark in bold and the latter does not.  This pull request changes both question marks to bold so they look the same.

Fix dubious puzzle rating showing differently from no puzzle rating

---

ui/@types/lichess/index.d.ts
ui/analyse/src/ctrl.ts
ui/analyse/src/practice/practiceCtrl.ts
ui/analyse/src/retrospect/retroCtrl.ts
ui/ceval/src/util.ts
ui/ceval/src/view.ts
ui/puzzle/src/ctrl.ts

As discussed on Discord, it's strange to have a ceval going on without being able to see anything. Since there isn't really space to nicely show both the cloud eval depth and the ongoing work, preferring the local eval if it's ongoing seems to be the best option.
This now prefers incoming local evals over cloud evals if the local eval has a higher max depth than the cloud eval has actual depth. This should only happen when the user asked to go deeper than the cloud eval or in the rare case that the cloud eval's depth is so low that the initial local eval isn't stopped, in which case it should quickly catch up anyway.
Coincidentally, this also means users are now able to disregard cloud evaluations in case they are faulty (e.g. due to #9715) or have an overrated depth due to improvements …

Prefer ongoing ceval over cloud

---

app/views/user/perfStat.scala
app/views/user/show/page.scala
modules/history/src/main/RatingChartApi.scala
modules/user/src/main/User.scala
public/javascripts/chart/ratingHistory.js

The navigator below the rating graph on a user's profile always shows bullet rating history. This PR shows the user's rating history from their most played time control or variant instead.

Show user's best perf in rating graph navigator

---

ui/dasher/src/board.ts

After #9675, zoom is represented in the range [0, 100] instead of [100, 200].
Reported [in the forums](https://lichess.org/forum/lichess-feedback/resizing-board#4).

Fix zoom input range

---

ui/analyse/css/study/panel/_comment.scss
ui/analyse/src/study/commentForm.ts
ui/analyse/src/study/studyComments.ts
ui/common/css/component/_button.scss

Fixes #9718
Closes #9599 
The comment box now consistently gains focus when pressing `d` and keeps that focus when switching to another move, except when making a move on the board (unlike currently, where the focus is kept through some navigation, e.g. scrolling and clicking the arrow buttons, but not through clicking on a move in the table).
There's also a new `X` button to immediately start editing the comment for the current move when the comment for another move is shown.

study: Fix comments focus behavior

---

ui/gulpfile.js
ui/package.json

Closes #7190
This seems to be the best way to keep nicely formatted error messages, don't abort watching but still cause the tasks to actually fail for the non-zero exit code.
`plugin-error` is already a dependency of `gulp-sass` (and probably more) so not really an extra dependency.

ui/gulp: Induce non-zero exit status when sass build fails

---

modules/msg/src/main/MsgSecurity.scala

Private messages communication between shadow-banned users was still possible (received notifications, messages weren't hidden in inbox).

Fix sbed-sbed communication

---

ui/dasher/css/_dasher.scss

Removing the padding-top from the dasher, so that there will be no extra space sticking out in the dasher when the sound is set to full.
Full sound:
Mute:
Full sound:
Mute:

Removing dasher padding to get rid of extra space

---

modules/hub/src/main/actorApi.scala

They cannot access these items anyway.

Hide Streamer and Blog likes notifications for kids

---

public/javascripts/chart/ratingHistory.js

Last year we did this one to make a horizontal line in the ratings chart for days with no activity: https://github.com/ornicar/lila/pull/6902
But the end of the ratings chart is whatever day you last played:
In theory the line should end at today. If no activity in three months, it should just be a horizontal line.

Flatten rating line to today

---

ui/analyse/src/study/commentForm.ts
ui/analyse/src/study/description.ts
ui/analyse/src/study/gamebook/gamebookEdit.ts

Is there a reason to use the other two? They don't work with autocorrect: https://lichess.org/forum/lichess-feedback/spell-check-corrections-dont-save-in-study

Use oninput instead of onkeyup & onpaste

---

ui/common/css/component/_button.scss

`button` tags are already `inline-block` so this just makes `a` tags consistent with them.
Main reason is to allow proper line-wrapping and avoid overflow on the team edit page (the buttons at the top) and in certain cases also blogs (when viewing as oneself, with the edit button) on slim screens.
I checked some random pages with buttons and I don't think this breaks anything?

css: Make .button display: inline-block

---

app/controllers/Api.scala
bin/mongodb/tournament-lichess.js
conf/routes
modules/tournament/src/main/Status.scala
modules/tournament/src/main/TournamentApi.scala
modules/tournament/src/main/TournamentRepo.scala

Current API endpoint always returns all tournaments created by a given user - past ("status":30), currently running ("status":20) and future ("status":10)
People who organize tournaments regularly on lichess.org and would like to provide a list of upcoming tournaments on their own web site for participants to join would have to filter out all past tournaments after first receive a huge JSON containing mostly irrelevant records.
This can be especially slow with time once many completed tournaments accumulate and number of past tournaments becomes significantly larger than the regularly organized future tournaments (which at any given moment are somewhat constant). 
Taking into account also the throttling that is happening during generating those JSON results by lichess API, this can …

Add filtering by status to api/user/{username}/tournament/created

---

app/views/tournament/bits.scala
modules/tournament/src/main/Schedule.scala

Reverts ornicar/lila#9852
See [zulip convo](https://hq.lichess.ovh/#narrow/stream/58-dev-bug/topic/confusing.20arenas.20names)
should be "Daily SuperBlitz" instead of "Daily Blitz Arena"
Also I seem to recall that these translations were intentionally not done to avoid awkward weirdness in some languages, but I might be wrong about that.

Revert "Improve tournament names translation"

---

ui/common/css/vendor/chessground/_chessground.scss

Currently _dragging z-index_ set in CSS is not applying to 3D pieces cause piece's _z-index_ set as inline style overwrites it. As a result dragging piece might be displayed under other pieces.
https://user-images.githubusercontent.com/66057996/134406773-54b0be2c-8605-4fb8-9c22-c374ec644217.mp4
This could be fixed by adding _!important_ rule to _dragging z-index_ in CSS.
Naturally, it's not the best practice to rely on _!important_ rule, but since _z-index_ for 3D pieces is set as an inline style that is the only option to override it. Other option could be reusing inline styles, i.e., setting _dragging z-index_ on drag start and setting back _normal z-index_ on drag end, but this looks less pragmatic since the same _dragging z-index_ would be defined in both _css_ and _js_ in this case. …

Fix dragging 3D piece elevation

---

modules/ublog/src/main/UblogMarkup.scala

For #9767, `unescapeUnderscoreInLinks` was defined but wasn't being called after 5225485c7bf3386a127148614d7f28e0a1a78007, as `unescapeAtUsername` was called twice instead.

Call the unescapeUnderscoreInLinks function

---

app/controllers/Ublog.scala

For now they can still post blogs, which could be useful to post articles (like maia) on their specifities and/or development.

Bots cannot like ublogs.

---

modules/game/src/main/PgnDump.scala

closes #9883
The default FEN is not necessary as it can be inferred from the variant.
FEN is anyways fetched for games with custom start position. https://github.com/ornicar/lila/blob/master/modules/game/src/main/GameRepo.scala#L436
Related discussion
https://github.com/ornicar/lila/pull/9899

remove default initial fen

---

app/controllers/Tournament.scala

One of the many ways in which "user organized" tournaments are currently in a disadvantage compared to the "official" lichess arenas is that they are almost impossible to access on mobile app.
This is a source of substantial frustration in lichess players, to the point a workaround has actually been invented and is being communicated mouth-to-mouth about how to join a community arena on mobile app (see private description of lichess.org/team/underground-crazyhouse-hourly-arenas for details of the workaround). 
Goal of this PR is to make this workaround obsolete and make team tournaments visible in mobile app's "Tournaments" screen
- Scope: This change will affect requests to "/tournament" endpoint when made with "application/vnd.lichess.vXY+json" header.
- As far as I can tell this is …

Mobile app to show team tournaments

---

modules/perfStat/src/main/PerfStat.scala

Bug: the first game of a new streak is not counted in the streak,
neither in `games played in a row` nor in `max time spent playing`. Bug
is not present if the game is the first one ever under that time
control.
Step to reproduce: play one rated game using a time control previously
used (e.g. blitz) even though not in the last hour, than go to
`lichess.org/@/<user>/perf/blitz` and note
that both `current streak` at the bottom of the page are still zero.
From the second game the `current streak` of `games played in a row` is
systematically one less than expected, while the other one does not
count the elapsed time of the first game.
Troubleshooting: the bug is due to the call at `Streak.init`
(i.e. `(0, none, none)`) when a game is discontinued from the previous one.
I propose, with this …

Bugfix in PlayStreak

---

ui/analyse/src/autoShape.ts
ui/analyse/src/explorer/explorerView.ts
ui/analyse/src/fork.ts

In the current analysis view, the opening database has a hover functionality.
If you hover over any moves in the opening explorer,
an arrow will appear, showing you that move on the board.
This pull requests implements the same functionality for the fork selection box.
Just a nice-to-have feature that I wanted myself as I'm relatively new to chess and am not yet fast enough at reading moves by name. The arrows make it nicer to browser studies imo.
Potential Issues
==========
The opening explorer effectively made the assumption it was the only tool adding a hover arrow to the board. `postpatch` effectively removed any hovers produced by other tools as a result. Therefore I had to remove this, but it did serve a function, which was to ensure `hovering` was correctly cleared when no longer …

Add hover arrows for mouseover of forks

---

ui/ceval/src/view.ts

Clicking on pvs tries to play moves even in threat mode. This isn't a problem on the analysis board because the server rejects nonsensical moves, but in puzzles, this allows one color to move twice in a row.
Reported [in the forums](https://lichess.org/forum/lichess-feedback/bug-moves-played-within-threat-confuses-whiteblack-notation-in-scorecard).

Don't play pv in threat mode

---

ui/round/src/ctrl.ts

Previous behavior kept the board unsynced with the server position, confusing players as to why they lost on time AFTER moving. It wasn't until the expiration of the `TransientMove` that the board would be synced again.
Unlike when premoving I haven't found an easy way to undo the move, hence reloading chessground. I have restricted it to `outoftime` outcome for now, maybe `abort` would make sense too.
Illustration of the initial issue:

Show correct position when timing out before the move reaches the server

---

app/views/forum/post.scala
ui/site/css/forum/_post.scss

Resolves #9836 
I've explored a bit how OP's highlighting is implemented in other forums and seems that the most common patterns are showing "OP" badge next to a username or simply highlighting a username (or even the whole post header) with some different background.
My personal feeling is that adding a different background to user link is a better choice than "OP" badge cause even though "OP" is a pretty common phrase in web it still might be misunderstood by non-English speaking users.
I looked it up in other Lichess pages for some suitable pattern/colors in order not to bring something new and found that topic badge design from [Study topics](https://lichess.org/study/topic) might work. Using the same background colors highlights the user link well (but doesn't draw too much …

Highlight original poster in forum topic

---

ui/tournamentSchedule/src/view.ts

When calculating which bar can or cannot fit on which lane, the logic sometimes discards a bar as unable to fit just because of an overlap in mere seconds, which creates huge gaps in the timeline which however seem unnecessary because overlap is invisible or negligable.
This lichess forum post contains one screenshot showing the problem:
https://lichess.org/forum/team-underground-crazyhouse-hourly-arenas/tournament-timeline-gaps#1
However I am almost sure i have seen this problem happening not only with community organized tourneys, but also with official tournaments when they start/end on a full hour sometimes.
- I've added truncation to a whole minute when comparing the epoch value for start/end of tourneys in the UI logic
- Don't know if an existing util js/ts function or library that …

Tourney Schedule: trunc seconds when fitting tourney bars into lanes

---

ui/site/css/mod/_communication.scss

Issue: 
On smaller displays the public-chat page can push tournament chats to the next row rather than always render 3 chats in a row. This happens when 1 of the 3 tournament title texts is longer than the others and wraps to a new line. 
Before 
https://user-images.githubusercontent.com/77537716/135719388-bfc37caf-aa25-4599-a0d0-ab72dcd3b1a5.mov
After
https://user-images.githubusercontent.com/77537716/135719412-33ea9c72-2401-425a-8e55-45ccfd84e055.mov

Public chats grid flex fix 

---

modules/chat/src/main/ChatApi.scala
modules/chat/src/main/ChatTimeout.scala

They were removed from the public-chat page.

Public-chat page: remove "simul" channel

---

ui/round/css/_app-layout.scss
ui/round/css/_constants.scss
ui/round/css/_streamer.scss

Since that one Chrome update a few weeks ago that broke the chat height as well, there's also a weird gap on round pages between the crosstable and the board.
https://lichess.org/tv/classical is an easy way to see it. In Firefox it looks like before.

Fix gap below round board on new Chromium

---

public/javascripts/chart/ratingDistribution.js

Lower the z index of the x/y gridlines so they don't obscure other chart elements like the "Your rating" line.
Fixes #9926

Render grid lines behind other chart elements

---

ui/analyse/src/wiki.ts

Wikibooks has redirects for common transpositions, e.g. "[Chess Opening Theory/1. Nc3/1...c5/2. e4](https://en.wikibooks.org/w/index.php?title=Chess_Opening_Theory/1._Nc3/1...c5/2._e4&redirect=no)" redirects to "[Chess Opening Theory/1. e4/1...c5/2. Nc3](https://en.wikibooks.org/wiki/Chess_Opening_Theory/1._e4/1...c5/2._Nc3)".
I added the [`redirects`](https://www.mediawiki.org/wiki/API:Query#Resolving_redirects) parameter to resolve these redirects.
I did not test this PR.

Resolve Wikibooks redirects

---

ui/round/src/plugins/keyboardMove.ts

Closes issue #10058 
* Edited regex for Crazyhouse keyboard move inputs so that the `@` is recognized without looking like an error. 
* Also put in a similar fix to the `resign` input so that the string is recognized while being typed.
1. Ensure that `Input moves with the keyboard` is set to `Yes` in settings
2. Start a Crazyhouse variant game
3. After a peice has been taken, attempt to place it using the `@` character, such as `B@a3`
4. Attempt to resign the game by inputting `resign`
5. Both (3) and (4) should not cause an error sound or cause the box to turn red at any point in the input.
Refer to issue #10058 for full details

String parsing of keyboard move input fix

---

translation/source/challenge.xml

Cancelled takes two `l` in british english, also makes it consistent with other source strings

Fix source string

---

modules/game/src/main/GameRepo.scala
modules/lobby/src/main/AbortListener.scala
modules/lobby/src/main/Biter.scala
modules/user/src/main/UserRepo.scala

Not sure about the cache duration. Normal games are auto-aborted after 1 hour and correspondence games after 1 day I think but unlimited only after 10 days.
Also added an upper limit of 5 to be safe.

Don't adjust colorIt when aborting fixed color lobby games

---

ui/analyse/src/wiki.ts

Replacing the characters: `+` `!` `#` `?` after they are read from `PGN` textarea on the Analysis Board Page, this was done to solve this[ issue-10088](https://github.com/ornicar/lila/issues/10088):
>  Steps to reproduce the bug
> 
> Open the Analysis Board, and import following PGN:
> 1. e4 b6 2. d4 Bb7 3. Bd3 f5 4. exf5 Bxg2 5. Qh5+ g6
> Chess_Opening_Theory/1._e4/1...b6/2._d4/2...Bb7/3._Bd3/3...f5/4._exf5/4...Bxg2/5._Qh5/5...g6 should be displayed.
> 
> Import following PGN:
> 1. f3 e5 2. g4 Qh4#
> Chess_Opening_Theory/1._f3/1...e5/2._g4/2...Qh4 should be displayed.
> 
> What happened instead?
> The + and # signs were not removed when creating the Wikibooks URL. If you navigate to the move Qh5+ the Wikibooks page does get displayed but only because the + sign is interpreted as a …

issue-1088 | Fix: + and # sign are not removed from Wikibooks URL

---

ui/common/css/component/_loader.scss

Disables the path animation of the loading spinner if the OS asks for reduced animation.

Don't animate spinner motion according to prefer-reduced-motion

---

modules/fishnet/src/main/FishnetOpeningBook.scala

so that low levels can still play natural blunders from the book
at level 1, the weight is proportional the number of times the move has been played: wins + draws + losses
at level 8, the weight is proportional to the expectation value: wins + 1/2 draws
when there are few games in the database, give fishnet a higher chance to think on its own

tweak fishnet book move selection

---

modules/common/src/main/Random.scala
modules/fishnet/src/main/FishnetOpeningBook.scala

On certain levels, e.g. SF level 2 in Blitz, the total number of moves * 14 (during [score calculation](https://github.com/ornicar/lila/blob/master/modules/fishnet/src/main/FishnetOpeningBook.scala#L86)) will overflow the int limit and `nextInt` will throw since the bound will be negative.

Fix overflow in fishnet opening book

---

app/controllers/LilaController.scala
modules/common/src/main/HTTPRequest.scala

On pages embedding Stockfish (i.e. using SharedArrayBuffer).
To allow custom backgrounds from non-CORS pages.

Use 'Cross-Origin-Embedder-Policy: credentialless' in Chrome 96+

---

ui/ceval/src/ctrl.ts

Some browsers don't report navigator.deviceMemory to keep
fingerprintability to a minimum. Currently, lila assumes that
such a machine provides at most 256MB RAM, thus setting a 32MB
max hashtable limit.
This was a reasonable starting point when Stockfish was pure
JavaScript in a single thread, but with up 16 core WASM support
this limitation is a bit more painful.
Modify the memory estimation: if the browser is modern enough to
have full WASM/SharedArrayBuffer support, and thus run the
parallel WASM versions, assume the machine has at least 2GB of
RAM. If it doesn't, assume 512MB. This gives a maximum hashtable
of 256MB and 64MB, respectively.
The assumed minimum RAM values roughly correspond to Firefox's
official system requirements for the 32-bit and 64-bit version.
Although that …

Improve maximum hash table memory estimation.

---

ui/lobby/src/view/pools.ts

Closes #10214 
I opted to not show any rating range as I think that is most inline with the intended UX of no rating mode

hide rating range in lobby pools if showRatings disabled

---

ui/puzzle/css/_tools.scss

The top border of the moves list is perceived as an off-by-one error:
Because it looks like a shadow it appears to be 1px below the chess board.
before:
after:

Remove top border of puzzle__moves

---

ui/analyse/css/_player-clock.scss
ui/analyse/css/study/_player.scss

|Before|After|
|:--:|:--:|
|![analysis_before](https://user-images.githubusercontent.com/19309705/144051082-0a30ec49-a5f8-486e-9826-4fdca1e2fd75.png)|![analysis_after](https://user-images.githubusercontent.com/19309705/144051105-eae188ae-9070-469c-aef6-6170e194ac0f.png)|
|![study_before](https://user-images.githubusercontent.com/19309705/144051158-af13b8cd-cda0-49a0-88a9-f757fa8f1086.png)|![study_after](https://user-images.githubusercontent.com/19309705/144051181-fbf37c63-5cd1-4444-a89c-4e7398547216.png)|
It looks a bit weird but I'm not sure there's a better simple solution and I think it's better than it just not being visible at all.

Fix top player/material/clock bar on 3D boards

---

ui/analyse/src/explorer/explorerView.ts

This addresses issue #10238
Motivations of the change:
1/ It's not clear what the close button is going to do when pressed
2/ The message 'no game found' is only for the player tab, but the close button removes everything (masters, lichess and player)

don't show close button when no game found

---

app/controllers/Editor.scala
app/controllers/Setup.scala
app/controllers/Study.scala
app/views/board/bits.scala
app/views/board/editor.scala
app/views/setup/bits.scala
app/views/setup/forms.scala
app/views/study/create.scala
ui/analyse/package.json
ui/chess/package.json
ui/common/package.json
ui/editor/package.json
ui/editor/src/ctrl.ts
ui/editor/src/view.ts
ui/game/package.json
ui/lobby/package.json
ui/nvui/package.json
ui/puz/package.json
ui/puzzle/package.json
ui/racer/package.json
ui/round/package.json
ui/round/src/crazy/crazyView.ts
ui/simul/package.json
ui/site/package.json
ui/storm/package.json
ui/swiss/package.json
ui/tournament/package.json
yarn.lock

Find all places that produce editor links on the server and client side and let them produce identical URLs, taking into account the variant.
Also needs chessground 8.1.9 to fully fix #10230 (handling of `~` was broken at some point, `[]`-style pockets were causing runtime errors).

preserve variant when editing game position (fixes #10230)

---

app/controllers/Auth.scala
app/views/oAuth/authorize.scala
build.sbt
modules/api/src/main/ReferrerRedirect.scala
modules/api/src/test/ReferrerRedirectTest.scala
modules/common/src/main/Form.scala
modules/common/src/main/String.scala
modules/common/src/main/model.scala
modules/db/src/main/Handlers.scala
modules/oauth/src/main/AuthorizationRequest.scala
modules/oauth/src/main/OAuthTokenForm.scala
modules/oauth/src/main/Protocol.scala
modules/relay/src/main/RelayFetch.scala
modules/relay/src/main/RelayFormat.scala
modules/relay/src/main/RelayRound.scala
modules/relay/src/main/RelayRoundForm.scala
modules/relay/src/main/RelayTourForm.scala
modules/user/src/main/Links.scala
project/Dependencies.scala

Differences between browsers (following https://url.spec.whatwg.org/) and io.lemonlabs.uri (following https://www.ietf.org/rfc/rfc3986.txt) can lead to subtle bugs.

replace lemonlabs.uri with a whatwg compliant parser

---

ui/analyse/src/explorer/explorerConfig.ts

Add date input placeholders with required format (YYYY and YYYY-MM)
Add meaningful hover title with required format for date inputs
Add default since-until dates: 1952-01 for master games\2012-01 for lichess games for since, current year and month for until. I found that first games on lichess date from 2012-12, so 2012-01 should be a reasonable default value and a bit more suitable than 1952.
Couldn't find any reference to default Jan 2010 since date that was mentioned by @maxrosenb, or any default date at all. These fields are stored in LocalStorage, probably it was set to 2010 manually once and after that it automatically populates inputs with stored values.
Since now inputs have default values and empty fields have placeholders, adjusting styles to make it look more editable doesn't …

Add placeholders and default dates for explorer

---

modules/challenge/src/main/JsonView.scala
ui/challenge/css/_challenge.scss
ui/challenge/src/interfaces.ts
ui/challenge/src/view.ts

Even though the starting position is sent to the challenged client there is currently no way to see it before you decide to accept or decline the challenge. For prearranged challenges between friends this is fine, but for a streamer taking challenges it could be nice to be able to make sure you only accept challenges where the position is somewhat interesting, and not just a mate in one challenge just to score a cheap win (these "games" can of course be aborted).
This change adds a miniboard with the position to challenges of type from position. To make sure the board is oriented correctly for the challengee I have also modified the challenge information sent to include the actual colour chosen in case it is random.

Add preview to challenges from position.

---

modules/simul/src/main/Env.scala
modules/simul/src/main/JsonView.scala
ui/simul/src/interfaces.ts
ui/simul/src/view/util.ts

Only queries the host's online status to reduce server load, for other players there's no change in behaviour. Fixes #10272
Looks like it works without issues, but requires testing to make sure nothing is broken.

Make simul host's online status consistent

---

app/views/user/show/header.scala

When writing a private note about a user, I think Save is better action.
It uses "Send" right now which was a little confusing because it's supposed to be a private note.

Change Note form button from "Send" to "Save"

---

modules/game/src/main/StatusText.scala

Close #10339 
In case `OutOfTime` I assume that there is only way to draw is `insufficient material`.

Correct pgn comment for insufficient material flag-draws

---

modules/perfStat/src/main/JsonView.scala

The API now uses roundDownAt like app/views/user/perfStat.scala.
See #9605 and #9635 for reference.
Closes #10183.

Change /api/user/:name/perf/:perfKey to match /@/:username/perf/:perfKey

---

app/views/chat.scala

Makes no sense to timeout there and sometimes mods want to report people for their game chats.

Don't show timeout interface in private game chats

---

modules/round/src/main/ApiMoveStream.scala

Currently returns the clocks from the wrong players (it swaps back and forth each turn).

Fix replayed clocks in /api/stream/game/:id

---

app/views/activity.scala
modules/simul/src/main/Simul.scala

If the player is the host the behaviour is the same as before, otherwise the page shows player's result in the given simul.
Fixes #5066

Fix simul results in partecipant's profile

---

build.sbt
modules/bookmark/src/main/BookmarkApi.scala
modules/bookmark/src/main/Env.scala
modules/game/src/main/Game.scala

Another solution would have been to simply remove this trick which avoids a db call for most games
```scala
def exists(game: Game, user: User): Fu[Boolean] =
if (game.bookmarks > 0) exists(game.id, user.id)
else fuFalse
```

Update the proxy `Game` when bookmarking

---

app/controllers/Puzzle.scala
conf/routes
modules/puzzle/src/main/JsonView.scala

WIP for https://github.com/ornicar/lila/issues/10019
For now only two endpoints added (path names are a bit funky, if you have better ones).
`GET /training/batchV2?nb=X&theme=Y` to fetch puzzles. Sample response:
```json
[
{
"game": {
"id": "5yZe0I6r",
"perf": {
"icon": "",
"name": "Rapid"
},
"rated": true,
"players": [
{
"userId": "reda",
"name": "reda (1984)",
"color": "white"
},
{
"userId": "cted",
"name": "cted (1968)",
"color": "black"
}
],
"pgn": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 f3 b5 Be3 e6 Qd2 Nbd7 Nc6 Qc7 Nb4 Bb7 O-O-O Qa5 a3 d5 exd5 Bxb4 dxe6 Ne5 axb4 Qa1+ Nb1 Bd5 exf7+ Kxf7 Qc3 Ba2 Kd2 Rhd8+ Bd3 Nc4+ Ke2 Nxe3 Kxe3",
"clock": "10+0"
},
"puzzle": {
"id": "9h38Q",
"rating": 1562,
"plays": 1859,
"initialPly": 42,
"solution": [
"f6d5",
"e3f2",
"d5c3",
"b1c3",
"a1b2"
], …
```

Mobile: Puzzle v2 api

---

app/templating/GameHelper.scala

When the game ended after black's move the preview said that the game
lasted one move more than those effectively played.
Now the number of moves is computed using (1+ply)/2.

Fix bug in link's preview

---

ui/round/css/_control.scss
ui/round/src/view/button.ts
ui/round/src/view/table.ts

Fix #6757
The threefold button is a bit narrower and higher than the normal button.  
Apart from that, this change appears to work well.
I haven't changed `nvui.ts`, but the issue doesn't appear in accessibility mode anyway, as far as I can tell.

Combine buttons for claiming threefolds and offering draws

---

app/views/analyse/replay.scala

Fixes #10416.
Since we were using a single line `<input>`, we weren't preserving new line characters. Switch to `<textarea>` to preserve those characters.

Fix blind mode PGN copy functionality

---

app/controllers/LilaController.scala
app/controllers/Mod.scala

Closes #10217
Not sure if I'm missing something here but it seemed quite weird to me that `SecureOrScopedBody` wasn't actually passing the body in the scoped case and changing that was by far the easiest way to implement this.

Add API for timeouts

---

ui/round/src/plugins/keyboardMove.ts

Fixes #5046. See that issue for a detailed explanation of the bug.
With this change, we will no longer erase invalid keyboard moves that are being entered while the opponent makes their move.

Don't clear the keyboard input for valid premoves

---

app/views/analyse/replay.scala

This is a fix for #10497. Apparently, `display: none` disallows `<textarea>`s from being selected, which we need to do in order to copy the text inside of it. Simply styling it as invisible seems to be the recommended strategy per [Stack Overflow](https://stackoverflow.com/questions/51681669/how-can-i-copy-text-from-hidden-textarea-to-clipboard). I followed that recommendation even though this is a blind mode feature. I also included `tabindex = -1` so that screen readers might skip over it.

Fix the blind mode PGN copy feature

---

modules/puzzle/src/main/JsonView.scala

I'm also open to changing the key to `wins`. Either way, one of `firstWins` and `wins` is computable from the other also given `nb` and `replayWins`.

Fix puzzle dashboard API firstWins data

---

modules/tournament/src/main/Spotlight.scala

Like it's already done for authenticated users.
To avoid double BBBs like right now:

Don't show spotlight tournaments without "homepageHours" to unauthenticated users

---

.github/workflows/assets.yml
ui/README.md
ui/babel.config.js
ui/jest.config.js
ui/package.json
ui/round/src/keyboardMove.ts
ui/round/src/plugins/keyboardMove.test.ts
ui/round/src/plugins/keyboardMove.ts
ui/tsconfig.base.json
yarn.lock

Fixes #10538.
Prior to this change, if you selected a pawn via the keyboard input (`e7`), and then attempted to promote (`e8`), the pawn would be auto promoted to a queen. Now, we don't auto promote and instead wait for a more specific input (e.g. `e8=r`). Hitting enter will allow you to auto promote (e.g. `e8` + <enter>). All of the preceding statements also apply to the case of a selected pawn attempting to promote while capturing.
To build confidence in this change, I added some unit tests. I set up Jest and included some information on its usage in the `ui/README.md`.

Do not auto-promote to queen with selected pawns

---

modules/importer/src/main/ImporterForm.scala

Fixes #10519 
Adjusted some logic when importing a game. No longer assumes resignation if no Termination tag was provided, which results in this (using the same PGN in the issue):
`Finished • Black is victorious`

Import game status does not assume resignation

---

ui/round/src/ctrl.ts
ui/round/src/keyboardMove.ts
ui/round/src/plugins/keyboardMove.test.ts
ui/round/src/plugins/keyboardMove.ts

Fixes #10534.
Adds the ability to offer or accept a draw with the keyboard input. It operates similarly to the resign command in the sense that it will not ask you to confirm; it will immediately offer or except the draw.

Keyboard draw
