lichess-org/lila

- app/controllers/Notify.scala
- conf/routes
- modules/notify/src/main/NotifyApi.scala
- ui/notify/css/_notify.scss
- ui/notify/src/ctrl.ts
- ui/notify/src/interfaces.ts
- ui/notify/src/view.ts
closes https://github.com/ornicar/lila/issues/8396
Added a trash can icon when the notification list is not empty
Trash can visible only in the first page of the notification list
> allow users to clear notifications

- app/mashup/UserInfo.scala
- bin/mongodb/create-trophy-kinds.js
- bin/mongodb/update-trophy-kinds.js
- modules/security/src/main/Permission.scala
- modules/user/src/main/Trophy.scala
- modules/user/src/main/TrophyApi.scala
Implemented using the blog icon for the trophy.
> creator badge for #9889

- ui/analyse/src/ground.ts
- ui/analyse/src/interfaces.ts
> Respect click vs drag pieces setting in analysis

- ui/@types/lichess/index.d.ts
- ui/challenge/src/ctrl.ts
- ui/notify/src/ctrl.ts
- ui/site/src/component/sound.ts
To avoid the current massive concert when you have a dozen Lichess tabs open and get pinged in the forum.
> Only play notification sounds once over all tabs

- ui/challenge/css/_challenge.scss
https://lichess.org/forum/lichess-feedback/accessibility-issue-with-nvda-screen-reader-to-accept-or-decline-a-challenge
> Always show challenge accept/decline buttons in blind mode

- ui/round/src/view/table.ts
Address https://github.com/ornicar/lila/issues/6757
> Swapping the order of the buttons and icons in round controls

- modules/irwin/src/main/IrwinApi.scala
- modules/report/src/main/Report.scala
- modules/report/src/main/ReportApi.scala
- modules/report/src/main/ReportScore.scala
Discussion: https://hq.lichess.ovh/#narrow/stream/22-mod-comms-private/topic/comms.20order
Also simplifies and centralizes the whole auto report scoring.
> Increase auto comms report score to 42

- ui/round/css/_moves-col1.scss
> Prevent board moving in zen mode

- ui/site/css/user/_activity.scss
> Add right margin to user activity

- modules/relay/src/main/RelaySync.scala
- modules/study/src/main/ServerEval.scala
- modules/study/src/main/StudyApi.scala
Since some official broadcasts are created by people without relay perms.
> Never use analysis quota for official broadcasts

- ui/analyse/src/explorer/explorerConfig.ts
- ui/analyse/src/explorer/explorerXhr.ts
> Explorer: Separate since/until config by db

- ui/site/src/teamAdmin.ts
"Existing values" refers to re-opening the tab or going back and forth in the browser history.
Could also check whether the pasted members actually exist but not sure if that's worth it.
> team kick: Allow pasting members and existing values

- ui/analyse/src/ctrl.ts
> Fix move being unselected in study

- ui/@types/lichess/index.d.ts
- ui/analyse/src/study/practice/studyPracticeCtrl.ts
- ui/learn/src/sound.ts
- ui/puz/src/util.ts
- ui/puzzle/src/ctrl.ts
- ui/site/src/component/sound.ts
Fixes #10123 (which also just happens when you switch sound set at all and then continue playing)
> Don't unload soundSet-independent sounds on soundSet change

- app/views/base/layout.scala
- ui/@types/lichess/index.d.ts
Fixes #10122
Tested locally on some random pages and in a game.
> Use DOMContentLoaded instead of window.onload

- ui/common/css/component/_loader.scss
> Use full form of stroke-dasharray for Safari

- modules/insight/src/main/Share.scala
- modules/pref/src/main/Pref.scala
- modules/pref/src/main/PrefApi.scala
- modules/round/src/main/Drawer.scala
Only applies to anonymous players, and accounts created after this change.
> default to dark theme

- modules/plan/src/main/PlanApi.scala
Previously nothing was changed for the receiver.
Could not test it locally.
> Fix patron gift when the receiver is already patron.

- app/controllers/Study.scala
- modules/study/src/main/ChapterMaker.scala
- modules/study/src/main/StudyApi.scala
- modules/study/src/main/StudySocket.scala
> Hide ratings when importing game to existing study if option selected

- app/views/swiss/show.scala
Couldn't test due to build errors in bbpPairings on my side for now.
> Swiss round page is not an infiniteScroll page

- app/views/insight.scala
- ui/chat/src/discussion.ts
- ui/chat/src/moderation.ts
- ui/common/src/userLink.ts
- ui/insight/css/_insight.scss
- ui/insight/src/info.ts
- ui/insight/src/interfaces.ts
> Display title and patron icon in insights

- translation/dest/puzzle/en-US.xml
> Fixed small typo in puzzles

- ui/common/src/throttle.ts
- ui/tournament/src/xhr.ts
To throttle promises with delay, the previous implementation was working with three possible states:
* Idle
* In flight
* In delay phase
To simplify, the delay phase can be made part of the promise itself by chaining `new Promise(resolve => setTimeout(resolve, delay))`.
The old synchronous throttling can also be implemented in terms of this.
> unify throttling functions

- app/controllers/Analyse.scala
- app/controllers/GameMod.scala
- app/controllers/Importer.scala
- app/controllers/Mod.scala
- app/controllers/Puzzle.scala
- app/controllers/Report.scala
- app/controllers/User.scala
- app/controllers/UserTournament.scala
- app/views/analyse/replay.scala
- app/views/mod/games.scala
- app/views/oAuth/token/create.scala
- app/views/user/mod.scala
- modules/irc/src/main/IrcApi.scala
- modules/irc/src/main/ZulipClient.scala
- modules/mod/src/main/ModlogApi.scala
- modules/security/src/main/Granter.scala
- modules/security/src/main/Permission.scala
Migration:
```js
db.user4.updateMany({roles: "ROLE_HUNTER"}, {$push: { roles: { $each: ["ROLE_CHEAT_HUNTER", "ROLE_BOOST_HUNTER"] }}});
db.user4.updateMany({roles: "ROLE_HUNTER"}, {$pull: { roles: "ROLE_HUNTER" }});
```
> Split Hunter into cheat and boost

- app/controllers/User.scala
- app/views/kaladin.scala
- app/views/user/mod.scala
- modules/irwin/src/main/BSONHandlers.scala
- modules/irwin/src/main/KaladinApi.scala
- modules/irwin/src/main/KaladinUser.scala
- modules/tournament/src/main/package.scala
- ui/site/css/mod/_irwin.scss
- ui/site/css/mod/_user.scss
Essentially fixes expected data structure from Lila, and add Kaladin report to user profile when available
Could certainly be visually improved but it has at least all relevant informations
> Kaladin improvements

- app/controllers/Pref.scala
- app/views/base/layout.scala
- modules/insight/src/main/Share.scala
- modules/pref/src/main/Pref.scala
- modules/pref/src/main/PrefApi.scala
- modules/pref/src/main/PrefHandlers.scala
- modules/round/src/main/Drawer.scala
- ui/common/css/_lichess.scss
- ui/common/css/component/_agreement.scss
- ui/common/css/component/_announce.scss
- ui/site/src/component/agreement.ts
- ui/site/src/site.ts
merge after the new ToS/privacy go live
> new ToS/privacy agreement request

- app/views/activity.scala
- modules/activity/src/main/ActivityView.scala
- modules/relay/src/main/RelayFormat.scala
Fixes https://github.com/ornicar/lila/issues/10310
> Hide activity sections with no content

- ui/common/css/base/_elements.scss
> Fix styling issue for ordered list items

- ui/site/css/team/_show.scss
> Fix styling issue for ordered list items in teams

- ui/site/css/practice/_icons.scss
[icons.zip](https://github.com/ornicar/lila/files/7833055/icons.zip)
Icons in zip, wasn't sure how I can deal with assets otherwise.
Thanks and credit to @Yeltcki for the study updates.
> new practice icons

- modules/mod/src/main/ModlogApi.scala
- modules/mod/src/main/SandbagWatch.scala
- modules/report/src/main/ReportApi.scala
> Use number of games boosted/sandbagged and previous warnings to prioritize reports

- ui/puzzle/src/view/side.ts
Not sure if it's the canonical way to check if the puzzle is finished.
> Go to next puzzle immediatly when checking "Jump to next puzzle" after puzzle is complete

- ui/common/src/richText.ts
- ui/msg/src/view/enhance.ts
- ui/site/src/inquiry.ts
Still use a client-side fix, instead of server-side one because it allows to only make clickable Lichess links.
> Fix broken search and user profile links in reports

- app/controllers/Appeal.scala
- app/views/appeal/discussion.scala
- app/views/appeal/queue.scala
- modules/mod/src/main/ModlogApi.scala
- ui/site/css/_appeal.scss
- ui/site/css/mod/_report.scss
close https://github.com/lichess-org/tavern/issues/142
> Warnings when processing own mark in appeal

- app/views/analyse/replay.scala
Fixing an autopilot mistake in #10496
> Actually hide the blind mode PGN textarea

- modules/tournament/src/main/TournamentApi.scala
One of the ideas from #10523.
Organizer can compute `HMAC-SHA256(access code, user id)` and pass it to the user. Only that user can use the code to join.
Feels a bit dirty/ad-hoc. Only way to revoke one of these access codes is to revoke all of them, by changing the tournament access code.
> accept HMAC-SHA256(access code, user id) for tournament entry

- README.md
> Minor readme link change

- modules/game/src/main/Game.scala
- ui/game/src/view/status.ts
> Fix draw reason when offering draw before making an auto-draw move

- ui/analyse/css/study/_modal.scss
- ui/analyse/src/study/chapterEditForm.ts
- ui/analyse/src/study/chapterNewForm.ts
- ui/analyse/src/study/studyForm.ts
> study: Improve destructive form actions layout

- app/controllers/ForumPost.scala
- app/views/forum/post.scala
- conf/routes
- modules/forum/src/main/PostApi.scala
fixes https://hackerone.com/reports/1499573
> check team forum membership when reacting

- modules/swiss/src/main/SwissApi.scala
fixes https://hackerone.com/reports/1498173
> verify swiss conditions on join

- app/controllers/Simul.scala
- modules/simul/src/main/SimulApi.scala
fixes https://hackerone.com/reports/1498180
> check team membership when joining simul

- modules/importer/src/main/ImporterForm.scala
Solve #10520 by prefer result from pgn file over game logic.
here is the test case:
```
[Event "World Blitz Championship"]
[Site "Dubai UAE"]
[Date "2014.06.19"]
[EventDate "2014.06.19"]
[Round "7.1"]
[Result "1-0"]
[White "Magnus Carlsen"]
[Black "Le Quang Liem"]
[ECO "D73"]
[WhiteElo "2881"]
[BlackElo "2712"]
1. d4 Nf6 2. Nf3 g6 3. g3 Bg7 4. Bg2 d5 5. c4 c6 6. cxd5 cxd5
7. Ne5 O-O 8. Nc3 e6 9. O-O Nfd7 10. Nf3 Nf6 11. Bf4 Nc6
12. Rc1 Bd7 13. Qd2 Rc8 14. Ne5 Qe7 15. Rfd1 Rfd8 16. Bg5 Qf8
17. h4 h6 18. Bxf6 Bxf6 19. f4 h5 20. e3 Be8 21. Bf3 Ne7
22. Kf2 Nf5 23. Ne2 Qd6 24. Qa5 Qb6 25. Qxb6 axb6 26. Rxc8
Rxc8 27. Rc1 Ra8 28. a3 Nd6 29. Nc3 Kf8 30. e4 dxe4 31. Nxe4
Bxe5 32. dxe5 Nxe4+ 33. Bxe4 Bc6 34. Ke3 Ke7 35. Bd3 Ra5
36. Rc3 Rc5 37. Rb3 b5 38. Rc3 Rxc3 39. bxc3 Kd7 40. Kd4 b6
41. Ke3 Kc7 …
```
> Respect result from pgn over game logic

- modules/irwin/src/main/KaladinUser.scala
Actually tested locally this time
> Fix mod requests when user has already been analysed in the past

- ui/puzzle/src/ctrl.ts
- ui/puzzle/src/interfaces.ts
- ui/puzzle/src/keyboard.ts
this fixes https://github.com/lichess-org/lila/issues/10724
> Added the *n*ext puzzle shortcut to puzzles page

- app/views/user/show/header.scala
One more way to discover the feature.
> link personal opening explorer from profile

- COPYING.md
I have changed the year on the Copying.md to 2022.
> Updated the year on the Copying.md

- ui/lobby/src/boot.ts
- ui/lobby/src/ctrl.ts
- ui/lobby/src/main.ts
- ui/lobby/src/view/table.ts
Just doing a further refactoring to get more UI stuff out of `boot.ts`, no functionality changes.
> Refactor players, games counters in lobby

- modules/shutup/src/main/Analyser.scala
- modules/shutup/src/main/Dictionary.scala
updating dict, pluralising `fr`, latinifying addition
thanks to [Zebra9876543210](https://lichess.org/@/Zebra9876543210) for the contribution in critical comms regex edit.
> Shutup updates

- app/controllers/Export.scala
- app/views/analyse/replay.scala
- conf/routes
- modules/game/src/main/GifExport.scala
- ui/analyse/src/serverSideUnderboard.ts
- ui/analyse/src/study/studyCtrl.ts
- ui/analyse/src/study/studyShare.ts
Quick fix to include the check square when we generate thumbnails
> Include check square in thumbnails

- modules/msg/src/main/MsgSecurity.scala
> Only let public mods bypass message security

- app/views/timeline.scala
> fix empty timeline entries for game end vs anon

- ui/simul/src/view/results.ts
found this while investigating #11050
> fix incorrect simul results tally for abort status

- modules/memo/src/test/SyncacheTest.scala
- ui/round/src/tourStanding.ts
testing my theory that a wrong test is an improvement on a test that doesn't compile
> mitigate unit test compile error

- app/views/analyse/replay.scala
- ui/analyse/src/serverSideUnderboard.ts
> generate proper game gif after board was flipped #7844

- app/controllers/Team.scala
- app/views/team/show.scala
- modules/mod/src/main/ModlogApi.scala
* Hide closed team description
* Log reason for reopening teams
> Team moderation tweaks

- COPYING.md
just to demo the power of OpenSource to the amazing friends from nate.tech company
> remove unnecesary "." from the list

- ui/puzzle/src/ctrl.ts
From discord:
> On puzzle replay, if it's the last puzzle in a sequence, it goes back automatically to the "Improvement Areas" page, but I want it to stay on the puzzle I just completed. I have the switch disabled that says "Jump to next puzzle immediately". How do I get it to stop doing this?
Actually, it goes back to the puzzle dashboard. Regardless, I'd like it to stay on the puzzle
So that I may analyze
Nothing has changed if the user has "Jump to next puzzle immediately" enabled. If they have it disabled, they will stay at the last puzzle of the replay until they press thumbs up or down, at which point they will redirect to the dashboard.
This way, the behavior of the last puzzle in the replay is consistent with all the other puzzles in the replay.
> In puzzle replay, wait until next puzzle is requested to redirect back to dashboard

- app/views/ublog/index.scala
"RawFrag(Drafts) • lichess.org" → "Drafts • lichess.org"
> Fix drafts title translation

- app/views/forum/categ.scala
- ui/site/css/forum/_table.scss
closes #11200
also fix rtl alignment for replies column
> decorate closed topics with lock icon in topic lists

- ui/analyse/src/study/studyDeps.ts
- ui/analyse/src/view.ts
Fixes the second bug mentioned in #11244 (in the description of the issue)
> Add practice view back to /analysis

- app/views/site/page.scala
- conf/base.conf
- modules/practice/src/main/PracticeStructure.scala
typo happened in https://github.com/lichess-org/lila/commit/b97c5c0e31e0ba754b55cde2e9db852dd5b6a2fa
> fix typo (force-rtl > force-ltr)

- modules/msg/src/main/MsgApi.scala
https://hq.lichess.ovh/#narrow/stream/34-mod-dev/topic/Some.20ppl.20not.20receiving.20Lichess.20warnings.3F
> Ignore msg security when Lichess sends DMs

- ui/ceval/src/ctrl.ts
> Disable nnue cache when indexedDB isn't supported

- ui/analyse/src/view.ts
> Remove autoselect class from PGN import field

- ui/analyse/src/ctrl.ts
- ui/round/src/view/replay.ts
> always use correct current move in correspondence analysis

- ui/analyse/src/pgnImport.ts
> Perform client-side check-detection

- app/views/user/show/header.scala
- ui/site/css/user/_profile.scss
Implements social distancing and closes #11389
> Separate social media links from teams list in user profile

- modules/common/src/main/LameName.scala
- modules/user/src/main/UserForm.scala
Since it's case-sensitive in some situations e.g. gmcarlsen (allowed) -> GMcarlsen (not allowed)
> Check for title imitation when changing username

- ui/ceval/src/ctrl.ts
fix max memory regression on chrome/edge/opera, allow them to use 1 GB hash, refactor max hash size with explanatory comments for all values.
> fix chrome/edge/opera regression in previous commit

- modules/api/src/main/TextLpvExpand.scala
- ui/site/src/lpv.ts
> pass ply to lpv in text expands

- modules/swiss/src/main/SwissCondition.scala
- modules/tournament/src/main/Condition.scala
Titled players should no longer be allowed to join tournaments without meeting minimum rating required, per internal discussion
> Do not exempt titled players from min. rating condition

- modules/common/src/main/MarkdownRender.scala
- modules/common/src/test/MarkdownTest.scala
- ui/learn/src/mithrilFix.ts
> allow ply & orientation in ublog lpvs

- ui/common/css/component/_lichess-pgn-viewer.scss
- ui/common/css/theme/_dark.scss
- ui/common/css/theme/_default.scss
- ui/learn/src/mithrilFix.ts
together with pgn-viewer PR #5
fixes #11356
> light bg lpv color fixes

- CONTRIBUTING.md
Small typos and grammatical errors found when reading the contributing guidelines.
> Fix typos/grammer in contributing

- ui/tree/src/ops.ts
> tree merge don't accidentally discard eval

- app/controllers/Auth.scala
- modules/api/src/main/AccountClosure.scala
the commit was meant for lichess-org/lila#11464 but revoof too speedy.
> also revoke device tokens on api pwd reset and account closure

- ui/ceval/src/view.ts
together with memory fixes and moving safari to hce, i can no longer make the engine misbehave.
closes #11373
> fix "loading engine/calculating moves" hang (3fold draw)

- modules/relay/src/main/RelayApi.scala
Closes #11382
https://hq.lichess.ovh/#narrow/stream/6-content-broadcast/topic/limited.20number.20of.20featured.20broadcasts
> Increase max featured broadcasts to 40

- ui/chart/src/acpl.ts
> add colored markers to advantage graph

- ui/ceval/src/protocol.ts
> Prevent a multi-PV setting of zero

- ui/@types/lichess/index.d.ts
- ui/analyse/src/serverSideUnderboard.ts
- ui/analyse/src/study/serverEval.ts
- ui/chart/src/acpl.ts
Tried to add some types at the same time, but [as discussed on discord](https://discord.com/channels/280713822073913354/352976626558042122/1018113099066245130) didn't find a suitable way to import `AnalyseData`
> Do not show inaccuracy/mistake/blunder for mods on chart

- ui/chart/src/acpl.ts
the vertical selection line suggests this behavior.
> click advantage graph to navigate

- app/views/game/crosstable.scala
> crosstable score must always be LTR

- ui/common/src/richText.ts
> Correctly link to lichess URLs without a URI scheme

- ui/analyse/src/crazy/crazyView.ts
- ui/chess/css/_zh-pocket.scss
> Prevent extra drops when a crazyhouse game has ended

- ui/analyse/src/study/practice/studyPracticeSuccess.ts
> Handle draws in the practice interface

- ui/site/css/user/_activity.scss
> Fix rtl alignment in profile activity timeline

- COPYING.md
> Correct typo in copying

- ui/site/src/forum.ts
> Allow quotes to use selection

- ui/analyse/css/_round-underboard.scss
- ui/analyse/src/roundTraining.ts
- ui/chart/src/acpl.ts
- ui/chart/src/common.ts
- ui/chart/src/division.ts
- ui/chart/src/movetime.ts
vertical lines, buy one get one free.
i put dots back in on acpl summary mouseover (so you'll have something to revert).
> advantage & movetimes graph tweaks

- conf/application.conf.default
This one may end up eclipsing my heroic removal of topicLastPage from Post.scala.
> tips for new contributors in application.conf.default

- app/views/game/crosstable.scala
> crosstable should always be ltr

- app/controllers/Account.scala
- app/controllers/Api.scala
- app/controllers/Auth.scala
- app/controllers/PlayApi.scala
- app/controllers/Relation.scala
- app/controllers/Team.scala
- app/controllers/User.scala
- modules/api/src/main/UserApi.scala
- modules/team/src/main/JsonView.scala
- modules/user/src/main/JsonView.scala
After 7219ba851218b258c5e8c8c5b8836f7431fff229
Related #11749
> Cleanup remaining (now useless) withOnline usage

- modules/challenge/src/main/Challenge.scala
- modules/challenge/src/main/ChallengeBulk.scala
- modules/challenge/src/main/ChallengeJoiner.scala
- modules/setup/src/main/SetupBulk.scala
Same as already possible using the challenge API, useful for 960 tournaments among other things.
> Allow fen in bulk pairings

- app/views/streamer/show.scala
- modules/forum/src/main/Topic.scala
- modules/mod/src/main/Modlog.scala
- modules/streamer/src/main/Stream.scala
- modules/streamer/src/main/Streaming.scala
still waiting on clarity for which youtube language property is best so feel free to sit on this one
I see scalafmt is f#*king around with spaces again - that makes me happy
> use language from youtube & twitch streams

- app/controllers/Api.scala
- app/controllers/Challenge.scala
- app/views/challenge/bits.scala
- app/views/challenge/mine.scala
- app/views/challenge/theirs.scala
- modules/challenge/src/main/Challenge.scala
Currently, it always displays "restricted" on open challenges even if the challenge is completely open (i.e. `users` wasn't set to).
> Fix and translate color displayed on challenge page

- app/controllers/Mod.scala
- app/views/mod/log.scala
- app/views/mod/menu.scala
- conf/routes
- modules/mod/src/main/ModlogApi.scala
Useful in case somone want to double check their action later/need to fix a mistake Mostly based on the old log mod removed by 085463c5d18d4c5b33ca5d8fc22c83e5775797a0
Put under the `GamifyView` permission so that timeout mods can have access to it too
> Personal mod log

- app/controllers/Mod.scala
Button appearance was fixed but not controller access. Should we change the name of the `GamifyView` to emcopass this new feature? To something like `ViewModStats`. Would require a db migration, not sure if worth it for the moment
> fix log permission for timeout

- ui/analyse/src/ctrl.ts
- ui/analyse/src/interfaces.ts
- ui/analyse/src/pgnImport.ts
- ui/analyse/src/util.ts
> Process sidelines while importing PGNs via the analysis board

- ui/notify/src/renderers.ts
https://github.com/lichess-org/lila/issues/11306
> Redirect to /faq#rating-refund when clicking on refund notification

- app/views/relay/roundForm.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/broadcast.xml
> Further internationalise Lichess broadcasts

- ui/@build/bleep/bleep.config.json.default
- ui/@build/bleep/src/build.ts
- ui/@build/bleep/src/main.ts
- ui/@build/bleep/src/tsc.ts
no more need to delete bleep.config.json
> improve handling of defaults

- ui/puzzle/src/main.ts
- ui/site/src/component/assets.ts
- ui/site/src/component/top-bar.ts
thanks niklas, i swear this is the last window global!  (fingers crossed)
> fix puzzles & iife loading

- modules/explorer/src/main/ExplorerIndexer.scala
Rewrite using immutable buffer behind AtomicReference.
> make ExplorerIndexer.flowBuffer thread-safe (fixes #11861)

- ui/@build/bleep/src/esbuild.ts
- ui/@build/bleep/src/main.ts
- ui/@build/bleep/src/parse.ts
- ui/@build/bleep/src/sass.ts
most of the style partials are included by many, many themed scss files, so a single error gets repeated ad nauseum.
> bleep - stop sass builds after first error (but keep watching)

- ui/@build/bleep/src/esbuild.ts
- ui/coordinateTrainer/src/main.ts
- ui/dgt/src/main.ts
- ui/insight/src/main.ts
- ui/learn/src/main.ts
- ui/mod/src/activity.ts
- ui/opening/src/main.ts
- ui/puzzle/src/dashboard.ts
- ui/racer/src/main.ts
- ui/simul/src/main.ts
- ui/site/src/analyseEmbed.ts
- ui/site/src/challengePage.ts
- ui/site/src/checkout.ts
- ui/site/src/login.ts
- ui/site/src/passwordComplexity.ts
- ui/site/src/plan.ts
- ui/site/src/team.ts
- ui/storm/src/main.ts
- ui/swiss/src/main.ts
- ui/tournament/src/main.ts
- ui/tournamentCalendar/src/main.ts
- ui/tournamentSchedule/src/main.ts
add corresponding assignments in module source so the variables actually reference something
> esbuild - js globals referenced in embedJsUnsafeLoadThen calls from scala

- ui/@build/bleep/src/main.ts
- ui/@build/bleep/src/sass.ts
It probably won't be correct, but at least it's not nothing
> Bleep - at least rebuild existing scss on directory changes

- ui/analyse/src/ctrl.ts
- ui/analyse/src/study/commentForm.ts
- ui/analyse/src/wiki.ts
> Don't show wikibooks in variants

- package.json
- ui/build
Updated package.json and `./ui/build` to reflect this change.
> Node 19 is now supported

- README.md
> Readme: Scala 3

- modules/perfStat/src/main/JsonView.scala
> fix stack overflow

- ui/@build/bleep/src/build.ts
- ui/@build/bleep/src/esbuild.ts
- ui/@build/bleep/src/main.ts
- ui/@build/bleep/src/parse.ts
- ui/@build/bleep/src/sass.ts
- ui/@build/bleep/src/tsc.ts
no idea if the min.js stuff actually works.
> use -w / --watch to watch and -p / --prod for minified prod builds

- modules/notify/src/main/BSONHandlers.scala
Deadban noticed this.  No exceptions, that's weird.
> fix forum mention and study invite notifications

- ui/round/src/boot.ts
- ui/round/src/interfaces.ts
> Respect 'do not show ratings' preference when loading new games on TV

- modules/insight/src/main/BSONHandlers.scala
- modules/insight/src/main/PovToEntry.scala
- modules/insight/src/main/model.scala
https://hq.lichess.ovh/#narrow/stream/34-mod-dev/topic/Insights.20for.20correspondence.20games
Not really super confident in this since I haven't really understood how all the insights stuff works but I guess testing it, it seems to work?
Closes #11890 Though I don't really understand how correspondence insights worked before? But lots of people confirm they did at some point.
> Correspondence insights

- ui/@build/readme
- ui/@build/src/build.ts
- ui/@build/src/esbuild.ts
- ui/@build/src/main.ts
- ui/@build/src/sass.ts
--tsc, --sass, --esbuild, --no-color, --no-context, --no-time
> simplify config and add cli args

- ui/@build/src/main.ts
> fix comments

- .github/workflows/assets.yml
- package.json
- pnpm-lock.yaml
- ui/build
- ui/round/package.json
> fix ab github workflow

- pnpm-lock.yaml
- ui/cli/package.json
- ui/editor/package.json
- ui/keyboardMove/package.json
- ui/lobby/package.json
- ui/round/package.json
- ui/serviceWorker/package.json
- ui/simul/package.json
- ui/tournament/package.json
for consistency with tsconfig.base.json
> cash dependency in all package.jsons

- modules/streamer/src/main/Streaming.scala
> streamer notify prefs

- modules/push/src/main/PushApi.scala
so we don't have to update lichobile every time we add a new one that just opens a browser link
> provide urls as a fallback for device notifications

- ui/challenge/src/ctrl.ts
- ui/msg/src/ctrl.ts
Chrome && FF Notification API and push permissions are no longer separate.  Challenge and inbox messages are delivered via web push when those permissions are granted.
Users browsing normally will no longer receive duplicate notifications after this.  Unfortunately, incognito users will not get notified at all.
> remove redundant notifications

- app/views/account/close.scala
- app/views/account/kid.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/settings.xml
- translation/source/site.xml
> Add i18n strings for managed accounts

- ui/chart/src/acpl.ts
- ui/chart/src/movetime.ts
> Disable ply line animation in acpl and movetime charts

- ui/analyse/src/ctrl.ts
- ui/analyse/src/interfaces.ts
- ui/analyse/src/persistence.ts
> persist flip state when clearing local moves

- ui/chat/src/discussion.ts
> Add enterkeyhint="send" to chat inputs

- modules/streamer/src/main/Env.scala
https://hq.lichess.ovh/#narrow/stream/34-mod-dev/topic/Sanction.20-.20autoremove.20streamer
> Demote streamers on boost mark and SB

- modules/user/src/main/Links.scala
Beautify ChessMonitor profile links
> Add ChessMonitor to user links

- ui/analyse/css/_action-menu.scss
|Before|After|
|:--:|:--:|
|<img width="274" alt="image" src="https://user-images.githubusercontent.com/19309705/211627497-6844a8a6-3f6d-4c63-b4d6-422405847e7d.png">|<img width="274" alt="image" src="https://user-images.githubusercontent.com/19309705/211627348-eaa8eb11-04ff-4733-942a-4489ae8fe049.png">|
> Fix analysis .action-menu padding

- modules/msg/src/main/MsgApi.scala
Fixes edge case where received PM alls would not be sorted correctly in the same inbox as a sent PM all.
> leader inbox fix 2

- modules/challenge/src/main/ChallengeMaker.scala
> Fix anon rematches vs bots

- modules/common/src/main/mon.scala
- modules/push/src/main/PushApi.scala
tell the world, ye glorious streamers!
> give kamon streamer notifications

- app/views/user/mod.scala
context: https://hq.lichess.ovh/#narrow/stream/35-mod-dev-admin/near/2172993. To avoid having to look at the db directly again
> Show report status as tooltip in the mod zone

- app/Env.scala
- app/controllers/Team.scala
- app/mashup/TeamInfo.scala
- app/templating/DateHelper.scala
- app/views/team/admin.scala
- app/views/team/show.scala
- app/views/user/mod.scala
- modules/memo/src/main/MongoRateLimit.scala
> show # of team messages remaining

- ui/site/src/component/serviceWorker.ts
first commit is the actual change, second is just refactoring
Unsub web push notification if the user isn't authenticated e.g. because the cookie timed out or was manually deleted.
> Unsub web push notifications if logged out

- ui/site/src/component/socket.ts
> Immediately resend ws msgs when it opens

- app/views/blog/bits.scala
- app/views/blog/show.scala
- modules/api/src/main/TextLpvExpand.scala
- modules/blog/src/main/BlogApi.scala
- modules/blog/src/main/Env.scala
> support old lichess blog game embeds

- modules/msg/src/main/MsgApi.scala
wasteful O(n2) relic that no longer serves a purpose
> Remove unnecessary distinctBy on inbox construction

- modules/shutup/src/main/Dictionary.scala
> Update en dict

- modules/tournament/src/main/Tournament.scala
Uses 40 moves though but seems more consistent this way?
> Use clock.estimateTotalSeconds

- ui/challenge/css/_page.scss
|Before|After|
|:--:|:--:|
|![old-slim](https://user-images.githubusercontent.com/19309705/214441935-bbdbcf57-abcb-4d33-a94d-a71e17d868b1.png)|![new-slim](https://user-images.githubusercontent.com/19309705/214441933-e4285517-f216-4ae6-bbe2-1f9912916c7b.png)|
> Tweak challenge page style

- app/ui/scalatags.scala
- app/views/base/layout.scala
- app/views/forum/bits.scala
- app/views/study/list.scala
- ui/analyse/src/view/view.ts
- ui/editor/src/view.ts
- ui/msg/src/view/interact.ts
For #12152: Added enterkeyhint attribute to suggested areas.
> 12152: add enterkeyhint where useful

- modules/shutup/src/main/Dictionary.scala
*remove duplicate n-word from en dict, it's now in critical. *Restore previous status quo for "nigga" until internal consensus is reached
> Edit en, critical dict

- ui/input/css/_keyboardMove.scss
- ui/input/src/main.ts
- ui/input/src/plugins/keyboardMove.test.ts
- ui/input/src/plugins/keyboardMove.ts
- ui/input/src/plugins/voiceInput.ts
Made a pretty basic animation for when the microphone is on, which can surely be improved upon but may be good enough for now. Also shuffled a few things around, now storing state on the keyboard move controller. Also show the text that it hears next to the microphone icon.
> Voice input - more icon updates

- modules/api/src/main/PersonalDataExport.scala
- modules/forum/src/main/ForumPostRepo.scala
- modules/msg/src/main/MsgApi.scala
- modules/security/src/main/Store.scala
- modules/ublog/src/main/UblogApi.scala
Fix https://github.com/lichess-org/lila/issues/12360
> Read personal data export temporarily from primary

- ui/analyse/src/view/view.ts
- ui/game/src/view/status.ts
- ui/round/src/speech.ts
- ui/round/src/view/replay.ts
Small refactoring in the process but primarily changing the combination of untranslated "Finished" with translated "White is victorious" to just the victorious part.
> Improve unknownFinish status rendering

- ui/analyse/src/persistence.ts
- ui/common/src/objectStorage.ts
- ui/common/src/spinner.ts
- ui/input/css/_inputMove.scss
- ui/input/src/interfaces.ts
- ui/input/src/main.ts
- ui/input/src/plugins/voskWorklet.ts
- ui/input/src/voiceCtrl.ts
> add download progress

- app/views/round/bits.scala
- ui/input/css/_inputMove.scss
- ui/input/src/interfaces.ts
- ui/input/src/keyboardMove.ts
- ui/input/src/main.ts
- ui/input/src/moveCtrl.ts
- ui/input/src/voiceCtrl.ts
- ui/puzzle/css/_layout.scss
- ui/puzzle/src/ctrl.ts
- ui/puzzle/src/view/main.ts
- ui/round/css/_app-layout.scss
- ui/round/css/_table.scss
- ui/round/src/ctrl.ts
- ui/round/src/view/main.ts
> Try it above the move list

- modules/shutup/src/main/Dictionary.scala
> update TR dict.

- modules/fishnet/src/main/UciToPgn.scala
- modules/game/src/main/Game.scala
- modules/opening/src/main/OpeningPage.scala
- modules/opening/src/main/OpeningQuery.scala
- modules/round/src/main/Player.scala
- modules/study/src/main/PgnImport.scala
- project/Dependencies.scala
This requires scalachess `14.5.0`
For https://github.com/lichess-org/scalachess/pull/368
> Migrate scalachess MoveOrDrop

- ui/input/src/handlerUtil.ts
- ui/input/src/moveCtrl.ts
Feel free to take it or leave it, just some code golf/OCD/desire to deduplicate the list of commands as I read through code
> Handler util code golf

- modules/game/src/main/actorApi.scala
- modules/hub/src/main/actorApi.scala
- modules/round/src/main/ApiMoveStream.scala
- modules/round/src/main/Player.scala
- modules/round/src/main/TvBroadcast.scala
The change closes #12357 by replacing BoardFen with EpdFen.
> Send full FEN on all /api/stream/game events

- ui/input/css/_inputMove.scss
- ui/input/src/interfaces.ts
- ui/input/src/keyboardMoveHandler.ts
- ui/input/src/main.ts
- ui/input/src/voiceCtrl.ts
Put the microphone inside the input?
https://giphy.com/gifs/u3sxXciCjE6M1tv6G3
> first pass at microphone over text input

- app/controllers/Mod.scala
- app/controllers/Report.scala
- modules/mod/src/main/ModApi.scala
- modules/report/src/main/ReportApi.scala
But make sure to always close the inquiry report when auto-next-report is turned on.
Not tested properly yet
> Don't close reports on marks

- app/views/puzzle/bits.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/puzzle.xml
- ui/puzzle/src/view/theme.ts
It's otherwise quite hard to get to that page from the daily puzzle
> Translate "daily puzzle" and link to puzzle theme/opening

- modules/importer/src/main/ImporterForm.scala
- project/Dependencies.scala
This requires scalachess 14.5.6: https://github.com/lichess-org/scalachess/pull/377
> Scalachess 14.5.6 with Opaque type Sans

- modules/rating/src/main/Glicko.scala
- ui/analyse/src/explorer/explorerConfig.ts
- ui/chart/src/ratingDistribution.ts
Due to:
Discussion: https://hq.lichess.ovh/#narrow/stream/8-dev/topic/lower.20minimum.20rating
Last lowered in b248195f9bd4b1539d4078e903cff28d661569e3 + dffe5c655e264f05c635d3f9cce26b6a8209be21 + 67637670e8209dbe67ea35d062f51b444a7839c4.
> lower minRating: 600 -> 400

- ui/analyse/src/ctrl.ts
L892 pretty much solves #12469 , rest solves #12517 .
> ~Reworked analysis menu navigation to solve #12469 and #12517

- ui/analyse/src/treeView/columnView.ts
- ui/analyse/src/treeView/common.ts
- ui/analyse/src/treeView/inlineView.ts
- ui/tree/css/_tree.scss
Should do everything properly, except for some weirdness for the owner of the study when editing it.
#12470
> Truncated comment redirect (Issue #12470)

- app/controllers/Mod.scala
- app/views/mod/search.scala
- app/views/user/mod.scala
- modules/security/src/main/Permission.scala
https://hq.lichess.ovh/#narrow/stream/34-mod-dev/topic/Email.20answerer.20perms
though mostly just cleaning up some inconsistencies
> Adjust SetEmail and gdpr erasure perms

- modules/appeal/src/main/AppealApi.scala
https://hq.lichess.ovh/#narrow/stream/54-mod-coordination
> Show more appeals in the queue

- COPYING.md
Sorry I forgot to add mpchess in the COPYING file.
> COPYING file for mpchess

- app/controllers/Appeal.scala
- app/views/appeal/discussion.scala
- modules/appeal/src/main/Appeal.scala
from https://hq.lichess.ovh/#narrow/stream/30-mod-admin-appeal/topic/main/near/2509236
Tested both as user and mod.
(picture is outdated, now button display "send and process appeal")
> Appeal: Add "send and process" button

- ui/mod/src/inquiry.ts
- ui/site/css/mod/_inquiry.scss
Display the note with a warning flash, and after a short cooldown of 1s for now to allow to read the note, can click again if discarding is made on purpose.
Note: `flash` class was turned into `note-flash` because it was otherwise conflicting with the flash mixin.
https://user-images.githubusercontent.com/56031107/236045984-20b36e0f-a027-477b-8356-b910956d2d3d.mov
> Inquiry: warning on close when note unsaved

- build.sbt
- modules/i18n/src/main/I18nKey.scala
- modules/i18n/src/main/PeriodLocales.scala
- modules/i18n/src/main/package.scala
- project/Dependencies.scala
> replace joda with naive showDuration impl (closes #12670)

- ui/@types/lichess/index.d.ts
- ui/site/src/component/mic.ts
- ui/voice/src/main.ts
- ui/voice/src/plugins/voiceMove.ts
- ui/voice/src/plugins/vosk.ts
fix lazy loading race conditions
> fixes from schlawg/master

- modules/pref/src/main/Pref.scala
- modules/pref/src/main/PrefForm.scala
- modules/pref/src/main/PrefHandlers.scala
so we can one day see how many people tried it
> lazy create db.pref.voice

- ui/common/css/abstract/_uniboard.scss
https://discord.com/channels/280713822073913354/1103959605261893632
fixes #9522
> 3 column layout fix

- modules/study/src/main/ChapterMaker.scala
- modules/study/src/main/Node.scala
- modules/study/src/main/StudyMaker.scala
> merge game and pgn trees on study create

- modules/evalCache/src/main/BSONHandlers.scala
- modules/evalCache/src/main/EvalCacheEntry.scala
- modules/study/src/main/BSONHandlers.scala
- modules/study/src/main/Node.scala
- modules/tree/src/main/Eval.scala
Proposal to refactor `Score` to `Enum`.
If this looks ok, I'll finish up the work.
> Refactor Score to Enum

- app/templating/FormHelper.scala
- app/views/base/captcha.scala
- app/views/swiss/form.scala
- app/views/tournament/form.scala
- modules/swiss/src/main/BsonHandlers.scala
fix https://github.com/lichess-org/lila/issues/12847
> Fix disabling swiss conditions for players to have played their last game

- ui/lobby/css/_layout.scss
This attemps to fix the gap described in #12776.
> Fix gap on homepage

- ui/puzzle/css/_layout.scss
> Fix uniboard on puzzles in "squeeze" resolutions

- ui/analyse/css/_layout.scss
- ui/ceval/css/_eval-gauge.scss
- ui/common/css/abstract/_uniboard.scss
- ui/common/css/layout/_uniboard.scss
- ui/coordinateTrainer/css/_layout.scss
- ui/learn/css/_layout.scss
- ui/puzzle/css/_layout.scss
- ui/racer/css/_racer.scss
- ui/round/css/_app-layout.scss
- ui/round/css/_layout.scss
- ui/simul/css/_layout.scss
- ui/site/css/tv/_single.scss
- ui/storm/css/_play.scss
- ui/swiss/css/_layout.scss
- ui/tournament/css/_layout.scss
> Fix uniboard layout fallback for old browsers (take 2)

- app/templating/UserHelper.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/site.xml
> Translate and pluralise mini-user rating title

- app/views/game/crosstable.scala
- app/views/game/widgets.scala
- app/views/mod/gamify.scala
- app/views/opening/show.scala
- app/views/setup/filter.scala
- app/views/tournament/teamBattle.scala
- app/views/user/top.scala
- modules/analyse/src/main/Info.scala
- modules/fishnet/src/main/AnalysisBuilder.scala
- modules/fishnet/src/main/FishnetEvalCache.scala
- modules/game/src/main/BinaryFormat.scala
- modules/game/src/main/PgnDump.scala
- modules/insight/src/main/PovToEntry.scala
- modules/opening/src/main/OpeningPage.scala
- modules/opening/src/main/OpeningSearch.scala
- modules/opening/src/main/OpeningTree.scala
- modules/relay/src/main/RelayFetch.scala
- modules/simul/src/main/SimulApi.scala
- modules/study/src/main/ChapterRepo.scala
- modules/study/src/main/StudyForm.scala
- modules/swiss/src/main/SwissOfficialSchedule.scala
- modules/swiss/src/main/SwissRankingApi.scala
- modules/swiss/src/main/SwissTrf.scala
- modules/tournament/src/main/PlayerRepo.scala
- modules/ublog/src/main/Env.scala
With `mapWithIndex` we'll traverse the list in one go instead of two with `zipWithIndex.map`. But probably it doesn't matter anyway. Feel free to ignore.
> Replace zipWithIndex.map by mapWithIndex

- bin/gen/licon.py
- ui/ceval/src/worker.ts
favor single quotes in licon script
> log external engine fails

- modules/study/src/main/NewPgnImport.scala
- modules/study/src/main/StudySocket.scala
- modules/study/src/test/PgnFixtures.scala
Fixes #12945 
Regression by #12936
> Crazy house drop in study bug

- modules/round/src/main/ApiMoveStream.scala
Fixes #12907 
tested locally:
```
λ curl "localhost:9663/api/stream/game/kKH7T9VE"                                                                                                                                                                                            ⏎
{"id":"kKH7T9VE","variant":{"key":"standard","name":"Standard","short":"Std"},"speed":"blitz","perf":"blitz","rated":false,"fen":"rn1qkbnr/1bp1p2p/8/ppPp1pp1/3P3P/5NP1/PP2PPB1/RNBQK2R b KQkq - 3 7","player":"black","turns":13,"source":"friend","status":{"id":20,"name":"started"},"createdAt":1685783811920,"lastMove":"f1g2","players":{"white":{"user":{"name":"nt9","id":"nt9"},"rating":1500,"provisional":true},"black":{}}}
{"fen":"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1","wc":300,"bc":300} …
```
> Use fullMoveNumber when writing played moves

- app/Lila.scala
- project/BuildSettings.scala
- project/Dependencies.scala
but play-mailer is not ready https://github.com/playframework/play-mailer/issues/273
> Scala 3.3.0

- app/controllers/Ublog.scala
> increase ublog paginator limits

- ui/board/css/_menu.scss
- ui/common/src/common.ts
- ui/common/src/controls.ts
- ui/puzzle/src/ctrl.ts
- ui/puzzle/src/view/boardMenu.ts
- ui/round/src/ctrl.ts
- ui/round/src/view/boardMenu.ts
fix too short mouseup detection, enable keyboard & voice toggles from puzzles, add blur filter to transp themes, refactor some stuff
> enable voice/keyboard move from puzzles

- ui/round/src/ctrl.ts
> Fix move confirm voice

- ui/site/src/component/mic.ts
- ui/voice/src/main.ts
- ui/voice/src/move/moveCtrl.ts
- ui/voice/src/view.ts
continue shuffling order of variable definitions in moveCtrl to satiate the Refactoring Gods
> fix coordinate trainer status. don't show help modal on voice.rtfm

- ui/puzzle/css/_layout.scss
See comment @ https://github.com/lichess-org/lila/issues/12960#issuecomment-1592147217
> ~Fix daily puzzle ui jumping when toggling #12960

- ui/puzzle/src/ctrl.ts
- ui/voice/src/move/moveCtrl.ts
> fix promotion ctrl issue in puzzles

- .gitignore
- .jvmopts
- modules/streamer/src/main/YouTubeApi.scala
never clobber pubSubVideoId with non-stream video ids
> Youtube streamer tweak

- ui/round/css/_app-layout.scss
- ui/voice/css/_voice.scss
Resolves #13016
Looks like
https://github.com/lichess-org/lila/assets/10794178/1f846a3c-1e36-467a-b1e2-722c481f0800
> move voice bar to bottom on mobile devices

- modules/tree/src/main/newTree.scala
- project/Dependencies.scala
For https://github.com/lichess-org/scalachess/pull/424
> Bump scalachess 15.2.12

- modules/challenge/src/main/Challenge.scala
- modules/game/src/main/Player.scala
- modules/game/src/main/Source.scala
- modules/plan/src/main/PayPalClient.scala
- modules/rating/src/main/PerfType.scala
- modules/report/src/main/Room.scala
- modules/streamer/src/main/Streamer.scala
- modules/streamer/src/main/StreamerForm.scala
- modules/tournament/src/main/Schedule.scala
- modules/tournament/src/main/TournamentShield.scala
- project/BuildSettings.scala
- project/Dependencies.scala
this requires: https://github.com/ornicar/scalalib/pull/17 and scalachess `15.3.0`.
I pushed new code to scalachess to master by accident ( it was supposed to be another pr) but we can revert it if we want.
> Make`Option.has` safe by requires Eq instance for type

- app/controllers/Report.scala
- modules/report/src/main/ReportApi.scala
when moving to X-file, redirect to next user when auto-next report enabled. Otherwise end the inquiry and stay on the same user profile (like processing the report)
> move to X-file, open next report

- modules/game/src/main/PgnDump.scala
Remove add SanStr when black moves first
Pgn already handles this situation
closes #13143
> Fix PgnDump when black moves first

- modules/ublog/src/main/UblogRank.scala
I'm not sure if you wanted to just spam tier penalize them or hide them altogether.
Should we explain the consequences of going picless in the image upload text or just let them scream ublogs are broken on support and feedback forum?
> disappear blogs without pics

- ui/puzzle/src/ctrl.ts
- ui/voice/@build/src/makeGrammar.ts
> fix voice puzzles

- app/views/account/pref.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/dest/preferences/de-DE.xml
- translation/source/preferences.xml
this one was left hardcoded. Added a translation and variable for it
> feat(i18n): introduce key for voiceInput + de-DE translation

- modules/game/src/main/Game.scala
- modules/swiss/src/main/SwissApi.scala
- project/Dependencies.scala
Mostly for this pr: https://github.com/lichess-org/scalachess/pull/449
> Scalachess 15.4.4

- ui/analyse/src/ctrl.ts
> Pass along external engine data when changing pgn

- modules/common/src/main/base/LilaLibraryExtensions.scala
- modules/relay/src/main/RelayFetch.scala
- modules/relay/src/main/RelayGame.scala
- modules/relay/src/main/RelayPush.scala
- Remove Try' extensions
- Remove Validated's extension
- improve on `Either.toFuture`, avoid creating new Exception if the left side is already Exception.
- Use Either instead of Try for RelayFetch.multiPgnToGames.apply
> Cleanup old extensions

- ui/@types/lichess/index.d.ts
- ui/site/src/component/sound.ts
> Gracefully handle absence of AudioContext

- modules/game/src/main/BSONHandlers.scala
- modules/game/src/main/package.scala
- project/Dependencies.scala
with hash improvement and some breaking changes: https://github.com/lichess-org/scalachess/pull/462
> Bump scalachess 15.6.1

- ui/puzzle/src/ctrl.ts
Issue #12176
This pull request introduces enhancements to the puzzle fail speech feedback feature. The changes focus on improving the way the system delivers audio message when a user fails to solve a puzzle. The primary goal is to enhance the user experience by providing clearer and more informative feedback.
> feat: Improved puzzle fail speech feedback

- ui/puzzle/src/ctrl.ts
This pull request builds upon the previous changes made in the #13296 pull request and introduces additional enhancements to provide a more polished user experience when encountering puzzle failures. After reviewing the merged changes, I realized that there was room for improvement in the speech feedback. Hence, this follow-up pull request aims to address those concerns and refine the feature even further.
> update: Improved puzzle fail speech feedback

- app/templating/SetupHelper.scala
- app/views/account/bits.scala
- app/views/account/pref.scala
- app/views/base/layout.scala
- app/views/round/player.scala
- modules/i18n/src/main/I18nKeys.scala
- modules/pref/src/main/Pref.scala
- modules/pref/src/main/PrefForm.scala
- translation/source/preferences.xml
- ui/puzzle/src/ctrl.ts
- ui/round/src/ctrl.ts
- ui/storm/src/ctrl.ts
Simplification of PR #13154
Vs other PR : 
- Removed the 4th hidden state, from which derives the 3 following points : 
- Removed pref controller doing logic
- Removed "aliasing" that was needed for the 4th hidden state
- Removed bit complexity 
+ Now checking for zen-automatic in two more places
> +AutoZen (Closes #12537)

- README.md
[https://database.lichess.org/](https://database.lichess.org/)
4.711 billion games 2023-AUG06
> Update README.md 4.7 billion games 2023-AUG06

- ui/analyse/src/ctrl.ts
- ui/analyse/src/keyboard.ts
~Fix missing shortcuts in analysis (bmir + shift-space + 'enter')
~Fixes flip erroring in /broadcast
Fixes #13332
> ~Fix missing shortcuts in analysis & fix flip - Fixes #13332

- ui/analyse/src/autoShape.ts
- ui/analyse/src/ctrl.ts
- ui/analyse/src/view/actionMenu.ts
Issue #12898
Moved Annotations on Board Toggle outside COMPUTER ANALYSIS section.
> refactor: annotations on board

- ui/puzzle/src/ctrl.ts
> improve sound on puzzles

- modules/security/src/main/DisposableEmailDomain.scala
* Whitelist ikmail.com, https://www.infomaniak.com/fr/email-gratuit
> Whitelist ikmail.com (infomaniak)

- modules/game/src/main/Namer.scala
> Add provisional rating support with namer for player text.

- project/Dependencies.scala
For https://github.com/lichess-org/scalachess/pull/477
> scalachess 15.6.7

- ui/@types/lichess/index.d.ts
- ui/round/src/ctrl.ts
- ui/round/src/plugins/nvui.ts
- ui/round/src/socket.ts
- ui/round/src/sound.ts
- ui/site/src/component/sound.ts
- ui/site/src/soundMove.ts
The TOTAL reversal of last week's sound refactoring is now complete.
> rounds - fix check sound and pentatonic

- app/views/blog/show.scala
> Unbox title for blog post

- modules/gathering/src/main/Quote.scala
Wanted to add quotes to the file but noticed some inconsistencies etc. and thought I'd fix them first.
- "William Steinitz" -> Wilhelm Steinitz
- "Francois-Andre Danican Philidor" -> François-André Danican Philidor
- "Capablanca" & "Jose Capablanca" & "Jose Raul Capablanca" -> José Raúl Capablanca
- "Judith Polgar" -> Judit Polgar
- "Richard Reti" & "Reti" -> Richard Réti
- "Assaic" -> Assiac
- "Neil McDonald (1998)" -> Neil McDonald
- "P-KKt3" -> g2-g3 (who understands descriptive notation?)
- "Aron Nimzowitsch (1925)" -> Aron Nimzowitsch
- "Robert Fischer" -> Bobby Fischer
- "Robert Hübner (1990, Schach)" -> Robert Hübner
- "Moses Mendelssohn 1729-86" -> Moses Mendelssohn
- adjusted "..." ellipsis according to [this](https://www.ox.ac.uk/sites/files/oxford/media_wysiwyg/University%20of%2 …
> Fix some inconsistencies etc. in quotes

- app/controllers/Ublog.scala
- app/views/ublog/post.scala
close https://github.com/lichess-org/lila/issues/13514
tested
> Only show follow button on ublog post when possible

- .gitignore
- app/templating/AssetHelper.scala
- app/views/puzzle/embed.scala
- app/views/tv/embed.scala
- ui/site/package.json
- ui/site/src/component/assets.ts
- ui/site/src/component/mini-game.ts
- ui/site/src/puzzleEmbed.ts
- ui/site/src/tvEmbed.ts
This was previously broken by chessground bundling. lichess.makeChessground will not always be there to save you.
resolves #13515
> Fix tv & puzzle embeds

- ui/analyse/src/study/description.ts
> Study pinned comment: make the close button function more obvious.

- app/views/challenge/theirs.scala
**Show player ratings on:**
**Show player ratings off:**
> Honor show ratings pref on challenge page

- modules/security/src/main/Spam.scala
Include `membership` in referral replacements.
> Update referral blacklist and replacements

- modules/gathering/src/main/Quote.scala
1. "Success in chess requires many factors such as environment, hard practice, coach, talent... When we are children, we should not set the goal of becoming a super grandmaster. Do not play chess because of pressure, let chess become your joy and success will come naturally." - "Lê Quang Liêm"
2. "In chess, there is only one mistake: over-estimation of your opponent. All else is either bad luck or weakness." - "Savielly Tartakower"
3. "I do not set limits for myself. I will continue to play chess as long as I enjoy the fun of competing and learning new things." - "Lê Quang Liêm"
4. "In chess, as in life, a man is his own most dangerous opponent." - "Vasíliy Smyslóv"
5. "You can become a big master in chess only if you see your mistakes and shortcomings. Exactly the same as in life …
> Add 5 quotes

- ui/@types/lichess/index.d.ts
- ui/puz/src/util.ts
- ui/racer/src/ctrl.ts
- ui/round/src/ctrl.ts
- ui/site/src/component/sound.ts
- ui/site/src/soundMove.ts
- ui/storm/src/ctrl.ts
- add pentatonic sound to racer
- fix pentatonic sound in storm (san was historically always '--')
> lichess.sound() provides more control to prevent future mishaps

- app/views/round/watcher.scala
- ui/round/src/ctrl.ts
- ui/round/src/view/boardMenu.ts
Add ability to toggle zen mode when spectating a players TV channel (example: l.org/@/maia5/tv)
> Add zen mode to player TV

- modules/gathering/src/main/Quote.scala
This adds 10 more quotes from women players.
**Sources:**
Irina Krush: [Interview](https://thefearlessnomad.com/tfn-talks/tfn-talks-with-irina-krush)
Humpy Koneru: [Interview](https://www.onmanorama.com/sports/other-sports/2021/05/19/koneru-humpy-interview-chess-kerala-lockdown.html)
Pia Cramling: _Matthew Sadler & Natasha K Regan - Chess for Life_
Jennifer Shahade: [Interview 1](https://en.chessbase.com/post/interview-with-wgm-jennifer-shahade), [Interview 2](https://storytimechess.com/blog/womens-history-month-interview-with-grandmaster-jen-shahade/)
Judit Polgar: [Interview](https://www.thebeliever.net/a-nice-game-and-a-beautiful-game-an-interview-with-judit-polgar/)
Nona Gaprindashvili: [Interview](https://chessdailynews.com/interview-with-nona-gaprindashvili/)
Mariya Muzychuk: …
> Add 10 more quotes from women players

- ui/common/css/component/_dialog.scss
- ui/lobby/css/_setup.scss
> fix rtl dialog placement, align setup dlg labels properly

- app/views/site/help.scala
- ui/analyse/src/ctrl.ts
- ui/analyse/src/keyboard.ts
> press v to toggle variation arrows

- app/views/site/faq.scala
- pnpm-lock.yaml
- ui/site/src/component/sound.ts
In response to https://github.com/lichess-org/lila/issues/13586
> update autoplay faq for mobile draggers

- modules/gathering/src/main/Quote.scala
Found 7 duplicates in the quotes. This removes them.
> Remove duplicate quotes

- ui/analyse/src/autoShape.ts
> respect user arrows

- app/controllers/ForumPost.scala
- app/views/forum/post.scala
- conf/routes
- modules/forum/src/main/ForumDelete.scala
- modules/forum/src/main/ForumPostRepo.scala
- modules/forum/src/main/model.scala
- modules/msg/src/main/MsgPreset.scala
close https://github.com/lichess-org/lila/issues/13661
So that the user get to better understand why it was deleted. Also add a new reason to delete a post, "incorrect subforum".
Here's what the message looks like from the user perspective.
Not really sold on the "subforum" word, felt slightly more specific than "category" though.
> Include forum post message in deletion message

- app/views/forum/post.scala
- modules/forum/src/main/ForumPost.scala
- modules/forum/src/main/ForumTopicApi.scala
- modules/relation/src/main/RelationApi.scala
- modules/relation/src/main/RelationRepo.scala
- ui/site/css/forum/_post.scss
- ui/site/src/forum.ts
fixes #13653
I did the bare minimum fetching blocked users knowing that you _live_ for rewriting PRs to use indexes / secondaries / aggregations
> hide blocked forum posts

- modules/team/src/main/Request.scala
- modules/team/src/main/TeamApi.scala
This is an attempt to solve issue https://github.com/lichess-org/lila/issues/13590
A pre-declined request is added when kicking a team member to prevent re-joining
> add pre-declined team request when kicking a team member

- public/oops/toomanyrequests.txt
https://hq.lichess.ovh/#narrow/stream/96-infra/topic/leeeeeeroy.20jenkins/near/3032933
Need to be changed in nginx config after restart.
> Add a very slim 429 page

- modules/study/src/main/ServerEval.scala
- project/Dependencies.scala
For https://github.com/lichess-org/scalachess/pull/486 & https://github.com/lichess-org/scalachess/pull/488.
And a minor optimization for gameMoveWhileValid
> Scalachess 15.6.8

- ui/analyse/src/serverSideUnderboard.ts
Use login referrer on attempted game analysis to send the user back to the game after login.
Resolves #13746
> Use login referrer on attempted game analysis

- app/views/base/layout.scala
Added role tag for span elements: notification and challenges in order to be aria accessible.
> added role for span elements to be aria accessable

- app/controllers/Auth.scala
When a new user clicks the link to verify their email address, this will give them an indication that it was successful.
> Show success message after verifying email

- app/views/lobby/home.scala
- modules/puzzle/src/main/DailyPuzzle.scala
- ui/lobby/css/_about.scss
- ui/lobby/css/_layout.scss
- ui/lobby/css/_timeline.scss
- ui/lobby/src/main.ts
picking up some ideas from https://github.com/lichess-org/lila/pull/13780
avoiding forum and JS layout
> Lobby tweaks light

- app/views/analyse/jsI18n.scala
> Fix broken translation seen on NVUI analyze

- app/controllers/Team.scala
- app/views/team/form.scala
Exceptions always come back to bite 😅
> Fix edit page for mods when not in the team

- project/build.properties
https://github.com/sbt/sbt/releases/tag/v1.9.7
> Update sbt 1.9.7

- app/controllers/ForumPost.scala
- modules/forum/src/main/ForumDelete.scala
closes #13693
The deleteTopic function is similar to the doDelete function right below it. Perhaps there is some way to refactor, though I'm not sure how to.
> Delete topic if first and only post is deleted

- ui/analyse/src/study/studyShare.ts
closes #13876
Also auto selects when clicking the text
> Add clipboard buttons to embed and FEN on study share page

- modules/tournament/src/main/TournamentApi.scala
- modules/tournament/src/main/TournamentForm.scala
Fix https://github.com/lichess-org/lila/issues/8330
> Allow thematic tournaments to be rated, if position is balanced

- modules/study/src/main/ServerEval.scala
Split Merger.apply function into several smaller functions.
Tested locally.
> Refactor server eval

- project/Dependencies.scala
Fix https://github.com/lichess-org/scalachess/issues/495
> scalachess 15.6.9

- ui/swiss/css/_player-info.scss
- ui/tournament/css/_player-info.scss
> fix borders on tournament and swiss pairing

- app/views/site/help.scala
- ui/voice/css/_voice.scss
- ui/voice/css/_voiceMove.help.scss
fixes #13887, add links to more help
> voice help tweaks

- app/views/ublog/post.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/ublog.xml
> Translate "Discuss this blog post in the forum"

- build.sbt
- project/BuildSettings.scala
- project/Dependencies.scala
Beware, this updates x86 to RC11 as well
> Shaded native aarch64

- build.sbt
- modules/round/src/main/Rematcher.scala
- modules/round/src/test/RematcherTest.scala
Fix https://lichess.org/forum/lichess-feedback/not-able-to-castle-in-960
I refactored the logic of create new return game and also moved it out in order to test it.
> Fix castling issue when rematching chess960

- ui/analyse/src/study/chapterNewForm.ts
> render new chapter dlg as non modal to unbreak shepherd

- ui/common/src/dialog.ts
- ui/lobby/src/ctrl.ts
fix #13758 which also affected old Safari versions.
> wait for polyfill before showing a dialog on page load

- ui/site/src/component/mic.ts
- ui/voice/src/view.ts
> improve microphone errors

- ui/chart/src/acpl.ts
- ui/chart/src/common.ts
- ui/chart/src/division.ts
- ui/chart/src/game.ts
- ui/chart/src/movetime.ts
- ui/insight/src/chart.ts
follow up of https://github.com/lichess-org/lila/pull/13897
> Chartjs hotfixes

- modules/opening/src/main/OpeningPage.scala
- modules/opening/src/main/OpeningQuery.scala
- modules/tournament/src/main/BSONHandlers.scala
- modules/tournament/src/main/JsonView.scala
- modules/tournament/src/main/Schedule.scala
- modules/tournament/src/main/Thematic.scala
- modules/tournament/src/main/Tournament.scala
- modules/tournament/src/main/TournamentForm.scala
- project/Dependencies.scala
Migrate OpeningFen to StandardFen
> Bump Scalachess 15.6.11

- app/controllers/Analyse.scala
- app/controllers/Setup.scala
- ui/analyse/src/ctrl.ts
- ui/analyse/src/practice/practiceCtrl.ts
- ui/ceval/css/_settings.scss
- ui/ceval/src/ctrl.ts
- ui/ceval/src/engines/engines.ts
- ui/ceval/src/engines/externalEngine.ts
- ui/ceval/src/engines/simpleEngine.ts
- ui/ceval/src/engines/stockfishWebEngine.ts
- ui/ceval/src/engines/threadedEngine.ts
- ui/ceval/src/types.ts
- ui/ceval/src/view/settings.ts
> practice fixes

- ui/chart/src/acpl.ts
- ui/chart/src/common.ts
- ui/chart/src/division.ts
- ui/chart/src/movetime.ts
- ui/chart/src/ratingDistribution.ts
- ui/insight/src/chart.ts
> Chartjs-hotfixes-2

- app/views/ublog/form.scala
Per the discussion in content-blog, I have no attachment to this change. Just close if you prefer "Blog Etiquette"
> Two can play the clickbait game

- ui/ceval/src/engines/externalEngine.ts
> use movetime for external engine

- ui/cli/src/main.ts
Tested on mobile and desktop with commands/usernames.
Fixes #14026
> Fix cli search for mobile

- ui/.build/src/build.ts
- ui/.build/src/rebuild.ts
- ui/.build/src/tsc.ts
- ui/chart/tsconfig.json
- ui/insight/tsconfig.json
Seems ceval snuck in there and broke the tree. Could also move winningChances/povChances to common.
Purely cosmetic ui/build refactoring as well.
> Fix chart & insight dependencies in tsconfig

- .prettierignore
- ui/.build/readme
- ui/.build/src/main.ts
document --update and -n in readme as well
> add -n alias for --no-install, prettierignore readme

- ui/ceval/src/ctrl.ts
- ui/ceval/src/engines/engines.ts
- ui/ceval/src/engines/stockfishWebEngine.ts
Perhaps rudimentary error handling is a good idea for a new default foisted upon hundreds of thousands
> Tell users why their browser can't load a module

- ui/analyse/css/_keyboard.scss
- ui/analyse/src/ctrl.ts
- ui/analyse/src/keyboard.ts
I think everyone has seen it by now.
> remove "once" variation arrow help

- ui/puz/src/current.ts
- ui/racer/src/ctrl.ts
- ui/site/src/component/sound.ts
- ui/storm/src/ctrl.ts
> add opponent capture sound to storm & puzzle racer

- ui/site/src/component/powertip.ts
fix #14039. it will be interesting to see what this breaks.
> powertip smart placement

- app/views/swiss/bits.scala
- app/views/tournament/bits.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/site.xml
> Fix misunderstanding between "Draw rate" and "Draw games"

- ui/common/src/userLink.ts
- ui/tournament/css/_team-info.scss
also remove trailing space from user rating
fix https://github.com/lichess-org/lila/issues/14117
before
after
> Team battle: add space between username and rating

- translation/source/broadcast.xml
I was translating and I noticed this error
> missing plural

- modules/user/src/main/UserFlair.scala
[`flair/list.txt`](https://github.com/lichess-org/lila/blob/master/public/flair/list.txt) is in this repo now so we can read it with `scala.io.Source` instead of an HTTP request
> Flair db refactoring

- ui/site/src/component/log.ts
Partially close https://github.com/lichess-org/lila/issues/14120, but good enough for now
> Always include the URL for unhandled errors

- ui/insight/src/view.ts
https://github.com/lichess-org/lila/issues/14174
> hide clear btn  when no filters

- ui/site/src/forum.ts
part of https://github.com/lichess-org/lila/pull/14151  
can just use `innerHtml` ?
> remove redundant checking

- translation/source/site.xml
> change formatting on import game explanation

- app/views/lobby/bits.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/site.xml
> translate showUnreadLichessMessage text

- app/templating/SetupHelper.scala
- app/views/site/faq.scala
- modules/i18n/src/main/I18nKeys.scala
- modules/rating/src/main/PerfType.scala
- translation/source/site.xml
follow https://github.com/lichess-org/lila/commit/8ed7fe84f9b2b6499224b1f4c590212fe001616a
In Vietnamese, this word can still be translated
> Translate Bullet time control

- ui/ceval/src/engines/externalEngine.ts
- ui/ceval/src/util.ts
> better 503 error dialog for external engine

- app/templating/FormHelper.scala
- translation/source/site.xml
> tweak `Set your flair`

- ui/site/src/component/sound.ts
Restores changes from #13287 that handled the absence of AudioContext. Tested.
Resolves #14240
> Handle absence of AudioContext

- app/controllers/Appeal.scala
- app/views/appeal/tree.scala
- modules/ublog/src/main/UblogApi.scala
close https://github.com/lichess-org/lila/issues/13687
(account now removed from the sentence for clarity)
> Implement appeal page for users whose blogs are hidden

- ui/puzzle/src/view/main.ts
> puzzle rating change hide when disabled

- ui/site/src/component/socket.ts
- ui/site/src/diagnostic.ts
add a copy to clipboard button and log sri on timeout in case of multiple tabs
> more knowing, easier to haz

- ui/site/css/user/_rating.stats.scss
make rating chart responsive for all devices.
https://lichess.org/stat/rating/distribution/blitz
> responsive rating chart

- ui/analyse/src/study/relay/relayTourView.ts
- ui/analyse/src/study/studyView.ts
- ui/analyse/src/view/view.ts
- ui/common/src/snabbdom.ts
- ui/lobby/src/view/setup/components/timePickerAndSliders.ts
- ui/puzzle/src/view/after.ts
- ui/puzzle/src/view/main.ts
- ui/puzzle/src/view/side.ts
- ui/racer/src/view/main.ts
- ui/round/src/view/user.ts
- ui/simul/src/view/created.ts
- ui/storm/src/view/end.ts
- ui/storm/src/view/main.ts
- ui/tournament/src/view/playerInfo.ts
- ui/tournament/src/view/table.ts
Don't allow numbers in looseH (which is not default) snab arguments.
> convert number -> string in snab args

- modules/game/src/main/GameRepo.scala
> Fix suggestion of anonymous users on challenge creation

- app/controllers/Ublog.scala
- app/views/ublog/post.scala
- modules/mod/src/main/ModlogApi.scala
- modules/ublog/src/main/Env.scala
- modules/ublog/src/main/UblogApi.scala
- modules/ublog/src/main/UblogForm.scala
- modules/ublog/src/main/UblogPost.scala
- modules/ublog/src/main/UblogRank.scala
- ui/site/css/ublog/_post.scss
- ui/voice/css/_voice.scss
- ui/voice/src/move/moveCtrl.ts
In case we need to use a trebuchet to launch Phil and Prismic.io into an active volcano.
> UI lets mods pin ublog to top spot

- ui/chart/src/lag.ts
- ui/chart/src/ratingHistory.ts
Apologies for the repeated PRs.
> More chart fixes.

- app/http/HttpFilter.scala
- app/http/ResponseHeaders.scala
- ui/common/src/wakeLock.ts
Allow usage of wake lock API on safari. Also list browser permissions we need (just for adherence to spec).
> wake lock fixes

- modules/pref/src/main/PrefForm.scala
- modules/pref/src/main/PrefSingleChange.scala
Needed for https://github.com/lichess-org/mobile/pull/478
> [Mobile] Add "follow" to single pref API

- ui/chess/src/moveRootCtrl.ts
- ui/keyboardMove/src/main.ts
- ui/puzzle/src/ctrl.ts
- ui/round/src/ctrl.ts
- ui/voice/src/main.ts
- ui/voice/src/move/interfaces.ts
- ui/voice/src/move/moveCtrl.ts
fix #14477
also cleanup auxiliary move update calls
> fix blindfold busting keyboard move

- app/views/base/layout.scala
- app/views/base/topnav.scala
- https://github.com/lichess-org/lila/issues/14498
https://github.com/lichess-org/lila/assets/11773963/b9f0a470-8249-46da-93c6-db5afdf1b1da
> Feat: friends link in community

- app/views/board/bits.scala
- app/views/game/mini.scala
- modules/game/src/main/JsonView.scala
- ui/round/src/ctrl.ts
- ui/round/src/view/main.ts
fixes #14483
and holy hell, what the *#!? was i smoking when i hid pieces in JSON?
> show mini-board pieces for completed games

- app/controllers/Game.scala
- app/views/user/download.scala
- conf/routes
This endpoint is still undocumented so I don't think it should affect anyone.
> Don't give users the option to download others' imports in the first place

- ui/analyse/src/study/studyChapters.ts
Maybe using the location object here is not the way to go, I am not sure about that.
And currently it works also for studies which is a slight deviation from the issue.
#14502
> Broadcast: Individual game URL in address bar

- ui/analyse/css/study/panel/_multiboard.scss
- ui/analyse/src/study/multiBoard.ts
> Added visual indicator to help knowing game advantage

- ui/analyse/src/study/practice/studyPracticeCtrl.ts
- ui/analyse/src/study/studyChapters.ts
- ui/analyse/src/study/studyCtrl.ts
- ui/analyse/src/view/view.ts
Also allow back button to return to broadcast overview
> always show most complete address in studies/broadcasts

- app/controllers/RelayRound.scala
- modules/relay/src/main/RelayFetch.scala
- modules/relay/src/main/RelayGame.scala
- modules/relay/src/main/RelayInputSanity.scala
- modules/relay/src/main/RelayPush.scala
- modules/relay/src/main/RelaySync.scala
- modules/study/src/main/Chapter.scala
- modules/study/src/main/MultiPgn.scala
it works now. golf away
You can use this script to verify changes.
[push-test.zip](https://github.com/lichess-org/lila/files/14077791/push-test.zip)
> always match tags on push

- modules/study/src/main/MultiPgn.scala
Closes #14598
Idk why the current version doesn't work. Testing it on regex101 with java8 seems to yield the desired result.
> Fix pgn split regex

- modules/db/src/main/dsl.scala
- modules/notify/src/main/Notification.scala
- modules/notify/src/main/NotificationRepo.scala
- modules/notify/src/main/NotifyApi.scala
where "spammy" includes broadcast round started and streamer started.
> spammy notifications marked as read 6 hours after creation

- ui/analyse/css/practice/_underboard.scss
- ui/common/css/base/_elements.scss
- ui/common/css/component/_reconnecting.scss
- ui/common/css/component/_tagify.scss
- ui/learn/css/_learn.scss
- ui/learn/css/_map.scss
- ui/learn/css/_screen.scss
- ui/round/css/_control.scss
- ui/site/css/mod/_activity.scss
- ui/site/css/mod/_user.scss
- ui/site/css/practice/_app.scss
- ui/tutor/css/build/_tutor.scss
Removes duplicated properties and empty scss files
> CSS cleanup

- app/controllers/RelayRound.scala
- modules/db/src/main/dsl.scala
- modules/relay/src/main/BSONHandlers.scala
- modules/relay/src/main/RelayApi.scala
- modules/relay/src/main/RelayTourForm.scala
> merge form data into existing relay_tour documents

- modules/study/src/main/BSONHandlers.scala
- modules/study/src/main/ChapterRepo.scala
- modules/study/src/main/Node.scala
As we don't ever read that field
> Remove order field in study database

- modules/study/src/test/MultiPgnTest.scala
- modules/study/src/test/PgnFixtures.scala
> Add test for MultiPgn

- app/views/base/layout.scala
- modules/i18n/src/main/I18nKeys.scala
- translation/source/site.xml
- ui/common/css/abstract/_z-index.scss
- ui/common/css/component/_reconnecting.scss
- ui/site/src/component/socket.ts
Don't consume firefox demerits and log errors when there's no hope of connecting.
> dont attempt lila-ws connection when offline

- app/controllers/RelayTour.scala
- app/views/relay/tour.scala
- conf/routes
- modules/i18n/src/main/I18nKeys.scala
- modules/relay/src/main/RelayPager.scala
- modules/relay/src/main/RelayTourRepo.scala
- translation/source/broadcast.xml
Closes #14645 
Took me a lot of time. Thanks to @schlawg (for his help on discord) and @fitztrev (for making it simple to work on lila to lila-docker)
> Added broadcast subscription list

- ui/analyse/src/study/chapterEditForm.ts
- ui/analyse/src/study/chapterNewForm.ts
- ui/analyse/src/study/inviteForm.ts
- ui/analyse/src/study/studyForm.ts
- ui/analyse/src/study/topics.ts
This is a temporary fix to get studies up and running again without reloads after every edit. I'll need to spend a bit more time for a better fix which will come later today.
> hotfix snab dialogs clobbering body overflow

- modules/relay/src/main/RelayFetch.scala
It's an idea to try to add more data to the pgns
Maybe in the future it will be used for something else
> LCC: Add fideId

- app/controllers/RelayRound.scala
- ui/pagelets/css/coach/_list.scss
close https://github.com/lichess-org/lila/issues/14729
> hide overflow even n coach list

- app/views/site/page.scala
Mention new functionality on https://lichess.org/developers after #14726
> Update docs for channel tv embeds

- .github/workflows/assets.yml
- .github/workflows/lint.yml
- v3 of `pnpm/action-setup` to remove deprecation warnings
- can run install from the same step
> Update github actions

- modules/user/src/main/UserForm.scala
no more 1000
https://www.fide.com/news/2831
> Min rating FIDE is now 1400

- public/images/fide-fed/BLR.svg
- public/images/fide-fed/RUS.svg
- public/images/fide-fed/W.svg
I tried to reduce the flag a little more
and I put it as a symbolic link so as not to have 2 identical files
> reduce worldwide.svg and use symbolic

- modules/relay/src/main/RelayPlayers.scala
Sometimes we may have to force a title to appear
Like NM which is not shown by FIDE
In replace:
```
Original Name = FIDE ID / Title
```
> be able to change the title imposed by fide

- ui/pagelets/css/_video.scss
Reverts lichess-org/lila#14816
> Revert "Fix Video Title Cutoff"

- translation/source/appeal.xml
Feedback from [crowdin comment](https://crowdin.com/editor/lichess/180/en-pt?view=comfortable&filter=basic&value=0#20152)
> Remove unnecessary comma in translation string

- modules/study/src/main/JsonView.scala
Closes #14880 
```bash
http --json http://localhost:8080/study
```
```diff
{
"paginator": {
"currentPage": 1,
"currentPageResults": [
{
"chapters": [
"Chapter 1"
],
"id": "0mO67S28",
"liked": false,
"likes": 1,
"members": [
{
"role": "w",
"user": {
"flair": "people.person-frowning-medium-dark-skin-tone",
"id": "admin",
"name": "Admin"
}
}
],
"name": "Test Study",
"owner": {
"flair": "people.person-frowning-medium-dark-skin-tone",
"id": "admin",
"name": "Admin"
},
+                "topics": [
+                    "Openings",
+                    "Ruy Lopez"
+                ],
"updatedAt": 1710599159175
}
],
"maxPerPage": 16,
"nbPages": 625,
"nbResults": 9999,
"nextPage": 2,
"previousPage": null
}
}
```
> Add topics to study list API response

- ui/analyse/src/study/interfaces.ts
- ui/analyse/src/study/serverEval.ts
Closes https://github.com/lichess-org/lila/issues/14881
> Use existing json data to determine if analysis is completed

- app/views/userTournament/list.scala
> fix missing space in user's tournaments

- ui/analyse/css/study/relay/_layout.scss
|---|---|
| ![Screen Shot 2024-03-19 at 19 11 33](https://github.com/lichess-org/lila/assets/53343585/2c775103-0bab-4784-b5c8-a142a42aa3d5)  | ![Screen Shot 2024-03-19 at 19 11 51](https://github.com/lichess-org/lila/assets/53343585/bd0ecccf-09dd-42cf-8f1f-30eca0718456) |
> Fix relay round-training mobile view

- modules/user/src/main/Links.scala
> Remove chess24

- ui/analyse/src/plugins/studyTour.ts
1. Fix bug that allowed users to create multiple tours at the same time.
2. Code golf
> studyTour refactor

- modules/user/src/main/Links.scala
- Mastodon's “official” Mastodons added
- Removed servers that were shut down
- Added some extra servers
> Update mastodon domains

- modules/study/src/main/StudySocket.scala
- modules/study/src/main/TreeBuilder.scala
they do nothing, right?
Probably been useless after: https://github.com/lichess-org/lila/commit/0dd1e3759635cd23979aedfc9a3fbcd937b05301
> Remove some recursive call that does nothing

- modules/hub/src/main/tree/newTree.scala
- modules/puzzle/src/main/JsonView.scala
- modules/puzzle/src/main/Puzzle.scala
- modules/puzzle/src/test/JsonViewTest.scala
- project/Dependencies.scala
Use NewTree more, start with Puzzle (only for backward compatible), so it's kind of small.
We can remove the tests later to replace with some kind of snapshots tests if We want.
> NewTree for puzzle

- app/controllers/Analyse.scala
- app/controllers/UserAnalysis.scala
- build.sbt
- modules/api/src/main/RoundApi.scala
- modules/game/src/main/Game.scala
- modules/round/src/main/JsonView.scala
- modules/round/src/main/RoundAsyncActor.scala
- modules/round/src/main/TreeBuilder.scala
- modules/study/src/main/GameToRoot.scala
- modules/tree/src/main/ExportOptions.scala
- modules/tree/src/main/Game.scala
- modules/tree/src/main/TreeBuilder.scala
- Create `Game` trait in tree
- Move `TreeBuilder` to tree
- Remove `round` deps from study
- Rename WithFlags to ExportOptions and move it to its own file
> Move round.TreeBuilder to tree

- ui/site/src/topBar.ts
shows the topBar when invisible from scrolling
fixes [14954](https://github.com/lichess-org/lila/issues/14954)
> Show topBar when s or / is pressed

- app/controllers/User.scala
Closes #14629 
Only 'Ana' was friend in the shown screenshot
> Show additional results in user search not only friends

- modules/common/src/main/Iso.scala
- modules/common/src/main/Json.scala
- modules/db/src/main/Handlers.scala
- modules/forum/src/main/BSONHandlers.scala
- modules/irwin/src/main/IrwinThresholds.scala
- modules/memo/src/main/SettingStore.scala
- modules/mod/src/main/Presets.scala
- modules/puzzle/src/main/PuzzleAngle.scala
- modules/puzzle/src/main/PuzzlePath.scala
- modules/rating/src/main/RatingFactor.scala
- modules/relay/src/main/RelayGame.scala
- modules/report/src/main/Reason.scala
- modules/report/src/main/ReportThresholds.scala
- modules/report/src/main/Room.scala
- modules/security/src/main/EmailChange.scala
- modules/security/src/main/StringToken.scala
- modules/tutor/src/main/TutorNumber.scala
- project/Dependencies.scala
conflicting with master pretty hard now
> upgrade to split scalalib

- bin/trans-dump
> Fix hub -> core path in bin/trans-dump

- ui/analyse/src/study/relay/relayTourView.ts
- ui/analyse/src/study/relay/relayView.ts
- ui/analyse/src/study/relay/videoPlayerView.ts
- ui/analyse/src/study/studyDeps.ts
- ui/analyse/src/view/components.ts
The changes in this PR are also applied in the lichess-org:post-patch branch on top of [7c02625](https://github.com/lichess-org/lila/commits/7c02625c0de582153cd269d70cb230585a99fbe1), which is live on prod.
> fixes for pinned image on mobile (round 1)

- modules/evalCache/src/main/BSONHandlers.scala
- modules/evalCache/src/main/Env.scala
- modules/evalCache/src/main/EvalCacheApi.scala
- modules/evalCache/src/main/EvalCacheEntry.scala
- modules/evalCache/src/main/package.scala
- project/Dependencies.scala
After https://github.com/lichess-org/lila-ws/pull/555.
> use normalized BinaryFen as evalCache id (#15020)

- ui/common/css/header/_header.scss
> z-index tricks

- modules/analyse/src/test/AnnotatorTest.scala
> Revert annotator test

- COPYING.md
- README.md
Could not find any source of it left.
> Remove highcharts licensing exception

- modules/tree/src/main/newTree.scala
- modules/tree/src/main/tree.scala
Then We can make it constant.
Similar for `NewTree.makeNodeWriter`.
> Tree.nodeListJsonWriter argument is always true

- modules/study/src/main/ExplorerGame.scala
regression from https://github.com/lichess-org/lila/commit/3a2a9d9b89baf3f38dc4cf3584e6a44175f4aa36#diff-c2a3376c8f9e5a8ef107d9c1e789b5a36d235af4779bfa70a2632d1f78bd9577L64
Fix #15145
> Fix wrong player names when citing games

- ui/chart/src/chart.ratingHistory.ts
> Rating History Chart: Use UTC always

- modules/common/src/main/LameName.scala
- modules/common/src/test/LameNameTest.scala
https://hq.lichess.ovh/#narrow/stream/91-mod-usernames/topic/main/near/3299574
> remove "shit" from lamename

- ui/common/css/header/_header.scss
- ui/site/src/topBar.ts
fix pieces overlaying dasher, notifications, and challenge menu without removing the original hack that lets 3d pieces overlay top bar.
> continue 3d vs sticky topnav rock paper scissors

- modules/study/src/main/AnaDests.scala
- modules/tree/src/main/tree.scala
As We use play-json module from scala chess
> Remove unused destString funcion

- ui/site/src/sound.ts
> Fix pentatonic

- modules/relay/src/main/RelayPlayers.scala
follow up bug I created after golfing in #15235
> Duplicate player's name with it's umlautified version

- ui/dasher/src/links.ts
I didn't notice that this field is missing #15223
> fix translante in board

- app/controllers/Practice.scala
- app/controllers/Puzzle.scala
- app/controllers/Study.scala
- app/views/puzzle/ui.scala
- modules/analyse/src/main/ExternalEngine.scala
- modules/api/src/main/RoundApi.scala
- modules/puzzle/src/main/ui/PuzzleUi.scala
- modules/web/src/main/AssetManifest.scala
- ui/analyse/src/autoShape.ts
- ui/analyse/src/ctrl.ts
- ui/analyse/src/practice/practiceCtrl.ts
- ui/ceval/src/ceval.ts
- ui/ceval/src/ctrl.ts
- ui/ceval/src/engines/engines.ts
- ui/ceval/src/engines/externalEngine.ts
- ui/ceval/src/protocol.ts
- ui/ceval/src/types.ts
- ui/ceval/src/view/main.ts
- ui/ceval/src/view/settings.ts
- ui/common/src/common.ts
- ui/puzzle/src/ctrl.ts
- ui/puzzle/src/interfaces.ts
must be deployed with lila-engine b7a309b
- fix ceval, puzzle, learn, and practice issues
- add support for other search types
> ceval and external engine tweaks

- modules/fishnet/src/main/FishnetPlayer.scala
This reverts commit 118550d94e47dc6026b22b1071a71005daab8f76.
This was an oversight from me as We already check it here: https://github.com/lenguyenthanh/lila/blob/182c35685082e31803dcbb3cd6b90b23fcbdb1f6/modules/round/src/main/Player.scala#L122
and https://github.com/lenguyenthanh/lila/blob/182c35685082e31803dcbb3cd6b90b23fcbdb1f6/modules/fishnet/src/main/FishnetPlayer.scala#L55
> Revert "Dont send request to lila-fishnet when the game is finished"

- modules/team/src/main/ui/RequestUi.scala
- ui/bits/css/team/_show.scss
- ui/common/css/layout/_page-menu.scss
Closes #13195 
[team-lichess.webm](https://github.com/lichess-org/lila/assets/11333925/8ff49fc0-f9df-4997-aea5-d5b2b4d199a1)
> Improved responsiveness to join team requests

- modules/relay/src/main/ui/RelayTourUi.scala
[Screen recording 2024-05-18 20.34.45.webm](https://github.com/lichess-org/lila/assets/9739913/243e60c7-3126-43da-ada2-116558e00461)
> fix menu in broadcasts

- modules/forumSearch/src/main/ForumSearchApi.scala
- project/Dependencies.scala
> Bump lila-search 3.0.0-RC6

- modules/core/src/main/forum.scala
- modules/forum/src/main/ForumPostRepo.scala
- modules/forumSearch/src/main/Env.scala
- modules/forumSearch/src/main/ForumSearchApi.scala
tested with `LILA_CLI_TOKEN_DEV=mytoken ./bin/cli "forum search backfill 1717286401"`
> Add forum posts backfill functionality to cli

- ui/dasher/src/piece.ts
https://hq.lichess.ovh/#narrow/stream/8-dev/topic/reduce.20knight.20size.20in.20piece.20set.20browser.3F
> piece set menu - reduce knight size & add 4th column 

- ui/puz/css/_puz.scss
https://github.com/lichess-org/lila/assets/126312812/3ceaf96c-92e5-418c-9593-da015ffd17d0
https://github.com/lichess-org/lila/assets/126312812/0ebf5f5f-8c1c-4308-baf7-6dd561e2830a
> Make puzzle storm board scale correctly

- ui/analyse/src/study/multiBoard.ts
> Remove rating 0 in multiboard

- modules/fide/src/main/FidePlayerSync.scala
- modules/fide/src/main/ui/FideUi.scala
> If a user with a rating of 0 says they are `No Rated`

- app/controllers/Relation.scala
- conf/routes
Api is missing for the mobile app.
> Enable OAuth for /rel/block/:userId

- .github/workflows/assets.yml
- .github/workflows/lint.yml
- pnpm-lock.yaml
- ui/@types/lichess/index.d.ts
- ui/README.md
- ui/chat/src/spam.ts
- ui/chat/tests/spam.test.ts
- ui/common/src/richText.ts
- ui/common/tests/richText.test.ts
- ui/game/src/status.ts
- ui/jest.config.js
- ui/keyboardMove/package.json
- ui/keyboardMove/tests/keyboardSubmit.test.ts
- ui/package.json
- ui/site/src/clockWidget.ts
- ui/site/src/log.ts
- ui/site/src/once.ts
- ui/site/src/powertip.ts
- ui/site/tests/once.test.ts
- ui/site/tests/timeago.test.ts
- ui/vitest.config.ts
```bash
cd ui
pnpm test    # or pnpm test:watch
```
> Vitest with jsdom for frontend tests

- modules/forumSearch/src/main/ForumSearchApi.scala
- modules/gameSearch/src/main/GameSearchForm.scala
- modules/search/src/main/PaginatorBuilder.scala
- modules/search/src/main/SearchReadApi.scala
- modules/studySearch/src/main/Env.scala
- project/Dependencies.scala
- Use Long in CountOutput
- Fix forum post date (in milliseconds instead of seconds)
> Lila search RC9

- modules/study/src/main/JsonView.scala
> Add study flair to json page view

- modules/api/src/main/Cli.scala
- modules/core/src/main/forum.scala
- modules/forum/src/main/ForumDelete.scala
- modules/forum/src/main/ForumPostApi.scala
- modules/forumSearch/src/main/Env.scala
- modules/forumSearch/src/main/ForumSearchApi.scala
go with https://github.com/lichess-org/lila-search/pull/228
> Stop using http request to index forum posts  as We use lila-search's ingestor for indexing

- pnpm-lock.yaml
- ui/insight/package.json
- ui/opening/package.json
Fix insights hot reload. Follow up of 0cc944c9c3c7d5ab6f3c3b3d70b0d80072a97156.
> upgrade chartjs everywhere

- ui/bits/css/user/_show.scss
> Align multi-line text next to icon on profile dropdown

- modules/relay/src/main/ui/FormUi.scala
Someone was too lazy to comment on documentation for a while. And I take advantage and correct a space that shouldn't exist
> Fix texts and add missing info

- modules/forum/src/main/ForumForm.scala
> Limit forum post length to 10k charaters

- modules/pref/src/main/PrefForm.scala
- modules/pref/src/main/PrefSingleChange.scala
This is required to implement https://github.com/lichess-org/mobile/issues/785
> feat: allow changing clock.sound via PrefSingleChange

- ui/analyse/src/study/relay/relayTourView.ts
Broadcast overview: if tourney last a day, don't show end date
> Broadcast calendar view

- ui/site/src/boot.ts
> restore source code link in console

- modules/relay/src/main/ui/FormUi.scala
> Broadcast email: set hyperlink

- modules/team/src/main/JsonView.scala
> Add team flair to API response

- ui/bits/src/bits.login.ts
> Login: load password visibility toggle after unsuccessful attempt 

- package.json
- pnpm-lock.yaml
- ui/.build/package.json
- ui/chess/src/chess.ts
- ui/chess/src/sanWriter.ts
- ui/chess/tsconfig.json
﻿As discussed in zulip, let's use the latest Typescript 5.5 feature for composite projects like ours - [isolated declarations](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#isolated-declarations)!
Note that there is some tsconfig caching going on - I had to delete `ui/chess/tsconfig.tsbuildinfo` to get the latest `tsconfig.json` changes to be honored.
> Enable IsolatedDeclarations in chess module

- modules/pref/src/main/JsonView.scala
- modules/pref/src/main/PrefForm.scala
- modules/pref/src/main/PrefSingleChange.scala
Similar to [#15613](https://github.com/lichess-org/lila/pull/15613)
This is needed for https://github.com/lichess-org/mobile/issues/759
> feat: add pieceNotation to settings API

- modules/game/src/main/Event.scala
- project/Dependencies.scala
And refactor `Event.Castling` more ergonomic.
> Scalachess 16.1.0

- modules/relay/src/main/ui/RelayUi.scala
image in the relay is the cover of the event
we will show it in embed
> Add image the relay to embed

- app/controllers/Game.scala
I wasn't sure of what API you'd want to have, so I opted for the simplest way. Feel free to change.
> [Mobile] Open /bookmark to oAuth

- conf/routes
> Alias broadcast round reset to /api prefix

- ui/.build/src/main.ts
- ui/msg/tests/enhance.test.ts
- ui/msg/tsconfig.json
Also fix test that was reverted
> Fix build assets passing silently

- ui/ceval/src/ctrl.ts
- ui/ceval/src/engines/engines.ts
- ui/ceval/src/engines/externalEngine.ts
- ui/ceval/src/engines/simpleEngine.ts
- ui/ceval/src/engines/stockfishWebEngine.ts
- ui/ceval/src/engines/threadedEngine.ts
- ui/ceval/src/util.ts
- ui/ceval/tsconfig.json
Follow up of #15700 and #15698
> Enable IsolatedDeclarations in ceval module

- modules/analyse/src/main/Annotator.scala
- modules/analyse/src/test/AnnotatorTest.scala
- modules/game/src/main/PgnDump.scala
- modules/game/src/test/EventTest.scala
- modules/game/src/test/PgnDumpTest.scala
- modules/relay/src/main/RelayFetch.scala
- modules/study/src/main/PgnDump.scala
- modules/study/src/main/StudyPgnImport.scala
- modules/study/src/test/StudyArbitraries.scala
- project/Dependencies.scala
With improvement for generalize PGN:
https://github.com/lichess-org/scalachess/pull/562 and
https://github.com/lichess-org/scalachess/pull/565
> Bump scalachess 16.2.1

- app/controllers/User.scala
- modules/user/src/main/ui/UserBits.scala
- ui/site/src/boot.ts
[Screen recording 2024-07-21 14.37.59.webm](https://github.com/user-attachments/assets/8748bd53-ed67-4c33-ba20-a7960d13bc1b)
Many people complain that the unlock button is unavailable for closed accounts
Will try to help resolve this issue.
close #15756
> Show unblock button if user has closed

- modules/relay/src/main/RelayFetch.scala
Relay without Tag Date can make problems
> Let's get date in json

- app/controllers/RelayRound.scala
Closes https://github.com/lichess-org/lila/issues/15745.
> Add mobile OAuth scope to broadcast round endpoint

- app/controllers/User.scala
- modules/user/src/main/ui/UserBits.scala
- ui/site/src/boot.ts
The unfollow button is very requested so I took advantage of it and added it 
When I discovered that there was an error I hadn't seen, everything returned hide and didn't continue
> Add button unfollow for accounts clossed and fix #15760

- app/controllers/Insight.scala
- modules/insight/src/main/Share.scala
what they see when it's closed
> No insights for closed accounts

- modules/core/src/main/user.scala
Commit d40fbda refactored firstName and lastName into a single realName, but didn't adjust the profile completion percentage calculation.
https://lichess.org/forum/lichess-feedback/75-profile-completion
> Fix profile completion percentage

- modules/user/src/main/ui/UserBits.scala
fix https://github.com/lichess-org/lila/commit/18e9131e7e34d363516e916784654dc1ce1b57ab
Looks like you forgot to remove `!` for unfollow
> Fix unfollow for acc closed

- modules/fide/src/main/Federation.scala
- modules/fide/src/main/ui/FideUi.scala
after https://github.com/lichess-org/lila/commit/f4757e048982a3a55a9be9e3314d4329fea914b2 was done
Old code may be removed due to no longer being verified
> Remove Dead: not need check "NON" fed

- modules/api/src/main/GameApiV2.scala
> Fix game export api

- modules/activity/src/main/ActivityUi.scala
> Activity: hide forum posts from sbed/sb/troll users

- ui/common/css/component/_markdown.scss
> Add icon for markdown header anchor links

- modules/gameSearch/src/main/GameSearchApi.scala
close #15885 and possible #15899
> Fix infinite loop when response is empty

- ui/learn/src/view.ts
> In /learn link specifically to videos tagged beginner

- modules/study/src/main/StudyApi.scala
- modules/study/src/main/StudyRepo.scala
This helps ingestor index study more often.
> Use StudyRepo.updateNow when updating study/chapters

- modules/gameSearch/src/main/GameSearchApi.scala
Another attempt to fix #15885
@ornicar Do We have any logs related to this?
> Don't query max number of items at one

- modules/api/src/main/GameApiV2.scala
> Revive Config.postFilter filter

- ui/bits/src/bits.cropDialog.ts
close https://github.com/lichess-org/lila/issues/15909, cc @schlawg
> Image cropper: fallback to jpeg if source is not a png

- ui/analyse/src/study/relay/relayTourView.ts
> Broadcast notes: hyperlink support

- modules/analyse/src/main/Analyser.scala
- modules/core/src/main/game/misc.scala
- modules/gameSearch/src/main/Env.scala
- modules/gameSearch/src/main/GameSearchApi.scala
Required https://github.com/lichess-org/lila-search/pull/291
> Remove indexing games in favor of lila-search ingestor

- app/controllers/Opening.scala
- modules/irc/src/main/IrcApi.scala
- modules/irc/src/main/ZulipClient.scala
close https://github.com/lichess-org/lila/issues/15968
> Send /opening edits to Zulip

- eslint.config.mjs
- pnpm-lock.yaml
- ui/@types/lichess/index.d.ts
- ui/ceval/package.json
- ui/ceval/src/engines/engines.ts
- ui/dgt/src/play.ts
actual work done by disservin & niklasf
> add stockfish 17

- app/controllers/Study.scala
Needed for https://github.com/lichess-org/mobile/pull/990
> add mobile OAuth scope to mine.*() study endpoints

- ui/analyse/src/ctrl.ts
- ui/analyse/src/study/practice/interfaces.ts
- ui/analyse/src/study/practice/studyPracticeCtrl.ts
- ui/analyse/src/study/studyCtrl.ts
fixes #15367 
I'm brand new to Lila and new to Lichess as a user, so any suggestions of improvements or unintended consequences from this change are more than welcome. I tested that it shows a normal analysis chapter as complete immediately and upon refresh and does not affect behaviour for interactive lesson and practice with computer chapters, but there may be other downstream effects I haven't accounted for.
Thanks to commenters on the original issue for providing extremely detailed reproduction details and diagnosis.
> fix: can't complete knight bishop "epic failure"

- ui/bits/src/bits.user.ts
Closes #16043 
[16043.webm](https://github.com/user-attachments/assets/9c1c05d0-c20b-40f6-9189-08476c0e4085)
> Fix Infinite scroll on user profile page

- modules/simul/src/main/ui/SimulHome.scala
- ui/simul/package.json
- ui/simul/src/simul.home.ts
> move javascript from SimulHome.scala to ui/simul/src/simul.home.ts

- ui/chart/src/chart.ratingDistribution.ts
Untested, but it's a solution for https://github.com/lichess-org/lila/pull/16035#issuecomment-2344071425
cc @seren5240
> Show Your Rating in parens too

- ui/bits/src/bits.user.ts
fixes #15814
Unify behaviour between bio and social media links. Tested in dev environment.
> External link warning in bio links

- app/controllers/Mod.scala
> lifetime patron for content and broadcast teams

- ui/analyse/src/study/gamebook/gamebookPlayCtrl.ts
- ui/analyse/src/study/studyCtrl.ts
fixes #15808
Fixed the actual state corruption and also removed non-null assertion to improve future type safety.
> fix: interactive lesson state

- ui/analyse/css/study/_chapters.scss
- ui/analyse/css/study/_list.scss
- ui/analyse/css/study/_members.scss
- ui/analyse/css/study/_search.scss
- ui/analyse/src/study/studyChapters.ts
- ui/analyse/src/study/studyMembers.ts
- ui/analyse/src/study/studySearch.ts
- ui/common/src/dialog.ts
Improves accessibility and keyboard navigation when selecting games from chapter search in studies. Related to #9509
> Replace divs with buttons in study chapter

- modules/relation/src/main/ui/RelationUi.scala
I apologize in advance for the commit that has been around for about a year now.
It appears that users who don't have wings are redirected back to index without the correct parameters.
I made the correction that checks if the user has wings or not
if you don't have to use index
> FIX: User without Wings Gift Wings to another user

- pnpm-lock.yaml
- ui/package.json
Prevents deprecation notice when running
```
cd ui
pnpm run test
```
> Update jsdom to v25.0.1

- modules/relay/src/main/RelayTour.scala
- modules/relay/src/main/RelayTourForm.scala
- modules/relay/src/main/ui/FormUi.scala
- ui/analyse/src/study/relay/interfaces.ts
- ui/analyse/src/study/relay/relayTourView.ts
add more information in the quick information, to reduce the long description
> Relay Tour Info: add location, websiteOfficial, standings

- modules/tournament/src/main/BSONHandlers.scala
Instead of using Tourney instant, which is staggered.
> Store Schedule's LocalDateTime

- bin/mongodb/create-trophy-kinds.js
Removes deprecation notice when running in Mongodb v7 environments
Also tested on Mongodb v4.4 to ensure it still works for other versions too.
> Trophy seed script to use insertOne

- ui/analyse/src/study/relay/relayTourView.ts
- ui/analyse/src/study/studyForm.ts
- ui/bits/css/build/bits.account.scss
- ui/bits/css/build/bits.flairPicker.scss
- ui/bits/css/build/bits.team.scss
- ui/bits/src/bits.flairPicker.ts
- ui/bits/src/exports/flairPicker.ts
- ui/common/css/form/_emoji-picker.scss
- don't wreck study settings dialog
- use correct lichess theme if set
> flair picker

- ui/analyse/src/study/relay/relayTourView.ts
Leave the default as it is in the full description
> add `rel="nofollow noopener noreferrer"` links on RelayTourInfo

- ui/analyse/src/study/relay/relayTourView.ts
Show a message when there are no boards
Vision in a contributor:
View in a viewer:
> Relay: Show mensage in board tab if do not have boards

- modules/game/src/test/Arbitraries.scala
Apply https://github.com/lichess-org/scalachess/pull/583
> Clean up arbitraries for game.EventTest

- ui/common/css/component/_dialog.scss
- ui/common/src/dialog.ts
https://github.com/lichess-org/lila/commit/fbf0b65ed6af559f41abf617ecf00a6445a28bdf#r148442558
> disable body scroll on touch devices with css

- ui/analyse/src/view/actionMenu.ts
> Fix `showVariationArrows` trans

- .github/workflows/assets.yml
- Cache pnpm store
- Also, fix ab step to avoid generating errors.
> Speed up gh assets action

- modules/web/src/main/ui/contact.scala
> Contact page, but non-serious options at the bottom

- app/views/game/side.scala
- modules/clas/src/main/ui/ClasPages.scala
- modules/clas/src/main/ui/DashboardUi.scala
- modules/clas/src/main/ui/StudentFormUi.scala
- modules/clas/src/main/ui/StudentUi.scala
- modules/cms/src/main/CmsUi.scala
- modules/feed/src/main/FeedUi.scala
- modules/forum/src/main/ui/PostUi.scala
- modules/mod/src/main/ui/ModUi.scala
- modules/mod/src/main/ui/ModUserTableUi.scala
- modules/mod/src/main/ui/ModUserUi.scala
- modules/oauth/src/main/ui/AuthorizeUi.scala
- modules/oauth/src/main/ui/TokenUi.scala
- modules/practice/src/main/PracticeUi.scala
- modules/relay/src/main/ui/RelayFormUi.scala
- modules/security/src/main/ui/AccountSecurity.scala
- modules/simul/src/main/ui/SimulFormUi.scala
- modules/swiss/src/main/ui/SwissFormUi.scala
- modules/team/src/main/ui/TeamUi.scala
- modules/title/src/main/ui/TitleUi.scala
- modules/tournament/src/main/ui/TournamentForm.scala
- modules/ublog/src/main/ui/UblogFormUi.scala
- modules/user/src/main/ui/NoteUi.scala
- ui/bits/src/bits.account.ts
- ui/bits/src/bits.ts
- ui/round/src/view/table.ts
- ui/site/src/boot.ts
- ui/site/src/domHandlers.ts
> fix button text for create token danger confirm

- translation/source/broadcast.xml
- translation/source/study.xml
- ui/@types/lichess/i18n.d.ts
- ui/analyse/src/study/multiBoard.ts
Fix https://lichess.org/forum/lichess-feedback/multiboard-button-glitchbug-in-lichess-study
> Move i18n perPage to study

- modules/user/src/main/UserApi.scala
Exclude closed and marked accounts. Closes #14350
> Filter results on Online Bots page

- ui/game/src/view/status.ts
- ui/game/tests/status.test.ts
This position was being considered insufficient material https://lichess.org/editor/8/8/1B6/8/1KB5/8/2k5/8
> Fix insufficient material check (KBB vs K)

- modules/mod/src/main/ui/ModInquiryUi.scala
- ui/mod/css/_inquiry.scss
- ui/mod/src/mod.inquiry.ts
For cheat the only part requiring the keyboard was copy-pasting URLs (could be done with mouse but slow)
Admins
|--------|--------|
| <img width="355" alt="image" src="https://github.com/user-attachments/assets/3fb713fe-8865-4def-ab33-47ba70af9040"> | <img width="356" alt="image" src="https://github.com/user-attachments/assets/ef5499c5-0997-4acc-a2bb-f7e784b230af"> |
Hunters/shushers
|--------|--------|
| <img width="353" alt="image" src="https://github.com/user-attachments/assets/0cc2c1c1-c12f-47a6-ae87-18659889cb99"> | <img width="361" alt="image" src="https://github.com/user-attachments/assets/41d835a6-93c6-45e4-ac4b-0cf44f9de2d8"> |
> Inquiry: add button to copy current URL to note

- ui/ceval/src/engines/engines.ts
- ui/ceval/src/types.ts
- ui/common/src/device.ts
- ui/puzzle/src/report.ts
> require stockfish 16+ wasm for puzzle report

- app/controllers/Auth.scala
- modules/round/src/main/PerfsUpdater.scala
Split pure functions from effectful functions and some other neat.
My effort to make it easier to understand + testable.
> Refactor PerfsUpdater

- modules/common/src/main/MarkdownRender.scala
> use correct hotlink domain for xkcd.com

- ui/analyse/src/study/studyForm.ts
> let study admins pick lichess flair

- ui/bits/src/bits.diagnosticDialog.ts
- ui/ceval/src/engines/engines.ts
- ui/ceval/src/types.ts
- ui/ceval/src/view/main.ts
1. some type tweaks.
2. SF14 used to be obsoleted by SF16+ but now all engines are listed after 873c708d3068ccb320909108e94f09b2ecea0e78
> Browser engine tweaks

- modules/common/src/main/Form.scala
- modules/user/src/main/UserForm.scala
Addresses #16450
Something that might be nice for users to have imo.
> Allow up to 10 emojis/symbols in a user's profile bio.

- ui/ceval/src/winningChances.ts
- ui/ceval/tests/winningChances.test.ts
- ui/puzzle/src/report.ts
- ui/puzzle/src/util.ts
- ui/puzzle/src/view/tree.ts
Reduce fps, display mate score
> Puz report v5

- modules/mod/src/main/ModlogApi.scala
> Fix alt marks seeing "closed by your teacher" notice

- ui/ceval/src/ctrl.ts
- ui/ceval/src/engines/engines.ts
- ui/ceval/src/types.ts
is this ok? do we want fsf14+ HCE in there?
> express cloud eval capability with engine property

- app/controllers/Main.scala
- app/prometheus.scala
- build.sbt
- modules/web/src/main/PrometheusReporter.scala
also need to update config file:
```
kamon.modules.prometheus-reporter {
factory = "lila.app.prometheus.PrometheusReporter$Factory"
}
```
> Fix kamon prometheus exporter

- .scala-steward.conf
To avoid https://github.com/lichess-org/lila/pull/16504 & https://github.com/lichess-org/lila/pull/16503
> Ignore play sbt plugin update from scala steward

- bin/mongodb/create-trophy-kinds.js
Script is used by lila-docker/gitpod
> update trophyKind seed script after font changes

- modules/pref/src/main/PrefForm.scala
- modules/pref/src/main/PrefSingleChange.scala
Implements the necessary changes for the privacy settings of the challenges to be changed in the mobile app.
Related Pull request in the mobile repo: https://github.com/lichess-org/mobile/pull/1208
> [mobile] add challenge to single prefs

- app/controllers/Plan.scala
see https://hq.lichess.ovh/#narrow/stream/58-dev-bug/topic/Patron.20issues/near/3549065 before considering a merge
> hopefully fix update payment method on stripe

- ui/.build/src/manifest.ts
I dropped the `JSON.stringify` on `current.hashed` keys, as I didn't see why it was needed
> reformat the client manifest for concision

- ui/common/css/component/_markdown.scss
> remove background in code text

- ui/analyse/src/study/chapterNewForm.ts
- ui/common/css/component/_dialog.scss
- ui/common/src/dialog.ts
fix #16527 and remove "unmodal" hack on new chapter dialog as it is no longer required for shepherd
> fake snab modals

- ui/recap/src/ui.ts
- ui/recap/src/util.ts
- ui/recap/src/view.ts
- ui/recap/tests/duration.test.ts
> Refactor recap showDuration to fix singular/plural

- ui/recap/css/_recap.scss
Was overlapping the swiper autoplay progress
> Hide friends box on recap

- ui/recap/src/ui.ts
Arrow keys conflict with swiperjs
depends on https://github.com/lichess-org/pgn-viewer/pull/42
> Disable lpv keyboard nav in slider

- modules/web/src/main/ui/layout.scala
> Add icon for page/event managers

- ui/puzzle/src/report.ts
Trying to understand where FPs come from
> Puzzle report: add engine name to report

- ui/api/src/api.ts
requested by our favorite extension developer
> provide non-blocking, lichess styled dialog functions in api

- ui/round/src/ctrl.ts
Not exactly what #16549 requested, but it's a similar case when my opponents has connection issues and run out of time eventually.
> Send notification to player when opponent time is out

- ui/analyse/src/ctrl.ts
> Redraw when deleting moves (analysis, studies)

- ui/analyse/src/ctrl.ts
- ui/ceval/src/ctrl.ts
> tiny ceval refactor and fix practice multipv bug

- modules/security/src/main/LilaCookie.scala
secure = true got lost somewhere in the recent past.
> mark cookies secure when https is available

- modules/web/src/main/ui/layout.scala
- ui/site/package.json
i think cloudflare edge cache has a corrupted noto-sans-v14-latin-regular in my region.
> hash all the woff2 fonts

- app/controllers/Round.scala
```
http://localhost:9663/dyIwz6fAsgek - {"SyntaxError":"JSON.parse: unexpected end of data at line 1 column 1 of the JSON data","stack":""} [permalog.ts:58:12](http://localhost:9663/ui/common/src/permalog.ts)
Uncaught (in promise) SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```
xhr.setNote() eventually expects a valid json response
```
/* fetch a JSON value */
export const json = (url: string, init: RequestInit = {}): Promise<any> =>
jsonAnyResponse(url, init).then(res => ensureOk(res).json());
```
> Fix error in browser console when typing a note

- modules/ublog/src/main/ui/UblogPostUi.scala
> User who can edit lichess post should see a edit link on the post

- modules/coreI18n/src/main/key.scala
- translation/source/site.xml
- ui/@types/lichess/i18n.d.ts
- ui/challenge/src/view.ts
> Translate No challenges

- ui/@types/lichess/i18n.d.ts
These kept being autogenerated, so just adding them to the repo here.
> Autogenerated strings for the vukovic mate.

- conf/base.conf
- modules/streamer/src/main/Env.scala
- modules/streamer/src/main/TwitchApi.scala
See https://github.com/lichess-org/lila-docker/pull/139 for use
> Make Twitch API endpoint configurable for testing

- modules/web/src/main/ui/help.scala
fixes #16859
feature was removed
> remove blindfold mode from shortcuts help

- ui/analyse/src/plugins/analyse.nvui.ts
- ui/nvui/src/chess.ts
- ui/nvui/src/command.ts
- ui/puzzle/src/plugins/puzzle.nvui.ts
- ui/round/src/plugins/round.nvui.ts
* fix study/broadcast players' info display
* Add board mode commands to switch between next/previous moves/lines. Closes #16866
* Add clocks for studies/broadcasts. Closes #16880
* Add links to other broadcast groups
* golf
> More nvui tweaks

- modules/feed/src/main/FeedUi.scala
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Flichess.org%2Ffeed.atom
> Validate feed atom

- modules/puzzle/src/main/PuzzleForm.scala
- ui/ceval/src/winningChances.ts
- ui/ceval/tests/winningChances.test.ts
- ui/puzzle/src/ctrl.ts
- ui/puzzle/src/report.ts
each commit is a self-contained improvement to reduce fp, or tweak send params
> Puzzle report improvements

- modules/common/src/main/HTTPRequest.scala
undici is the built-in fetch in nodejs
> add undici in http lib

- app/controllers/PlayApi.scala
- modules/api/src/main/EventStream.scala
- modules/game/src/main/Game.scala
- modules/round/src/main/Drawer.scala
- modules/round/src/main/RoundAsyncActor.scala
- modules/round/src/main/Takebacker.scala
- modules/tournament/src/main/TournamentApi.scala
When trying Bot API with Arena game, I got an error message when trying to connect to the game: 
```json
{"error":"This game cannot be played with the Bot API."}
```
This Pull Request adds Arena as a compatible game source.
Relates: f3b241c2
> Game source Arena Bot compatible

- modules/relay/src/main/RelayRoundForm.scala
- modules/relay/src/test/RelayFetchTest.scala
> Add tests for relay cleanUrl

- app/controllers/RelayRound.scala
- modules/common/src/main/mon.scala
- modules/relay/src/main/RelayPush.scala
To test locally:
```bash
LICHESS_URL="http://localhost:8080"
API_TOKEN="lip_admin"
BROADCAST_ROUND_ID="CC01EY6u"
curl -X POST \
-A "Lichess Broadcaster/0.0.1 tauri:2.2.5 as:foo" \
-H "Authorization: Bearer $API_TOKEN" \
-H "Content-Type: text/plain" \
-d "
[Event \"Game 1\"]
[White \"White 1\"]
[Black \"Black 1\"]
[Result \"*\"]
1. e4" "$LICHESS_URL/api/broadcast/round/$BROADCAST_ROUND_ID/push"
```
Then visit the metrics debugging endpoint: http://localhost:8080/prometheus-metrics/x
> Add relay push mon

- ui/nvui/src/chess.ts
> Allow user to select own color again in blind mode

- modules/relay/src/main/RelayApi.scala
Avoid miss clicking and organizer/recruit deleting without us knowing
> Do not delete tour if official

- ui/ceval/src/util.ts
As for translating, do you have the same position as for #17026 ?
> Fix mistake in error message

- modules/playban/src/main/PlaybanFeedback.scala
- ui/round/src/round.ts
context (from which the updated wording comes from): https://hq.lichess.ovh/#narrow/stream/1-general/topic/Warning.20message.20in.20game.20chat
> Ragesit: make the warning less scary

- modules/coreI18n/src/main/key.scala
- modules/ublog/src/main/ui/UblogUi.scala
- translation/source/ublog.xml
- ui/@types/lichess/i18n.d.ts
> Missing translations

- app/Env.scala
- modules/common/src/main/config.scala
- modules/user/src/main/Env.scala
- modules/user/src/main/FlairApi.scala
- modules/web/src/main/AssetManifest.scala
When running lila from the `target/universal/stage/bin/lila` binary after a `./lila.sh stage`, I was getting this error:
java.io.FileNotFoundException: public/flair/list.txt (No such file or directory)
> Fix flair/list.txt pathname

- app/controllers/Api.scala
This reverts commit 77008a8bbab48ba0d94aca2017a76af4d3d635fe.
Resolves: #17091
> Revert "code golf"

- ui/.build/package.json
- ui/.build/pnpm-lock.yaml
- ui/.build/src/console.ts
- ui/.build/src/manifest.ts
- ui/common/src/device.ts
- ui/common/src/dialog.ts
- ui/common/src/storage.ts
- ui/common/tests/device.test.ts
- ui/common/tests/once.test.ts
- ui/site/src/boot.ts
the nag is only shown for webkit versions under 15.4 for now.
typescript the remote logging monkey patch and forward remote user agent to the console on page loads
> improve device regexes and add bi-monthly browser upgrade nag

- ui/round/src/plugins/round.nvui.ts
for https://lichess.org/forum/lichess-feedback/issue-in-blind-mode
> fix nvui round input disambiguation

- project/Dependencies.scala
For https://github.com/lichess-org/scalachess/pull/638
> Bump scalachess 17.3.0

- ui/.build/src/sass.ts
Also refactored the logic a bit and added error messages instead of silent fallbacks.
~~Haven't tested this properly yet, have to go now, if nobody else tests it I'll try it later.~~
> ui/build/sass: Fall back to default theme when resolving variables

- ui/analyse/src/study/relay/relayTourView.ts
- ui/analyse/src/study/studyChapters.ts
- ui/analyse/src/study/studyView.ts
Fixes some missing translations (using existing translations)
Question for the search tooltip: there is a translation in search.xml but it's not loaded for study. 
Should I:
-  load search 
- duplicate search key in study
- move search key to site
> study tooltip translations

- ui/nvui/src/chess.ts
- ui/nvui/tests/command.test.ts
Sort output of the scan command by key
> Nvui scan sort

- modules/fide/src/main/FidePlayerSync.scala
fix https://lichess.org/fide/5010179/Danny_Zohmingliana
> Fide's federation id may not be all caps

- pnpm-lock.yaml
- ui/analyse/package.json
- ui/analyse/src/study/relay/relayPlayers.ts
Update tablesort to 5.5.0 and use the new data-sort-reverse attribute to sort broadcast players by name
> Tablesort 5.5.0

- ui/analyse/css/study/relay/_layout.scss
https://hq.lichess.ovh/#narrow/stream/111-content-dev/topic/broadcast.20analysis.2Bliveboard.20view/near/3675603
> fix liveboard clipping in short windows with many rounds

- pnpm-lock.yaml
- ui/lib/package.json
- ui/lib/src/ceval/engines/engines.ts
lovingly crafted from a single block of wood by the stockfish team with a little help from Niklas.
> stockfish 17.1 engine

- ui/lib/css/component/_ublog-card.scss
Allows https://github.com/lichess-org/lila/commit/d728a24106506cc648ab88cb87ba023ab450642f to take effect
> Use ublog color title variable

- pnpm-lock.yaml
- ui/lib/package.json
- ui/lib/src/ceval/engines/engines.ts
lovingly crafted from a single block of wood by the Stockfish team with a little help from Niklas.
> stockfish 17.1

- .gitignore
- bin/deploy
- bin/git-hooks/post-checkout
- bin/git-hooks/post-commit
- bin/git-hooks/post-merge
- bin/git-hooks/pre-push
Before running this bin/deploy:
- rename our recently created git repo
```bash
mv /home/lichess/lfs-deploy /home/lichess/deploy
```
- modify service file
```
ExecStart=/home/lichess/deploy/bin/lila
WorkingDirectory=/home/lichess/deploy
```
> use /home/lichess/deploy for prod deploy_dir

- modules/study/src/main/BSONHandlers.scala
probably an oversight from me in https://github.com/lichess-org/lila/pull/14917
> Remove unused given (we have given outside)

- modules/relay/src/main/RelayFetch.scala
- modules/relay/src/test/RelayFetchTest.scala
This is more optimize as we only do fold once and only do map when we have an real TounamentClock
> Optimize injectTimeControl.in by do fold before map

- modules/game/src/main/Importer.scala
- modules/relay/src/main/RelayPush.scala
- modules/relay/src/test/RelayPushTest.scala
- modules/study/src/main/StudyPgnImport.scala
- modules/study/src/main/StudyPgnImportNew.scala
- modules/tree/src/main/ParseImport.scala
Some refactor to avoid parsing and replaying the game twice for every games.
Tests are added at the begining and pass for every later commits.
> Optimize relay push validate

- ui/bits/css/_search.scss
- ui/insight/css/_insight.scss
> fix: Themes for calendar in advanced search and chess insights header

- app/controllers/Dev.scala
- conf/base.conf
- modules/common/src/main/Form.scala
- modules/common/src/main/mon.scala
- modules/core/src/main/data.scala
- modules/memo/src/main/SettingStore.scala
- modules/ublog/src/main/Env.scala
- modules/ublog/src/main/UblogApi.scala
- modules/ublog/src/main/UblogAutomod.scala
- modules/ublog/src/main/UblogBsonHandlers.scala
- modules/ublog/src/main/UblogForm.scala
- modules/ublog/src/main/UblogPost.scala
- modules/ublog/src/main/ui/UblogPostUi.scala
- modules/web/src/main/ui/DevUi.scala
- ui/bits/css/ublog/_post.scss
- ui/mod/css/_dev.scss
this example automatically applies rankAdjustDays based on automod assessment. it takes no action on flagged or commercial other than to display that finding in post view mod tools.
you'll need to set `ublog.automod.apikey` in application.conf and i will provide you with the prompt over zulip.
> ublog automod wip

- modules/study/src/main/StudyApi.scala
Instead of PR #17272 (the author seems to be away)
> Do not automatically update conceal state of study chapter

- modules/core/src/main/game/misc.scala
- modules/game/src/main/PgnDump.scala
- modules/relay/src/main/RelayFetch.scala
- modules/round/src/main/ApiMoveStream.scala
- modules/study/src/main/ExplorerGame.scala
- modules/study/src/test/StudyArbitraries.scala
- project/Dependencies.scala
And adapt/take advantage of some changes
> Update scalachess 17.3.1

- ui/coordinateTrainer/src/ctrl.ts
- ui/coordinateTrainer/src/side.ts
- ui/lib/css/component/_sparkline.scss
> Add a tooltip to the coordinates training graphs showing the score

- modules/relay/src/main/JsonView.scala
> Add round url to broadcast/top api

- app/controllers/RelayRound.scala
Changes it to return the data in the same structure as the show + create endpoints
> relay round update endpoint response update

- ui/analyse/src/interfaces.ts
- ui/analyse/src/plugins/analyse.nvui.ts
- ui/analyse/src/study/relay/relayTourView.ts
- ui/analyse/src/view/main.ts
fixes #17234 
Immersive experience: https://youtu.be/iZzea-fmEO8
As per comment https://github.com/lichess-org/lila/issues/17231#issuecomment-2825285263 tour info is kept at the bottom of the page
> add tour info and players (lazy load) for nvui

- modules/ublog/src/main/UblogApi.scala
- modules/ublog/src/main/UblogAutomod.scala
- modules/ublog/src/main/ui/UblogPostUi.scala
- pnpm-lock.yaml
- ui/bits/css/ublog/_post.scss
- ui/bits/src/bits.ublog.ts
- ui/lib/package.json
- ui/lib/src/ceval/engines/stockfishWebEngine.ts
- add offtopic tag to ublog automod.
- offtopic tag needs the prompt in sysadmin/prompts/ublog-system-prompt.txt in order to do anything, but it's safe to merge without that.
- update all references lila-stockfish-web -> @lichess-org/stockfish-web
these are probably both uncontroversial so same PR
> ublog offtopic tag and @lichess-org/stockfish-web

- ui/round/src/plugins/round.nvui.ts
fixes #17413
[Video](https://youtu.be/ECmmYnmNZng) showing bug and fix
> Add punctuation to help screen reader

- modules/tournament/src/main/Env.scala
- modules/tournament/src/main/PairingRepo.scala
- pnpm-lock.yaml
if a streamer finishes a game but does not immediately return to the tournament screen, they can fall through the cracks when a cache update finds they are neither in the waiting list nor are they playing a game. this causes at least 15 seconds of them being considered offline on the tournament description page.
> a streamer is "in" tournament if they recently played

- modules/setup/src/main/ApiConfig.scala
> send error if sending fromPosition rated challenges through the API

- ui/lib/src/game/clock/clockCtrl.ts
- ui/lib/src/game/clock/clockView.ts
As suggested by @fitztrev 
Benefits:
- common logic
- translated
Video (with sound) ... first word after typing clock was not recorded but it's there ...
https://youtu.be/IKK-c5sy0m4
Note: ClockCtrl.speak is not called for times above and including 1 day ...
> Use formatClockTimeVerbal in clock speak

- ui/lobby/src/setupCtrl.ts
> nullish coalescing to allow 0 time values in challenge modal

- ui/round/src/ctrl.ts
> Disable wake lock in correspondence games

- ui/lobby/src/view/setup/modal.ts
At the moment, the title of modal dialogs are not announced.
This PR fixes the 3 dialogs in the lobby (which are part of the nvui flow)
https://youtu.be/cx0Ht2VX2LM
> Add aria to lobby modal dialogs

- ui/round/src/plugins/round.nvui.ts
Square is better than coordinates.
> Better description for board focus nvui

- modules/lobby/src/main/BoardApiHookStream.scala
- modules/lobby/src/main/LobbySocket.scala
- modules/lobby/src/main/LobbySyncActor.scala
- modules/lobby/src/main/actorApi.scala
- modules/setup/src/main/Processor.scala
Due to migration to type-bus, event was not subscribed
> Fix lobby hooks not appearing

- modules/study/src/main/StudyPgnImport.scala
- modules/study/src/main/StudyPgnImportNew.scala
Replace `Game` with `Position` and `Ply` which carry the exact
information we need and also lighter (for both memory and cpu)
> Optimize StudyPgnImport's accumulated context

- .github/workflows/reviewable.yml
Depends on https://github.com/lichess-org/.github/pull/2
Will be easier to add to other repos within the org
> Use workflow template for reviewable workflow

- package.json
- pnpm-lock.yaml
> Update vitest dependency

- ui/lib/package.json
- ui/lib/src/ceval/engines/engines.ts
Prod is using `/assets/npm/lila-stockfish-web/sf16_7.js` which doesn't exist on a clean install
> sync npm stockfish-web to assets

- modules/web/src/main/StaticContent.scala
> Update appstore link

- app/controllers/Main.scala
Closes https://github.com/lichess-org/lila/issues/17558
> remove unused title verification google form link

- ui/analyse/src/plugins/analyse.nvui.ts
- ui/lib/src/nvui/command.ts
Closes https://github.com/lichess-org/lila/issues/17565
> fix nvui command listing

- app/views/lobby/blindLobby.scala
I reused translations
It changes the initial untranslated text but it adds consistency (... I think)
> nvui - i18n ongoing games in lobby

- modules/relay/src/main/RelayPush.scala
As scalachess should only contains one line error now
> Remove online error function

- modules/web/src/main/StaticContent.scala
It seems that apple automatically adds
> Remove the nationality code from the appstore link

- modules/activity/src/main/JsonView.scala
Due to a model change of the `ActivityView.corresEnds`.
Mobile app issue: https://github.com/lichess-org/mobile/issues/1100
> Fix user activity API JSON corresEnd view which is wrong

- modules/api/src/main/GameApi.scala
- project/Dependencies.scala
- **Update scalachess 17.7.1** for https://github.com/lichess-org/scalachess/pull/691
- **Game.position is a latest state not the first**
> Fix scalachess canplay regression

- modules/game/src/main/GifExport.scala
This changes the semantic a little bit. Before `frames` returns all positions until the first faulty move, now it only returns the first position if there is any failure.
tested locally. This is how I found out regression in scalachess 17.7.0. Feel so lucky, that I found it before deploying.
> Refactor gif-export using playPositions

- modules/game/src/main/GamesByUsersStream.scala
`/api/stream/games-by-users`
`/api/stream/games/<streamId>`
If a player is Anonymous or AI, the current JSON contains null values:
```json
"black": {
"userId": null,
"rating": null
}
```
This commit adds Anonymous and AI player info:
```json
"black": "Anonymous"
```
or
```json
"black": {
"ai": 4
}
```
Example, given 3 games, where black is played by account, anon and AI
```
PVqFo09M - yulia vs bobby
PsjdrEXt - yulia vs Unregistered/Anonymous
pTU6trNw - yulia vs AI level 4
```
```
curl -H "accept: application/x-ndjson" "http://localhost:8080/api/stream/games/StreamId" -d 'pTU6trNw,PsjdrEXt,PVqFo09M'
```
Before commit:
```
{"id":"PVqFo09M",...,"players":{"white":...,"black":{"userId":"bobby","rating":1704}}}
{"id":"PsjdrEXt",...,"players":{"white":...,"black":{"userId":null,"rating":null}}} …
```
> Add player info Anonymous and AI to game streams

- ui/lib/src/view/boardMenu.ts
> Translate confirm move

- ui/analyse/src/study/relay/relayPlayers.ts
> Broadcast: Fix player score

- modules/tournament/src/main/BSONHandlers.scala
regression from https://github.com/lichess-org/lila/pull/17624/files#diff-42e4cda0c4dac64a147396581ef0805034c6d801be71cd457af194df8b7ae652L201
Fix #17641
tested locally
> Fix unable to create un-rated tournaments

- ui/lib/src/nvui/chess.ts
- ui/lib/tests/nvui.test.ts
> Allow capital letters in drop and promotion

- modules/game/src/main/Importer.scala
- modules/insight/src/main/PovToEntry.scala
- modules/opening/src/main/OpeningQuery.scala
- project/Dependencies.scala
- **Remove unused private variable**
- **Update scalchess 17.81 and adapt OpeningDb changes**
> Update scalachess 17.8.1

- ui/site/src/sound.ts
- ui/voice/src/voice.ts
> Safe guard window.speechSynthesis

- modules/coreI18n/src/main/key.scala
- modules/relay/src/main/Env.scala
- modules/relay/src/main/JsonView.scala
- modules/relay/src/main/RelayTour.scala
- translation/source/broadcast.xml
- translation/source/site.xml
- ui/@types/lichess/i18n.d.ts
- ui/analyse/css/study/relay/_tour.scss
- ui/analyse/src/study/relay/interfaces.ts
- ui/analyse/src/study/relay/relayTourView.ts
context: #content-broadcast > show note: "This broadcast is not official"
> Show note for unofficial broadcasts

- modules/relay/src/main/ui/RelayFormUi.scala
- ui/bits/src/bits.relayTourForm.ts
- ui/bits/src/bits.ts
Become a bit like in the past, but with the possibility to switch
> Timezone: auto select user timezone

- modules/round/src/main/StepBuilder.scala
- modules/study/src/main/ServerEval.scala
- modules/tree/src/main/TreeBuilder.scala
- project/Dependencies.scala
Use `Canplay.foldRight`:
- StepBuilder
- ServerEval
- TreeBuilder
`TreeBuilder` is a complicated one, but we have tests at `fishnet.TreeBuilderTests`. Tested locally for all of changes.
> Update scalachess 17.8.3 and use Canplay.foldRight

- ui/lib/src/nvui/notify.ts
> don't use liveText in Notifiy

- modules/fishnet/src/main/JsonApi.scala
- modules/fishnet/src/main/UciToSan.scala
- modules/fishnet/src/main/Work.scala
- project/Dependencies.scala
- **Update scalachess 17.8.5**
- **Use Canplay.play ucis version**
> Update scalachess 17.8.5

- modules/mod/src/main/ModStream.scala
<sup>[context](https://hq.lichess.ovh/#narrow/channel/34-mod-dev/topic/Watcherbot.20for.20teams.20.28implementation.29/near/3786763)</sup>
> Add TeamCreate event to ModStream

- modules/relay/src/main/RelayTagManualOverride.scala
> remove override if value is empty

- modules/relay/src/main/RelayNotifier.scala
Only notify FIDE player followers if broadcast is public
> Filter notifications on Visiblity

- ui/@types/lichess/index.d.ts
- ui/analyse/src/analyse.nvui.ts
- ui/analyse/src/view/nvuiView.ts
- ui/lib/src/chat/discussion.ts
- ui/lib/src/nvui/chess.ts
- ui/lib/src/nvui/notify.ts
- ui/site/src/mousetrap.ts
- simplify notify implementation (christmas miracle - voiceover with no setTimeout hacks)
- add missing key commands
- unfuck mousetrap, just a smidge, so that analyse nvui doesn't compete with chat/discussion.ts over who gets the 'c' key
> fix voiceover, again

- ui/lib/src/nvui/handler.ts
- ui/lib/src/nvui/render.ts
- ui/puzzle/src/view/nvuiView.ts
- ui/round/src/view/nvuiView.ts
- refactor board events
- make o announce the piece if there is one: instead of A1 we now hear A1 white rook (consistent with what is announced when moving around with the arrows)
> nvui - Better announcements

- modules/core/src/main/irc.scala
- modules/irc/src/main/IrcApi.scala
- modules/mod/src/main/ModApi.scala
- modules/mod/src/main/ModlogApi.scala
<sup>[context](https://hq.lichess.ovh/#narrow/channel/35-mod-dev-admin/topic/Perms.20given.20log/near/3802263)</sup>
> Log permission changes to Zulip

- ui/site/src/renderTimeAgo.ts
> nvui - Remove time attributes when blind mode is on

- project/Dependencies.scala
with tiebreak: https://github.com/lichess-org/scalachess/pull/712
> Update scalachess 17.9.0

- modules/history/src/main/RatingChartApi.scala
> fix: chart tooltip order same as profile page

- ui/chart/src/chart.ratingHistory.ts
After https://github.com/lichess-org/lila/pull/17873
> fix ratingChart perf style

- modules/relay/src/main/RelayApi.scala
- modules/relay/src/main/ui/RelayFormUi.scala
> Make grouping avaliable for everyone in broadcasts unofficial

- app/controllers/Analyse.scala
- app/controllers/Push.scala
- app/controllers/RelayTour.scala
- app/views/mod/ui.scala
- app/views/relay.scala
- modules/api/src/main/Env.scala
- modules/api/src/main/EventStream.scala
- modules/bot/src/main/GameStateStream.scala
- modules/core/src/main/misc.scala
- modules/fishnet/src/main/UciToSan.scala
- modules/forum/src/main/ForumPostApi.scala
- modules/lobby/src/main/BoardApiHookStream.scala
- modules/mod/src/main/ui/GamifyUi.scala
- modules/mod/src/main/ui/PublicChatUi.scala
- modules/relay/src/main/RelayPlayer.scala
- modules/relay/src/main/RelayTagManualOverride.scala
- modules/relay/src/main/RelayTourForm.scala
- modules/relay/src/main/ui/RelayCardUi.scala
- modules/relay/src/main/ui/RelayGroupUi.scala
- modules/relay/src/main/ui/RelayMenuUi.scala
- modules/relay/src/test/RelayUpdatePlanTest.scala
- modules/round/src/main/Moretimer.scala
- modules/security/src/main/GarbageCollector.scala
- modules/security/src/main/SecurityApi.scala
- modules/security/src/main/SessionStore.scala
- modules/security/src/main/UserLogins.scala
- modules/tree/src/main/NewTreeBuilder.scala
- project/BuildSettings.scala
> Update scala 3.7.2

- modules/pref/src/main/PrefForm.scala
- modules/pref/src/main/PrefSingleChange.scala
Implements the necessary changes for the privacy settings of the messages to be changed in the mobile app.
> [mobile] add messages to single pref

- app/controllers/Report.scala
For https://github.com/lichess-org/mobile/pull/2096
> Open /report/flag to mobile

- modules/study/src/test/CommentParserTest.scala
- modules/tree/src/main/tree.scala
maybe fix part of https://github.com/lichess-org/scalachess/issues/735
> support TCEC clock as millis

- ui/lib/src/nvui/handler.ts
- ui/round/src/view/nvuiView.ts
support letter k on desktop and additional king promotion key on touchscreen.
> nvui - promote to king from board (antichess )

- ui/analyse/css/_tools.scss
- ui/analyse/src/view/nvuiView.ts
fixes #18032
https://github.com/user-attachments/assets/81e1ae1b-fe6f-4707-b975-434915d76919
> Use a css exception for blind mode to always show ceval

- modules/ublog/src/main/ui/UblogUi.scala
- public/lifat/background/gallery/bg01-thumb.webp
- public/lifat/background/gallery/bg02-thumb.webp
- public/lifat/background/gallery/bg03-thumb.webp
- public/lifat/background/gallery/bg04-thumb.webp
- public/lifat/background/gallery/bg05-thumb.webp
- public/lifat/background/gallery/bg06-thumb.webp
- public/lifat/background/gallery/bg07-thumb.webp
- public/lifat/background/gallery/bg08-thumb.webp
- public/lifat/background/gallery/bg09-thumb.webp
- public/lifat/background/gallery/bg10-thumb.webp
- public/lifat/background/gallery/bg11-thumb.webp
- public/lifat/background/gallery/bg12-thumb.webp
- public/lifat/background/gallery/bg13-thumb.webp
- public/lifat/background/gallery/bg14-thumb.webp
- public/lifat/background/gallery/bg15-thumb.webp
- public/lifat/background/gallery/bg16-thumb.webp
- public/lifat/background/gallery/bg17-thumb.webp
- public/lifat/background/gallery/bg18-thumb.webp
- public/lifat/background/gallery/bg19-thumb.webp
- public/lifat/background/gallery/bg20-thumb.webp
- public/lifat/background/gallery/bg21-thumb.webp
- public/lifat/background/gallery/bg22-thumb.webp
- public/lifat/background/gallery/bg23-thumb.webp
- public/lifat/background/gallery/bg24-thumb.webp
- public/lifat/background/gallery/bg25-thumb.webp
- public/lifat/background/gallery/bg26-thumb.webp
- public/lifat/background/gallery/bg27-thumb.webp
- public/lifat/background/gallery/bg28-thumb.webp
- ui/lib/css/component/_ublog-card.scss
backgrounds are chosen by creation date
> more colorful placeholders for ublog thumbnails

- ui/lobby/src/view/setup/components/gameModeButtons.ts
> nvui - implement gameMode as a select

- ui/lib/src/game/glyphs.ts
The glyphs are laid-down from right to left, with the first one being at the top right, then the others are progressively moved to the left, until the top left.
The right-most (and first) glyph is at the top of the stack.
tested on multiple viewports
there is a small discrepancy where, when you add and remove glyphs in a study, while staying on the same, the order of the stack get "messed-up"
I think this is due to Chessground only redrawing what has changed, thus putting the changed glyph at least. I don't think it's a big deal.
(side-note, tried copilot review)
> Glyphs: Show multiple of them as a stack

- package.json
- pnpm-lock.yaml
- ui/analyse/src/ctrl.ts
- ui/analyse/src/ground.ts
- ui/lib/src/ceval/view/settings.ts
- ui/lib/src/game/clock/clockCtrl.ts
- ui/round/src/ctrl.ts
- ui/round/src/ground.ts
submitting for review in case we do not want the Map on YAGNI grounds. i just figured why not.
> use fat ignore radius when under a minute remains

- ui/analyse/src/ctrl.ts
- ui/analyse/src/idbTree.ts
- ui/analyse/src/treeView/inlineView.ts
- ui/analyse/src/view/actionMenu.ts
- ui/lib/css/tree/_tree.scss
this has not yet been tested like the build currently on testy.lichess.dev
~~EDIT - pushed it to testy since, if there are any new issues, they should be confined to "disclosure buttons disabled" mode.~~
> add disclosure buttons toggle in action menu

- ui/lib/src/ceval/types.ts
- ui/lib/src/ceval/view/main.ts
It toggles on but doesn't toggle off
> fix threat mode toggle

- ui/analyse/src/view/nvuiView.ts
> nvui  - Allow mixed case in commands

- ui/lib/css/component/_user-link.scss
This PR helps to make patrons colour distinguishable.As visualdennis stated in the discord server, all of the previous  colors consistently share similar value of brightness, and contrast, and easy to distinguish.The colours I have implemented in this PR helps a user to easily figure out whether a person is online or not.
Thank you ,hope it get mergs
> Rearranging patron's colour to make it distinguishable

- ui/racer/css/_home.scss
> Approaching the vehicle to the text

- ui/@types/lichess/index.d.ts
- ui/analyse/src/analyse.ts
- ui/analyse/src/study/analyse.study.ts
- ui/lib/src/chat/discussion.ts
- ui/puzzle/src/puzzle.ts
- ui/racer/src/racer.ts
- ui/round/src/round.ts
- ui/site/src/asset.ts
- ui/storm/src/storm.ts
and don't start a game, puzzle, or analysis without them.
> manually fetch & decode pieces to permalog failures

- app/controllers/OAuth.scala
- modules/core/src/main/lilaism/LilaLibraryExtensions.scala
- modules/oauth/src/main/AuthorizationApi.scala
- modules/oauth/src/main/AuthorizationRequest.scala
This makes us have less pattern matching/ nested code.
> Add more combinators for `FuRaise`

- project/Dependencies.scala
oops it's was published for a while
> Update cats-mtl 1.6.0

- pnpm-lock.yaml
- ui/botDev/package.json
- ui/botDev/src/botDev.ts
- ui/botDev/src/devBotCtrl.ts
- ui/lib/package.json
- ui/lib/src/bot/bot.ts
- ui/lib/src/bot/botLoader.ts
- ui/lib/src/bot/types.ts
repo: https://github.com/lichess-org/zerofish
npm: https://www.npmjs.com/package/@lichess-org/zerofish
> update zerofish dependency

- modules/pref/src/main/ui/AccountPref.scala
- ui/round/css/_app-layout.scss
- ui/round/src/view/boardMenu.ts
fix preference wording. swap keyboard toggle for invert clock toggle on mobile board menu.
fix #18355
> fix material hidden by clock
